### ISSUE TITLE
Decrypted Message: No such signedprekey with id: 7470

### ISSUE THREAD

**Issue by yairnet** [mgp25/Chat-API#1498]
-> Decrypted Message: No such signedprekey with id: 7470 - /home/src2/src/SqliteAxolotlStore.php - 246Message DAE49F474986FF0460C could not be decrypted, sending retry.

**Comment by mgp25** [comment]
@yairnet in theory, after that, you send a `retry` and the contact should answer, and everything from this point should be alright, if you keep getting that error, i recommend you deleting the `axolotl.db`

Regards
