### ISSUE TITLE
Error receiving message with encrypted image

### ISSUE THREAD

**Issue by usinadeideia** [mgp25/Chat-API#1499]
I'm $file param, but messages with encrypted image get as below: (remembering that encrypted text messages I am getting normal)

My code: 

function onGetImage($mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimetype, $filehash, $width, $height, $preview) {
    global $contact_id, $user_id, $w;
    preg_match('/(.*)@s\.whatsapp\.net/', $from, $numbercontact);
    $from = $numbercontact[1];
// $file is encrypted.
    FUNCOES::logMsg($login . " [onGetImage  " . $file. '] ', 'warning');
    
}

I get it:

[2016-01-17 09:43:58] [ WARNING ]  [onGetImage  ÿØÿà JFIF  ` `  ÿÛ C 	
ÿÛ C		ÿÀ à€" ÿÄ           	
ÿÄ µ   } !1AQa"q2‘¡#B±ÁRÑð$3br‚	
%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyzƒ„…†‡ˆ‰Š’“”•–—˜™š¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ        	
ÿÄ µ  w !1AQaq"2B‘¡±Á	#3RðbrÑ
$4á%ñ&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz‚ƒ„…†‡ˆ‰Š’“”•–—˜™š¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚâãäåæçèéêòóôõö÷øùúÿÚ   ? ý!Ð.<ÿ is™-ÊÀÊŽ+\H@®gÃrmøy¡ðT›¸=¾QZí1Ü@#î-QÏÊÑnI“ÒªƒÛÂù÷¤.ôÅ'Øv‚5N@|ÏÆ®gpÈ¨¤Ì5QV4‹¹W:š™Ø ÜvªÙ,â¬rØ¸‡°êjìm—çÒªFåúTá‚ž*Z3I³CŒŽ{Ô»×šË3í¤k‘å
gÊÂå×™qœÕrÙ`AçOÎ.x§#±9Í>VZW$Üy©×‘žÕZ¥ÆÀ:Ô´ÐZÄÛFìÓNj|SsŒP‰cPdƒéWBPjº&ô=jÀ$>3CV|¥{Óa@>µe•K7~8¨H ñëM±$Fî¾¸Å1›(WiÎ:b¢l9êkñsö½Ð¿h/ƒ

**Comment by VanDevos** [comment]
Have you installed dependencies explained in wiki ?

**Comment by 0xTryCatch** [comment]
Normal behaviour

**Comment by usinadeideia** [comment]
yes all dependencies

**Comment by usinadeideia** [comment]
Receive audio, text, video, only image not

**Comment by usinadeideia** [comment]
I receive audio, video, text, all encrypted. Only image does not.

It appears a broken image link
