### ISSUE TITLE
onGetGroupAudio event

### ISSUE THREAD

**Issue by ducch** [mgp25/Chat-API#1501]
A while ago, somebody created a workaround for audio messages that were sent in a group. See 4cc7c5954a2ea45a701cb41b2cc54db46df7e621.
We should have this thing through an onGetGroupAudio event, separately from onGetAudio.

Also, from my testing, [MessageHandler.php:173](https://github.com/mgp25/Chat-API/blob/master/src/handlers/MessageHandler.php#L173) always returns `''`. Maybe this parameter was changed or something and needs updating?

**Comment by nitin-krisil** [comment]
tx  <stream:features></stream:features>

tx  <auth user="918401877845" mechanism="WAUTH-2">����918401877845��BUmã�?��R�^�=JMy1453113696</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>��Y���O����̬#=��</challenge>

tx  <response>�˴sKVE7� ��M�I�+}#�M���(&��"��[��>4 /s�����0�����\��ۭ��Uz����d[�.��3��</response>

rx  <success t="1453113697" props="4" kind="free" status="active" creation="1453111932" expiration="1484647932">-��3�b��}iQ7*',h</success>

tx  <presence name="nitin" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <message to="9737894547@s.whatsapp.net" type="text" id="f0038487beddb02ea4895f" t="1453113697" notify="nitin">
tx    <body>Hi</body>
tx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="918401877845@s.whatsapp.net"></presence>

rx  <ack from="9737894547@s.whatsapp.net" class="message" id="f0038487beddb02ea4895f" t="1453113698"></ack>

above is my sent message response but my phone have not any message. so what i do..??/

**Comment by 0xTryCatch** [comment]
Outdated API, commenting in another issue, not reading the Wiki
