### ISSUE TITLE
 Decrypted Message: No keys for

### ISSUE THREAD

**Issue by yairnet** [mgp25/Chat-API#1504]
,,, 
 Decrypted Message: No keys for: 1440336761 - /home/src2/src/libaxolotl-php/groups/state/SenderKeyRecord.php - 40tx  <receipt id="1453108169.--5256" to="972539009001-1451799465@g.us" type="retry" t="1453108180">
,,,

Please Help How do I fix problem
It happens to some phones (not all)

**Comment by 0xTryCatch** [comment]
Stop posting invalid issues. Normal behaviour.
