### ISSUE TITLE
Message with preview link in it

### ISSUE THREAD

**Issue by Coennie** [mgp25/Chat-API#1506]
Hi There,
I'm experiencing issues with receiving messages which includes link previews. So when someone send me a message like: 'Http://www.nu.nl' with the link preview, I ended up with the following in the script:

    -> Decrypted Message: HEX:0a10487474703a2f2f7777772e6e752e6e6c1210487474703a2f2f7777772e6e752e6e6c2211687474703a2f2f7777772e6e752e6e6c2f2a25486574206c616174737465206e696575777320686574206565727374206f70204e552e6e6c322a4e55202d20486574206c616174737465206e696575777320686574206565727374206f70204e552e6e6c

while the same message without the preview send gives me:

    -> Decrypted Message: Http://www.nu.nl
    Can someone tell me how I can fix this issue?

Regards Coen

**Comment by 0xTryCatch** [comment]
Will be added soon

**Comment by Faber73** [comment]
Hello, any news about it ?
