### ISSUE TITLE
added required dependencies but incoming messages still encrypted

### ISSUE THREAD

**Issue by darthdaniel16** [mgp25/Chat-API#1511]
Hi, I installed the php extensions curve25519 and protobuf but incoming messages are still encrypted. How may I resolve this?

Running on wamp 2.5 & php 5.6

**Comment by mgp25** [comment]
@darthdaniel16 im pretty sure, extensiones are not loaded correctly, check it with `php -m` and make sure you have added them in the `php.ini`, if you don't do that it won't work.

Anyway, you should read closed issues before opening a new one, because this was already discused.

Regards
