### ISSUE TITLE
event handling

### ISSUE THREAD

**Issue by andrekat** [mgp25/Chat-API#1512]
hi guys,

lets say im listening to following event:

```php
	public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
	{
		$this->HandleIncomeMessage($from);
	}
```
Step 1: im currently offline and two guys are sending me 2 messages. 
Step 2: im connecting to whatsapp using API and call following function:
```php
$this->WhatsApp->pollMessage();
```
BEWARE: im **not** calling this function within an endless ```while(true)``` loop

Step 3: Now each message is beeing polled ...

My question: 

does the API call the event function **step for step** or **asynchronously**?

regards,

**Comment by mgp25** [comment]
@andrekat step by step.

When you poll the data, is processed, check this for more detail: `processInboundDataNode`

Regards

**Comment by andrekat** [comment]
well done, thank you =)
