### ISSUE TITLE
Is it mandatory to write .db and .dat files on wadata folder?

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1513]
Hi there,

In the wiki documentation there is a topic: Saving messages in db

There is said that "only add this line in your script after initialicing WhatsProt class."
I did not inserted this function and all messages that I receive has been stored there.

Is it mandatory to write this files?

**Comment by mgp25** [comment]
@edudesouza you can change `wadata` folder path, some `.db` files and `.dat`  files are required like the `nextChallenge` or the `axolotl` ones.

The other `.db` that stored messages is not enabled by default.

Regards

**Comment by edudesouza** [comment]
Hi there, 

Here is my script to send messages:
-----------------------------------------------------------------------------------------

$msg 		= $_REQUEST['msg'];
$destino 	= $_REQUEST['destino'];

$username 	= ***
$nickname 	= ***;
$password 	= ***
$debug 		= false;
$log 		= true;
$datafolder = "";

function ReceivedClient($username, $from, $id, $type, $time){
	echo "Client<br/>";
	echo $id."<br/>";
	echo date("m/d/Y - H:i", $time).'<br/>';
}

function ReceivedServer($username, $from, $id, $type, $time){
	echo "Server<br/>";
	echo $id."<br/>";
	echo date("m/d/Y - H:i", $time).'<br/>';
}

$w 			= new WhatsProt($username, $nickname, $debug, $log, $datafolder);
$events 	= new MyEvents($w);

$w->eventManager()->bind("onMessageReceivedClient", "ReceivedClient");
$w->eventManager()->bind("onMessageReceivedServer", "ReceivedServer");

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

$target  = $destino;
$message = $msg;

$w->SendPresenceSubscription($target);
$w->sendMessage($target,$message );

while($w->pollMessage());

$w->disconnect();

--------------------------------------------------------------

I  am not calling the function so store messages, why it is still storing the messages?
