### ISSUE TITLE
Unable to get encrypted images using onGroupImage()

### ISSUE THREAD

**Issue by iNewLegend** [mgp25/Chat-API#1514]
rx  <message from="************-1453199613@g.us" type="media" id="2C0B5346704B4B259059" participant="************@s.whatsapp.net" t="1453219283" notify="Dr">
    rx    <enc v="2" type="skmsg" mediatype="image"> 1853 byte data</enc>
    rx  </message>

There is another way for get encrypted images in groups?

(curve25519+protobuf of course installed and working in text)
Note: Only new groups have encryption (not sure : when it meet some conditions)

**Comment by mgp25** [comment]
@iNewLegend i haven't enabled group images yet, but i'll add it soon

Regards
