### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by sagikarni** [mgp25/Chat-API#1515]
Hello, 
Can i use the api for a "virtua"l agent ?
This "virtual agent" will not send any spam, and willl not be used to invite any user to join any group.
Its only use is the following : when a user invites this virtual agent to join a group, it accepts the invite and send one and only message with a link to this group. This link represents the group official site.
Does this use follows the license ?

**Comment by mgp25** [comment]
@sagikarni You can **only** use this API for personal usage.
