### ISSUE TITLE
PresenceSubscription last=deny

### ISSUE THREAD

**Issue by xiphos91** [mgp25/Chat-API#1516]
I have been using this library for 2 months now (always updated api, I have installed the extensions required), Eveything was working fine until past 3 days then I have faced very strange problem. I stop/start my php script sometimes. The last time I restarted my script it stoped working "consistently".
I have 100 contacts, I send presenceSubscription on them, most of them returns last=deny. I say most of them because it is not consistent. The number which returned last=deny may work in another iteration and the numbers that worked before may stop. And even strange problem is that the number which returned last=deny may work 10 minutes later or 1 hour later, then stop working after another subscribe request.  Each time I loop contacts with sending presence subscriptions, I get different results

```
tx<presence type="subscribe" to="SOMENUMBER@s.whatsapp.net"></presence>
rx<presence from="SOMENUMBER@s.whatsapp.net" type="unavailable" last="deny"></presence>
```

I know that:
-If user disables lastSeen feature in his/her whatsapp via privacy settings then last becomes none, like:
```
rx  <presence from="PHONENUMBER@s.whatsapp.net" type="unavailable" last="none"></presence>
```
-If a number does not exist last become error, like:
```
rx  <presence from="1234@s.whatsapp.net" type="unavailable" last="error"></presence>
```

So, why am I facing this random last=deny issue, I could not see anything in wiki. Also what does last=deny mean ? I tried with api different number, same results. Numbers are not blocked. (Checked with block checker)

P.S. I am using $w->pollMessage() after $w->sendPresenceSubscription() like this:
```php
foreach($contacts as $contact) {
   $w->sendPresenceSubscription($contact);
   $w->pollMessage();
}
while(1) {
  $w->pollMessage();
}
```
Thanks

**Comment by mgp25** [comment]
@xiphos91 i guess you are sending presence subscription too many times and WA server is denying your requests.

Regards

**Comment by xiphos91** [comment]
I thought of that as well but why it does not deny all of them but only some of them ?
