### ISSUE TITLE
Some user having trouble sending whatsapp message to api

### ISSUE THREAD

**Issue by david6055my** [mgp25/Chat-API#1519]
i'm experiencing some cases where some user that unable to sent message to chatapi. 
There's message is mark as 1 grey tick. I've tested using different whatsapp account and it works. This effect only some user. I've already enable encryption protocol to the api.
Thanks a lot!

update: I've deleted the axolotl-xxx.db file and restarted the api, the user able to sent message to chatapi again. Any idea why this happens.

**Comment by mgp25** [comment]
ause the number doesnt have the key to decrypt the message and mark it as read, if not decrypted, only one grey tick

Regards
