### ISSUE TITLE
Android Messages not recieving

### ISSUE THREAD

**Issue by WalterM404** [mgp25/Chat-API#1520]
Hi Guys,

The API works fine here. Exept one thing. iOS  messages are coming trough correctly, but Android messages are not working. There is just 1 tick there.. I have 3 account for WhatsApp CHAT API usage (Personal, testing), and just one account haves this problem.. Suggestion? Very global maybe, i don't have acces to the debug log right now.

**Comment by rogobob** [comment]
@WalterM404 that looks like a decryption issue. Are you sure you have installed protobuf and curve correctly? To my knowledge the difference between iOS and Android comes from the fact that iOS uses a different encryption version still. Without debug log it's just speculation, but deleting the axolotl database file may help.
