### ISSUE TITLE
UntrustedIdentityException after re-installation of whatsapp at one of my contacts

### ISSUE THREAD

**Issue by jonofe** [mgp25/Chat-API#1521]
As already described in the title, I get an UntrustedIdentityException and I think it was due to a re-installation of whatsapp on one of my phones, which is a registered contact of my whatsapi script.
Therefore my questions:
1. Is that correct, that this could be the reason for this exception?
2. if yes: How can I indetify this change and how do I have to react on it (in my script)?

I recovered the problem by deleting the database in wadata, but I want to prevent this kind of exception in the future. What would happen, when I catch the Exception, is there a function how to update the database in the right way?

Thanks in advance for your help.

**Comment by 0xTryCatch** [comment]
Removing the database is the way to do it
