### ISSUE TITLE
checking for block number throwing error everytime

### ISSUE THREAD

**Issue by zzeebbii** [mgp25/Chat-API#1522]
hello, I've downloaded API just now and I'm trying to run "blockChecker.php" inside "examples" folder.
but whenever i run that script on bash i get following output. no matter which SIM number i gave as input
Note: I'm giving a sim number with country code and without zero to check if SIM is blocked or not. Am I giving right input or do I need to input something else?

Wrong identity.
```xml
Array
(
    [cc] => 92
    [in] => __'sim number goes here'__
    [lg] => en
    [lc] => PK
    [id] => ▒▒▒?n#▒ʢ▒+x▒2▒▒▒:▒
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 8956
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /tmp/Chat-API/src/Registration.php:89
Stack trace:
#0 /tmp/Chat-API/examples/blockChecker.php(36): Registration->checkCredentials()
#1 {main}
  thrown in /tmp/Chat-API/src/Registration.php on line 89
```

**Comment by mgp25** [comment]
@zzeebbii if you don't quote things properly, i won't read your issues.

The registered identity is different from the one your and checking credentials. Register with the API
