### ISSUE TITLE
Simple CLI Client - Sending messages with one command?

### ISSUE THREAD

**Issue by capsload** [mgp25/Chat-API#1523]
Hey @mgp25 

Im trying to send a message with "Simple CLI client.php"

u:@#   php -e cli.php 49151xxx test

but i see its only for checking if the number is online or offline.

is there any way to do it with one command?

**Comment by mgp25** [comment]
@capsload `Simple CLI Client` is just an interactive chat, you only need to pass the number you want to chat with:

```
php simpleClient.php <number>
```

And then the interactive chat starts. And you only need to write and press [Enter] to send the message.

Regards

**Comment by capsload** [comment]
Wait, thats not what i wanted, is there any way to use it from the command line? I want it like yowsup, 

yowsup works like this:

./yowsup-cli demos --config bot.conf -s 49151xxxx-1xxx "hello @mgp25"

then the process is closed again.

is there anyway to do it with php? :) interactive chat is not what i wanted :)

**Comment by mgp25** [comment]
@capsload then you need to create your own script or modify some of the examples, and yes you can use it CLI

**Comment by capsload** [comment]
aaah, dont you have something up already? :3 im too dumb for this :(

**Comment by capsload** [comment]
Got. it.

For anyone else who is interested in this:

<?php
require_once('whatsprot.class.php');

$input = var_dump($argv);
$debug = false;

$nickname = 'xxx';
$username = 'xxx';
$password = 'xxx';

$w      = new WhatsProt($username, $nickname, $debug);

$w->connect();
$w->loginWithPassword($password);

$w->sendMessage('491511xxx-141xxx@g.us', "$argv[1]");

?>

Then through CLI, just use php script.php "hello sirs"

**Comment by ddouma** [comment]
Above is not working for me, messages not getting received on the other end. 
Did it worked for you capsload?


But debug says:

tx  <stream:features></stream:features>

tx  <auth user="31682409XXX" mechanism="WAUTH-2">c7da93913331363832343039303138dae335ef949bd9f29d2ccd25364008325198574                                                                                                                       131343533343538363534</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>ee426630879625c29aa0abdf871b1bd73fdbb906</challenge>

tx  <response>dae8dafaa24199606301d4704e74f67e25447508eccbbff58621764508f33bbc40ef97d27d941e5d3333c137f3867fdd042419f9                                                                                                                       5d10ca0f6d181e5c96504a85359244c2cba13af97a90a1c2cd</response>

rx  <success t="1453458684" props="4" kind="free" status="active" creation="1453371713" expiration="4444444444">785bb3                                                                                                                       898bc7fe912a0a3abfb47d00e2323c638f</success>

tx  <presence name="test" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <message to="31682409XXX@s.whatsapp.net" type="text" id="411a27022513a81a3c4f8c" t="1453458654" notify="test">
tx    <enc v="1" type="msg">330a21056c98b341cea948f673d49d254fc3b78a6ed2e1eb9b6a43c1b99b01b36c0c953e100a180122101458ca                                                                                                                       104654793e8d046055492e4ef7b47affe8a6d666d7</enc>
tx  </message>
