### ISSUE TITLE
Number getting blocked after adding participant

### ISSUE THREAD

**Issue by gahlotkrishan** [mgp25/Chat-API#1526]
```javascript
SENT: <iq id="1453315750-2" type="set" xmlns="w:g2" to="91766736xxxx-1453284749@g.us">
SENT:   <add>
SENT:     <participant jid="919x1xxxxx11@s.whatsapp.net"></participant>
SENT:   </add>
SENT: </iq>

RECVD: <stream:error>
RECVD:   <system-shutdown></system-shutdown>
RECVD: </stream:error>
```
If I query groups or send message to group then it's working fine but number got blocked immediately if I fire participant add/remove command. Please guide what's wrong, may be there's some protocol change for adding/removing participant!

**Comment by mgp25** [comment]
@gahlotkrishan i see that debug log is not from the PHP API, its from Chat API .NET, this is only for php

Regards
