### ISSUE TITLE
File permisson on wadata folder

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1530]
Sorry to bother again with the same topic.

nextChallenge.PHONENUMBER.dat shoulbe 777 or 644?

Thanks!

**Comment by edudesouza** [comment]
I explain my question, I am running a php script in CLI mode and once this file is in 644 if I ran a script on the web browser it crashes.

**Comment by VanDevos** [comment]
```chmod 777 -R wadata```
