### ISSUE TITLE
I cant't register any phone number anymore using WART to get a password

### ISSUE THREAD

**Issue by eman1000** [mgp25/Chat-API#1534]
I registerd a number a few days ago using WART and it was working just fine sending whatsapp messages etc, but then it got blocked. I tried to use a new phone number but WART can't register any of the phone numbers. I jus get  an error like the one in the screen shot. My numbers just get blocked when I am just trying to register.

![screen shot 2016-01-21 at 8 44 58 pm](https://cloud.githubusercontent.com/assets/16818188/12480799/e6317a1e-c07f-11e5-8a24-f6b879c0a725.png)

**Comment by mgp25** [comment]
Not WART repo
