### ISSUE TITLE
Pdo error

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1535]
Why am I getting this error (below), since I am not setting to write on sqlite Uncaught exception 

'PDOException' with message 'SQLSTATE[HY000] [14] unable to open
 database file' in /home/v1/src/SqliteMessageStore.php:19

My code

$w 		= new WhatsProt($username, $nickname, $debug, $log, $datafolder);
$events 	= new MyEvents($w);

$w->eventManager()->bind("onMessageReceivedClient", "ReceivedClient");
$w->eventManager()->bind("onMessageReceivedServer", "ReceivedServer");

$w->connect(); 
$w->loginWithPassword($password);

$w->SendPresenceSubscription($to);
$w->sendMessage($to,$mensagem );

try{
	while($w->pollMessage());
}catch(Exception $e){
	echo "Exaception: ".$e;
}

**Comment by mgp25** [comment]
http://lmgtfy.com/?q=SQLSTATE%5BHY000%5D+%5B14%5D+unable+to+opendatabase+file
