### ISSUE TITLE
Uncaught exception 'ConnectionException' 

### ISSUE THREAD

**Issue by VanDevos** [mgp25/Chat-API#1537]
Hello,

I have been using this API for long time. From past 2-3 days I'm experiencing ``` Uncaught exception 'ConnectionException'  ``` error even though using updated API.

Even though after using function I use ``` pollMessage() ``` with loop. This message comes due to pollMessages I guess.

While sending images,vCards or even single message, the following error comes up.
```
Warning: socket_write(): unable to write to socket [32]: Broken pipe in /var/www/html/src/whatsprot.class.php on line 2750
rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>
```

And then at last it closes the connection.

```
Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/src/whatsprot.class.php:299 Stack trace: #0 /var/www/html/index2.php(80): WhatsProt->pollMessage() #1 {main} thrown in /var/www/html/src/whatsprot.class.php on line 299
```
```And finally number blocked..```

The API was working fine for 3-4 months. But from past 2-3 days this error is coming.

Thanks!

**Comment by mgp25** [comment]
Bad behaviour or not related. API working perfectly.
