### ISSUE TITLE
pkmsg

### ISSUE THREAD

**Issue by hurbanores** [mgp25/Chat-API#1539]
When i recive a message i get this response

```xml
 <message from="5215545432291@s.whatsapp.net" type="text" id="95E75E683816AC79FAB" offline="2" t="1453419111" notify="Hector Urbano">
  <enc v="1" type="pkmsg">331221052c830d989dbf18648f132d2248fb26bc0593acdee9ddddb245a89d199cde53161a21059aa84b784b8f5a2f3be5c82908bfdae98ac996079d640207dfca00269fc773642242330a2105d090dc6cc6fd2240b56b79703ee0ecd6af7c5c850963c68580233b3dcc4f164910041800221062a3bcbc29551931f6f99d000ed5cccf0ea90ff7195d5efd28867430a294db05</enc>
</message>
```

I've readed the wiki and install the dependencies but im still can't get the message sucefully

**Comment by mgp25** [comment]
First of all, quote debug properly, this time i'll do it for you, but next time i wont bother to read it.

If the message is not decrypted, then the extensions are not loaded correctly, make sure the extensions are listed when doing `php -m`

Regards

**Comment by TryCatchLoop** [comment]
hurbanores, you can do it dude
?

**Comment by TryCatchLoop** [comment]
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
filter
gd
hash
iconv
json
libxml
mcrypt
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Comment by hurbanores** [comment]
When i run the php -m i recived that

[```]
Warning: PHP Startup: curve25519: Unable to initialize module
Module compiled with module API=20131226
PHP    compiled with module API=20121212
These options need to match
 in Unknown on line 0
[```]

**Comment by oshimin** [comment]
I have the same probleme, when i type `` php -m ``,  i have it : 

```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curve25519
date
dom
ereg
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
odbc
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
protobuf
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug
```

I have installed the extension but i can't already decode the message.

**Comment by oshimin** [comment]
I found the error : composer package is not updated.
