### ISSUE TITLE
Fatal Error: Call to undefined method

### ISSUE THREAD

**Issue by WalterM404** [mgp25/Chat-API#1541]
Hi Guys,

i wanted to use the blockchecker buti am getting an Fatal error:
```
PHP Fatal error:  Call to undefined method WhatsProt::checkCredentials() in /home/watermelon/api/server/blockChecker.php on line 35
``` 
blockchecker.php is executed, i can fill in the number, but then this occurs. In WhatsProt is no function called checkCredentials().. Is this changed in the last weeks?

**Comment by 0xTryCatch** [comment]
Your blockChecker.php is outdated, update it.
