### ISSUE TITLE
how get lastseen in contact sync

### ISSUE THREAD

**Issue by adelp30** [mgp25/Chat-API#1542]
hello
thx for useful api...
i use contactsync and work ok . BUT:
i need after contact sync whatsapp exist get lastseen + (and) get status text(no status send message!)
i read 4 times Requesting 'Last seen' and profile picture :(
but this code do not work
edit events/MyEvents.php and add:

public function onPresenceUnavailable( $mynumber, $from, $last )
{
  echo "Last seen of $id: ".gmdate("H:i:s", $last);

}

$w->sendPresenceSubscription($to);

do not work for me .
my code 
$username = "989353593193";
$nickname = "adel";
$password = "Hb0JwsgUAVV5aGHt/Nj0FUmXXXXX"; // The one we got registering the number
$debug = true;
$w = new WhatsProt($username, $nickname, $debug);
$w->connect(); 
$w->loginWithPassword($password); // logging in with the password we got!
$w->sendPresenceSubscription('989353593193');
and recive
"tx  presence type="subscribe" to="989353593193@s.whatsapp.net  presence"
i uncommented function and add function onPresenceUnavailable  the myevent.
at end i could not found code or api for get status text ....
THX

**Comment by mgp25** [comment]
@adelp30 quote things properly, otherwise i wont read it. Poll messages, you are disconnecting too soon

**Comment by adelp30** [comment]
why you can not read my problem ?
what part of my problem Illegible ???
thanks
