### ISSUE TITLE
API not working on Live server

### ISSUE THREAD

**Issue by Syeda123** [mgp25/Chat-API#1544]
Hello,
I am not able to run this API on live server but on local server I am able to send the messages.
Please help me as it is worthless for me if it is not working on live server.I checked all possible ways to work on live server but failed.
Hoping the best answer that could solve my problem.
Thank You

**Comment by VanDevos** [comment]
Have you installed all dependencies ?
1) PHP >= 5.6
2) All Extensions required

**Comment by Syeda123** [comment]
Thank you for your reply,
1 We have 5.4 version of php
2 yes we have  installed all extensions and modules required.
3 it is in 777 permission.

**Comment by VanDevos** [comment]
I said 5.6
