### ISSUE TITLE
MessageStoreInterface missing required functions

### ISSUE THREAD

**Issue by TimVosch** [mgp25/Chat-API#1547]
Hey,

The WhatsProt class refers to **MessageStoreInterface** as if it always is the **SqliteMessageStore** by calling functions that are not required in the interface:

*Trying to call functions like setPending and getPending, which are not required by the interface*
https://github.com/mgp25/Chat-API/blob/a8bb25d88566117d583f3aa3cea5769175019fc1/src/whatsprot.class.php#L2188

*MessageStore doesn't have to be the SqlliteMessageStore*
```PHP
    public function setMessageStore(MessageStoreInterface $messageStore)
    {
        $this->messageStore = $messageStore;
    }
```
https://github.com/mgp25/Chat-API/blob/a8bb25d88566117d583f3aa3cea5769175019fc1/src/whatsprot.class.php#L1984

I assume the interface just needs to have *getPending etc.* just added to it.

**PS:** To clarify: are 'PendingMessages' messages that where tried to send but the whatsapp server hasn't received/acknowledged?

**Comment by mgp25** [comment]
@TimVosch pending messages are for sending with another version of encryption aka v1 or v2.

If you see something that can be improved or fixed, send a pull request.

Regards

**Comment by TimVosch** [comment]
Ill make a pull request that updates the interface to contain the pending messages but someone needs to add some comments to the functions since i dont understand the working of them.
