### ISSUE TITLE
Problem with sendGetGroups() 

### ISSUE THREAD

**Issue by alpires** [mgp25/Chat-API#1549]
Hi, when I use the sendGetGroups() function the following error occurs:

{"success":false,"type":"contacts","errormsg":""}

It is no longer returning the groups names.
there some issue with this function?

Even In whatsapp.php example the contacts are not listed.
Thanks for some help

**Comment by alpires** [comment]
Update:
The returned code is
{"success":true,"type":"contacts","data":[],"messages":null}
and not 
"success":false,"type":"contacts","errormsg":""}

Some idea?

**Comment by mgp25** [comment]
@alpires post proper debug log in order for support 

Regards

**Comment by alpires** [comment]
Here:

tx  <stream:features></stream:features>

tx  <auth user="5517991324534" mechanism="WAUTH-2">daf8fdcc35353137393931343333373736dec387ee9074f635a59d4e535798c4cff1e2589931343533363732313134</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>35b7b9fc852aa2757710262e6512321f4b4e6949</challenge>

tx  <response>9cba89d94be0774e79314ae2d91389144fc5f295b6c1145afae4b0396c9dd855512236c9bd08a0de8fc7028ae52b03928982a18fc989d36b0b558f62591bbb5760ee62bdaf3617209d51886060c1e2</response>

rx  <success t="1453672115" props="4" kind="free" status="active" creation="1386281449" expiration="4444444444">4c3f481e1773fb62d10b6d08ed0098fd07bf1ab8</success>

tx  <presence name="Alpires" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

{"success":true,"type":"contacts","data":[],"messages":null}

**Comment by alpires** [comment]
Here:

tx  <stream:features></stream:features>

tx  <auth user="5517991433776" mechanism="WAUTH-2">daf8fdcc35353137393931343333373736dec387ee9074f635a59d4e535798c4cff1e2589931343533363732313134</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>35b7b9fc852aa2757710262e6512321f4b4e6949</challenge>

tx  <response>9cba89d94be0774e79314ae2d91389144fc5f295b6c1145afae4b0396c9dd855512236c9bd08a0de8fc7028ae52b03928982a18fc989d36b0b558f62591bbb5760ee62bdaf3617209d51886060c1e2</response>

rx  <success t="1453672115" props="4" kind="free" status="active" creation="1386281449" expiration="4444444444">4c3f481e1773fb62d10b6d08ed0098fd07bf1ab8</success>

tx  <presence name="Alpires" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

{"success":true,"type":"contacts","data":[],"messages":null}

**Comment by alpires** [comment]
Here, in attached file
[log.txt](https://github.com/mgp25/Chat-API/files/102564/log.txt)

**Comment by alpires** [comment]
Here, in attached file
[log.txt](https://github.com/mgp25/Chat-API/files/102565/log.txt)

**Comment by mgp25** [comment]
@alpires i guess you are not polling enough, by the way, `whatsapp.php` example file is outdated, try other examples

Regards

**Comment by alpires** [comment]
Yes, I put pollMessage() after cal the function and works. Thanks
