### ISSUE TITLE
Problem with sendGetGroups()

### ISSUE THREAD

**Issue by alpires** [mgp25/Chat-API#1550]
Hi, when I use the sendGetGroups() function the following error occurs:

{"success":true,"type":"contacts","data":[],"messages":null}

It is no longer returning the groups names.
there some issue with this function?

Even In whatsapp.php example the contacts are not listed.
Thanks for some help

See debug log in attached log
[log.txt](https://github.com/mgp25/Chat-API/files/102566/log.txt)

**Comment by mgp25** [comment]
@alpires why do you open a new issue? Stick to #1549
