### ISSUE TITLE
Getting fatal error: Call to undefined method  Server\DB\MessageStore::getPending()

### ISSUE THREAD

**Issue by cezdev** [mgp25/Chat-API#1552]
Hi there!

When I start the server in debug mode, and am trying to receive whatsapp messages to the server, I constantly am getting this fatal error. 

<pre><code>
PHP Fatal error:  Call to undefined method Server\DB\MessageStore::getPending() in 
/home/whatsapp/api/assets/whatsapp/whatsprot.class.php on line 3029
</pre></code>

What can I do to resolve this issue? thanks in advance

**Comment by 0xTryCatch** [comment]
Did you create your own MessageStore?

**Comment by cezdev** [comment]
Yes I did, and I added the new functions for setPending and getPending messages. Now I get a different error :

<pre><code>
PHP Fatal error:  Call to a member function nodeString() on null in /home/whatsapp/api/assets/whatsapp/protocol.class.php on line 179
</pre></precode>

I have the feeling I'm getting close to solving it.

**Comment by 0xTryCatch** [comment]
Show your debug log and code please

**Comment by cezdev** [comment]
Composing email right now. I will send it a minute or 2!

**Comment by TriPSs** [comment]
Created an pull request who solves this.

#1554

**Comment by cezdev** [comment]
Thanks! Fixed it.
