### ISSUE TITLE
not-autorized issue

### ISSUE THREAD

**Issue by yoannboxtel** [mgp25/Chat-API#1556]
Please can you tell me why have you placed my issue to outdated ? i just want an answer to my issue but you closed it without reason...........

**Comment by mgp25** [comment]
@yoannboxtel `not-authorized` means the number is blocked, this can also happen when having and outdted source or wrong password, that's it, take your time to read closed issues and the wiki

**Comment by yoannboxtel** [comment]
OK thank you !
