### ISSUE TITLE
Sending recorded media.

### ISSUE THREAD

**Issue by VanDevos** [mgp25/Chat-API#1560]
Hello, 

Is there any function which sends audio as a ``` Recorded Audio ``` form ? Though we can send audio but it would be better if we can send that audio in record audio form.

Thanks!

**Comment by mgp25** [comment]
Have you searched in closed issues? because there is an issue about that and the solution is in there.

Regards

**Comment by VanDevos** [comment]
Yeah I searched a lot but couldn't find. Searched with ``` record ``` ```record media```
