### ISSUE TITLE
Message just 1 tick and errors.

### ISSUE THREAD

**Issue by WalterM404** [mgp25/Chat-API#1562]
Hey Guys,

I get this error when i send an message to my testnumber.

-> Decrypted Message: No such signedprekey with id: 37743 - /home/whatsappserv/api/assets/whatsapp/SqliteAxolotlStore.php - 246Message E768DAE26897689F3A1F could not be decrypted, sending retry.

PHP Fatal error:  Call to undefined method Server\DB\MessageStore::getPending() in /home/whatsappserv/api/assets/whatsapp/whatsprot.class.php on line 3029
webedit@dev01:/home/whatsappserv/api/server$ tx  <stream:features></stream:features>

Everything is correcly loaded, en not all of my scripts (Some testing) does have this problem. I have deleted the axolotl DB file. What can i do?  I have te debug log if you want.

**Comment by mgp25** [comment]
You are using a modified version of the API, we don't give support to modifications, only API issues
