### ISSUE TITLE
CLIENT CLI - Number

### ISSUE THREAD

**Issue by Hawkz69** [mgp25/Chat-API#1564]
Hello! I 'm from Brazil , new programmer in php .

I am using Client CLI example to make a bot, it worked with a number that I put ( php simpleClient.php <number > )

Would like to know
How do I use different numbers at the same time ?
Is there a way to capture the number of user , when he sent me a message ?
Please help .

Congratulations for your work mgp25 , is there any way to contribute to the project or make a donation ?

thank you

**Comment by mgp25** [comment]
Check examples and wiki

Regards

**Comment by mgp25** [comment]
Çv–

**Comment by Hawkz69** [comment]
I check wiki and examples. I did not find it.
So I asked for help. I am new to php.
thank you

**Comment by mgp25** [comment]
We solve API issues, not PHP

**Comment by Hawkz69** [comment]
OK, thank you

**Comment by lucasmazevedo** [comment]
@Hawkz69 você é brasileiro? estou trabalhando em um projeto com esta API, caso queria compartilhar conhecimentos sobre ela, lucazmazevedo@gmail.com
