### ISSUE TITLE
Fatal error trying to read inbound messages Maximum function nesting level of '256' reached, aborting! in \src\BinTreeNodeReader.php on line 422

### ISSUE THREAD

**Issue by alemdg** [mgp25/Chat-API#1568]
Fatal error: Maximum function nesting level of '256' reached, aborting! in \src\BinTreeNodeReader.php on line 422

Call Stack:
    0.0240     141680   1. {main}() send.php:0
   18.8671    2918696   2. WhatsProt->pollMessage() send.php:121
   19.8551    2919336   3. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   19.8661    2921152   4. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   19.8671    2921168   5. MessageHandler->Process() \src\whatsprot.class.php:2381
   19.8671    2921216   6. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   19.8721    2921776   7. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   19.8721    2922264   8. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   19.8771    2924168   9. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   21.9193    2931728  10. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   21.9193    2932368  11. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   21.9303    2934184  12. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   21.9303    2934216  13. MessageHandler->Process() \src\whatsprot.class.php:2381
   21.9313    2934264  14. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   21.9353    3000320  15. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   22.0933    3000688  16. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   53.4931    3041240  17. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:477
   53.4931    3041272  18. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   53.4931    3041912  19. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   53.5051    3043728  20. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   53.5051    3043776  21. MessageHandler->Process() \src\whatsprot.class.php:2381
   53.5051    3043824  22. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   53.5101    3044384  23. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   53.5111    3044672  24. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   53.5151    3046440  25. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   53.5221    3046568  26. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   53.5221    3047208  27. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   53.5351    3049024  28. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   53.5361    3049040  29. MessageHandler->Process() \src\whatsprot.class.php:2381
   53.5361    3114584  30. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   53.5411    3115144  31. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   53.5411    3115248  32. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   53.5461    3117096  33. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   53.9551    3117208  34. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   53.9551    3117888  35. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   53.9691    3123344  36. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   53.9701    3123376  37. IqHandler->Process() \src\whatsprot.class.php:2381
   54.1871    3124312  38. MessageHandler->Process() \src\handlers\IqHandler.php:274
   54.1871    3124360  39. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   54.1921    3124920  40. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   54.3421    3126168  41. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   54.3421    3126200  42. WhatsProt->resetEncryption() \src\whatsprot.class.php:444
   61.1195    3125072  43. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:432
   61.1195    3190600  44. MessageHandler->Process() \src\whatsprot.class.php:2381
   61.1205    3190680  45. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   61.1245    3191240  46. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   61.1255    3191560  47. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   61.1295    3193408  48. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   61.4615    3193520  49. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   62.0425    3194200  50. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   62.0575    3199656  51. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   62.0585    3199688  52. IqHandler->Process() \src\whatsprot.class.php:2381
   62.6716    3201488  53. MessageHandler->Process() \src\handlers\IqHandler.php:274
   62.6726    3201536  54. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   62.6766    3267592  55. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   62.6776    3267960  56. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   62.6816    3269808  57. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   62.6816    3269840  58. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   63.4856    3270528  59. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   63.5006    3275984  60. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   63.5016    3276032  61. IqHandler->Process() \src\whatsprot.class.php:2381
   63.7336    3276968  62. MessageHandler->Process() \src\handlers\IqHandler.php:274
   63.7336    3277016  63. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   63.7386    3277576  64. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   63.8967    3278088  65. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   63.9057    3279720  66. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:477
   63.9057    3279816  67. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   63.9057    3280456  68. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   63.9177    3282272  69. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   63.9177    3347816  70. MessageHandler->Process() \src\whatsprot.class.php:2381
   63.9177    3347864  71. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   63.9227    3348424  72. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   63.9227    3348840  73. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   63.9267    3350688  74. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   64.1497    3350816  75. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   64.3387    3351488  76. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   64.3527    3356944  77. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   64.3537    3356960  78. IqHandler->Process() \src\whatsprot.class.php:2381
   64.5447    3357896  79. MessageHandler->Process() \src\handlers\IqHandler.php:274
   64.5457    3357944  80. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   64.5497    3424000  81. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   64.7507    3425040  82. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   64.7507    3425072  83. WhatsProt->resetEncryption() \src\whatsprot.class.php:444
   64.7517    3424936  84. WhatsProt->sendSetPreKeys(???) \src\whatsprot.class.php:425
   65.9168    3780992  85. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:381
   65.9168    3781088  86. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   65.9178    3781728  87. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   65.9288    3783544  88. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   65.9288    3783592  89. MessageHandler->Process() \src\whatsprot.class.php:2381
   65.9288    3783640  90. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   66.5228    3784200  91. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   66.5238    3784664  92. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   66.5278    3786512  93. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   66.5298    3786624  94. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   67.1078    3787296  95. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   67.1228    3792752  96. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   67.1238    3858280  97. IqHandler->Process() \src\whatsprot.class.php:2381
   67.8279    3860400  98. MessageHandler->Process() \src\handlers\IqHandler.php:274
   67.8279    3860512  99. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   67.8329    3861072 100. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   67.8329    3861584 101. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   67.8369    3863432 102. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   67.8369    3863464 103. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   68.6389    3864136 104. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   68.6529    3869592 105. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   68.6539    3869640 106. IqHandler->Process() \src\whatsprot.class.php:2381
   68.9249    3936072 107. MessageHandler->Process() \src\handlers\IqHandler.php:274
   68.9249    3936120 108. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   68.9299    3936680 109. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   69.1380    3937184 110. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   69.1470    3938816 111. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:477
   69.1470    3938912 112. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   69.1470    3939552 113. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   69.1610    3941368 114. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   69.1620    3941416 115. MessageHandler->Process() \src\whatsprot.class.php:2381
   69.1620    3941464 116. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   69.1660    3942024 117. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   69.1670    3942584 118. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   69.1710    3944432 119. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   69.3570    3944560 120. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   69.9380    3945232 121. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   69.9530    4016184 122. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   69.9540    4016200 123. IqHandler->Process() \src\whatsprot.class.php:2381
   70.1170    4017136 124. MessageHandler->Process() \src\handlers\IqHandler.php:274
   70.1180    4017184 125. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   70.1220    4017744 126. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   70.2810    4018784 127. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   70.2810    4018816 128. WhatsProt->resetEncryption() \src\whatsprot.class.php:444
   70.2820    4018680 129. WhatsProt->sendSetPreKeys(???) \src\whatsprot.class.php:425
   71.3781    4440208 130. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:381
   71.3781    4440304 131. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   71.3781    4440944 132. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   71.3891    4442760 133. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   71.3901    4508304 134. MessageHandler->Process() \src\whatsprot.class.php:2381
   71.3901    4508352 135. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   71.6441    4508912 136. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   71.6451    4509552 137. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   71.6491    4511400 138. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   71.6511    4511512 139. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   72.3911    4512184 140. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   72.4071    4517640 141. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   72.4081    4517672 142. IqHandler->Process() \src\whatsprot.class.php:2381
   73.0432    4519792 143. MessageHandler->Process() \src\handlers\IqHandler.php:274
   73.0432    4519840 144. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   73.0482    4585896 145. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   73.0482    4586584 146. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   73.0522    4588432 147. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   73.0522    4588464 148. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   73.8472    4589136 149. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   73.8622    4594592 150. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   73.8632    4594640 151. IqHandler->Process() \src\whatsprot.class.php:2381
   74.0992    4595576 152. MessageHandler->Process() \src\handlers\IqHandler.php:274
   74.0992    4595624 153. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   74.1042    4596184 154. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   74.3233    4596688 155. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   74.3323    4598320 156. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:477
   74.3323    4598416 157. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   74.3323    4599056 158. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   74.3433    4600872 159. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   74.3433    4666416 160. MessageHandler->Process() \src\whatsprot.class.php:2381
   74.3443    4666464 161. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   74.3483    4667024 162. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   74.3493    4667760 163. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   74.3533    4669608 164. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   74.5253    4669736 165. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   75.0923    4670408 166. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   75.1073    4675864 167. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   75.1083    4675880 168. IqHandler->Process() \src\whatsprot.class.php:2381
   75.2673    4676816 169. MessageHandler->Process() \src\handlers\IqHandler.php:274
   75.2673    4676864 170. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   75.2723    4742920 171. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   75.4063    4743960 172. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   75.4063    4743992 173. WhatsProt->resetEncryption() \src\whatsprot.class.php:444
   75.4073    4743856 174. WhatsProt->sendSetPreKeys(???) \src\whatsprot.class.php:425
   76.6674    5099864 175. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:381
   76.6674    5099960 176. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   76.6684    5100600 177. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   76.6794    5102416 178. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   76.6794    5102464 179. MessageHandler->Process() \src\whatsprot.class.php:2381
   76.6794    5102512 180. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   76.9714    5103072 181. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   76.9724    5103856 182. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   76.9764    5105704 183. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   76.9794    5105816 184. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   77.7004    5106496 185. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   77.7144    5111952 186. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   77.7164    5177480 187. IqHandler->Process() \src\whatsprot.class.php:2381
   78.3135    5179608 188. MessageHandler->Process() \src\handlers\IqHandler.php:274
   78.3135    5179656 189. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   78.3185    5180216 190. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   78.3195    5181048 191. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   78.3235    5182896 192. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   78.3235    5182928 193. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   79.1435    5183608 194. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   79.1585    5189064 195. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   79.1595    5189112 196. IqHandler->Process() \src\whatsprot.class.php:2381
   79.3825    5255544 197. MessageHandler->Process() \src\handlers\IqHandler.php:274
   79.3825    5255592 198. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   79.3875    5256152 199. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   79.6286    5256664 200. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   79.6376    5258296 201. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:477
   79.6376    5258392 202. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   79.6376    5259032 203. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   79.6486    5260848 204. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   79.6486    5260896 205. MessageHandler->Process() \src\whatsprot.class.php:2381
   79.6486    5260944 206. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   79.6546    5261504 207. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   79.6546    5262384 208. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   79.6586    5264232 209. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   79.8316    5264360 210. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   80.4076    5265040 211. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   80.4226    5335992 212. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   80.4236    5336008 213. IqHandler->Process() \src\whatsprot.class.php:2381
   80.5826    5336944 214. MessageHandler->Process() \src\handlers\IqHandler.php:274
   80.5836    5336992 215. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   80.5876    5337552 216. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   80.7466    5338600 217. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   80.7466    5338632 218. WhatsProt->resetEncryption() \src\whatsprot.class.php:444
   80.7476    5338496 219. WhatsProt->sendSetPreKeys(???) \src\whatsprot.class.php:425
   81.8597    5825576 220. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:381
   81.8597    5825672 221. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   81.8597    5826312 222. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   81.8717    5828128 223. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   81.8717    5893672 224. MessageHandler->Process() \src\whatsprot.class.php:2381
   81.8717    5893848 225. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   82.1327    5894408 226. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   82.1327    5895336 227. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   82.1367    5897184 228. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   82.1397    5897296 229. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   82.8787    5897976 230. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   82.8937    5903432 231. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   82.8947    5903464 232. IqHandler->Process() \src\whatsprot.class.php:2381
   83.5658    5905592 233. MessageHandler->Process() \src\handlers\IqHandler.php:274
   83.5658    5905640 234. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   83.5708    5971696 235. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   83.5708    5972672 236. WhatsProt->sendGetCipherKeysFromUser(???, ???) \src\handlers\MessageHandler.php:386
   83.5748    5974520 237. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:416
   83.5758    5974552 238. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   84.5648    5975232 239. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   84.5798    5980688 240. WhatsProt->processInboundDataNode(???) \src\whatsprot.class.php:2089
   84.5808    5980736 241. IqHandler->Process() \src\whatsprot.class.php:2381
   84.7398    5981672 242. MessageHandler->Process() \src\handlers\IqHandler.php:274
   84.7398    5981720 243. MessageHandler->processMessageNode(???) \src\handlers\MessageHandler.php:38
   84.7448    5982280 244. MessageHandler->processEncryptedNode(???) \src\handlers\MessageHandler.php:309
   84.9029    5982800 245. WhatsProt->sendRetry(???, ???, ???, ???, ???) \src\handlers\MessageHandler.php:403
   84.9119    5984432 246. WhatsProt->waitForServer(???, ???) \src\whatsprot.class.php:477
   84.9119    5984528 247. WhatsProt->pollMessage() \src\whatsprot.class.php:1802
   84.9329    5985168 248. WhatsProt->processInboundData(???) \src\whatsprot.class.php:311
   84.9329    5985168 249. BinTreeNodeReader->nextTree(???) \src\whatsprot.class.php:2087
   84.9399    5985560 250. BinTreeNodeReader->nextTreeInternal() \src\BinTreeNodeReader.php:43
   84.9399    5985664 251. BinTreeNodeReader->readAttributes(???) \src\BinTreeNodeReader.php:297
   84.9399    5985920 252. BinTreeNodeReader->readString(???) \src\BinTreeNodeReader.php:270
   84.9399    5986000 253. BinTreeNodeReader->readString(???) \src\BinTreeNodeReader.php:144
   84.9399    5986048 254. BinTreeNodeReader->readPacked8(???) \src\BinTreeNodeReader.php:156
   84.9399    5986048 255. BinTreeNodeReader->readInt8() \src\BinTreeNodeReader.php:180
   84.9399    5986048 256. BinTreeNodeReader->peekInt8(???) \src\BinTreeNodeReader.php:432

**Comment by mgp25** [comment]
Your are trying to manage too much data. API cant handle it

**Comment by alemdg** [comment]
I sent 2 messages with 4 characters each one, from my phone to the chatapi

**Comment by alemdg** [comment]
this error started to happen by my fault.
I sent a message from chatapi configured with a xxxxxx phone number to the SAME xxxxxx phone number, after that, i chatapi can not read or send messages, because this recursive pollmessage error.

**Comment by alemdg** [comment]
I fixed it deleting both local .db from wadata
