### ISSUE TITLE
Return to issuses #1561

### ISSUE THREAD

**Issue by sadistdimaz** [mgp25/Chat-API#1569]
Hello.

Return to issues <a href="https://github.com/mgp25/Chat-API/issues/1561">#1561</a>

I remove all axolotl .db and make test 1 day work all okay. But now problem returns. 

<pre>
[2016-01-26 23:27:22] [DEBUG]: rx  &#060;chatstate from="XXX132757XXX@s.whatsapp.net"&#062;
rx    &#060;paused&#062;&#060;/paused&#062;
rx  &#060;/chatstate&#062;
[2016-01-26 23:27:25] [DEBUG]: rx  &#060;message from="XXX132757XXX@s.whatsapp.net" type="text" id="6F7064844C2A0D0D4D0" t="1453839776" notify="Hola"&#062;
rx    &#060;enc v="2" type="pkmsg"&#062;3308c3809106122105ce469af3dcc6e3418e496c6a017adc1d2ca28adbcc18a45c7b4dbe14f6d9a3671a210544b6345fb81122123a3a37e032524cc20ae632ee1db256e6fd1c78ecffc662722252330a2105f7e58d1a56daa11eb4378eae6e6faae8cada6b809634a8c780d3c8a6eb662c0b1000180022203716317b81db1fdca66fed60a576ceeb08b221a4873837a02d2732677a7d9301f824103ede585265289cbeb1b60630fdf203&#060;/enc&#062;
rx  &#060;/message&#062;
[2016-01-26 23:27:25] [DEBUG]: tx  &#060;ack to="XXX132757XXX@s.whatsapp.net" class="message" id="6F7064844C2A0D0D4D0" t="1453839776"&#062;&#060;/ack&#062;
[2016-01-26 23:27:25] [INFO]: Requesting cipher keys from XXX132757XXX
[2016-01-26 23:27:25] [DEBUG]: tx  &#060;iq id="54" xmlns="encrypt" type="get" to="s.whatsapp.net"&#062;
tx    &#060;key&#062;
tx      &#060;user jid="XXX132757XXX@s.whatsapp.net"&#062;&#060;/user&#062;
tx    &#060;/key&#062;
tx  &#060;/iq&#062;
[2016-01-26 23:34:19] [DEBUG]: rx  &#060;iq from="s.whatsapp.net" type="result" id="5b"&#062;
rx    &#060;list&#062;
rx      &#060;user jid="XXX132757XXX@s.whatsapp.net"&#062;
rx        &#060;registration&#062;66cc5f1c&#060;/registration&#062;
rx        &#060;type&#062;05&#060;/type&#062;
rx        &#060;identity&#062;44b6345fb81122123a3a37e032524cc20ae632ee1db256e6fd1c78ecffc66272&#060;/identity&#062;
rx        &#060;skey&#062;
rx          &#060;id&#062;000000&#060;/id&#062;
rx          &#060;value&#062;6b9d8efa5d4e1aca68ef0cacd12ae6fabf425ac71b2f3c0e3fd96139ce54432f&#060;/value&#062;
rx          &#060;signature&#062;fa88fe3526819e21b7530f6151529e5db5661dab64d4b65b2a0a24ffe2b5b9607695ea0b555447554133f6308441624a2fe6730d4243c036742c8a9e31ee478b&#060;/signature&#062;
rx        &#060;/skey&#062;
rx        &#060;key&#062;
rx          &#060;id&#062;9d17f0&#060;/id&#062;
rx          &#060;value&#062;0dcaec4b91a4866538751037f412c6549864469ae38889af6b2631fea07cde52&#060;/value&#062;
rx        &#060;/key&#062;
rx      &#060;/user&#062;
rx    &#060;/list&#062;
rx  &#060;/iq&#062;
</pre>

Again too much time.

2016-01-26 23:27:25 - Reqest key
2016-01-26 23:34:19 - Answer key

This is an isolated case of all other answers come instantly and messges decrypt ok!
Maybe there is a timeout for that?

How often it is necessary to clean the dB. it depends on the number of messages, or ...?

Thanks for all.

**Comment by mgp25** [comment]
Not API issue, ideally DB shouldnt be removed

**Comment by sadistdimaz** [comment]
Why after received key, no posts about decrypted in log and debug, as it happens when the keys come at the same time? 

I would be grateful for your help in this matter!
