### ISSUE TITLE
Use functions variable out side

### ISSUE THREAD

**Issue by AloneMate** [mgp25/Chat-API#1571]
Hello,

I have a serious problem of accessing group id list out of the function.
```
<?php

require_once('src/whatsprot.class.php');
require_once('src/events/MyEvents.php');
require_once('src/events/AllEvents.php');

$get_grouplist = "";

    function onGetGroups($mynumber, $groupList)
    {
           //This works perfectly 
           print_r($groupList);
            //This doesnt work
            $get_grouplist = $groupList;
    }

  
    $username = "XXXXXXXXXXX";
    $nickname = "XXXXXXXXXXX";
    $password = "XXXXXXXXXXX";
    $debug = false;

    $w = new WhatsProt($username, $nickname, $debug);
    $events = new MyEvents($w);
    $w->eventManager()->bind("onGetGroups", "onGetGroups");
    $w->connect(); 
    $w->loginWithPassword($password); 

        for($i=0;$i<=5;$i++)
   {
     $w->pollMessage();
  }    
  $w->sendGetGroups();

   // I can not access group list here. It shows an error.

   print_r($get_grouplist );

```

**Comment by mgp25** [comment]
Not API issue

Regards

**Comment by AloneMate** [comment]
@mgp25  mate  In stead of writing "Not related issue regards" you could answer it in one sentence.
Thanks anyway.

**Comment by mgp25** [comment]
Oks, as your request, i answer you in one sentence.

Google is your friend: https://www.google.es/ You will find all solutions to PHP issues in there.

Keep in mind that this is a very big repository and only 2 people maintain all this, we can't spend time answering question with non-related topics, so we instead stick to the ones related to the API. But this is something that is explained in the readme, wiki, and #556.

Regards
