### ISSUE TITLE
"contacts" notification and presence (un)subscription behaviour

### ISSUE THREAD

**Issue by rogobob** [mgp25/Chat-API#1573]
I think I found out something weird in how ```onNumberWasRemoved``` works and if I am right the flow for handling "contacts" notifications in the wiki and the NotificationHandler.php may need to be updated.

Today I got an issue where messages were not being received from a certain number. I checked the logs and it turns out a presence unsubscription was sent and a subscription was not sent afterwards. 
My code follows the <a href="https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#presence-subscriptionunsubscription">wiki flow for presence (un)subscription</a>. Here is the log (OTHERPHONE is the number with missing messages) with step-by-step interpretation:

```
*** The number made some change to its WhatsApp account
rx  <notification from=""OTHERPHONE@s.whatsapp.net"" type=""contacts"" id=""944238211"" t=""1453886403"">
rx    <update jid=""OTHERPHONE@s.whatsapp.net""></update>
rx  </notification>

*** Handling onNumberWasUpdated():
***** 1. unsubscribe from presence
***** 2. subscribe to presence
***** 3. call sendGetStatuses()
***** 4. call sendGetProfilePicture()
tx  <presence type=""unsubscribe"" to=""OTHERPHONE@s.whatsapp.net""></presence>
tx  <presence type=""subscribe"" to=""OTHERPHONE@s.whatsapp.net""></presence>

tx  <iq to=""s.whatsapp.net"" type=""get"" xmlns=""status"" id=""03fe"">
tx    <status>
tx      <user jid=""OTHERPHONE@s.whatsapp.net""></user>
tx    </status>
tx  </iq>

tx  <iq id=""03ff"" type=""get"" xmlns=""w:profile:picture"" to=""OTHERPHONE@s.whatsapp.net"">
tx    <picture type=""preview""></picture>
tx  </iq>

*** Automatic ack to the "update" notification
tx  <ack to=""OTHERPHONE@s.whatsapp.net"" class=""notification"" id=""944238211"" type=""contacts""></ack>

*** (!) The unsubscription above triggers a "remove" contact notification which triggers "onNumberWasRemoved()" event. The "from" is MY number, so it means unsubscription removes the contact from my contact list
rx  <notification from=""MYPHONE@s.whatsapp.net"" type=""contacts"" id=""2533762904"" t=""1453886403"">
rx    <remove jid=""OTHERPHONE@s.whatsapp.net""></remove>
rx  </notification>

*** onNumberWasRemoved() is handled, and it unsubscribes from the contact for the second time, and marks him as non-existent from whatsapp (which is incorrect - he exists but I removed him from the contact list)
tx  <presence type=""unsubscribe"" to=""OTHERPHONE@s.whatsapp.net""></presence>
```

So, here's the weird thing I see:
```sendPresenceUnsubscription()``` triggers ```onNumberWasRemoved()``` but  ```sendPresenceSubscription()``` does not trigger ```onNumberWasAdded()```. So the number is never re-subscribed. That's OK if whatsapp handles it this way but it means I should only unsubscribe from presence if I get a "remove" notification from the OTHER phone, not if I removed it from MY phone. Currently there is no way to get the "from" parameter of the notification (who triggered it) and I think it should be included in ```onNumberWasRemoved / Updated / Added```. Am I understanding things correctly? Should I change how I'm doing things?

Regards

**Comment by mgp25** [comment]
Presence unsubscription is sent when the number was removed, you should receive a notification telling that. When the number was updated or added, is not required to subscribe to it. Norma behaviour.

**Comment by rogobob** [comment]
@mgp25 ok, If it's normal behaviour then correct the wiki ("When to subscribe for presence" and "When to unsubscribe for presence")

**Comment by rogobob** [comment]
@mgp25 As explained here I should unsubscribe and subscribe again. <a href="https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes">https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes</a>. Is this correct?
