### ISSUE TITLE
Read but don't send

### ISSUE THREAD

**Issue by catnap1974** [mgp25/Chat-API#1574]
Hi i use the new version of chat-api ed i have installed on myserver
protobuf  version 0.9 and curve25519 support is enabled

i recive the message from user but i can't send attach a file and screen

only ffmpeg not is installed on my server is necessary?

Thanx in advance
![screen1](https://cloud.githubusercontent.com/assets/10775962/12620308/1ac0a796-c51c-11e5-9531-93104674290b.jpg)
![screen2](https://cloud.githubusercontent.com/assets/10775962/12620316/1f36cd64-c51c-11e5-9eba-deb8f7e74868.jpg)

[debugger.txt](https://github.com/mgp25/Chat-API/files/106955/debugger.txt)

**Comment by catnap1974** [comment]
Re attach screen
![screen1](https://cloud.githubusercontent.com/assets/10775962/12620929/9772ce2a-c51e-11e5-8b6b-36fe93f31dbd.jpg)
![screen2](https://cloud.githubusercontent.com/assets/10775962/12620931/9c3dc216-c51e-11e5-9f49-4b719c3d833b.jpg)

**Comment by mgp25** [comment]
If everything is installed correctly. Then, you are not syncing users.

Regards
