### ISSUE TITLE
How to block a contact?

### ISSUE THREAD

**Issue by gahlotkrishan** [mgp25/Chat-API#1576]
I'm wondering how to block someone using API requests. I tried presence unsubscribe but I think it's not for blocking a contact number.
Please guide...

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L1591

Regards

**Comment by gahlotkrishan** [comment]
@mgp25  Thanks bro for quick response & help
