### ISSUE TITLE
Can't register a number

### ISSUE THREAD

**Issue by agossouvi** [mgp25/Chat-API#1585]
When I tried to register a number with exampleRegister.php , I get this error  : 
Fatal error: Uncaught exception 'Exception' with message 'The provided phone number is not valid.

**Comment by mgp25** [comment]
Read, the error `The provided phone number is not valid.`

**Comment by agossouvi** [comment]
@mgp25 please be patient... The number is correct. I can send it to you.

**Comment by mgp25** [comment]
@agossouvi send debug log

**Comment by agossouvi** [comment]
Due to Fatal error I can't get debug log.

Fatal error: Uncaught exception 'Exception' with message 'The provided phone number is not valid.' in Registration.php:197 Stack trace: #0 exampleRegister.php(43): Registration->codeRequest('sms') #1 {main} thrown in Registration.php on line 197

**Comment by mgp25** [comment]
_sigh..._ use `registrationTool.php` CLI script

**Comment by agossouvi** [comment]
@mgp25 Same error !
![error-number](https://cloud.githubusercontent.com/assets/17027648/12755490/ff0c4c0e-c9cf-11e5-9d80-41cf901fa2d7.jpg)
I send you an email
Thanks !
