### ISSUE TITLE
on check  a number is registered on whatsapp 

### ISSUE THREAD

**Issue by fares-coder** [mgp25/Chat-API#1586]
Hello
thank you for your hard work on this script .
i am using script on my special number but i have more than 500 contacts !
so i need to know how many numbers can i checked at one time ?

a waiting your reply
Thanks .

**Comment by gi097** [comment]
This is a question, not an issue. I don't know how many contacts are allowed to the server, but remember, don't do too weird things.

**Comment by fares-coder** [comment]
Thank you for your reply .
can any one help on this ?

**Comment by viniciusjarina** [comment]
@fares-coder it seems you have a lot of friends :stuck_out_tongue_winking_eye:  you should be more selective with your friendships

**Comment by fares-coder** [comment]
@viniciusjarina
haha 
do you use this api ?

**Comment by viniciusjarina** [comment]
Yep, you should use **judiciously**.
This is a good tool to send and receive messages from your actual friends, not for spamming or mailing
:wink:
