### ISSUE TITLE
Untrusted Identity related to #1204 and #1178

### ISSUE THREAD

**Issue by JJF2** [mgp25/Chat-API#1587]
Sometimes I have Untrusted Identity exception.
Every time it happen, I delete axolotl.db and restart but to me this don't seems the right way.

Why recycle the whole db? There are no ways to handle the exception and refresh only the changed identity?

**Comment by archergod** [comment]
I am about to open a similar ticket, I do not have untrusted identity, but session related error, where it doesn't found unique session just after login and the solution is to delete the db files and start over. It seems that either Whatsapp server change something.

**Comment by PViva** [comment]
Hi, I had to create a method in which any action to delete the axolotl-xxxxxxxxx.db file 'src / Wadata', is not the best way to go, but settled temporarily.

**Comment by JJF2** [comment]
Maybe I'm wrong but I don't think deleting db too often is a good idea.
This cause the api to send again all the keys and I think it can be a suspect behaviour.

**Comment by PViva** [comment]
is true, this file is some settings that are losing worked ... 
when the conversation was not as dynamic.

**Comment by JJF2** [comment]
Happened again an'hour ago.
I made an experiment: instead of deleting the whole axolotl.db, I edited the tables"identities" and "sessions" removing the records relative to the offending number. 
After restarting the script, the api recreated the two records and all seems to work.

Is there a way do do this automatically?

**Comment by archergod** [comment]
Deleting file is what we do, but no real reason is known for this.

**Comment by AloneMate** [comment]
It wont happen if you use latest code. And also it happens when you use same number on phone and on pc or vps.

**Comment by archergod** [comment]
Well, my code is latest and we do not use our number on Phone, we only use them through our scripts. and script is coded that once a number is connected to whatsapp it do not reconnect same number again, however it might get reconnect to same number within 2 minutes of time of last connection. Do you think this is why it is not clearly session or picking old session. 

Also, `disconnect()` function never run for me, it always give socket error, so we are not disconnecting, maybe that is the problem then?

**Comment by AloneMate** [comment]
Post your code because it's working fine for me.

**Comment by archergod** [comment]
Code is working for me, it just generate the issue lately about a week ago. I am not in office right now, will send you code later.

**Comment by JJF2** [comment]
@AloneMate 
>It wont happen if you use latest code. 
>And also it happens when you use same number on phone and on pc or vps.

Don't post random solutions!
If you never had the issue you neither know what you're talking about.

**Comment by archergod** [comment]
@gi097 you simply disable the Check, can you explain why this check was there and why it is not needed. If check is there it must have a reason.

**Comment by gi097** [comment]
@archergod when you look at the WA source, they do the same. It is wrong but true.

**Comment by archergod** [comment]
What you mean by WA Source, please refer the file name you says "they are doing same".

**Comment by PViva** [comment]
Worked for 10 minutes to me @ gi097, I have to delete axolotl-xxxxxxxxx.db to send a message, is there anything else to do?

**Comment by JJF2** [comment]
Four disappeared posts! What's going on

**Comment by JJF2** [comment]
OK
