### ISSUE TITLE
How Watools doesn't get blocked?

### ISSUE THREAD

**Issue by dishark** [mgp25/Chat-API#1589]
Hi, i want to build a tool that works like watools does. However, i'm aware that whenever i register a certain amount of numbers i eventually get my IP address blocked (then i switch and continue on). Is there a way to don't get blocked? Could anyone explain the solution used on watools? 

Thank you.

**Comment by mgp25** [comment]
WATools was made with :heart: by @mgp25 and it uses some kind of black magic.

Jokes aside, it uses the same as explained in the wiki and examples, nothing new.

Regards

**Comment by dishark** [comment]
And how do you manage to don't get blocked? If you don't mind to answer.
