### ISSUE TITLE
Bad Mac! Bad Mac! No valid sessions

### ISSUE THREAD

**Issue by cpussetto** [mgp25/Chat-API#1591]
Hey there
I'm having problems when receiving messages from certain numbers.
a) I upgraded to the latest commit api chat
b) I have active libraries
curve25519 support enabled
Version 0.9 protobuf ok

Some numbers are OK, for example the following debug

--
rx  [chatstate from="5493515106772@s.whatsapp.net"]
rx    [composing][/composing]
rx  [/chatstate]

rx  [chatstate from="5493515106772@s.whatsapp.net"]
rx    [paused][/paused]
rx  [/chatstate]

rx  [message from="5493515106772@s.whatsapp.net" type="text" id="B69592B0BE3C55306212" t="1454503815" notify="ing pussetto"]
rx    [enc v="2" type="msg"]330a2105f23ece10b26d54bde6e190492aa23bea448e4074663371c3c708c3a957039566100018002210fe589358d33bee4b64ad0ba7ff87cc9e079c679484d8c10e[/enc>]
rx  [/message]

tx  [ack to="5493515106772@s.whatsapp.net" class="message" id="B69592B0BE3C55306212" t="1454503815"][/ack>]

-] Decrypted Message: Hola tx  [receipt type="read" to="5493515106772@s.whatsapp.net" id="B69592B0BE3C55306212" t="1454503815">[/receipt>]]_

--

and others give the following error

---

rx  [message from="5493515578916@s.whatsapp.net" type="text" id="5AD906A9D1150072CA2" t="1454503778" notify="Nano Giordano"]
rx    [enc v="2" type="pkmsg"]3308eeaef904122105b96005d7bb1c246d91944b5e89ef053f4e9c6ff3ff7a08a7368c72daa7783b591a210527ec1e81bf604e4a8fb9819fd515460d3a671628fdc1bf019e7f369a30ccfd722242330a2105ba71718fe3c0c2be878b06dbc73fa9608e76418ede3a9e24985076262f82f673100718002210c3c418488b0f342a3dc7567301b6ca50aaeaa00ca7d8ce64289db9d4870430d9f301[/enc][
rx  [/message]

tx  [ack to="5493515578916@s.whatsapp.net" class="message" id="5AD906A9D1150072CA2" t="1454503778"][/ack]

-] Decrypted Message: Bad Mac! Bad Mac! No valid sessions - /home/whatsapp/public_html/mod/social/chat-api/src/libaxolotl-php/SessionCipher.php - 178Message 5AD906A9D1150072CA2 could not be decrypted, sending retry. tx  [receipt id="5AD906A9D1150072CA2" to="5493515578916@s.whatsapp.net" type="retry" t="1454503778"]
tx    [retry v="1" count="1" id="5AD906A9D1150072CA2" t="1454503778"][/retry][
tx    [registration]Qz3[/registration][
tx  [/receipt]

rx  [ack from="5493515578916@s.whatsapp.net" class="receipt" type="retry" id="5AD906A9D1150072CA2" error="400"][/ack][

--

Both sent from Android to the latest version of WhatsApp
I await any comments you can help
Thank you

**Comment by gratbrav** [comment]
Remove axolotl .db and try again
