### ISSUE TITLE
Cannot read messages

### ISSUE THREAD

**Issue by ma1069** [mgp25/Chat-API#1593]
Hello,
first of all, I assure you I tried everything I could to avoid having to write you here: I followed the wiki, read the FAQs and tried the examples.

However, the test application I made perfectly sends messages, but for some reason it's not able to read the incoming ones.

Basically, the onGetMessage event does not not seem to trigger, either by using the new code or by using the "legacy" style. 
I also tried to manually go through the messages, unpacking the output of the getMessages() method in the waiting loop, but the message content is encrypted so I cannot read it (I cannot find the "body" child mentioned in the examples, only the "enc" child is there but it's not so easy to understand).
Am I missing something? 

Here it follows the code (the "legacy" style seemed to be easier to share, as everything is in the same file): http://pastebin.com/6s3ikxHy

And, here it follows the debug log: http://pastebin.com/JrJXn1uF

I'm really sorry I am writing you about this issue... I've read the amount of dumb questions you are forced to answer so often, and I probably am one of them... but your API seems so cool to use, and I really tried everything I could to solve the issue on my own... 

Thank you,

ma1069

*ps: I forgot to mention that even the exampleFunctional.php file seems to suffer the same issue! After configuring it, I receive the "challenge" message, but then it doesn't react to my replies*

**Comment by mgp25** [comment]
You have not read the wiki. You havent installed dependencies.

Regards
