### ISSUE TITLE
Call to a member function getChainKey () on null in

### ISSUE THREAD

**Issue by usinadeideia** [mgp25/Chat-API#1594]
I'm getting the error below, messages appear on my device as read, but they do not appear in the API, only this error:

<br />
<b> Warning </ b>: Invalid argument supplied for foreach () in <b> /home/sacplusnet/public_html/lib/whatsapi/src/handlers/IqHandler.php </ b> on line <b> 249 </ b> <br />
<br />
<b> Fatal error </ b>: Call to a member function getChainKey () on null in <b> /home/sacplusnet/public_html/lib/whatsapi/src/libaxolotl-php/state/SessionState.php </ b> on line <b> 137 </ b> <br />

**Comment by mgp25** [comment]
@usinadeideia without debug log we consider the issue as invalid, but this issue is caused because a bad format of the number or invalid number.

Check it.

Regards
