### ISSUE TITLE
sendPresenceUnsubscription

### ISSUE THREAD

**Issue by mylogin** [mgp25/Chat-API#1595]
After sendPresenceUnsubscription() l get presence available/unavailable statuses, although they do not have to come?
`tx  <presence type="unsubscribe" to="xxx@s.whatsapp.net"></presence>`
`rx  <presence from="xxx@s.whatsapp.net" type="unavailable" last="123"></presence>`

**Comment by mgp25** [comment]
Maybe it works that way, the important thing is that you unsubscribed a contact which means you have blocked the contact or the contact has removed the account.

Regards
