### ISSUE TITLE
Error v1 padding bug

### ISSUE THREAD

**Issue by aal89** [mgp25/Chat-API#1597]
The first message send to an iOS device will throw an error-v1. Upon this error-v1 chat-api will try to resend that message. However in some cases the padded message was saved to the messagestore (because it assumed it was version 2, when it was 1). So when that message arrives at the iOS device it will have an \n prepended to it, making it look like you typed an enter as first while this was not the case.

I have created a pull request with an explanation and a proposed fix. Please review.

**Comment by aal89** [comment]
#1596

**Comment by 0xTryCatch** [comment]
No need to open an issue when you submitted a pull request
