### ISSUE TITLE
Cannot get information group

### ISSUE THREAD

**Issue by vinsei** [mgp25/Chat-API#1599]
I use function $w->sendGetGroups(), but I don't get participating group.
I attach result.
![result](https://cloud.githubusercontent.com/assets/9445436/12804293/801555ac-cb24-11e5-9700-69e801431d61.png)

**Comment by AloneMate** [comment]
do pollmessage more than once using loop.

**Comment by vinsei** [comment]
thanks for answer my question.

I get other error.

Fatal error: Uncaught exception 'LoginFailureException' in D:\Webase\library\2016\Chat-API\src\Login.php:54 Stack trace: #0 D:\Webase\library\2016\Chat-API\src\whatsprot.class.php(286): Login->doLogin() #1 D:\Webase\library\2016\Chat-API\tests\send.php(10): WhatsProt->loginWithPassword('svI/k662oncKr52...') #2 {main} thrown in

**Comment by AloneMate** [comment]
you are banned
