### ISSUE TITLE
Bad Mac!

### ISSUE THREAD

**Issue by rabrux** [mgp25/Chat-API#1603]
Sometimes the API receives messages from unknown people, this to begin to establish a communication with the application. But sometimes it did not received messages from unknown phone numbers. Then some applications have automatically sync functions, and others do not.

In another issue one of the solutions is remove a data file located in src/wadata/axolotl-*.db. But did not works well.

Some idea, that what happens?

I reinstall API from composer again and the problem persists.

Thanks and greetings.

**Comment by mgp25** [comment]
@rabrux If you don't post debug log and code this issue is invalid

Regards

**Comment by mgp25** [comment]
@rabrux sorry you don't meet with Chat API agreement.

Regards
