### ISSUE TITLE
Bad Mac! (with solution)

### ISSUE THREAD

**Issue by FrancYescO** [mgp25/Chat-API#1604]
i was receiving messages with no issue, than i reinstalled whatsapp on my phone and ChatAPI (oviusly not same account of my phone) was not able to receive/decrypt messages and instead shows "Bad Mac!" everytime i'll try to send a message from my phone, no issue to receive/decrypt from no "reinstalled" client.

removing axolotl-xxx.db seems to solve the issue.

is there something that i have to do to check if a user "reinstalled" whatsapp and i have to refresh axolotl?

**Comment by mgp25** [comment]
@FrancYescO in theory API automatically requests new data if could not decrypt the message. Make sure you are using latest Chat API source code. And if all what i told doesnt fix it, for now remove axolotl db

Regards
