### ISSUE TITLE
Error "<not-authorized></not-authorized>" 

### ISSUE THREAD

**Issue by giuseppemiw** [mgp25/Chat-API#1608]
Hello, i'm trying to do this script:
<?php require 'src/whatsprot.class.php'; $nickname = "My-nick-test"; $sender = "+39............"; $imei = ""; $password = "........................."; $dst = "+39......................."; $wa = new WhatsProt($sender, $imei, $nickname, TRUE); $wa->connect(); $wa->loginWithPassword($password); $wa->sendMessage($dst, "Test messange from PHP"); ?>

The system reply with 
tx <stream:features></stream:features> tx <auth user="+393396280507" mechanism="WAUTH-2"></auth> rx <from s.whatsapp.net=""></from> rx <stream:features></stream:features> rx <challenge>a658afedadeef7e7a9d13d3ed80cea4b00aeb471</challenge> tx <response>1d323e45d2ca592ea4223414cbf294066e94fccb8eafd50c8975a974211e2d45d529d0e3192ada4987703910eee87cd8543b37705bdae61163fc9574a6fb8b5ca1468a267f0d7b6c40d76b396481af</response> rx <failure> rx <not-authorized></not-authorized> rx </failure>

The message isn't delivered.
How can i resolve it?
Please don't write me "Your number has been blocked" because i have tried to change the number of the sender and the recipient several time.

Thanks!

**Comment by giuseppemiw** [comment]
The problem was "+39.........", the correct format is "39............"

**Comment by mgp25** [comment]
@giuseppemiw 

1. Quote code and debug properly, is not that hard!
2. Read closed issues and do NOT create duplicate issues
3. Read thr wiki before posting anything.
4. Make sure to test before opening a new issue
