### ISSUE TITLE
Registration failure 

### ISSUE THREAD

**Issue by kchizi** [mgp25/Chat-API#1611]
array( 
[cc] => 254 
[in] => 714******
[lg] => sw 
[lc] => KE 
[id] => ��f��)e*�ћ��0�: 
[token] => 1yMhc9Fu650wu7ZUZg4B5DpTGU4=
[mistyped] => 6
[network_radio_type] => 1 
[simnum] => 1 
[s] => [copiedrc] => 1 
[hasinrc] => 1
[rcmatch] => 1 
[pid] => 5883 
[rchash] => c33fb3de69ea15a1da4547e3294a00daa240aa6bf7757e6191660f04c7d23798 
[anhash] => 0033c781b418a4bd6dc90d1a1219c9cb 
[extexist] => 1 
[extstate] => 1 
[mcc] => 639 
[mnc] => 000 
[sim_mcc] => 639 
[sim_mnc] => 000 
[method] => voice 
) 
stdClass Object (
 [status] => fail 
[reason] => no_routes 
[retry_after] => 3600 
[sms_wait] => 0 
[voice_wait] => 0
)

tried both SMS and voice, still fails, please assist, carrier is safaricom

**Comment by mgp25** [comment]
Maybe spam related.

Regards

**Comment by kchizi** [comment]
how? followed no-spam policy.

**Comment by mgp25** [comment]
@kchizi that mobile provider maybe is spam flagged

**Comment by kchizi** [comment]
which one do you recommend?

**Comment by kchizi** [comment]
using wart or the web tool works

**Comment by Griffins** [comment]
@kchizi tried airtel ke. it works
