### ISSUE TITLE
not work, error IncompleteMessage

### ISSUE THREAD

**Issue by IgCharles** [mgp25/Chat-API#1614]
my version has stopped working a while ago, to upgrade to the current, I am getting this error
`
PHP Fatal error:  Cannot redeclare class IncompleteMessageException in protocol.class.php on line 23
`

**Comment by Gabrielr47** [comment]
Seriously? Dammit I never see a error on this API

**Comment by mgp25** [comment]
@IgCharles thats means you have already created a class named `IncompleteMessageException`. To prevent inclusions, you need to use: `include_once "something.php";`

Regards

**Comment by IgCharles** [comment]
my code include only whatsprot class
