### ISSUE TITLE
Group Picture "send/on" GetGroupPicture

### ISSUE THREAD

**Issue by jquequezana** [mgp25/Chat-API#1615]
Some one know how I can get the picture of a group with a function getter or some event?

The event onGetGroupPicture and the function sendGetGroupPicture  doesn´t exist, but Is there any way to do this?

regards

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L851

And use the group ID, instead of a number, use the same event as you used to request a single profile picture of one of your contacts

Regards
