### ISSUE TITLE
Class 'KeyHelper' not found

### ISSUE THREAD

**Issue by usinadeideia** [mgp25/Chat-API#1616]
Hello guys

I'm having the following problem:

<Brb> Fatal error </ b>: Class 'KeyHelper' not found in <b> /home/sacplusnet/public_html/lib/whatsapi/src/whatsprot.class.php </ b> on line <b> 323 </ b> <br />

Protobuf and installed Curve, which could correct this error?

Thank you

**Comment by mgp25** [comment]
Do you have latest source code? There should be a folder named `libaxolotl-php`, if you haven't download the code again.

https://github.com/mgp25/Chat-API/tree/master/src/libaxolotl-php

Regards
