### ISSUE TITLE
Unable to get events working

### ISSUE THREAD

**Issue by scramatte** [mgp25/Chat-API#1618]
Hello,

I'm trying to get events working but I'm stuck here :(
I've followed the Wiki without success ...

I need to handle event like onGetMessage, onGetImage ,...

Regards

**Comment by mgp25** [comment]
Post your code

**Comment by AloneMate** [comment]
Have you enabled events ? And included event file ?

**Comment by scramatte** [comment]
Hi,

Yes I've include event file and setup  onGetMessage function.
Note I'm testing using  exampleFunctional.php code.

Looks that such events are never fired :(

**Comment by mgp25** [comment]
@scramatte if you dont post code or debug log, we can't help you, but i guess you havent installed all extensiones and because of encrypted messages, the API is not parsing messages, just that.

Next time, post debug log and code

Regards
