### ISSUE TITLE
getting a message

### ISSUE THREAD

**Issue by rohmanahmad** [mgp25/Chat-API#1620]
after bind onGetMessage() . i will get this result to my controller. how can i do this?

**Comment by rohmanahmad** [comment]
i use codeigniter.

**Comment by rohmanahmad** [comment]
how can i receive the results from onGetMessage()? because i need this results to insert to my DB.

**Comment by 0xTryCatch** [comment]
Everything is in the wiki. Programming questions will no be answered.
