### ISSUE TITLE
Cannot loggin anymore

### ISSUE THREAD

**Issue by malufett** [mgp25/Chat-API#1621]
my created app using this lib the login is not working anymore..
I also check the example scripts to check if is it in my code or the libraries fault..
I check using /examples/exampleFunctional.php
and this is what I got..
![image](https://cloud.githubusercontent.com/assets/3251821/12994881/5400e25c-d15e-11e5-9664-ac10606b99e1.png)

thanks and more power..

**Comment by mgp25** [comment]
`not authrized` means number blocked, wrong password or banned IP

Regards
