### ISSUE TITLE
Bad Mac!

### ISSUE THREAD

**Issue by styler2go** [mgp25/Chat-API#1622]
Hello,

sometimes i get spammed with the message `Bad Mac!`.
As far as i found out it happens in the events `onMessageReceivedClient` and/or `onMessageReceivedServer`

My functions are pretty simple and don't do much. Also, `Bad Mac!` is not being spammed always.

My functions:

>  public function onMessageReceivedClient($mynumber, $from, $id, $type, $time ){
>    global $db;
>    $db->query('UPDATE `messages` SET `status` = 2 WHERE `whats_id` = :id', array('id' => $id));
>  }
>
>  public function onMessageReceivedServer($mynumber, $from, $id, $type, $time ){
>    global $db;
>    $db->query('DELETE FROM `outgoing` WHERE `whatsid` = :id', array('id' => $id));
>    $db->query('UPDATE `messages` SET `status` = 1 WHERE `whats_id` = :id', array('id' => $id));
>  }

My PHP script is running permanently and is using this while:

> $x = true;
> $messages = array();
> while ($x) {
>   $messages = $db->query("SELECT * FROM `outgoing` WHERE `whatsid` IS NULL", array());
>   print_r($messages);
>   if (is_array($messages) && count($messages) > 0){
>     foreach ($messages as $value) {
>       Funcs::sendQueuedMessage($value);
>       print_r($value);
>     }
>   }
>   sleep(1);
>   $w->pollMessage(false);
> }

**Comment by 0xTryCatch** [comment]
Remove axolotl.db will solve it

**Comment by anativ** [comment]
Can you explain?
When removing axolotl.db there is no encryption...
As far as I know this is not supported by WhatsApp anymore

**Comment by mgp25** [comment]
It will simply reset axolotl data, plase read closed issues and wiki
