### ISSUE TITLE
Call to a member function nodeString() 

### ISSUE THREAD

**Issue by BjHelm** [mgp25/Chat-API#1623]
Hello,

I'm trying to use the function sendMessageRead.

$w->sendMessageRead($Number,$MessageID);

I'm using the Messageid i got from WhatsApp to send the receipt, but i always got a Fatal Error

tx  stream:features stream:features
tx  auth user="" mechanism="WAUTH-2" auth
rx  from s.whatsapp.net="" from
rx  stream:features stream:features
rx  challenge challenge
tx  response f29a1305539439d771b28ffe738cb3998b57f00cc293ca1fdc582219cc2288df08e119b910a218a38832580c2d2c269d795ad275dd858cab98c2d2bca17c55ba0bc54844084fc569d23973725340 response

rx  success t="1455270503" props="4" kind="free" status="active" creation="1425391689" expiration="4444444444">6cf4f0075e27d96f1791ffd5ded4e04ca46d1215 success

tx  presence name="" type="available" presence
tx  iq id="01" xmlns="jabber:iq:privacy" type="get"
tx    query
tx      list name="default" list
tx    query
tx  iq

tx  iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net"
tx    config config
tx  iq

Fatal error: Call to a member function nodeString() on a non-object in protocol.class.php on line 180

**Comment by mgp25** [comment]
@BjHelm post full code script + quote debug properly please, retry again everything should work fine.

Also check closed issues, there are some duplicates. Let me know if that solved it.

Regards

**Comment by MoudiZd** [comment]
@BjHelm  look for this

Regards
