### ISSUE TITLE
problem with encrypted messages

### ISSUE THREAD

**Issue by nch7** [mgp25/Chat-API#1625]
I know this has been discussed a couple times already, but I'm still getting encrypted messages.

here is an output of `php-m` 

```
[PHP Modules]
apc
apcu
bcmath
blackfire
bz2
calendar
Core
ctype
curl
curve25519
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
json
libxml
mailparse
mbstring
mcrypt
memcached
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
protobuf
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
blackfire
```

Both `curve25519` and `protobuf` are installed.

I was getting `Class 'ProtobufMessage' not found` and `Call to undefined function curve25519_private()` before installing those extensions now I'm getting no errors at all so they are installed correctly, yet I still get encrypted messages.

I run virtual machine: Ubuntu 14.04 & PHP 5.6 and I use 3.1 version of Chat-API.

Anywhere else I can look into?

**Comment by nch7** [comment]
nvm, my bad was looking at wrong output for over 1 hour lol

**Comment by RonnieVisser** [comment]
what did you do to fix this? if I may ask?
