### ISSUE TITLE
Only Receiving Messages from certain Users

### ISSUE THREAD

**Issue by fdrechsler** [mgp25/Chat-API#1626]
Hey Guys,

when i am polling Messages i am receiving all the Group Messages.
And messages from my private WhatsApp Account.

But if one of my Friends sends a message to the chat-api whatsapp account it is not receiving it with OnGetMessage. (Only Group Messages and Messages from my Private WhatsApp Account using iOS are received)

But i can send Messages to my Friends from the Chat-Api Whatsapp Account.

Any ideas? 

Thank you in advance,
will send you over some mBTC for this great project.

**Comment by mgp25** [comment]
@fdrechsler can you post debug log?

**Comment by fdrechsler** [comment]
I get this in the Debug Log, but it is not giving this message to the OnMessage event.
But it is giving a Message to this event when i write from another Account...

i don't get it...


```
tx  <iq id="04" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <message from="491XXXXXX@s.whatsapp.net" type="text" id="145553XXXX.--70" offline="3" t="1455539101" notify="XXXX XXXXXX">
rx    <enc v="1" type="pkmsg">331221053c8c322337b9c50a4075bd93e35b961885823bf77897e24a10fa613e7ee73d281a2105df8db9716062905d6f1daeec71d2944b3aea4d89be3823cad1f6ee4e88ee4e202242330a210574fe51227ae2c4b08f8384aee08d9fc82d35e320bd403eec1343e34f49a0bc1010041800221025d6486dc747b233c12d09f9709f2b45a73ce2cd412deb1628fd7d30c791e103</enc>
rx  </message>

```

**Comment by fdrechsler** [comment]
So this is a Example of the Working Message in the Debug log:

`
rx  <message from="491520XXXXX@s.whatsapp.net" type="text" id="14XXXX291.--2082" t="14555XXX291" notify="Florian">
rx    <body>aFDASDF</body>
rx  </message>

tx  <receipt type="read" to="491XXXXXXX@s.whatsapp.net" id="14555XXX91.--2082" t="14555XXX0291"></receipt>
`

Seems like my Messages arent encrypted??

**Comment by fdrechsler** [comment]
This will also explain why i can receive Group Messages from these Persons. Groups can't use end-to-end encryption, right?

**Comment by mgp25** [comment]
You need to install extensions as explained in the wiki. E2E encryption is also supported for groups.

Regards

**Comment by fdrechsler** [comment]
```
➜  liquidorganizer2 git:(master) ✗ php -i | grep curve        
curve25519
curve25519 support => enabled
➜  liquidorganizer2 git:(master) ✗ php app/console james:quiz 
PHP Fatal error:  Call to undefined function curve25519_private() in /Users/fdrechsler/projects/liquidorganizer2/src/AppBundle/ThirdParty/chatapi/libaxolotl-php/ecc/Curve.php on line 16

```

I have done so, now it is giving me this error. Any idea?

**Comment by amec1234** [comment]
have the same problem

**Comment by fdrechsler** [comment]
@amec1234 Reinstall the Extensions exactly as explained in the Wiki.

**Comment by amec1234** [comment]
it works now, i installed curve from another source that was wrong. i had to do install that one from the wiki
