### ISSUE TITLE
Is there any limit on how many (interactive) contact syncs I can perform?

### ISSUE THREAD

**Issue by yniv** [mgp25/Chat-API#1627]
Currently when someone new contacts me I add it to a list, and every 3 min or so I sync all the contacts in that list.
But, can I just sync a contact immediately after he contacted me for the first time? 
This will cause many contacts syncs but ensures I'll never send a message to someone which I didn't sync?

**Comment by mgp25** [comment]
Read wiki, and there is a limit per hour, you dont need to insta add if they started chatting with you.

Regards
