### ISSUE TITLE
Status of function OnGetLocation

### ISSUE THREAD

**Issue by nptracker** [mgp25/Chat-API#1629]
Hi,
I could always get locations send to my chat-api bot but from yesterday the location messages are now send encrypted:
debug log:
```xml
rx  <message from="xxxxx@s.whatsapp.net" type="media" id="0A04D9591F5EC96BE00" t="1455477886" notify="xxx">
rx    <enc v="2" type="pkmsg" mediatype="location"> 3100 byte data</enc>
rx  </message>
```
Ime using the latest code but the onGetLocation event never gets triggered/called.

As per issue #1624 when I use the normal onGetMessage I get a decrypted image (after disregarding the first 22 characters of the decrypted message - saved as bin. Note: the first 22 chars does not contain my coordinates)

Any idea where the gps latitude and longitude are now being saved or should I wait for a update to enable onGetLocation firing?

**Comment by mgp25** [comment]
Fixed in latest commit
