### ISSUE TITLE
MessageHandler parse error

### ISSUE THREAD

**Issue by anativ** [mgp25/Chat-API#1631]
From time to time a get a parse error on MessageHandler: for example

`PHP Fatal error:  Uncaught exception 'Exception' with message '�: parse error - "'group_id' field wire type is unknown but should be length-delimited"' in /app/src/handlers/MessageHandler.php:496 `

`PHP Fatal error:  Uncaught exception 'Exception' with message '�!: parse error - "unexpected wire type 3 for unexpected 12 field"' in /app/src/handlers/MessageHandler.php:496 `

`PHP Fatal error:  Uncaught exception 'Exception' with message 'p": parse error - "unexpected wire type 4 for unexpected 8 field"' in /app/src/handlers/MessageHandler.php:496`

I don't have debug logs...
Any idea what cause this issue?

**Comment by mgp25** [comment]
@anativ debug log is required
