### ISSUE TITLE
Cannot send media. Event onMediaUploadFailed found, "Message node not found in queue" found

### ISSUE THREAD

**Issue by hgc2002** [mgp25/Chat-API#1634]
I'm tracing a new issue that just happened. Sometimes it refuses to send media. I've tried different files and sizes (all below 100 kbytes), and they had worked before. But now I'm getting this output on every media I try: (example)

tx  iq id="01" to="s.whatsapp.net" type="set" xmlns="w:m"
tx    media hash="cs2DgrsWGr5xuoD7PGH7XnPrmrIw1ftLzPkjM6aR4VY=" type="image" size="8400"/media
tx  /iq

rx  iq from="s.whatsapp.net" type="result" id="1"
rx    media url="https://mmi254.whatsapp.net/u/MR-OxGR_J9-dLoGki9NCrGsMRGMABSvYPdDXDg/Ahjc5XSjEJK2d5D2BtCSWU5110yKKbv2Vxjbafs90UAg" ip="---hidden---"/media
rx  /iq

Then, this event: onMediaUploadFailed
`parameters = Array
(
    [0] = 15874051103
    [1] = 1
    [2] = ProtocolNode Object
        (
            [tag:ProtocolNode:private] = iq
            [attributeHash:ProtocolNode:private] = Array
                (
                    [from] = s.whatsapp.net
                    [type] = result
                    [id] = 1
                )

            [children:ProtocolNode:private] = Array
                (
                    [0] = ProtocolNode Object
                        (
                            [tag:ProtocolNode:private] = media
                            [attributeHash:ProtocolNode:private] = Array
                                (
                                    [url] = https://mmi254.whatsapp.net/u/MR-OxGR_J9-dLoGki9NCrGsMRGMABSvYPdDXDg/Ahjc5XSjEJK2d5D2BtCSWU5110yKKbv2Vxjbafs90UAg
                                    [ip] = ---hidden---
                                )

                            [children:ProtocolNode:private] = 
                            [data:ProtocolNode:private] = 
                        )

                )

            [data:ProtocolNode:private] = 
        )

    [3] = 
    [4] = Message node not found in queue
)
`

Any idea?

Regards,
Herman

**Comment by mgp25** [comment]
Provide code and debug log, don't `var_dump` just post debug log properly quoted. Retry again and if you still face this error provide all the data i just said, and add also a way to reproduce the error including the image it was used to reproduce the error.

Full debug log will be required.

Regards
