### ISSUE TITLE
$file_data sometimes has media binary, and sometimes has the file name. Why?

### ISSUE THREAD

**Issue by hgc2002** [mgp25/Chat-API#1635]
From MessageHandler.php:

`
if ($this->node->getChild('enc') != null && $this->node->getAttribute('participant') == null) { // for now only private messages

                if (extension_loaded('curve25519') && extension_loaded('protobuf')) {
                    $dec_node = $this->processEncryptedNode($this->node);
                }
                if ($dec_node) {
                    $this->node = $dec_node;
		    		if($dec_node->getChild("media") != null)

                    	//here, $file_data has the file name.
                    	$file_data = $dec_node->getChild("media")->getAttribute("file");
                }
            }
            else if (($this->node->getChild("enc") == null) && ($this->node->getChild('media')->getAttribute('url') != null)) {

              //here, $file_data has the media binary content
              $file_data = file_get_contents($this->node->getChild('media')->getAttribute('url'));
            }
`

Then the onGetImage event is called with $file_data as parameter names $file. This confuses a lot: $file is for file name or for the file itself (binary content)?

Regards,
Herman

**Comment by gi097** [comment]
It is the binary_content, providing the image name would be useless. But yeah, I agree that it would be confusing for you.

**Comment by mgp25** [comment]
If the image is decrypted you will get the image data, if is not decrypted, you will get the url so you can decrypt it later

Regards
