### ISSUE TITLE
number blocked

### ISSUE THREAD

**Issue by bgani** [mgp25/Chat-API#1636]
1) I tried register new number with wart last version.  I get confirm code. But number blocked when i push button confirm code, "Verification code not accepted".   With debug log :  
```
Response = { "status": "fail", "reason":"blocked"}.
``` 
2) Then i tried register second new number, they all never used. I decided register via [http://www.watools.es/pwd.html](http://www.watools.es/pwd.html) . I get confirm code, write it and push "Get password" button.  No reaction.  Then i tried with wart and get same message about "blocked"
```
Response = { "status": "fail", "reason":"blocked"}.
```
I tried with exampleRegister.php: 
```
<?php
require_once '../src/Registration.php';

$debug = true;
$username = '77059194422';   // Telephone number including the country code without '+' or '00'.

// Create an instance of Registration.
$w = new Registration($username, $debug);

$w->codeRequest('sms');
```
 And get debug log: 
```
Array ( [cc] => 77 [in] => 059194422 [lg] => kk [lc] => KZ [id] => 0rw2f������e�`55� [token] => Eunq7qW0fL0y5B6i5hApk+MPGjE= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 8888 [rchash] => 8d9f5f8cec1431f1af3b6f364ae0ac2a2ceb4b69b46360dd75628dc91b7e90a7 [anhash] => d648a6ef2c1f7d5083fe4866d924c3b9 [extexist] => 1 [extstate] => 1 [mcc] => 401 [mnc] => 000 [sim_mcc] => 401 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => fail [reason] => blocked ) 
Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in C:\inetpub\wwwroot\chatapi\src\Registration.php:314 Stack trace: #0 C:\inetpub\wwwroot\chatapi\examples\exampleRegister.php(41): Registration->codeRequest('sms') #1 {main} thrown in C:\inetpub\wwwroot\chatapi\src\Registration.php on line 314
```
What can be reason.  ?

**Comment by mgp25** [comment]
Number is blocked as the response says, probably due spamming or ilicit activities / commercial use.

Regards

**Comment by bgani** [comment]
Both of numbers was new and never used. i even couldn't get passwords.

**Comment by mgp25** [comment]
@bgani it doesnt matter if the number was used if others were used under the same IP

**Comment by bgani** [comment]
I re-registered my old number under the same ip success, after new numbers was blocked, sorry if annoying.

**Comment by bgani** [comment]
I sent e-mail to whatsapp support tream. I wrote that my new number blocked and i don't know why. Then i recevied message: 
```
Thanks for your message.

We apologize for any confusion and inconvenience this may have caused. Our system flagged your account activity as a violation of our Terms of Service and subsequently banned your number.

To ensure access, please reverify your number with our official WhatsApp client, which can be downloaded from our website: www.whatsapp.com/download

Please note that we do not provide support for unofficial clients or for jailbroken/rooted (including emulators), and unsupported devices.
```
Now my number re-registred success via whatsapp official application. What is your suggestions to safe register number with wart tool or  [http://www.watools.es/bloqueado.html](http://www.watools.es/bloqueado.html), in order to get whatsapp password ?

**Comment by diogoGuedes** [comment]
Good afternoon , this happened also with me, and was not only in number but with three absolutely new numbers , and with different external ips, what I realized is that this occurs after picking up the password, and / or running the chat api (scripts updated) after this WhatsApp simply bans the number permanently.

**Comment by henzard** [comment]
If I implement this in a commercial application would I need to change the IP of each number in a regular basis ?
