### ISSUE TITLE
 Call to a member function getData()

### ISSUE THREAD

**Issue by AloneMate** [mgp25/Chat-API#1639]
Hello,

I'm using latest code and I have installed all dependencies. still it shows the following errors.

```
PHP Fatal error:  Call to a member function getData() on null in /var/www/html/index.php on line 55
```

I'm using ```GetMessages()``` function to get message in real time. I tried deleting .db file but still problem exists. The script works fine for 10 minutes and after that it shows the following errors. Script is simple, gets message and stores it. it works perfectly using event system but I want to get messages in real time. I tried to debug using debug log but there is nothing to show since it suddenly shows this error and script stops working. Any solution to this ?

Thanks!

**Comment by mgp25** [comment]
Hello,

the error happends in your script, not API issue. If you want any help, be sure to post `index.php` script code and debug log

Regards

**Comment by AloneMate** [comment]
Here is script : 

```
$w->pollMessage();

while(1)
{
    $w->pollMessage();
    $msgs = $w->GetMessages();

    foreach ($msgs as $m) 
    {
        $from = $m->getAttribute('from');
        $dFrom = str_replace(array("@s.whatsapp.net","@g.us"), "", $from);
       
        $body = $m->getChild("body")->getData();
        $nick = $m->getAttribute('notify');
   }
sleep(5)
}
```
And then I store data in database.

**Comment by mgp25** [comment]
@AloneMate is a programming question, im going to answer it but next time search it in google:

The error you got is this one:

`PHP Fatal error:  Call to a member function getData() on null in /var/www/html/index.php on line 55`

And you are using this:
```php
        $body = $m->getChild("body")->getData();
```

What if `body` node does not exist? Then you are calling `getData()` which expects obviusoly data, on null.

So before doing that you shoul do:

```php
    if (isset($m->getChild("body")->getData()) && is_null($m->getChild("body")->getData()))
          $body = $m->getChild("body")->getData();
```

Please, use google next time

Regards

**Comment by AloneMate** [comment]
Ohk Thanks mate! But one correction. Isset cannot be used. It is used only to check variables. :P
