### ISSUE TITLE
Message could not be decrypted

### ISSUE THREAD

**Issue by sakaturo** [mgp25/Chat-API#1640]
Hi,

i have the problem, that 15-20% of the messages i receive could not be decrypted by the api.
And therefore the event onGetMessage will not be triggered.

I have tried to delete the axolotl .db, but after some messages the problem occurs again.
And the messages send before i delete wont be received you must send a new message and then it will work.

It seems that this problem occurs most times by the first message someone send to the number.
When there was a successful conversation between the user an the number the problem doesn't happen.

I have the newest release on my server and the dependencies are all installed.

       $w = new WhatsProt($username, $nickname, false);

       $w->eventManager()->bind("onGetMessage", "onMessage");

       $w->connect();
       $w->loginWithPassword($password);

        while ($w->pollMessage()) {
        }

**Comment by mgp25** [comment]
Post debug log

**Comment by gi097** [comment]
There could be a problem that you have the old CipherKeys from a user. Indeed, after some messages, API will automaticly request and update them, but it's weird that in your case the problem keeps existing.

**Comment by sakaturo** [comment]
sorry does it take so long for my answer. the strange thing is, that this happens at the moment to numbers who has already send me messages. But after sometime new messages from these numbers wont get recieved.

 I have put a log in my question
