### ISSUE TITLE
Image URL coming in encrypted format and end with .enc rather than .jpg (e,g ProtocolNode Object ( [tag:ProtocolNode:private] => media [attributeHash:ProtocolNode:private] => Array ( [size] => 45212 [caption] => [url] => https://mmi716.whatsapp.net/d/ptt08Rjgww8FicyKTOZuS1bJ6ZA/AvuMROu4ERJM1q3SIM33kKezTMp9_jUOP6MByX53Burf.enc [mimetype] => image/jpeg [filehash] => d386805a498cac412a870cf1f73ef469645a3d352923ffdf46ef90f730e13066 [width] => 0 [height] => 0 [)

### ISSUE THREAD

**Issue by anoopgpr** [mgp25/Chat-API#1643]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Invalid issue. Read closed issues and use event system
