### ISSUE TITLE
Error: <failure><not-authorized></not-authorized></failure>

### ISSUE THREAD

**Issue by Rexota** [mgp25/Chat-API#1645]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.

### Error
Hey

I was using WhatsProt class successfully a few months before. But today, I'm getting below error. I registered the number again with regTool.php and checked it with blockChecker.php but there is no problem. I also installed curve & protobuf.  What can be the error? I'm clearly missing something.

Thanks.

### Debug log
Post your debug log below:

```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="905xxxx">��qS905xxxx2T��3�B��N������},B1456078010</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>It�
                   ϩ��k�a�e���_</challenge>

tx  <response>���9�t��	�������Z``���H�s9��R�</response>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

Bad authentication: Bad password or blocked account

::start_polling::
tx  <iq id="3" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

----
tx  <presence type="subscribe" to="90xxxx@s.whatsapp.net"></presence>

tx  <iq id="4" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

```

**Comment by Rexota** [comment]
@0xTryCatch

Why "outdated"?

Thanks.

**Comment by 0xTryCatch** [comment]
You are using an old version of the API

**Comment by Rexota** [comment]
Ah... Thanks.
