### ISSUE TITLE
Proxy connection

### ISSUE THREAD

**Issue by opensrc1229** [mgp25/Chat-API#1646]
I think an opportunity to use a proxy is essential, so we respectively you should add this option to this API. Maybe a connection with an „CONNECT“-initiation would be enough.

**Comment by mgp25** [comment]
Nope, no proxy support sorry

Regards

**Comment by opensrc1229** [comment]
I cannot understand why you don't want to do that, because perhaps you only have to change a few lines.

**Comment by alxhotel** [comment]
I would like that feature. Why can't it be done ?

**Comment by mgp25** [comment]
Is not required, and the fact you want this makes me think you are going to use it for spam or similar. So no, as is not required it wont be implemented

**Comment by opensrc1229** [comment]
OK, you are right. But you can describe how the connections are established for persons like me who can't understand the code completely. Please create a connection establishing description or something like that.
