### ISSUE TITLE
Fatal Error using sendMessageRead

### ISSUE THREAD

**Issue by BjHelm** [mgp25/Chat-API#1648]
Hello,

i have a question about your code. In protocol.class.php on line 95 youe declared a method to remove a child. I think I found a mistake there. In line 99 and line 103 it should be this->children.
Furthermore I tried to use the the function sendMessageRead. If I use this function with a message id as a string it doesn't work, but if I use the same message id in an array it works. A fatal error occurs because in line 2920 in whatsprot.class.php you create a new protocol node with a $listnode but if you use a string $listnode is null and this causes a fatal error. I fixed it myself, but could you check it please.

**Comment by brenodouglas** [comment]
Post your debug log without your fix.

**Comment by dishark** [comment]
yeah https://github.com/mgp25/Chat-API/blob/master/src/protocol.class.php#L103

**Comment by mgp25** [comment]
Merged.

Regards
