### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by cooler-farmer** [mgp25/Chat-API#1651]
Hey, I'm unable to register with my new number. I'm using the registerTool.php in the examples directory.
the phone number I enter is "00491520XXX5360". It's a valid german number, however the tool shows me the error message "The provided phone number is not valid." What's wrong?

**Comment by cooler-farmer** [comment]
it worked with WART

**Comment by mgp25** [comment]
If you read the wiki you would know it. Damn it i have explained everywhere! Including inside the script! Oh God... No '00' or '+'
