### ISSUE TITLE
No Reply on Code Register

### ISSUE THREAD

**Issue by amohideen** [mgp25/Chat-API#1652]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
Yes. both are phpized and .so are added to cli php.ini (extensions=), and ldconfiged.
- [ x] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.

### Error
I was able to get the code but an error is thrown while performing $w->codeRegister('****');

root@debian:/var/www/html/whatsapp/Chat-API-master/examples# php -f  exampleRegister.php 
Array
(
    [cc] => 44
    [in] => *********
    [lg] => en
    [lc] => GB
    [id] => ��bt�)�^
                    ��
                      o�
                            [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3521
    [rchash] => 6a3aea05b99024801a6e9daf136e496e14509bd7b025f7d4f7dfd7924b581dd7
    [anhash] => 3c734baed43ae0a26cf3179ba94a8ff3
    [extexist] => 1
    [extstate] => 1
    [code] => ******
)
stdClass Object
(
    [status] => fail
    [reason] => missing
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp. Reason: missing' in /var/www/html/whatsapp/Chat-API-master/src/Registration.php:181
Stack trace:
#0 /var/www/html/whatsapp/Chat-API-master/examples/exampleRegister.php(68): Registration->codeRegister('*****')
#1 {main}
  thrown in /var/www/html/whatsapp/Chat-API-master/src/Registration.php on line 181
root@debian:/var/www/html/whatsapp/Chat-API-master/examples# 

### Debug log
[24-Feb-2016 15:15:08 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp. Reason: missing'
in /var/www/html/whatsapp/Chat-API-master/src/Registration.php:181
in Stack trace:
#0 /var/www/html/whatsapp/Chat-API-master/examples/exampleRegister.php(68):Registration->codeRegister('******')
#1 {main} thrown in /var/www/html/whatsapp/Chat-API-master/src/Registration.php on line 181

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
@amohideen hi, have you requested first the sms code?

I recommend you to use `registerTool.php` which is a CLI script, very easy to use to get your WA password. There are other altenatives like [WATools](http://www.watools.es/pwd.html) and [WART](https://github.com/mgp25/WART) that can help you obtaining your password.

Regards

**Comment by amohideen** [comment]
I requested and received the 6 digit code. This error is thrown only when I
tried to register the 6 digit code.
