### ISSUE TITLE
Class 'KeyHelper' not found - 

### ISSUE THREAD

**Issue by lkathke** [mgp25/Chat-API#1653]
I'm trying to run the "example/Simple CLI client.php" and I am getting the KeyHelper not found error message.
The directory "src/libaxolotl-php/" exists and src/libaxolotl-php/util/KeyHelper.php too.

I am also used the "composer require whatsapp/chat-api" command in src/ 
With "php -m" I can see that curve25519 and protocolbuffers are enabled.

Where is my fault? (I'm using Ubuntu Server and downloaded the master.zip with wget)

### Error
PHP Fatal error:  Class 'KeyHelper' not found in /home/lasse/Chat-API-master/src/whatsprot.class.php on line 334

## PhpModules
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
curve25519
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
openssl
pcntl
pcre
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
protocolbuffers
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

## src fileSystem:

-rw-rw-r--  1 lasse lasse 101429 Feb 24 09:05 whatsprot.class.php
drwxrwxr-x 12 lasse lasse   4096 Feb 24 09:04 libaxolotl-php
drwxrwxr-x  4 lasse lasse   4096 Feb 24 08:30 vendor
-rw-rw-r--  1 lasse lasse   2209 Feb 24 08:30 composer.lock
-rw-rw-r--  1 lasse lasse     63 Feb 24 08:30 composer.json
drwxrwxr-x  5 lasse lasse   4096 Feb 24 08:26 wadata
-rw-rw-r--  1 lasse lasse  13873 Feb 23 06:29 BinTreeNodeReader.php
-rw-rw-r--  1 lasse lasse  10035 Feb 23 06:29 BinTreeNodeWriter.php
-rw-rw-r--  1 lasse lasse   2444 Feb 23 06:29 Constants.php
-rwxr-xr-x  1 lasse lasse   9412 Feb 23 06:29 countries.csv
drwxrwxr-x  2 lasse lasse   4096 Feb 23 06:29 events
-rwxr-xr-x  1 lasse lasse   1717 Feb 23 06:29 exception.php
-rwxr-xr-x  1 lasse lasse  29400 Feb 23 06:29 func.php
drwxrwxr-x  2 lasse lasse   4096 Feb 23 06:29 handlers
-rwxr-xr-x  1 lasse lasse   2247 Feb 23 06:29 keystream.class.php
-rw-rw-r--  1 lasse lasse   1091 Feb 23 06:29 Logger.php
-rw-rw-r--  1 lasse lasse   5121 Feb 23 06:29 Login.php
-rwxr-xr-x  1 lasse lasse  19435 Feb 23 06:29 magic.dat
-rwxr-xr-x  1 lasse lasse   2863 Feb 23 06:29 mediauploader.php
-rw-rw-r--  1 lasse lasse  82973 Feb 23 06:29 networkinfo.csv
-rw-rw-r--  1 lasse lasse  14595 Feb 23 06:29 pb_wa_messages.php
-rwxr-xr-x  1 lasse lasse   7191 Feb 23 06:29 protocol.class.php
-rwxr-xr-x  1 lasse lasse   1777 Feb 23 06:29 rc4.php
-rw-rw-r--  1 lasse lasse  16951 Feb 23 06:29 Registration.php
-rw-rw-r--  1 lasse lasse  89537 Feb 23 06:29 smileys.class.php
-rw-rw-r--  1 lasse lasse  17303 Feb 23 06:29 SqliteAxolotlStore.php
-rw-rw-r--  1 lasse lasse   3528 Feb 23 06:29 SqliteMessageStore.php
-rwxr-xr-x  1 lasse lasse  12043 Feb 23 06:29 tokenmap.class.php
-rwxr-xr-x  1 lasse lasse   2069 Feb 23 06:29 token.php
-rwxr-xr-x  1 lasse lasse   9067 Feb 23 06:29 vCard.php

**Comment by mgp25** [comment]
@lkathke make sure you have downloaded the whole source, if required, don't use composer and do it manually.

I also noticed that you haven't installed `protobuf` module. You need to install the one mentioned in the wiki.

Regards
