### ISSUE TITLE
Register not work properly

### ISSUE THREAD

**Issue by KduOliva** [mgp25/Chat-API#1654]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.

### Error
Post your error below:
 experience trouble with registration. it give me the error: incorrect from registerTool.php, then, when a try to register from http://www.watools.es/pwd.html i got blocked.

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by capsload** [comment]
same for me!
