### ISSUE TITLE
No such signedprekey

### ISSUE THREAD

**Issue by sakaturo** [mgp25/Chat-API#1656]
Hi,
sorry for reopening this issue. I dont know if closed ones get read.

i have the problem, that 15-20% of the messages i receive could not be decrypted by the api.
And therefore the event onGetMessage will not be triggered.

I have tried to delete the axolotl .db, but after some messages the problem occurs again.
And the messages send before i delete wont be received you must send a new message and then it will work.

 the strange thing is, that this happens at the moment to numbers who has already send me messages. But after sometime new messages from these numbers wont get recieved.

But when i send them a message, then i will get there messages again.

I have the newest release on my server and the dependencies are all installed.

       $w = new WhatsProt($username, $nickname, false);

       $w->eventManager()->bind("onGetMessage", "onMessage");

       $w->connect();
       $w->loginWithPassword($password);

        while ($w->pollMessage()) {
        }

LOG:
`
    tx  <stream:features></stream:features>

    tx  <auth user="xxx5605xxx" mechanism="WAUTH-2">4���xxx56055xxx ΍��U&    MU�w�j�1456350144</auth>

    rx  <from s.whatsapp.net=""></from>

    rx  <stream:features></stream:features>

    rx  <challenge>��w��̼4��I�u�P</challenge>

    tx  <response>���ED~�N6�g�t�l�R�.Y�f�o��d�Ǘ�������eGX�Gٺ(Զ�`	Dθ_4c/�he�}՝j��v��</response>

    rx  <success t="1456350145" props="4" kind="free" status="active" creation="1453881370" expiration="4444444444">�k�%�n��#4�r���ot<-</success>

    tx  <presence name="Test" type="available"></presence>

    tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
    tx    <query>
    tx      <list name="default"></list>
    tx    </query>
    tx  </iq>

    tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
    tx    <config></config>
    tx  </iq>

    rx  <receipt from="1456348242@broadcast" id="ed1f46ae7531dc0845dbed" participant="xxx76823361xx@s.whatsapp.net" offline="0" t="1456350087"></receipt>

    tx  <ack participant="xxx76823361@s.whatsapp.net" to="1456348242@broadcast" class="receipt" id="ed1f46ae7531dc0845dbed"></ack>

    rx  <receipt from="1456348242@broadcast" type="read" id="ed1f46ae7531dc0845dbed" participant="xxx76823361@s.whatsapp.net" offline="0" t="1456350087"></receipt>

    tx  <ack participant="xxx76823361@s.whatsapp.net" to="1456348242@broadcast" class="receipt" id="ed1f46ae7531dc0845dbed" type="read"></ack>

    rx  <message from="xxx76823361@s.whatsapp.net" type="text" id="9297AAD7D3253867171" offline="0" t="1456350102" notify="Vivi">
    rx    <enc v="2" type="pkmsg">3���!#�d��	PǇ�X`i�����w�Ձ����P!�7�k��^����M�x����*t��l�/��"�3 !N>��6�Ě ���d�6b�S�O>���Y|X�z"��3w��/0��WM����MD�H:�Q��qg3�j� +���A'V����RQp4]&Xi�r�����y���	V@y��By�^.��t��s�(R��C HX�J�+��:�6J�B?O<��X1A�j<�υ|�:���gYD��c�REQ�G����� �&d@��8U<�soj�pɣp��h4"yH�ͷdZ���Ƴ�e_�&+�4�hX����!�>��S��]�'"���������D�V�g㏻ܸ{�k(0��</enc>
    rx  </message>

    tx  <ack to="xxx76823361@s.whatsapp.net" class="message" id="9297AAD7D3253867171" t="1456350102"></ack>

    tx  <iq id="03" xmlns="encrypt" type="get" to="s.whatsapp.net">
    tx    <key>
    tx      <user jid="xxx76823361@s.whatsapp.net"></user>
    tx    </key>
    tx  </iq>

    rx  <ib from="s.whatsapp.net">
    rx    <offline count="3"></offline>
    rx  </ib>

    rx  <presence from="xxx76823361@s.whatsapp.net"></presence>

    rx  <iq from="s.whatsapp.net" type="result" id="03">
    rx    <list>
    rx      <user jid="xxx76823361@s.whatsapp.net">
    rx        <registration></registration>
    rx        <type></type>
    rx        <identity>�7�k��^����M�x����*t��l�/��</identity>
    rx        <skey>
    rx          <id></id>
    rx          <value>�2�夑h�n��_��<��8�|�H�8�9*</value>
    rx          <signature>���Z��Gљ��'�����3��T��)��.�#\��{ ah�F�N����k�<Јr�2a�����7d= </signature>
    rx        </skey>
    rx        <key>
    rx          <id>n</id>
    rx          <value>uQ���'�D� ḻ�&�3>�7h쏟m����c</value>
    rx        </key>
    rx      </user>
    rx    </list>
    rx  </iq>

    tx  <ack to="xxx76823361@s.whatsapp.net" class="message" id="9297AAD7D3253867171" t="1456350102"></ack>

     -> Decrypted Message: No such signedprekey with id: 41468 - /whatsapp/src/SqliteAxolotlStore.php -  211Message 9297AAD7D3253867171 could not be decrypted, sending retry. tx  <receipt  id="9297AAD7D3253867171" to="xxx76823361@s.whatsapp.net" type="retry" t="1456350102">
    tx    <retry v="1" count="1" id="9297AAD7D3253867171" t="1456350102"></retry>
    tx    <registration>}�U</registration>
    tx  </receipt>

    rx  <ack from="xxx76823361@s.whatsapp.net" class="receipt" type="retry" id="9297AAD7D3253867171" error="400"></ack>`

**Comment by mgp25** [comment]
@sakaturo post full debug log please

**Comment by sakaturo** [comment]
what is missing?

**Comment by mgp25** [comment]
@sakaturo post full debug log, is incomplete

**Comment by mgp25** [comment]
I close this issue as its not an API issue. If you need further support, please post full debug log

Regards

**Comment by sakaturo** [comment]
hi,

found out that i have a cronjob wich a different while loop
Could that be the problem? That the loop gets stop before the api has finished the retrys ?

    while($w->pollMessage())
		{
			// stops after 4 minutes
			if(time() >= $start)
			{
				break;
			}
		}
