### ISSUE TITLE
Question about workflow

### ISSUE THREAD

**Issue by bgani** [mgp25/Chat-API#1657]
Wiki says: 
+ Rule 1: The number should be already synced and existing in WhatsApp before subscribing
+ Rule 2: You must subscribe before starting a conversation with a number
+ Rule 3: Do not subscribe for presence before unsubscribing first

1) What does means Rule 3 ?  

2) Should  do i enable all events for good flow ? Or i can enable events that only i need ?

Thanks

**Comment by mgp25** [comment]
@bgani 

1) It means that you can't subscribe a contact twice, in the case you don't receice any update from the contact you can send presense subcription again, but if you are already subscribed and you receive everything fine, don't subscribe to the contact again

2) Event system is for the user to be able to manage the data we want, you can enable the events you need.

Regards
