### ISSUE TITLE
No errors but the message not received

### ISSUE THREAD

**Issue by foxpcteam** [mgp25/Chat-API#1658]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
i don't get any error but the message not received in my phone.
have i missed something?

### Debug log

```xml
tx  <stream:features></stream:features>

tx  <auth user="972543138123" mechanism="WAUTH-2">c75d6fd0393732353433313338373035d9babbcfca0cd3737639c1daa048b5a0d6370a9c31343536353835383734</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>924fb20c45e3485c5cfe9ea793281b3190e22c89</challenge>

tx  <response>87cfb9982eb0124f1e83ac599d57a0916dfc337821dbf9e79d5ecec84a53d11997caaddbd23ebc867edc543fdf96e7c705f5b59fcb13a134b9653a772249236e7375dc6b1cade3f9b4163117d6fb</response>

rx  <success t="1456585875" props="4" kind="free" status="active" creation="1443685371" expiration="4444444444">fa58408364f9cb1921cbf887ed937ed1724d1381</success>

tx  <presence name="New TEST" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <message to="972546441123@s.whatsapp.net" type="text" id="d41d88b8e50d5d60e0d32d" t="1456585875" notify="New TEST">
tx    <body>test</body>
tx  </message>
```

**Comment by mgp25** [comment]
@foxpcteam please, read closed issues before opening a new issue, this question has been answered more than 20 times!! You are not polling enough, disconnecting too soon + nout using encryption, BAD!!
