### ISSUE TITLE
I'm blocked and I have a question about First Login flow

### ISSUE THREAD

**Issue by drieskensBR** [mgp25/Chat-API#1659]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

Hi, team! Sorry, but my English is not so good. But... I'm trying.

I have two Whatsapp numbers working fine and never blocked (with many contacts and online for more than 24h), but on the last week I'm trying to use a new number and I'm get blocked after 24h of use. 

I read the entire wiki and issues list looking for _block reasons_, and the answer is like "see the workflow".

In my code I'm using the same code explained on ["workflow"](https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#whatsapp-workflow) (First login), excluding the last three steps:

```PHP
$this->w->connect(); 

try{
    $this->w->loginWithPassword($this->senha); 
}catch(Exception $e) {
    echo "ERROR! MsgError: " . $e;
    exit();
}

$this->w->sendGetPrivacyBlockedList();
$this->w->sendClientConfig();

if($this->firstLogin) {
    $this->w->sendGetServerProperties();
    $this->w->sendGetGroups();
    $this->w->sendGetBroadcastLists();
}

$this->w->sendAvailableForChat($this->nome);

$this->ListenMessages();            
```

Those three steps are on wiki (workflow) but are not present in my code because my contacts database is empty (on first login):

```PHP
for (All contacts)
{
  $w->sendPresenceSubscription(contact); // subscribe to the user
}

$w->sendGetStatuses(All contacts);

for (All contacts)
{
  $w->sendGetProfilePicture(contact); // preview profile picture of every contact
}
```

**My questions are:**

1) In this case, I should to call this methods with empty array or can I ignore this steps?

2) Whatsapp can block if the account keep alive about long time (more than 24h online)?

3) The sync procedure needs to be performed only with new contacts or I need sync existing contacts? What is the frequency of sync?

**Important Info:**
My last blocked number had one contact synced (my own number) and I sent a couple message to me (testing) and get blocked after 24h online.

**Other common block reasons on Wiki and Issues list are ok:**

- I'm using Sync when receive the first message from a contact and I send a message only when is Synced.

- I'm not using broadcast message and spam.

Anybody can help me?

**Comment by mgp25** [comment]
@drieskensBR 

regarding to your code you can remove this calls since API does it automatically:

```php

$this->w->sendGetPrivacyBlockedList();
$this->w->sendClientConfig();
```

Answers:

1) Yes, you can ignore those calls.
2) Yes, there is a low probability but yes, i recommend you to emulate as much as possible a human behaviour.
3) In the first login all contacts, and then only new contacts

Maybe those messages you sent caused the block, maybe because the timing or other bad flow during the process.

Hope this solved your doubts

Regards
