### ISSUE TITLE
 Sending to a number that does not exist

### ISSUE THREAD

**Issue by projetosistema** [mgp25/Chat-API#1661]
Warning (2): Invalid argument supplied for foreach() [APP/Lib/ChatApi/src/handlers/IqHandler.php, line 257]

Error: Call to a member function getChainKey() on a non-object
File: /var/www/ChatApiWebApp/app/Lib/ChatApi/src/libaxolotl-php/state/SessionState.php
Line: 177

I wish I could handle this error, or fix it.

Thanks.

**Comment by 0xTryCatch** [comment]
Don't send to a number that does not exist
