### ISSUE TITLE
Event: onMessageReceivedServer

### ISSUE THREAD

**Issue by paulocotta** [mgp25/Chat-API#1662]
Hello, how are you?
I have a question can help me, because I did not find any documentation that answers my question.
I am sending a message to a group, but do not get any return event "**onMessageReceivedServer**".
This is normal?
Thanks

**Comment by mgp25** [comment]
@paulocotta please provide full debug log and code

Regards

**Comment by paulocotta** [comment]
OK
[send.txt](https://github.com/mgp25/Chat-API/files/150259/send.txt)

**Comment by paulocotta** [comment]
Note: If I send a message to "profile" everything is perfect

**Comment by bgani** [comment]
paulocotta, pollMessage

**Comment by paulocotta** [comment]
Thank you so much.
More a single question. Then I can use the "pollMessage" before disconnecting?
Or have any other way for the return of the events separately?

**Comment by 0xTryCatch** [comment]
Read the wiki for these answers.

**Comment by paulocotta** [comment]
Tks a lot
