### ISSUE TITLE
Changing profile picture.

### ISSUE THREAD

**Issue by AloneMate** [mgp25/Chat-API#1663]
Hello,

I have made a simple script for me that is to change profile picture after every hour. The image is randomly chosen from the directory. I have used a function ```sendSetProfilePicture($path)``` to change profile picture. 

As you said that we have to use ``` pollMessage()``` function every time. The problem is I use same phone number on my device as well as on vps too. 

Question is can I change profile picture without using pollMessage() function ? Because If I use this function and then change profile picture, some of the messages will receive on the server side and I will loose them since I have not made any code to store messages. If I change profile picture without pollmessage then WA will ban my number ?

Thanks!

**Comment by mgp25** [comment]
@AloneMate you need to pollMessages. WA wont block your number, but better poll messages

Regards
