### ISSUE TITLE
Login Failure Exception - Number Blocked

### ISSUE THREAD

**Issue by designerrsoft** [mgp25/Chat-API#1666]
Make sure these boxes are checked before submitting your issue -- thank you!

- [-] You are using PHP > 5.6
- [-] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [-] You have checked if someone has already asked the same issue you have.
- [-] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [-] Is not a programming question.
- [-] You are using latest Chat API code.

### Error
Post your error below:
I am using my the below code for sending msg to my friends. I was using it for quite a couple of time but suddenlty it gave me loginfailure Exception. I reset my account using wart get new password and start working again but after some time it again gave me same Exception and when i try to reset my number with wart it gave me that my number is blocked.

I see that when I user onMessageReceivedServer function the problem began to appear or onSyncResult because I just added these two methods for checking if the message has been send and if my friends has whatsapp or not an than send him the message. Can you please tell me the exact reason for this block so that I may not make the same mistake again and prevent getting blocked by whatsapp. I am not using it for illegal or bulk messaging purpose, just 2-3 messages in 5 minute, I don't think its consider as bulk. And these 2-3 messges are just for testing the API that its working as required, after that may be only 1 message per 10 minutes.

Here is my code how I used you API

Thats all it can you explain to me the exact reason of getting blocked. Is it that I used sync on same number many times? or its onMessageReceivedServer error. I am only saying that when I updated my code using these two functions this happened to me, but if you see something that I am not using as required by whatsapp kindly suggest me. 
Thanks for your support
`require('lib/src/whatsprot.class.php');
require('lib/src/vCard.php');

           $username ='xxxxxxxxxxxxxx';
           $password ='xxxxxxxxxxxxxxxxxxxxxxx=';
           $w = new WhatsProt($username, "some_title", false, false); 
           $w->eventManager()->bind('onGetSyncResult', 'onSyncResult');
          $w->eventManager()->bind('onSendMessage', 'onMessageReceivedServer');
          $w->connect();
          $w->loginWithPassword($password);

         function onMessageReceivedServer($mynumber, $from, $id, $type,$time)
         {
      
               // Some code to insert the message id into the database.
              // Nothing from the api used here.
         }
        function onSyncResult($result)
         {
               // Checking for existing number if its using whatsapp or not. If yes add to our array tha will be used to send message
             global $enums;
             foreach ($result->existing as $number) 
             {
                  array_push($enums,$number); 
              }
          }

          $numbers = $_POST['nums']; // This will get the numbers from the text field on html form
          $numbers = array_unique(explode(',',$numbers)); // Convert the numbers into an array of values only unique
          if(count($numbers)!=0)
           {
               if($message!="")
               {
                  for($i=0;$i<count($numbers);$i++)
                 { 
                     $w->sendSync($numbers[$i]);
                  } 
                  $numbers = array_values(array_unique($enums));
                 for($i=0;$i<count($numbers);$i++)
               {
                   $w->sendPing();
                   $w->sendMessage($numbers[$i],$message);
                    sleep(2);
               }
              }
            }
`

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```
@mgp25 @CODeRUS

**Comment by mgp25** [comment]
@designerrsoft you are using a very bad flow, its normal that WhatsApp blocked your number.

Make sure to have latest API source code. Read the wiki, check and fix your flow, there is useful information in the wiki

Regards

**Comment by designerrsoft** [comment]
@mgp25 Thank you for your reply 
can you tell me the right flow ?
i will be thankfull to you .
i used latest API
Regards
