### ISSUE TITLE
BroadCast array problem.

### ISSUE THREAD

**Issue by AloneMate** [mgp25/Chat-API#1668]
Hello,

I have used broadcast and facing some problem. I have list of numbers to broadcast in txt file.
```$target``` array has all the numbers from file.
```
$convert    = explode("\n", $file);
$target = array();
for ($i=0;$i<count($convert);$i++)  
{
    array_push($target, $convert[$i]);
}
$w->sendBroadcastImage($target, $image_name, $storeURLmedia = false, $fsize = 0, $fhash = "", $image_cap);
```

This code doesn't even work for me.

But when I create array manually like this, this works perfectly and every user gets the message.

```
Note : When I print_r both arrays, they gives the same result and type is of array. But when I do it manually everybody receives it but when I do with dynamically it doesnt work.
```

```
$target = array("no1","no2","no3");
$w->sendBroadcastImage($target, $image_name, $storeURLmedia = false, $fsize = 0, $fhash = "", $image_cap);
```

Debug Log : 

Nothing to show in debug log since in both the case it shows the boradcast lst created and send to those number in list, but in manual case everybody receives it. I can see that script made broadcast list but messages are not sent.

**Comment by mgp25** [comment]
As you hasve described, is not an API issue, is a php programming issue. Compare the two outputs using `var_dump`
