### ISSUE TITLE
WhatsApp doesn't support Nokia S40/S60 anymore?

### ISSUE THREAD

**Issue by tchibomann** [mgp25/Chat-API#1669]
Hi,

i read some days ago, that WhatsApp won't support Nokia S40 and S60 anymore at the end of 2016. In the code of ChatApi I saw, that it uses the device id from S40 or S60 (didn't know which one) as camouflage, did I understand that right?

Or is the device id generally unimportant? If it is important, what can we do here?

**Comment by AloneMate** [comment]
Not API related issue I guess.

**Comment by mgp25** [comment]
@tchibomann you dont have read the wiki and you dont have seen the code. Next time ill close the issue directly. We use android data btw
