### ISSUE TITLE
Register tool says there is a problem with requesting the code

### ISSUE THREAD

**Issue by harianus** [mgp25/Chat-API#1670]
All checkboxes are checked:

- [x] PHP 5.6.18 on Mac OS X 10.11.3
- [x] PHP Protobuf (0.9) and Curve25519 (your version) are installed
- [x] No [corresponding issues](https://github.com/mgp25/Chat-API/issues?utf8=%E2%9C%93&q=is%3Aissue+%22There+was+a+problem+trying+to+request+the+code.%22)
- [x] You have red the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] It is not a programming question.
- [x] Running [version 3.2](https://github.com/mgp25/Chat-API/releases/tag/v3.2) Chat API code.

### Error

When running this in my Terminal

```
$ php -f registerTool.php 
```

I get this response

```
There was a problem trying to request the code.
```

### Debug log
Here is the debug log

```xml
####################
#                  #
# WA Register Tool #
#                  #
####################

Username (country code + number, do not use + or 00): 31645161132
PHP Notice:  Trying to get property of non-object in /Users/Adriaan/Downloads/Chat-API-master/src/Registration.php on line 78

Notice: Trying to get property of non-object in /Users/Adriaan/Downloads/Chat-API-master/src/Registration.php on line 78
PHP Notice:  Trying to get property of non-object in /Users/Adriaan/Downloads/Chat-API-master/src/Registration.php on line 82

Notice: Trying to get property of non-object in /Users/Adriaan/Downloads/Chat-API-master/src/Registration.php on line 82
PHP Notice:  Trying to get property of non-object in /Users/Adriaan/Downloads/Chat-API-master/src/Registration.php on line 83

Notice: Trying to get property of non-object in /Users/Adriaan/Downloads/Chat-API-master/src/Registration.php on line 83
Array
(
    [cc] => 31
    [in] => 645161132
    [lg] => nl
    [lc] => NL
    [id] => ????t??29
                     6_?x
                         	?2
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 2996
    [extexist] => 1
    [extstate] => 1
)
```

I tried again a hour later, still the same error.

**Comment by AloneMate** [comment]
Have you checked exampleRegister file in examples folder ?

**Comment by mgp25** [comment]
@harianus please you `registerTool.php` with no modifications, because right after the number is asked which method you want to get back your code. Make sure you are using latest API code. Just tried and everything is perfect:

```
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): ******


Type sms or voice: sms
Array
(
    [cc] => **
    [in] => ****
    [lg] => es
    [lc] => ES
    [id] => ?g3?r
?
 ??8??s????
    [token] => ****
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 7262
    [rchash] => 0da8d5374a9692f76b99a45f1238ee3a82cbcae7a3a082d7d46631896d6f4eb9
    [anhash] => c34283809dd02a68b5e829a8d016084c
    [extexist] => 1
    [extstate] => 1
    [mcc] => ***
    [mnc] => 000
    [sim_mcc] => 214
    [sim_mnc] => 000
    [method] => sms
)
```

There are also other alternatives, like WATools or WART. More info. in the wiki.

Regards

**Comment by harianus** [comment]
> Have you checked exampleRegister file in examples folder ?

Of course I did.

> @harianus please you registerTool.php with no modifications

I didn't edit anything.

> because right after the number is asked which method you want to get back your code.

It errors there, so that code is probably not reached.

> Make sure you are using latest API code.

I downloaded it yesterday. As a .zip from GitHub from the master branch. That is the latest code, right?

**Comment by mgp25** [comment]
@harianus are you using PHP 5.6 and everything setup correctly? Make sure everything is okay with your enviroment

**Comment by harianus** [comment]
> are you using PHP 5.6 and everything setup correctly?

As stated in this issue description, yes I do have PHP 5.6.18 installed.

**Comment by mgp25** [comment]
@harianus remove the lines that gives error and post the debug log with the response from the server, its possible that WhatsApp has introduced some changes

**Comment by harianus** [comment]
In the meantime I did it with the WART executable on Windows and it worked, so I don't dare to do it again because the previous number was already blocked. Thanks for the help anyway.
