### ISSUE TITLE
Sync Problem

### ISSUE THREAD

**Issue by designerrsoft** [mgp25/Chat-API#1671]
Make sure these boxes are checked before submitting your issue -- thank you!

- [- ] You are using PHP > 5.6
- [- ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ -] You have checked if someone has already asked the same issue you have.
- [- ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ -] Is not a programming question.
- [ -] You are using latest Chat API code.

### Error
Post your error below:

I am using latest api and my problem is that I been blocked like 2 times in a day, I was only doing sync to see which of my friends have whatsapp, for this purpose I am using mysql database, I have very simple logic that if my contact has whatsapp move that contact to another table and if not move it to another table, the reason is that this contact list is very old and I am out of touch with my friends for a long time so if one of my firends have whatsapp i will send him message and If not i will search for him on facebook etc. Kindly let me know what I am doing wrong because I cannot change my numbers often if getting blocked. The database contains not more than 300 contacts.

I send email to whatsapp also they said that I am violating their terms of use, so my question is why? As I am not sending a single message from the number so bulk messaging is just out of question. 

                       <?php
                        require('lib/src/whatsprot.class.php');
                        require('lib/src/events/MyEvents.php');
                        require('includes/dbconn.php');

                        $limit = 10;
                        $numbers = array();
                        $fetch_query = mysql_query("SELECT numbers FROM mycontacts LIMIT $limit");
                        while($rows = mysql_fetch_assoc($fetch_query))
                        {
                          $n = $rows['numbers'];
                          array_push($numbers, $n);
                        }

                        sleep(5);

                        $username ='xxxxxxxxxxxxxxxx';
                        $password ='xxxxxxxxxxxxxxxxxxxxxxxxx=';
                        $w = new WhatsProt($username, "xxxx", false, false); 
                        $events = new MyEvents($w);
                        $w->eventManager()->bind('onGetSyncResult', 'onSyncResult');
                        $w->connect();
                        $w->loginWithPassword($password);

                        function onSyncResult($result)
                        {
                            foreach ($result->existing as $number) 
                            {
                                echo "$number  exists <br />";
                                $number = explode('@',$number);
                                $number = $number[0];
                                $qa = mysql_query("INSERT INTO numbers_hwa(numbers) VALUES ('$number')");
                                if($qa>0)
                                {
                                  mysql_query("DELETE FROM mycontacts  WHERE numbers='$number'");  
                                }
                            }
                            foreach ($result->nonExisting as $number) 
                            {
                                echo "$number does not exist<br />";
                                $q = mysql_query("INSERT INTO numbers_nwa(numbers) VALUES ('$number')");
                                if($q>0)
                                {
                                  mysql_query("DELETE FROM mycontacts  WHERE numbers='$number'");  
                                }
                            }
                        }
                        foreach($numbers as $number)
                        {
                          $w->sendSync($number);  
                        }
                        ?>

@mgp25 
### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Bad behaviour, read wiki
