### ISSUE TITLE
Whatsapp Groups - Need Help

### ISSUE THREAD

**Issue by Faber73** [mgp25/Chat-API#1673]
At first congratulation for this api software.

I need help about manage my groups.

I want to add people that ask to be in the group from a form in my webpage, and I want to take one post links from my blog and publish it on the group.

Questions is : 

1. where I can find the ID of my group
2. how add people in the group
3. can I use the same user account that I've configured in my phone ? or I need a dedicate account (sim number)

Thank you and Best Regards

**Comment by mgp25** [comment]
@Faber73 

Answers:

1. Explained in the wiki and closed issues
2. Explained in the wiki and examples in closed issues
3. That is also explained in the wiki.

Sorry by answering like that, but when you open a new issue, there is a text where we tell the requirements to open a new issue, and it seems you dont

Regards

**Comment by Faber73** [comment]
I'm sorry dude, but  don't find it.

In the wiki I read that I can promote an user admin of the group or demote him, not how add a simple user.

About the group ID I read

> Sending messages to a group:

> Where $gId is the group id.

> $w->sendMessage($gId, $msg);


but not very I find the ID of my group.

**Comment by mgp25** [comment]
Seriously, just by searching in the closed issues: https://github.com/mgp25/Chat-API/search?q=add+group&type=Issues&utf8=%E2%9C%93

Is not that difficult right?
