### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by paulocotta** [mgp25/Chat-API#1675]
Hello guys, I believe this occurring a small error on line 58 of the file "MessageHandler.php". The error occurs when there is some picture for example "mediatype" to read.

"PHP Fatal error: Call to a member function getAttribute () on null in /home/ubuntu/Dropbox/WebServer/www/apiwa/class/src/handlers/MessageHandler.php on line 58"

I hope you have understood me.

Thank you

**Comment by gojigeje** [comment]
this issue affects me too

**Comment by paulocotta** [comment]
I commented the block to not stop the application.
And you?

**Comment by gojigeje** [comment]
yes commenting the block did solve the error. but would it affect Chat-API functionality?

**Comment by paulocotta** [comment]
I'm not the right person to answer that, but analyzing the code I think YES.

**Comment by mgp25** [comment]
@paulocotta post the debug log

**Comment by aal89** [comment]
I just missed this issue, I have created a pull request which resolves this issue. See #1677

**Comment by mgp25** [comment]
@aal89 thanks, merged
