### ISSUE TITLE
How to decrypt the attached thumbnail with the url ?

### ISSUE THREAD

**Issue by jandrito80** [mgp25/Chat-API#1676]
In mediatype="url", there is an encrypted thumbnail . How do I decrypt it ? And I can how to send a URL with thumbnail , an tittle description?
In MessageHandler.php only extract body.

Thanks

**Comment by mgp25** [comment]
@jandrito80 use event system if you are talking about the images. Image will be decrypted in `$file` and decrypted thumbnail in `$thumbnail`

If you are talking about url of websites, i havent done the events yet

**Comment by jandrito80** [comment]
OK, thanks
I were talking about url. From here:
`rx  <message from="34699******@s.whatsapp.net" type="media" id="2EB4E03E45AAA1C939BB5E4613A7D2" t="1457070943" notify="******">
rx    <enc v="2" type="msg" mediatype="url"> 6067 byte data</enc>
rx  </message>
`
I hava can extract url, tittle and description, but not thumbnail

**Comment by jaikumarth** [comment]
this is hell.. what ever i post this stupid simply tells +91 not supported. do this code have brain to see +91 or something.
support for not working code

**Comment by chgss** [comment]
Hello @mgp25, @jandrito80. I dont want to disturb.

I am trying to get the image file, I tried with this function i saw in examples files but it doesnt work.

```
function onGetImage($mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption)
{
    $number = ExtractNumber($from);
    $nickname = findNicknameByPhone($number);
    $path = __DIR__.DIRECTORY_SEPARATOR."data/media/$nickname/";
    if (!file_exists($path)) {
        mkdir($path);
    }
    $filename = $path.time().'.jpg';
    $data = file_get_contents($url);
    $fp = @fopen($filename, 'w');
    if ($fp) {
        fwrite($fp, $data);
        fclose($fp);
    }
    echo " < Received image from $nickname >\n";
}
```

I have the last version and I can receive correctly audios, texts but I can save locally the image file I receive.

In function you said have variable $file but I dont see $thumbail, where you can send an example for this.

@jandrito80 maybe you can resolve this ??

Thanks a lot sorry again but I cant found information for this in wiki, I ve tried with all those variables and nothing

**Comment by hydefus** [comment]
I guess this is rather a programming question.
On the sample directory you will find several working codes that receive
images perfectly.

**Comment by chgss** [comment]
Hello @hydefus, I think you don't read my comment or maybe I cannot explain better.

When I put $data = file_get_contents($url) I get file with 0 bytes.
When I put $data = file_get_contents($file) I get file with bytes is not a legible image.

Can you help me with this ??

The last comment said use $file variable or $thumbail variable; I used system events onGetImage and example in file client.php, but it doesn't work, the $thumbail variable is not present in OnGetImage event.

Thanks a lot for your help.

**Comment by mgp25** [comment]
@jandrito80 event required an update. I'll add this in the next release
@chgss that question is already answered, search in closed issues.

Regards
