### ISSUE TITLE
No Notification after broadcast sending

### ISSUE THREAD

**Issue by Faber73** [mgp25/Chat-API#1678]
Hello,
finally all working fine, I can manage my group users and send messages to the group and directly to users with a broadcast sending. But when users receive the message, whatsapp don't notify it, like blink light or whatsapp icon on the phone bar. If you going to open whatsapp you can see the green circle near the username, but it's all.

It's normal or I mistake (or forget) something ?

Thank You

**Comment by AloneMate** [comment]
Working fine for me.

**Comment by mgp25** [comment]
@Faber73 Its working perfectly.

Regards
