### ISSUE TITLE
Messages are not decrypted.

### ISSUE THREAD

**Issue by AloneMate** [mgp25/Chat-API#1679]
Hello,

I have been using this API since 1 year and I faced this problem everytime. The messages are not decrypted. This is the error.

```
-> Decrypted Message: No such signedprekey with id: 9652 - /var/www/html/src/SqliteAxolotlStore.php - 248Message 6B5468A95482CE135D2D could not be decrypted, sending retry. tx  <receipt id="6B5468A95482CE135D2D" to="xxx@s.whatsapp.net" type="retry" t="1457232364">
tx    <retry v="1" count="1" id="6B5468A95482CE135D2D" t="1457232364"></retry>
tx    <registration>c37b0d45</registration>
tx  </receipt>
```

I have found why it happens. I'm a WhatsApp plus user but API is works as legal WhatsApp. So What I have done so far is I have created a program which reads the message and stores it. I do get this error in this case :

My WhatsApp configs :- 
1 ) Hide off blue ticks.
2 ) Hide Online Status.
3 ) Hide Second tick.

When the user with following configs sends 5-6 message to API it stops working because the WhatsApp plus receiving messages but it doesn't say that this message is received and remains with SINGLE TICK. But in reality I have received the message on my phone. So API will get confused and still it will show error because no ACK were sent from WhatsApp plus. Actually it doesn't send anything at all due to WhatsApp plus Features. Every time I send from that cracked whatsapp the script stops and shows the above message above. I have latest code and tried deleting .db files.

Ok now the solution I found after trying many times, When I turned off Hide Second tick, Hide BlueTick and made that whatsapp plus to original whatsapp the script first time stopped and then worked very well. Kindly look into this matter asap.

Thank you!

**Comment by mgp25** [comment]
@AloneMate the second tick is required, that means that the message has been received by the user. And also, after this:

```xml
-> Decrypted Message: No such signedprekey with id: 9652 - /var/www/html/src/SqliteAxolotlStore.php - 248Message 6B5468A95482CE135D2D could not be decrypted, sending retry. tx  <receipt id="6B5468A95482CE135D2D" to="xxx@s.whatsapp.net" type="retry" t="1457232364">
tx    <retry v="1" count="1" id="6B5468A95482CE135D2D" t="1457232364"></retry>
tx    <registration>c37b0d45</registration>
tx  </receipt>
```

The API is retrying to decrypt the message and its very possible that the API has decrypt it, check your debug log after that call. If you are disconnecting right after that, of course you will get errors.

The API has coded for working with official WhatsApp, there is no WhatsApp+ support in the API.

Regards

**Comment by AloneMate** [comment]
@mgp : No, I'm not disconnecting, I have while loop so it lasts forever. I know there is not whatsapp support. But what if WhatsApp plus user is my friend or some relatives ?

Thanks!
