### ISSUE TITLE
Class 'Login' not found in whatsprot.class.php

### ISSUE THREAD

**Issue by jay2413** [mgp25/Chat-API#1680]
### Error
I have checked and i got my password from exampleRegister.php

now when i go to login.php for login in WA
i got following error:

`Fatal error: Class 'Login' not found in G:\wamp\www\Chat-API\src\whatsprot.class.php on line 285
`

I have used this code for login in WA

```
<?php
require '../src/whatsprot.class.php';

$username = "my username";
$nickname = "my nickname";
$password = "my password"; // The one we got registering the number
$debug = true;

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->pollMessage();

$w->loginWithPassword($password); // logging in with the password we got!
?>
```

**Comment by mgp25** [comment]
@jay2413 make sure you are using the latest API source code and PHP 5.6 as explained in the wiki. Is not an API issue.

By the way, remove the `pollMessage` after `connect` it doesn't make any sense.

Regards
