### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by paulocotta** [mgp25/Chat-API#1681]
Guys like to give a suggestion for implementation. Where can I do this? Right here?

**Comment by mgp25** [comment]
@paulocotta yes

**Comment by paulocotta** [comment]
My suggestion is to add two more columns in "msgstore":
1-name
2-url_media

It is possible?
I believe so, because in Events (onGetMessage, onGetGroupMessage), these fields are returned.

Thank you so much

**Comment by paulocotta** [comment]
Name = $node->getAttribute('notify')

**Comment by mgp25** [comment]
@paulocotta send a pull request or you can modify that by yourself as is not something API requires.

Regards
