### ISSUE TITLE
After upgrade from WhatsAPI-Official to Chat-API: no messages are sent anymore

### ISSUE THREAD

**Issue by capsload** [mgp25/Chat-API#1684]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

<?php
require_once('../src/whatsprot.class.php');

$input = var_dump($argv);
$debug = false;

$nickname = 'BierBot';
$username = '49xxx';
$password = 'xxx';

$w      = new WhatsProt($username, $nickname, $debug);

$w->connect();
$w->loginWithPassword($password);

$w->sendMessage('4915xxx-14xxxxx@g.us', "$argv[1]");

?>

Do i miss something like from the new protocols?
Do i need another, additional "require_once" ?

**Comment by mgp25** [comment]
Is that hard to quote properly the code?

And second thing, why the heck you are not polling? Please check all examples in the closed issues, is not the API is what you do with the API what it makes work that way.

_sigh..._

**Comment by capsload** [comment]
Its working for direct chat. Just not in groups.

**Comment by mgp25** [comment]
@capsload without debug log, no support

**Comment by capsload** [comment]
php /home/wable/home/WhatsAPI-Official/examples/cli.php test
array(2) {
  [0]=>
  string(51) "/home/wable/home/WhatsAPI-Official/examples/cli.php"
  [1]=>
  string(4) "test"
}
tx  <stream:features></stream:features>

tx  <auth user="49176xxx" mechanism="WAUTH-2">xxxxxxxx</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>xxx</challenge>

tx  <response>xxxx</response>

rx  <success t="1457354541" props="4" kind="free" status="active" creation="1457350362" expiration="4444444444">b4387b0d650a1a269040104b868a59aa8e58e30f</success>

tx  <presence name="BierBot" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <message to="xxx-xxx@g.us" type="text" id="d1f7d063f0f42fa0cfdee7" t="1457354533" notify="BierBot">
tx    <body>test</body>
tx  </message>

**Comment by mgp25** [comment]
@capsload next time you dont quote things i wont answer you, seriously

you are not polling messages

**Comment by capsload** [comment]
@mgp25 
Thanks.

So im now polling messages, but its still not sending messages to groups.

Whats the correct format for group ID's ?

"Where $gId is the group id.
$w->sendMessage($gId, $msg);"

Im currently using this format, is it correct?

$w->sendMessage('49151xxx-141xxx@g.us', "$argv[1]");

**Comment by capsload** [comment]
How many times should $wa->pollMessage() appear per script @mgp25 in your oppinion?
