### ISSUE TITLE
Error to ResetAcount

### ISSUE THREAD

**Issue by borjapu** [mgp25/Chat-API#1687]
Hello, this days im having an error and i cant to implement the receibe method.
My problem is that the message its encryp, and im trying to follow previus Issues, but i cant. 

When i try to run the resetAcount.php, it throws me this error

```terminal

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php:299
```
I have the last API and installed all Dependencies.

I can send messages without problems, but receibe... 
Thanks in advance.

**Comment by mgp25** [comment]
If you have dependencies installed correctly, messages are decrypted, then you dont have installed or loaded the extensiones correctly.

Check it
