### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by budaraju** [mgp25/Chat-API#1688]
### Error
./examples/registerTool.php
wen I'm opening getting Error like this 

#################### # # # WA Register Tool # # # #################### Username (country code + number, do not use + or 00): 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\app\examples\registerTool.php on line 14

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\app\examples\registerTool.php on line 14
Wrong number. Do NOT use '+' or '00' before your number

Can u plz help me

**Comment by borjapu** [comment]
You have to open registerTool with the Console/Terminal, NO with the navigator. 
I did the same.

**Comment by budaraju** [comment]
I have open thru browser in windows and already i have installed Xampp with all Dependencies

"http://localhost/app/examples/registerTool.php"

**Comment by borjapu** [comment]
you have to use the terminal:
```cd app/examples/  ```
and
```php registerTool.php```
https://www.youtube.com/watch?v=pAV9U5I8sfs
