### ISSUE TITLE
¿Where are the KEY and the IV for decrypt the local database? ¿How can i get them?

### ISSUE THREAD

**Issue by durkh3im** [mgp25/Chat-API#1689]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Post your error below:

BTW isnt an error, well can be interesting search for the KEY and IV that whatsapp receives from the whatsapp server for encrypt the local android database. I have this cuestion because whatsapp backup get protected in the latest version and its impossible to do via ADB, can be awesome to get this data by 'only' register the phone number with this API. So that gave me here guys ;)

Awesome job, regards and thanks for the help.

**Comment by mgp25** [comment]
Not API related issue. Maybe if i ever do that, ill post in the wiki

Regards
