### ISSUE TITLE
Receive contacts info problem

### ISSUE THREAD

**Issue by gentjana** [mgp25/Chat-API#1692]
Hello Guys,

I've updated Chat-API to latest version but i have a problem on getting info about contacts. 
From the log is see data comming as below:

```xml
rx  <message from="355664060055@s.whatsapp.net" type="media" id="14391ADAD4243C0118807EDB8F8765" offline="0" t="1457517608" notify="Gentjana Malasi">
rx    <enc v="2" type="pkmsg" mediatype="contact">330899ee8a03122105b81d1ce669e676877f5924d6f0d955ebb672d232956ac857e43d8762b57925671a2105d814a097f5d0c2784f8d88e0c983c30216ffaed92fed968416d46b19228d1137229302330a21050ff69266d73d79ad0dc074477f5c043efde0a4a20e6bb23fb61611582b9ae24c1000180022e00142cb6f8ba930a264d9ae54bd90daeb88b3f1c50557da2aa8bd06a412f4cca6bc1fa0cb6fe5892b2c83be75445fad0cb082d250d369dabcaa457d5e64372865cd13e033726aad5adcf7c4ee85e3ea8e62e1f5c418b8522f8bf74ac347304537eb646460628b057dd8299d57a071d55c612a78000f6a1bb3af9f307afc2fc26e4513ff4d5e93902e75bd9f720dcbafca04748f91e09a734bb7b4b12314bf654733ba8a6f6a3f2023a50ad0afe6e5c2286b4f03f36facb28801e66f0befa873a13b17309da827e61e912a4bcf31cd11470ccae2eaf188df1d702bd74e2eea610e58efe97611674b5af72887bfc4ec0230a510</enc>
rx  </message>

-> Decrypted Message: HEX:0a0561626b6f6d820168424547494e3a56434152440a56455253494f4e3a332e300a4e3a3b61626b6f6d3b3b3b0a464e3a61626b6f6d0a6974656d312e54454c3a2b3335352036382032303620363134340a6974656d312e582d41424c6162656c3a4d6f62696c650a454e443a5643415244 tx  <receipt type="read" to="355664060055@s.whatsapp.net" id="14391ADAD4243C0118807EDB8F8765" t="1457517608"></receipt>
```

But on function: ( public function onGetvCard($mynumber, $from, $id, $type, $time, $name, $vcardname, $vcard)) i get no info about contacts that have been send. 

Plese can you check this issue. 
Thank you.

**Comment by jaikumarth** [comment]
this is hell.. what ever i post this stupid simply tells +91 not supported. do this code have brain to see +91 or something.
support for not working code

**Comment by feltkamptv** [comment]
I have exactly the same problem with the latest code. I cannot receive contacts anymore, but only see the enc message, same as above. This is also the same with receiving documents.

For processing the incoming messages I am using a ProcessNode class, same as in exampleFunctional.php.

I hope this can be fixed anytime soon! Thanks in advance!

**Comment by gratbrav** [comment]
Same Problem. But when I receive a contact from iPhone, the contact is not decrypted and fired the  onGetvCard function.
Only I use an Android Device, the contact is decrypted an the onGetvCard function is not fired.

Maybe its missing in the Process Function from MessageHandler file? Its seems the onGetvCard function is only fired when its encrypted.

**Comment by mgp25** [comment]
This is added in next release.

Regards

**Comment by feltkamptv** [comment]
Great! Looking forward to it! Thanks! :)
