### ISSUE TITLE
Access WhatsApp in my university.

### ISSUE THREAD

**Issue by johnmoress** [mgp25/Chat-API#1693]
Hello,

I currently study in my university where WhatsApp is banned for accessing. So I have came across this API. I wonder if I can use WhatsApp through proxy with this API ? Is there any way to use it ?

Thank You!

**Comment by mgp25** [comment]
@johnmoress this API has no proxy support and im not going to implement it. The best thing you can do in your case is talk with your university director to open whatsapp in your university

Regards

**Comment by hgc2002** [comment]
Well, the short answer is no, with a little but. Your smartphone won't connect anywhere different from Whatsapp's servers, so this is why this API won't work for you. The little but is that, if you make your own wasap client with this API and tied your phone number to it, sure you'll be able to access it from your university, but this is like a 100-mile run just to go crossing the street. It's too much work for it.

**Comment by johnmoress** [comment]
@mgp25 : Thanks for your reply. I know some kind of PHP. Can you tell me which class should I modify ? Please give me some hint :/
