### ISSUE TITLE
Register tool is not working

### ISSUE THREAD

**Issue by jpgomez1975** [mgp25/Chat-API#1694]
Hi whatsapi team,
The Register Tool is not working since yesterday. I think is because the lastest whatsapp update.
Regards,
Juan

**Comment by 0xTryCatch** [comment]
Where is the debug log? Otherwise this issue will be closed.

**Comment by jpgomez1975** [comment]
Hi @0xTryCatch, my code is:

$debug = true;
$username = '549xxxxxxxxxx';   
$w = new Registration($username, $debug);
$w->codeRegister('150115');



My debugPrint:

Array
(
    [cc] => 549
    [in] => 13116xxxxx
    [lg] => en
    [lc] => CN
    [id] => ▒▒▒1▒0:▒{˻▒lsv▒)2
    [token] => COphQAORV6aMqQlVlcKHBiczHAI=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 8903
    [rchash] => e51dd380e0a278e1a13016ba30c74408881d0fd85dde6f70a24235c266c3288a
    [anhash] => db3e834150811d52c77badf1aa24730b
    [extexist] => 1
    [extstate] => 1
    [mcc] => 460
    [mnc] => 000
    [sim_mcc] => 460
    [sim_mnc] => 000
    [method] => sms
)
debugPrint
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 65
    [sms_wait] => 65
    [voice_wait] => 65
)

debugPrint
stdClass Object
(
    [status] => fail
    [reason] => temporarily_unavailable
    [retry_after] => 3600
)

An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable


Thanks for your help.

**Comment by mgp25** [comment]
@jpgomez1975 its working, check the response: `temporary unavailable` you need to retry after 3600 seconds. By the way, quote properly debug log
