### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by jaikumarth** [mgp25/Chat-API#1695]
Make sure these boxes are checked before submitting your issue -- thank you!

- [Y ] You are using PHP > 5.6
- [ Y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ Y] You have checked if someone has already asked the same issue you have.
- [Y ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ Y] Is not a programming question.
- [ Y] You are using latest Chat API code.

### Error
i am able to register my number and got the below error when i try to log in

### Debug log
Post your debug log below:

```xml
[] Logging in as 'Jaya' (9197xxxxxxx) tx  <stream:features></stream:features>

tx  <auth user="9197xxxxxxx" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>0d7f01f9e970486a55361bc05a3221e665236c39</challenge>

tx  <response>a349f36d4b17361e33b0471c908dbdbaf00dbe084f5f9a879779114195710582fdc2a21bd335813cac56d1d0850a3e0bf02eef8126175935ef47d243a928342933f020f8e26c909293d46dc801e7</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\W2\src\Login.php:54 Stack trace: #0 C:\xampp\htdocs\W2\src\whatsprot.class.php(286): Login->doLogin() #1 C:\xampp\htdocs\W2\examples\exampleFunctional.php(67): WhatsProt->loginWithPassword('idhH3pT6YL1aF5T...') #2 {main} thrown in C:\xampp\htdocs\W2\src\Login.php on line 54
```

**Comment by johnmoress** [comment]
Number might get banned.

**Comment by jaikumarth** [comment]
no, number is not banned

**Comment by hydefus** [comment]
perhaps number is not banned but what about the IP ?

**Comment by jaikumarth** [comment]
oh! i am not aware of that :( any solution for this ?

**Comment by Alfafc** [comment]
@hydefus Is it known that whatsapp banned by ip? 

I have registered 3 phone numbers and everyone is getting login failure error (not_authorized).

I have use WA PW extractor to get the same password I am using in my Android phone and I am not able to login, but my phone's WA works perfectly.
Any idea?

**Comment by mgp25** [comment]
IP flagged. Bad behaviour/activities.
