### ISSUE TITLE
Verification not accepted

### ISSUE THREAD

**Issue by atalayaktas** [mgp25/Chat-API#1696]
Hİ,
I am not register Chinese number with this api, can u help about resigtration problem please?

Fatal error: Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable' in

**Comment by mgp25** [comment]
Read, the response: `temporarily_unavailable` and read the wiki

Regards

**Comment by renatocoeli** [comment]
Hi people the same in Brazilian numbers registration return BAD TOKEN number old activated work fine but number request from yesterday on connect has banned
