### ISSUE TITLE
Feature Notifications

### ISSUE THREAD

**Issue by drieskensBR** [mgp25/Chat-API#1700]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml

LOG EXAMPLE 1

rx  <notification from="xxxxxxx2165@s.whatsapp.net" type="features" id="xxxxx381" t="xxxxx65">
rx    <feature>
rx      <encrypt_audio value="allow"></encrypt_audio>
rx      <encrypt_video value="allow"></encrypt_video>
rx    </feature>
rx  </notification>

LOG EXAMPLE 2

rx  <notification from="xxxxx20@s.whatsapp.net" type="features" id="xxxx482" t="xxxx224">
rx    <feature>
rx      <document value="allow"></document>
rx      <encrypt value="allow"></encrypt>
rx      <encrypt_audio value="upgrade"></encrypt_audio>
rx      <encrypt_blist value="allow"></encrypt_blist>
rx      <encrypt_contact value="allow"></encrypt_contact>
rx      <encrypt_group_gen2 value="allow"></encrypt_group_gen2>
rx      <encrypt_image value="allow"></encrypt_image>
rx      <encrypt_location value="allow"></encrypt_location>
rx      <encrypt_url value="allow"></encrypt_url>
rx      <encrypt_v2 value="allow"></encrypt_v2>
rx      <encrypt_video value="upgrade"></encrypt_video>
rx      <identity_verification value="none"></identity_verification>
rx      <voip value="allow"></voip>
rx    </feature>
rx  </notification>

```

Hi, Team!

This isn't properly an issue, but a question.

At this week those notifications are arriving frequently.

Is it important?

In that examples, is allowing encrypt audio and video, contacts, location... By default the API is sending encrypted messages to all contacts.

It's ok? No ban risk?

Or I need to flag the contacts with this features to choose if the message should be encrypted or not?

Another point is: 
```xml
<identity_verification value="none"></identity_verification>"
```
Is it a new verification?

Thank you

**Comment by 0xTryCatch** [comment]
You can ignore these, API takes care of it.

**Comment by drieskensBR** [comment]
Ok!
Thank you @0xTryCatch
