### ISSUE TITLE
IP problem using php code

### ISSUE THREAD

**Issue by jaikumarth** [mgp25/Chat-API#1701]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ Y] You are using PHP > 5.6
- [ Y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ Y] You have checked if someone has already asked the same issue you have.
- [ Y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ Y] Is not a programming question.
- [ Y] You are using latest Chat API code.

### Error
Post your error below:
Hi, i am able to register a number using registertool.php and i got password but when i try to login i got error stating as "not authorized" in my earlier issue they mentioned ip problem. so today i used another isp (new ip) able to login successfully with the password in new ip address.

but after few moment when i try to login again same error as "not authorized", but i cannot change ip address every time to login. is the code doing any fault on whatapp server ?

any idea is fine.

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Working perfectly at my side

Regards
