### ISSUE TITLE
Sending message is not received on the Phone

### ISSUE THREAD

**Issue by Jacky8888** [mgp25/Chat-API#1703]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:
I have read the [issue:](https://github.com/mgp25/Chat-API/issues/624)
I have the same problem here ... sending text from PC to Handy dont works ,The message is sent, but no receive the message on the Phone... sending from Phone to PC works ... after updating Whatsapp Messenger on the PC.
I have been based on the way you offer,but not yet .
Is it because of my environment version?
**My Linux version : Centos 6.5 64 bit 
PHP version : PHP 5.6.18
Apache version : httpd 2.4.18**
And I have installed all the expansion,including curve25519 and protobuf ! But,the problem is still not solved.
I sending text from PC to Handy still dont works,but ,sending from Phone to PC works ,after updating Whatsapp Messenger on the PC.

What goes wrong?

### Debug log
Post your debug log below:

```xml
[] Logging in as 'Coke' (8613412534626) tx  <stream:features></stream:features>

tx  <auth user="8613412534626" mechanism="WAUTH-2">594b2c303836313334313235333436323657e9c9171f2fef09e3a968796a70cc1f8d31681e31343537353937393631</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>a8c6246bccc890fbfdfa8cf59509ea253c647ace</challenge>

tx  <response>b2de7dda471670890e8cc5f836444e947c411500663cec3d957995454543b523b94da7cc4170a3c30d7893a149313c7a50988568cf890e39ce8b6038c71fec66bb11c1dc0ed57f59e70e95c3863751</response>

rx  <success t="1457597838" props="4" kind="free" status="active" creation="1446608000" expiration="4444444444">bc42b927127419e20f180e0a919b106715b72601</success>

tx  <presence name="Coke" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

[] Send message to 8613128281826: 第三方的 tx  <message to="8613128281826@s.whatsapp.net" type="text" id="bcf9756e27336d0413d4aa" t="1457597962" notify="Coke">
tx    <enc v="1" type="pkmsg">3328cea6b1a70a0883ddb9063000122105c0707cc5b4bab7ba66926f741ee0920724b1e181a455f6c5fb873e62e5c00e011a2105ebb3824806f8f41c622937650691b0cacbd33bec218697ccc4772186b02b3b2b2240330a2105d4ad815c30416da78219155ea864b8b0ead3f46191f0b415cf80c08252565760100222101ccbd3204c017c9df7b0990b3a48b56a4e65265c76da29dc</enc>
tx  </message>
```

**Comment by mgp25** [comment]
Read closed issues
