### ISSUE TITLE
New Whatsapp protocol 2.0

### ISSUE THREAD

**Issue by yadox666** [mgp25/Chat-API#1710]
Hi mgp25,

Sorry to announce that there's a new Whatsapp WA protocol update 2.0. Seems to be a long list of changes.

**Comment by mgp25** [comment]
I know since 1 month ago. Heh, sorry to announce you it almost done and implemented

**Comment by yadox666** [comment]
Wow, nice work dude. I've also noticed that trying to parse the SSL init frame, also the ssl header protocol info is fully changed. Do you know how to get userid now?
