### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by jaikumarth** [mgp25/Chat-API#1711]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ Y] You are using PHP > 5.6
- [ Y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ Y] You have checked if someone has already asked the same issue you have.
- [ Y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ Y] Is not a programming question.
- [ y] You are using latest Chat API code.

### Error
Post your error below:
Tired of posting, whatever i post the reply from you is, it is workig from our end.
i have hosted in temp url http://whats.16mb.com/examples/exampleFunctional.php i used my number and password still not logging in.

### Debug log
Post your debug log below:

```xml
rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>c708ab09766ecd918e687b79ca65462aa735b665</challenge>

tx  <response>872a75314f4ee6347bef300b6f9a3d71d84d2e15e4a59769f35158fef8347d66e7f26d659854caa57956d1de664e8b02086641fb645fef71ef93bbe804ca2748409cb450b59e18042a5eda5820cf</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>```

**Comment by 0xTryCatch** [comment]
Use ```blockChecker.php```

**Comment by jaikumarth** [comment]
thanks and let me check.

**Comment by jaikumarth** [comment]
blockchecker is not working in http

**Comment by jaikumarth** [comment]
Array ( [cc] => 91 [in] => 8861158554 [lg] => hi [lc] => IN [id] => �9)!".y�t�����m� [token] => neuhtwlcigy+6OKiCyjrpYnBUOc= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 155 [rchash] => 00a1944bbdc601873d449d8ccd2098d8d91aa73cb1d54985bf26333bda9c4449 [anhash] => cdfaebcd5b888ed00efbdf6d4e0ee818 [extexist] => 1 [extstate] => 1 [mcc] => 404 [mnc] => 000 [sim_mcc] => 404 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => ok [login] => 918861158554 [type] => existing [pw] => vDLRUZ3xVq11SvOr1XY7mrnECXc= [expiration] => 4444444444 [kind] => free [price] => ₹ 55 [cost] => 55.00 [currency] => INR [price_expiration] => 1460745930 )

**Comment by 0xTryCatch** [comment]
Sorry, we don't support +91
