### ISSUE TITLE
WhatsApp will end support for various devices

### ISSUE THREAD

**Issue by jokebattle3** [mgp25/Chat-API#1712]
WhatsApp will end support to the following clients to the end of 2016:

https://blog.whatsapp.com/?l=en&set=yes

BlackBerry, including BlackBerry 10
Nokia S40
Nokia Symbian S60
Android 2.1 and Android 2.2
Windows Phone 7.1

As I can see from the debug log the chatAPI is sending a signature for Android version 2.12.440. Will ChatAPI stop working? Is it enough to "just" change the signature?

-->tx config platform="Android" version="2.12.440"></config

Make sure these boxes are checked before submitting your issue -- thank you!

- [X ] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X ] You have checked if someone has already asked the same issue you have.
- [X ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X ] Is not a programming question.
- [X ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
tx config platform="Android" version="2.12.440"></config
```

**Comment by jaikumarth** [comment]
this is hell.. what ever i post this stupid simply tells +91 not supported. do this code have brain to see +91 or something.
support for not working code

**Comment by mgp25** [comment]
@jokebattle3 there is lot of updates to do yet, we will keep updating and supporting this API. So be patient.

Regards

**Comment by jokebattle3** [comment]
Thank you for this information!
