### ISSUE TITLE
Person is online but Chat-API says he is offline

### ISSUE THREAD

**Issue by Rexota** [mgp25/Chat-API#1713]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

I'm talking to an online person for test and he is online, but chat-api says he is offline. What can be the problem?

### Debug log
Post your debug log below:
No debug unfortunately.

```xml
No debug unfortunately.
```

**Comment by mgp25** [comment]
Without debug log we can't know

**Comment by Rexota** [comment]
I'll try to provide.

**Comment by Rexota** [comment]
Log

```
tx  <presence type="subscribe" to="XXXXX@s.whatsapp.net"></presence>

rx  <presence from="YYYYY@s.whatsapp.net" type="unavailable" last="deny"></presence>
```

Thanks.

**Comment by TriPSs** [comment]
When *last="deny"* means the person has it disabled in his privacy settings.

**Comment by mgp25** [comment]
Adding to what @TriPSs has said. If you haven't synced that contact, you wont see the contact online

Regards
