### ISSUE TITLE
Proposal: Check for curve25519 and php-protobuf with composer

### ISSUE THREAD

**Issue by robertfausk** [mgp25/Chat-API#1716]
- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [ ] You are using latest Chat API code.

### Question (instead of Error)

Hi! I just stumbled across this library.
Is it possible to check for curve25519 and php-protobuf while running composer?
composer.json would look something like that:
```JS
    ...
    require: {
        ...
        "ext-curve25519": "*",
        "ext-protobuf": "*"
    }
...
```
As far as I can see these are also php extensions or aren't they?
Or won't it work because they are no official registered php extensions?
How could it be achieved?

### Debug log
No debug log cause its a question.

**Comment by mgp25** [comment]
There are no official extensions,only the ones mentioned in the wiki

Regards
