### ISSUE TITLE
Event to Receive Document

### ISSUE THREAD

**Issue by jaylabade** [mgp25/Chat-API#1717]
- [Y] You are using PHP > 5.6
- [Y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [Y] You have checked if someone has already asked the same issue you have.
- [Y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [Y] Is not a programming question.
- [Y] You are using latest Chat API code.

Hi,
with the new code i can download document media under /tmp directory for not able to fetch filename information.
Also, I am not able to find an event to Receive Document type media. any progress on this event

```xml
DEBUG LOG HERE
rx  <message from="XX88XXXXXXXX@s.whatsapp.net" type="media" id="9292F66B88CA059F771C4BAA2A705B" t="1457768145" notify="Sender Name">
rx    <enc v="2" type="pkmsg" mediatype="document"> 20813 byte data</enc>
rx  </message>
-> Decrypted Message: HEX: whole Decrypted message here
```

**Comment by mgp25** [comment]
@jaylabade this is added in the next release

Regards

**Comment by jaylabade** [comment]
Thanks @mpg25,

When can we expect next release Sir.
