### ISSUE TITLE
Unable to decrypted the FIRST message in the group

### ISSUE THREAD

**Issue by anativ** [mgp25/Chat-API#1719]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error

Repro:

1. Creating a group and add the api-bot to the group (in this case it's a group with 2 phone and the bot) - saw the same issue
2. send a message to the group from a phone
3. The message doesn't get read "v"
Error: Decrypted Message: No such signedprekey with id: 38771 - /SqliteAxolotlStore.php - 246Message B771C03F2D10DBB98E57B99B92D3E4 could not be decrypted, sending retry.
Error: Decrypted Message: No keys for: 1123814041

after the second message from the phone the code is able to decrypt it.

The test code is basically just doing 
`while (true) {
  $wp->pollMessage();
}
`

### Debug log
Post your debug log below:

https://gist.github.com/anativ/aaf89b1357407d893526

**Comment by 0xTryCatch** [comment]
No issue, normal behaviour

**Comment by anativ** [comment]
What is "normal" about it if I can't read the first message?
is there a way to fix it?

**Comment by 0xTryCatch** [comment]
Group encryption is not supported in the API

**Comment by anativ** [comment]
It is working from the 2nd message...
And in some cases it does work from the 1st message.
So I don't understand why it is "not supported"
Any idea how we can solve this issue?

Thanks,
A.

**Comment by anativ** [comment]
@0xTryCatch  Can you reopen the issue?
I understand that it is not supported but it is an "open" issue...
