### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by prix911** [mgp25/Chat-API#1721]
Hi,
I keep receiving the error that my number is not authorized, I tested with 3 different numbers and all of them are working fine in the mobile but not with the API, I also tried with differents IP's and the error is the same. There is a problem with the API or the WhatsApp server?

TKS!

**Comment by mgp25** [comment]
@prix911 

1) You haven't posted debug log which makes directly this issue invalid
2) Probably your account/IP is flagged or banned

**Comment by drieskensBR** [comment]
Hi. I had the same problem in the past.

Look number used in "login", because can be different of "original number" (used to do a voice call). 
In Brazil it's occours with frequency, because of "9" digit included recently.

Call the "CheckExists" in Registration.php and see the "login" and "password" returned. Use it as parameter on this API.

**Comment by prix911** [comment]
@drieskensBR I did what you suggest but didn't work... There is the error:
[15-Mar-2016 11:41:42 America/Sao_Paulo] ProtocolNode::__set_state(array(
   'tag' => 'failure',
   'attributeHash' => 
  array (
  ),
   'children' => 
  array (
    0 => 
    ProtocolNode::__set_state(array(
       **'tag' => 'not-authorized',**
       'attributeHash' => 
      array (
      ),
       'children' => NULL,
       'data' => '',
    )),
  ),
   'data' => '',
))
Tried with differents IP's too and didn't work... But, thanks anyway!

**Comment by drieskensBR** [comment]
Your number is blocked probably.

Check if is blocked with "BlockCheck.php" in examples.

If returns "blocked" try to register again with another number.

TIP: If you are in Brazil, use VIVO sim card because it's enabled to receive SMS without registration.

**Comment by prix911** [comment]
@drieskensBR I'm using VIVO sim card and the number in my mobile and keep saying my number is blocked, I think I'm gonna give up and go with Telegram :D thanks for the tips!
