### ISSUE TITLE
Number registration error 

### ISSUE THREAD

**Issue by ishaquehassan** [mgp25/Chat-API#1725]
Make sure these boxes are checked before submitting your issue -- thank you!

- [yes] You are using PHP > 5.6
- [yes] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [yes] You have checked if someone has already asked the same issue you have.
- [yes] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [yes] Is not a programming question.
- [yes] You are using latest Chat API code.

### Error
An error occurred registering the registration code from WhatsApp. Reason: old_version

### Debug log
( [status] => fail [reason] => old_version )

```xml
No XML log available
```

**Comment by mgp25** [comment]
@ishaquehassan post full debug log

**Comment by djade007** [comment]
@mgp25 quick question, can I run multiple instances using one whatsapp credentials?

**Comment by Griffins** [comment]
I dont think its possible.

**Comment by 0xTryCatch** [comment]
No

**Comment by ishaquehassan** [comment]
Array ( [cc] => 92 [in] => ********** [lg] => en [lc] => PK [id] => x���ahӱ��fa�o���� [token] => 1P4MpLpGQ/k8PEhGtJP+c8EleJ4= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 3358 [rchash] => f454f23c4db2ef45523d7136c5cfc70f9b806124566c1310de30920a48cc9a72 [anhash] => 164f4c4c09857e77e98fe620678cf052 [extexist] => 1 [extstate] => 1 [mcc] => 410 [mnc] => 000 [sim_mcc] => 410 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => fail [reason] => old_version )
