### ISSUE TITLE
Unable to use contactSync.php after receiving 6-digit code

### ISSUE THREAD

**Issue by AmrinRajani92** [mgp25/Chat-API#1727]
Make sure these boxes are checked before submitting your issue -- thank you!

- [yes ] You are using PHP > 5.6
- [ yes] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ yes] You have checked if someone has already asked the same issue you have.
- [yes ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [yes ] Is not a programming question.
- [yes ] You are using latest Chat API code.

### Error
Post your error below:

`Fatal error: Uncaught exception 'LoginFailureException' in D:\xampp\htdocs\Chat-API-master\Chat-API-master\src\Login.php:54 Stack trace: #0 D:\xampp\htdocs\Chat-API-master\Chat-API-master\src\whatsprot.class.php(286): Login->doLogin() #1 D:\xampp\htdocs\Chat-API-master\Chat-API-master\examples\contactsync.php(49): WhatsProt->loginWithPassword('oRjqAv7CmIa+oYX...') #2 {main} thrown in D:\xampp\htdocs\Chat-API-master\Chat-API-master\src\Login.php on line 54`

### Debug log
Post your debug log below:
```xml
tx  <stream:features></stream:features>

tx  <auth user="917208299290" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>63b953d1ea1e5911481a03f2d4a94dd542804b4b</challenge>

tx  <response>4ce95033d9557525f7414f51050fc1adba521cf6a86d371c21b9e9c247e2ea61f13bedef2d053ddce39ef9a0a3ffd272d0ccfd582e47734c8627df73780ed5cd412af4797ec47e3a7d6ac70cca8b</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

HI Team, I've been trying to work with contactSync.php after registering my number on whatsapp. But everytime I run the file with my mobile number and password, I receive these error logs. Could you guys help us identify our mistake or if we are missing something?

```php
<?php

set_time_limit(30);

require_once '../src/whatsprot.class.php';

$username = 'xxxxxxxxxxxx';
$password = 'oRjqAv7CmIa+oYX7VNcJqukEWX0=';
//$u = $_GET['u'];
$u=array('919833926449');

if (!is_array($u)) {
    $u = [$u];
	echo $u;
}
$number = [];
$numbers = [];
foreach ($u as $number) {
    if ($number[0] != '+') {
        //add leading +
        $number = "+$number";
		echo $number;
    }
    $numbers[] = $number;
	echo $numbers[];
}

//event handler
/**
 * @param $result SyncResult
 */
function onSyncResult($result)
{
    foreach ($result->existing as $number) {
        echo "$number exists<br />";
    }
    foreach ($result->nonExisting as $number) {
        echo "$number does not exist<br />";
    }
    die(); //to break out of the while(true) loop
}

$wa = new WhatsProt($username, 'abcd', true, true);

bind event handler
$wa->eventManager()->bind('onGetSyncResult', 'onSyncResult');

$wa->connect();
$wa->loginWithPassword($password);

//send dataset to server
$wa->sendSync($numbers);

//wait for response
while (true) {
    $wa->pollMessage();
}
```

**Comment by mgp25** [comment]
Your number is blocked, read wiki and closed issues

**Comment by AmrinRajani92** [comment]
I know its blocked, I read the wiki. I just wanted to know what did I do wrong that my number got blocked? I haven't sent a single message, I just tried to use contact Sync file.
