### ISSUE TITLE
Text messages doesnt get read.

### ISSUE THREAD

**Issue by arth1992** [mgp25/Chat-API#1729]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [Y ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ Y] You have checked if someone has already asked the same issue you have.
- [Y ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [Y ] Is not a programming question.
- [Y ] You are using latest Chat API code.

### Error
Post your error below:
I had replaced my code with latest repository, but the error is my text messages doesn't get read but all multimedia messages get read by the number.? i think the api is having some issues regarding text messages.

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
No code. No debug log? Invalid issue
