### ISSUE TITLE
URL preview encoded

### ISSUE THREAD

**Issue by Creapix89** [mgp25/Chat-API#1731]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x ] You are using latest Chat API code.

### Error
When I send a location with map display, it generates an error because there is no BODY node on line 67 of the code in the file /src/handlers/MessageHandler.php

### Debug log
Post your debug log below:

```xml
tx  <iq id="07" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="subscribe" to="5215530706832@s.whatsapp.net"></presence>

tx  <chatstate to="5215530706832@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="5215530706832@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="5215530706832@s.whatsapp.net" type="text" id="dcb0c45ae9300b1aa6fca8" t="1458323508" notify="Totalpat">
tx    <enc v="1" type="msg">330a2105312e819247efbdaac8ed2baf8dc0cec394c2294c63f5dfc12791b2161f7f36061005180322307486d9f3e28ec6f8672ad101d23e9ed1044a558e5c9ff907b2252b8e2503a8deb7f2337c38777a4d9534d433d150279f381d23d694fc2baf</enc>
tx  </message>

tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <message from="5215531308414-1452533004@g.us" type="media" id="EBD189AA3725C33340" participant="5215571270066@s.whatsapp.net" offline="3" t="1458320444" notify="Yasmin">
rx    <enc v="2" type="skmsg" mediatype="url"> 5052 byte data</enc>
rx  </message>

Fatal error: Call to a member function getData() on null in whatsapp/src/handlers/MessageHandler.php on line 67
```

**Comment by ibnubudir** [comment]
what happen with this, whatsapp can online just at moment 

rx  <iq from="16345634781@s.whatsapp.net" type="result" id="03">
rx    <picture id="1458406665"></picture>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="05">
rx    <list>
rx      <user jid="error.us">
PHP Notice:  Undefined offset: 1 in C:\xampp\htdocs\centerWA\wa.php on line 1
rx        <registration>f3e6ea4b</registration>
PHP Fatal error:  Call to a member function getChild() on null in C:\xampp\htdocs\centerWA\src\handlers\IqHandler.php on line 265
rx        <type>05</type>
rx        <identity>62c39c5b2c48b9981e9c42409877d973a5a7be16ef359ddff0c4c73940b16e12</identity>
rx        <skey>
rx          <id>efdf73</id>
rx          <value>3b63b8ab9dfdda972bbcdb6558e4703569c6ec427213fa552db6e0605762ab45</value>
rx          <signature>df33a7d48f1f37a54c9540707bf574217b626a1d0fe5e

PHP Fatal error:  Call to a member function getChild() on null in C:\xampp\htdocs\centerWA\src\handlers\IqHandler.php on line 265

but when i move other Computer, wa online nurmaly,

**Comment by mrjoebudi** [comment]
what happen with this, whatsapp can online just at moment

rx
PHP Notice: Undefined offset: 1 in C:\xampp\htdocs\centerWA\wa.php on line 1
rx f3e6ea4b
PHP Fatal error: Call to a member function getChild() on null in C:\xampp\htdocs\centerWA\src\handlers\IqHandler.php on line 265
rx 05
rx 62c39c5b2c48b9981e9c42409877d973a5a7be16ef359ddff0c4c73940b16e12
rx
rx efdf73
rx 3b63b8ab9dfdda972bbcdb6558e4703569c6ec427213fa552db6e0605762ab45
rx df33a7d48f1f37a54c9540707bf574217b626a1d0fe5e

PHP Fatal error: Call to a member function getChild() on null in C:\xampp\htdocs\centerWA\src\handlers\IqHandler.php on line 265

but when i move other Computer, wa online nurmaly,

**Comment by mgp25** [comment]
Fixed in next release!

Regards
