### ISSUE TITLE
About Registration

### ISSUE THREAD

**Issue by joglimartins** [mgp25/Chat-API#1732]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x ] You are using latest Chat API code.

Registration is working?

**Comment by mgp25** [comment]
Yes, if not wait for next release
