### ISSUE TITLE
ChatAPI hangs in loop and does not stops sending retries to whatsapp-server

### ISSUE THREAD

**Issue by jokebattle3** [mgp25/Chat-API#1734]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ X] You are using PHP > 5.6
- [ X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ X] You have checked if someone has already asked the same issue you have.
- [ X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ X] Is not a programming question.
- [ X] You are using latest Chat API code.

### Error
Post your error below:
I send a whatsapp message from my personal phone to my chatapi whatsapp instance. In the logs I can see the error message ("posted below"). ChatAPI does not stops to send requests to whatsapp to request the message again. This happens also with chatapi 3.1.

### Debug log
Post your debug log below:
Please ask me what portion of the log is required. The request from ChatAPI to WhatsApp ist requested every few seconds so the log is very big.

```xml
-> Decrypted Message: Bad Mac!
No valid sessions - /chat-api-3.2/src/libaxolotl-php/SessionCipher.php - 178Message ACABCAE29973A0E17B could not be decrypted, sending retry.

tx  <receipt id="ACABCAE29973A0E17B" to="mynumber@s.whatsapp.net" type="retry" t="1458373265">
tx    <retry v="1" count="1" id="ACABCAE29973A0E17B" t="1458373265"></retry>
tx    <registration>588e16be</registration>
tx  </receipt>

rx  <presence from="mynumber@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <ack from="mynumber@s.whatsapp.net" class="receipt" type="retry" id="ACABCAE29973A0E17B"></ack>

rx  <presence from="mynumber@s.whatsapp.net"></presence>

rx  <message from="mynumber@s.whatsapp.net" type="text" id="ACABCAE29973A0E17B" t="1458373267" notify="myname">
rx    <enc v="1" type="msg" count="1">330a2105fe162fcccd0a75a8b06c46c3b291700e36ea958a94204fec7c667b433149cc601084021801221025b8de8c86d1dfc34f103429a8a45418cca400ecdea7d170</enc>
rx  </message>

tx  <ack to="mynumber@s.whatsapp.net" class="message" id="ACABCAE29973A0E17B" t="1458373267"></ack>```

**Comment by jokebattle3** [comment]
Some more debug information: 

- ChatAPI calls the function "sendRetry" again and again.
- I added a global variable to check the count the function "sendRetry" is called and exit after 5 calls. this avoids chatapi to hang at least. However the encryption of the message failed.
- The $this->retryCounters variable counts to 1, then to 2, the ChatAPI does a resetEncryption, this->retryCounters starts counting at 1, then 2 and then ChatAPI calls the resetEncryption again. Without not ending.

Hope this helps. Please let me know if you need more debug information.

**Comment by jokebattle3** [comment]
For some reason, suddendly it is working again! Sadly I have absolutely no clue what the reason could be. If I have more information I will post.

Maybe it would be a good idea to add a global retrycount in sendRetry() to avoid that ChatAPI hangs in a loop. Just an Idea.

**Comment by rogobob** [comment]
@jokebattle3 I am having the same issue since yesterday with 3 numbers already. Apparently we should wait for the next Chat-API release.

**Comment by jokebattle3** [comment]
Now the problem occurs again for me! Any ideas how to fix it by myself?

**Comment by mgp25** [comment]
wait for the next Chat-API release.
