### ISSUE TITLE
Can't use identity registered by WART

### ISSUE THREAD

**Issue by luizlzz** [mgp25/Chat-API#1735]
Hi,

I have a number which was registered through WART, with password.

On WART, everything is fine, as showed above:

![tela1](https://cloud.githubusercontent.com/assets/17954946/13901424/04c59d8e-ee02-11e5-982b-2af3ddc72d8c.png)

Then, I ran the "RegisterTool.php" to generate the .dat file corresponding to the number. Of course the "id" created was wrong, and the script returned an error, so I replaced that for the "id" created on WART. 

![tela2](https://cloud.githubusercontent.com/assets/17954946/13901443/a6b9374a-ee02-11e5-8418-6b2ec0959a02.png)

So, even with this modification, the RegisterTool is still giving identity error. What is the problem?

Thank you in advance.

DEBUG LOG:

> Array
> (
>     [cc] => 86
>     [in] => 15xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>     [lg] => en
>     [lc] => CN
>     [id] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>     [mistyped] => 6
>     [network_radio_type] => 1
>     [simnum] => 1
>     [s] =>
>     [copiedrc] => 1
>     [hasinrc] => 1
>     [rcmatch] => 1
>     [pid] => 2752
>     [extexist] => 1
>     [extstate] => 1
> )
> stdClass Object
> (
>     [status] => fail
>     [reason] => incorrect
>     [sms_length] => 6
>     [voice_length] => 6
>     [sms_wait] => 10596
>     [voice_wait] => 0
> )
> There was a problem trying to request the code.

**Comment by mgp25** [comment]
@luizlzz the number seems wrong, at least i see a lot of `x`. Probably you are not pasting the identity in the correct format.

Regards

**Comment by luizlzz** [comment]
@mgp25 I obfuscated the "id" and "in" before post... 


This is the full thing...

> Array
> (
>     [cc] => 86
>     [in] => 15624580454
>     [lg] => en
>     [lc] => CN
>     [id] => ¹_ı^oyÝ0c[y▓☺à╩²js#╣
>     [mistyped] => 6
>     [network_radio_type] => 1
>     [simnum] => 1
>     [s] =>
>     [copiedrc] => 1
>     [hasinrc] => 1
>     [rcmatch] => 1
>     [pid] => 2752
>     [extexist] => 1
>     [extstate] => 1
> )
> stdClass Object
> (
>     [status] => fail
>     [reason] => incorrect
>     [sms_length] => 6
>     [voice_length] => 6
>     [sms_wait] => 10596
>     [voice_wait] => 0
> )
> There was a problem trying to request the code.
