### ISSUE TITLE
What's App Update or something else / 	temporarily_unavailable?

### ISSUE THREAD

**Issue by Bubelbub** [mgp25/Chat-API#1737]
Hello,

I used this Chat API a few weeks ago for simple Information Service for myself.
But now I tried to register a new number and I'm getting only `temporarily_unavailable`.
And that's since few days.
So I don't know if What's App blocked this Chat API through a new update or something else - but it doesn't work anymore.

Is this a general problem at the moment?

Or can someone help?

Thanks in Advance!

**Comment by albertschlau** [comment]
Me too!

I tried different sim cards from different telco already and even setup two different instances on our amazon servers (different locations) and run the register tool.php script then I was able to get the verification code successfully but after typing the received code I always get this error "An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable".

**Comment by Bubelbub** [comment]
Why it is duplicated @mgp25 if there is no other topic about this.
Please inform me about this other issue.
