### ISSUE TITLE
Login always get exception 'LoginFailureException'

### ISSUE THREAD

**Issue by bambangin** [mgp25/Chat-API#1740]
Make sure these boxes are checked before submitting your issue -- thank you!

- [Y] You are using PHP > 5.6
- [Y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [Y] You have checked if someone has already asked the same issue you have.
- [Y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [Y] Is not a programming question.
- [Y] You are using latest Chat API code.

### Error
Post your error below:
Fatal error: Uncaught exception 'LoginFailureException' in D:\home\site\wwwroot\whatsapi\src\Login.php:54 Stack trace: #0 D:\home\site\wwwroot\whatsapi\src\whatsprot.class.php(286): Login->doLogin() #1 D:\home\site\wwwroot\whatsapi\reg.php(14): WhatsProt->loginWithPassword() #2 {main} thrown in D:\home\site\wwwroot\whatsapi\src\Login.php on line 54

### Debug log
Post your debug log below:

```xml
tx  <stream:features></stream:features>

tx  <auth user="6285704954023" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b47e585ee206cb2b9207dd4b063c5cb59994afed</challenge>

tx  <response>54e590ddd677aae26066ead8457a145c5f3cefd90b480c4d51df45bbc85920504771416beed8e8db5947acf70fc7872f6e792acd08f8c870b92f56837047015b2c6a92a7de1986098a8e7cd62d5d5f</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

I have tried with 4 different numbers, try it on localhost, hostinger.com and windows azure but still the same result. the numbers are still used in whatsapp android and goes well, I get the password from the pw file using bash tutorials.
This is my phpinfo web app from my azure http://bambangin.azurewebsites.net/info.php you can check the extension.

My code to sendMessage
```xml
<?php
require_once __DIR__.'/src/whatsprot.class.php';
require_once __DIR__.'/src//events/MyEvents.php';

$username = '6285704954023';
$password = 'xxxxxxxxx';
$nickname = 'RopajiBot Services';
$target = "6285736316423";
$debug = true;  

$w = new WhatsProt($username, $nickname, $debug);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents);

$w->connect();
$w->loginWithPassword($password);
$w->sendMessage($target, 'Guess the number :)');
$w->sendMessage($target, 'Sent from RopajiBotServices at '.date('H:i'));
?>
```

Could you help me identify mistake or if I missing something? I just want to send message.

**Comment by mgp25** [comment]
Use `blockChecer.php` to check if your number is blocked. If you have registered the number with latest apk it wont work, i recommend you to register the number with `registerTool.php` that way it will work

**Comment by bambangin** [comment]
Yeah, I use the registryTool.php all goes well, I do not know if getting a password using bash tutorial is not working. Thanks man.

**Comment by jorgebetocampa** [comment]
Hi!, i used the RegisterTool.php, and it doesnt sent the message... 
The only thing different is the version of php... i got 5.4... any api for that version?

Thx a lot
