### ISSUE TITLE
sendSync correctly

### ISSUE THREAD

**Issue by eastuger** [mgp25/Chat-API#1742]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x ] You are using PHP > 5.6
- [ x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x ] You have checked if someone has already asked the same issue you have.
- [ x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x ] Is not a programming question.
- [ x ] You are using latest Chat API code.

Hey there got a quick question. 

If we are doing a delta, interactive sync. Do we need to send an array with all contacts. Or just a single new contact ?

**Comment by mgp25** [comment]
@eastuger this question is duplicate + is explained in the wiki. 

Single new contact. Please next time search in wiki/closed issues

Regards
