### ISSUE TITLE
Passive mode advice for profile picture and presence

### ISSUE THREAD

**Issue by 8manuel** [mgp25/Chat-API#1744]
Hi Whatsapi team, thanks for your work.

I'm building a passive mode app (only answering received messages, never initiate sending).
Even if seems that for passive mode is [not required to sync contacts](https://github.com/mgp25/Chat-API/issues/476) , I plan to answer immediately but do later a delta sync with the new contacts every 20 minutes (following @hansrouge [recommendation](https://github.com/mgp25/Chat-API/issues/620))

My question is about sendGetProfilePicture and sendPresenceSubscription:

1) Do you advise to call those functions before answering a message from a new user?
(I'm afraid to call because I plan to do delta sync later grouping new contacts to avoid sync backoff)

2) In case is not required, do you advise to listen onProfilePictureChanged and ask the contact new picture if changed?
(I would not do but I see in my phone whatsapp updates user pictures when I scroll contacts)

Thanks in advance for your support.

**Comment by mgp25** [comment]
@8manuel 

1) before
2) it is required.

Regards
