### ISSUE TITLE
Presence subscription and function sendSetPrivacySettings

### ISSUE THREAD

**Issue by 8manuel** [mgp25/Chat-API#1745]
Hi, in whatsapp settings, personal information, there is the possibility of setting the last seen to nobody (Hora de últ. vez).
I suppose that in this case the real whatsapp app does not send/receive presence subscription of my phone contacts.

1) I'm right?

2) If I do the same in whatsapi, calling sendSetPrivacySettings('last', 'none') , do you think is ok if I dont do any presence (un)subscription?

Thanks for your help

**Comment by mgp25** [comment]
@8manuel 

1) it sends presence subscription
2) only unsubs when blocking or removing a contact

Regards
