### ISSUE TITLE
How to sign-out all groups?

### ISSUE THREAD

**Issue by Anderuimm** [mgp25/Chat-API#1746]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

I've been added on some groups and minutes after the number was "blocked".

Reading the WIKI I see this:

$groupId;
$w->sendGroupsLeave($groupId);

But where can I get the Group Id for all groups the number was added to?

PS.: sorry about bad english.

**Comment by mgp25** [comment]
There is a function to get the active groups, please see the code before opening an issue

Function: https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L745

Regards
