### ISSUE TITLE
Image group encrypted

### ISSUE THREAD

**Issue by Creapix89** [mgp25/Chat-API#1750]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x ] You are using latest Chat API code.

### Error
when I receive a picture in a group, the api does not detect that receiving an image, I imagine this is because now is encrypted.

### Debug log

```xml
rx  <message from="5215515018211-1458673361@g.us" type="media" id="2F5321C9C5993D5734" participant="5215537348136@s.whatsapp.net" t="1458679850" notify="Israel Arellano">
rx    <enc v="2" type="skmsg" mediatype="image"> 2316 byte data</enc>
rx  </message>

tx  <receipt type="read" participant="5215537348136@s.whatsapp.net" to="5215515018211-1458673361@g.us" id="2F5321C9C5993D5734" t="1458679850"></receipt>

rx  <ack from="5215515018211-1458673361@g.us" class="receipt" type="read" id="2F5321C9C5993D5734" participant="5215537348136@s.whatsapp.net"></ack>
```

**Comment by johnmd5** [comment]
This API is totally fucked up now. Wait for the next release.

**Comment by mgp25** [comment]
@Creapix89 Hi, this is added in next release. I'll keep this open as a track if i forget to test anything.

**Comment by mgp25** [comment]
@Creapix89 added in next release and working.

Regards
