### ISSUE TITLE
Message is not sent

### ISSUE THREAD

**Issue by MarkusN99** [mgp25/Chat-API#1752]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

I don't know if this is an error code, but this is the text that is displayed when I tried to send a message.

### Error
Post your error below:
```
tx  <stream:features></stream:features>

tx  <auth user="*************" mechanism="WAUTH-2">50b3859234393135323237373139393437fb6046169267836b7100fa40663d435d5b964c5931343538373630363034</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>9846b5abd9f0d028d6511fd03428807f6cbbe49f</challenge>

tx  <response>ed282040fb02112e743718342400cb1f7ae02999b15fa3fa1d436af5adbcd03c344ddecc14f9a486cf0c6ec6a5f96259d9424f909a9546401dcade4a42a1a880b8a858f75a4d82e3937555e73c2551826738</response>

rx  <success t="1458760604" props="4" kind="free" status="active" creation="1458733785" expiration="4444444444">92e97332830e46ed690b1a913391f75ba374c28f</success>

tx  <presence name="Klassen-Manager" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <message to="*************@s.whatsapp.net" type="text" id="52a0a699b61b58e9fb08f4" t="1458760604" notify="Klassen-Manager">
tx    <body>Wie gehts?</body>
tx  </message>
```

**Comment by 0xTryCatch** [comment]
You are not polling after sending. Read the wiki before opening issues.

**Comment by MarkusN99** [comment]
In the Wiki there is no polling after sendMessage
https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#sending-messages

Or is elsewhere?
