### ISSUE TITLE
onGetAudio/onGetGroupAudio are not aware of "voice"

### ISSUE THREAD

**Issue by J-N-K** [mgp25/Chat-API#1753]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

sendMessageAudio supports sending voice messages by adding "true" as last parameter in the call. Both onGetAudio/onGetGroupAudio have no parameter to distinguish between voice messages and "normal" audio messages. The property "origin='live'" should be checked in the Handler and used to set $voice=true/false and passed as additional parameter.

**Comment by mgp25** [comment]
@J-N-K thanks! just added it in the next release

Regards
