### ISSUE TITLE
Parameter missing on "onGetError()" event documentation

### ISSUE THREAD

**Issue by Sdlion** [mgp25/Chat-API#1756]
On the wiki documetation `onGetError()` is defined like this

`onGetError( $mynumber, $from, $id, $data )`

Using this definition raises this error

`Declaration of MyEvents::onGetError() should be compatible with AllEvents::onGetError($mynumber, $from, $id, $data, $errorType = NULL)`

It should defined on the wiki as
`onGetError( $mynumber, $from, $id, $data, $errorType = NULL )`

**Comment by mgp25** [comment]
@Sdlion fixed. Thanks

Regards
