### ISSUE TITLE
Reopen #1754 please

### ISSUE THREAD

**Issue by Expressit** [mgp25/Chat-API#1759]
Hi Mpg I added more data to  ntegrity constraint violation: 19 column prekey_id is not unique' in SqliteAxolotlStore.php:280 #1754 , can you reopen it please ?

**Comment by mgp25** [comment]
Added and fixed in the next release!

Regards

**Comment by Expressit** [comment]
Did you check my additional comment, because only changing INSERT in INSERT OR UPDATE is not enough ? ;-)
