### ISSUE TITLE
encrypted vcard an image improvement

### ISSUE THREAD

**Issue by jlguardi** [mgp25/Chat-API#1760]
I've seen some interesting things while porting your code to yowsup:
- Encrypted vcard is not supported.
- thumbnails are incorrectly extracted from protobuf so y made a patch searching 'yoya' but is easy to fix. 
See  https://github.com/jlguardi/yowsup/blob/encrypted_media/yowsup/layers/axolotl/encrypted_media.proto

Now I'm quite busy porting so no PR is made.

**Comment by mgp25** [comment]
@jlguardi hi, next release has vcard support, soon it will be published.

Regards
