### ISSUE TITLE
Missing events in MyEvents.php

### ISSUE THREAD

**Issue by J-N-K** [mgp25/Chat-API#1762]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [ x You are using latest Chat API code.

There are some events missing in MyEvents.php (e.g. OnGetGroupsImage). The same goes for the wiki. If needed, I can prepare a PR for that. Just leave me a note.

**Comment by mgp25** [comment]
@J-N-K oks, send a pull request.

Regards
