### ISSUE TITLE
How do you view/debug the WhatsApp Android mobile Application

### ISSUE THREAD

**Issue by SudoHenk** [mgp25/Chat-API#1764]
I have a bit different question. Do you by any chance know how to view the HTTPS traffic between the Android APK client and the webserver? I've tried the android app Packet Capture, which allows Man in the Middle with the usage of an personal certificate (which is basiclly the same as SSLStrip).

However, I think the app is doing some kind of certificate pinning because it refuses to communicate once I enable the VPN loopback.

How did you guys debug/view this traffic exchange between the WA client and server?

**Comment by mgp25** [comment]
I tell you a secret: Is not http/s, http/s is only for registration.

Regards

**Comment by hydefus** [comment]
Use a sniffer ;-)

**Comment by SudoHenk** [comment]
Huh? If I use wireshark to sniff my WiFi connection to my mobile I only see TLS passing by when I send a message. How can that not be HTTPS?
