### ISSUE TITLE
Problem receive message iPhone

### ISSUE THREAD

**Issue by Udirley** [mgp25/Chat-API#1766]
Hello guys, I have several active numbers, and realized that after I updated the version of WhatsApp on my iPhone to 2.12.16 in most numbers the message is not decoded.
The message arrives and the system tries to Decrypta it but can not, then he tries again but without success.
Android devices in all works perfectly.
I am using the latest version of the API.
I use the iPhone 5S with IOS 8.3 and WhatsApp 2.12.16

-> Decrypted Message: No such signedprekey with id: 19544 - /var/www/html/whatsapp/Chat-API-master.NEW/src/SqliteAxolotlStore.php - 248Message A9EB911BD2DEFF38E0 could not be decrypted, sending retry.

**Comment by anativ** [comment]
+1
Got the same issue with IOS v9.2 (iPhone 5s) / v9.3 (iPhone 6s)

**Comment by zzeebbii** [comment]
+1
Same issue with me since last night. I was too much confused that from one number I can receive messages and from other no message at all. I can receive images and videos from iOS but text messages are not coming.

**Comment by Bubelbub** [comment]
:+1: 

Maybe it's the same problem why the registration not works.
#1737

**Comment by fbalaguera** [comment]
+1

The same problem

**Comment by mgp25** [comment]
People if you want support post full debug log. FULL DEBUG LOG, its really important

**Comment by anativ** [comment]
Here are the debug logs - group chat server + android + iphone
https://gist.github.com/anativ/4c0e740844a91b2a5df0

Also deleting the .db doesn't help

Thanks,
A.

**Comment by anativ** [comment]
@mgp25 Please let me know if there is anything else I can help with

Thanks,
A.

**Comment by jquequezana** [comment]
https://github.com/mgp25/Chat-API/issues/1758

**Comment by fbalaguera** [comment]
This is my Log file https://www.dropbox.com/s/f0whg6z9kmw1wwx/log_api.txt?dl=0
Thanks

**Comment by mgp25** [comment]
@fbalaguera that is not full debug log

@jquequezana the message is correctly decrypted, if you follow your debug log, you will see this:
`-> Decrypted Message: HEX:0a0d486c6120636d20657374616e3f126d0a1b33333735363739353339332d3134353538333638353940672e7573124e3308e1ef8ae80510021a20cdd3775be458320d48897ff4f6eb73f40857dd6bcebaf14ff15c1d024864c450222105bb1933b1a3138a09ebf9e728949a00c897dc5f9248c06e2425523c1bd950fd267b`

That is the decrypted message, so yes, it is working fine and decrypting it.

@anativ the same happens with you, the message is decrypted correctly after retrying it. Check this line: https://gist.github.com/anativ/4c0e740844a91b2a5df0#file-chat-api-iphone-error-L94

Regards

**Comment by anativ** [comment]
@mgp25 no thats not the case the decrypted message is from the Android
The flow is:
1. iPhone sends message no read ack on the iPhone (only V)
2. The Android sends message on the same group there is a read ack
If you want I can make another repro with different scenario. it happens all the time on the latest version
It started to happened  Thursday or Friday 

Thanks,
A.

**Comment by mgp25** [comment]
@anativ send me multiple (full) debug logs that happens that issue using different numbers if possible

**Comment by Udirley** [comment]
Following the two logs below: IOS and Android
The number used to send the messages have the same end but are different.
The receiver number is the same.

IOS
https://www.dropbox.com/s/efo9b20rrg0t0bi/log-ios.txt?dl=0

Android
https://www.dropbox.com/s/4n2rdb6pvz85zqd/log-android.txt?dl=0

Até quinta feira passada estava tudo funcionando corretamente.

**Comment by anativ** [comment]
@mgp25 
Here are some logs

1. iPhone1 server does **not** read - group chat server + android + iphone 
https://gist.github.com/anativ/6096ddc729feb904c443

2. iPhone1 server does **not** read - 1v1
https://gist.github.com/anativ/198284a0f69e280b388d

3. iPhone2  (new iPhone to the server never seen the number before) - 1v1 server **reads**
https://gist.github.com/anativ/d687973f3d8052a66277

4. iPhone2 after clearing the axodb - 1v1 server **not** reading
https://gist.github.com/anativ/4a645937ab4db2c167f8

With Android the server works like a charm even after clearing the axodb

Hope this helps
Please let me know if you need anything else.

Thanks,
A.

**Comment by mgp25** [comment]
Fixed in the next Chat API release

Regards

**Comment by 0xTryCatch** [comment]
This is fixed in iPhone 2.12.17 which was just released in the App Store.

**Comment by rflsouza** [comment]
@0xTryCatch, I try with 2.12.17 and work like a charm ! ;)    Thanks.

**Comment by anativ** [comment]
@0xTryCatch Yes, seems to work.
Can you explain a bit what was the bug?
