### ISSUE TITLE
Can't send direct messages. But i can send Broadcast messages

### ISSUE THREAD

**Issue by anthonyej** [mgp25/Chat-API#1768]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [x ] You are using latest Chat API code.

### Error
Can't send direct messages. But i can send Broadcast messages. No errors happen

### Debug log

http://pastebin.com/raw/pS3TeXkg

**Comment by mgp25** [comment]
@anthonyej 

1- You are not polling enough
2- You havent installed and loaded all extensions correctly

Regards

**Comment by anthonyej** [comment]
I have all the extens loaded -> http://pastebin.com/raw/en7JDcNV
