### ISSUE TITLE
Multiple numbers blocked in a short amount of time

### ISSUE THREAD

**Issue by david-perez** [mgp25/Chat-API#1769]
- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [ x] You are using latest Chat API code.

Over the last 48 hours, I've had 3 numbers blocked.
Moreover, I was unable to log in with one of them after a successful registration. After obtaining its password and attempting to log in, it was immediately blocked.

The fact that brand new numbers registering with this API's code are immediately getting blocked  leads me to believe that either the current client configuration, or the current registration process, is deprecated.

I suspect the reason for these sudden blockages is that **WA 2.0 protocol enforcement has finally kicked in**.

**Comment by anativ** [comment]
Same here lots of blocks
