### ISSUE TITLE
PR: I wrote more two other events

### ISSUE THREAD

**Issue by asluiz** [mgp25/Chat-API#1771]
Hi,

I was trying to catch the phone number responsible for the changing or removal of the group's picture soon as it happens.

The problem is that the current event for this, is missing an argument passed on the node, when the event occurs on a group. 

Here are the event arguments on the current version:

**onProfilePictureChanged($mynumber, $from, $id, $time)**

**onProfilePictureDeleted($mynumber, $from, $id, $time)**

These events are complete enough to catch all the attributes passed on the node when the event occurs on a particular profile, but on the group, the node has an "author", which is not currently catched.

```
NODE FOR PARTICULAR PROFILE:
rx  <notification from="XXXXXXX@s.whatsapp.net" type="picture" id="1454821727" notify="XXXXX" t="1459289012">
rx    <set jid="XXXXXXXX@s.whatsapp.net" id="1459289012"></set>
rx  </notification>

NODE FOR GROUP:
rx  <notification from="XXXXXXXXX-1458828047@g.us" type="picture" id="2785108750" notify="XXXXXXXX" t="1459289268">
rx    <set author="XXXXXXX@s.whatsapp.net" jid="XXXXXXXXX-1458828047@g.us" id="1459289268"></set>
rx  </notification>
```
So, I wrote some modifications to fix this. Those are the events that I wrote when these changes happens EXCLUSIVELY on a group:

**onPictureChangedGroup($mynumber, $from, $id, $time, $author)**

**onGroupPictureDeleted($mynumber, $from, $id, $time, $author)**

To events on personal profiles, use the events already included on the current version!

To apply this modification, you would have to change the whole **"case: 'picture':"**, which starts on the line 34, of the **\handlers\NotificationHandlers.php**, for this:

```
case 'picture':
			
            if ($this->node->hasChild('set')) {
				
				if ($this->node->getChild(0)->getAttribute('author')) {
				
						$this->parent->eventManager()->fire('onPictureChangedGroup',
							[
								$this->phoneNumber,
								$this->node->getAttribute('from'),
								$this->node->getAttribute('id'),
								$this->node->getAttribute('t'),
								$this->node->getChild(0)->getAttribute('author'),
							]);
							
				} else {
					   $this->parent->eventManager()->fire('onProfilePictureChanged',
							[
								$this->phoneNumber,
								$this->node->getAttribute('from'),
								$this->node->getAttribute('id'),
								$this->node->getAttribute('t'),
							]);
					
				}
					
					
            } elseif ($this->node->hasChild('delete')) {
				
				if ($this->node->getChild(0)->getAttribute('author')) {
					
					$this->parent->eventManager()->fire('onGroupPictureDeleted',
                    [
                        $this->phoneNumber,
                        $this->node->getAttribute('from'),
                        $this->node->getAttribute('id'),
                        $this->node->getAttribute('t'),
						$this->node->getChild(0)->getAttribute('author'),
                    ]);	

				} else {
                $this->parent->eventManager()->fire('onProfilePictureDeleted',
                    [
                        $this->phoneNumber,
                        $this->node->getAttribute('from'),
                        $this->node->getAttribute('id'),
                        $this->node->getAttribute('t'),
                    ]);
					
				}	
            }
            break;

```

I hope that helps someone, I'm not the smartest coder ever, but that should do the job.

I also would like to thank you everyone involved on this project, you are really awesome guys. Thanks.

**Comment by asluiz** [comment]
**ddddddddd**

**Comment by J-N-K** [comment]
I think that

onGroupPictureChanged and 
onGroupPictureDeleted

would be better names.

**Comment by mgp25** [comment]
I changed it to:

```
onGroupsPictureChanged
onGroupsPictureDeleted
```
so it fits with the rest of the events. Thanks! this is added in the next Chat API release.
