### ISSUE TITLE
Getting only composing / paused but not the message

### ISSUE THREAD

**Issue by anativ** [mgp25/Chat-API#1772]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Manytimes the server just stops getting messages gets only the composing / paused.
There is nothing more in the logs... and it doesn't sends ack (vv) or ack read

### Debug log

```xml
rx  <chatstate from="xxxxxxxxx-1456343750@g.us" participant="xxxxxxxx@s.whatsapp.net"> 
rx    <composing></composing> 
rx  </chatstate> 
rx  <chatstate from="xxxxxxxxx-1456343750@g.us" participant="xxxxxxxxx@s.whatsapp.net"> 
rx    <paused></paused> 
rx  </chatstate> 

```

**Comment by eduardobento** [comment]
Same with me..I will try to register again.. Its a old number...

**Comment by anativ** [comment]
Tested with old / new numbers

**Comment by mgp25** [comment]
If you don't get the message in debug log, no message is sent. You can receive a compossing without having to receive a message. Both are completly different nodes.

Regards

**Comment by anativ** [comment]
@mgp25 I am sending messages from my phone...
But I don't see it in the logs... only the <composing></composing>

Is there a chance that there is a client with iPhone v2.12.16 that sends the server messages that can't be decrypted so no ack sends to the to WhatsApp server so WhatsApp stops sending me messages?

If so is there a way to recognise this issue and automatically send "ack" to WhatsApp server?

Thanks,
A.

**Comment by dcardosoa** [comment]
Hi,

I'm having the same issue.
I can't send phone to API and I can send API to phone.

Is possible see composing and pause events. I tryied register the NUMBER again and doesnt solved the issue.

I have only one tick at my phone.

**Comment by eduardobento** [comment]
I have the same problem that @anativ said. I can send messages with api but not receive.. nothing in log/debug !!! 
I sent msg from Android oficial and iphone oficial last version.

Now I will delete account with resetAccount.php and register again to see what happens....

**Comment by eduardobento** [comment]
Hi, 

To resolve execute:

* resetAccount.php - will delete the account in wa server
* Register again normally
