### ISSUE TITLE
temporarily_unavailable when register

### ISSUE THREAD

**Issue by wufengleo** [mgp25/Chat-API#1773]
Make sure these boxes are checked before submitting your issue -- thank you!

- [Y ] You are using PHP > 5.6
- [ Y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [Y ] You have checked if someone has already asked the same issue you have.
- [ Y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [n] Is not a programming question.
- [ y] You are using latest Chat API code.

### Error
temporarily_unavailable
i use PHP API that retrun temporarily_unavailable error
i try at simulator,that is no problem
The SMS is deliveryed
just use your API to register,that will be block
i think whatsapp may block register from This API

### Debug log
Array ( [cc] => 86 [in] => 15649439848 [lg] => zh [lc] => CN [id] => %85%cf%a3%a4d28%f9%b5ig%c9l%84%91%7b%a0nx%95 [token] => Pp1Ct0xJhy7AQiVGUnHeLm8GlYg= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 2087 [rchash] => f7ffa4dca7241587d6c9671072aa9d2192ec7924c6f6477828d50d96a71fd4e0 [anhash] => 5806bee42991f28ea7d4a2995752a1b7 [extexist] => 1 [extstate] => 1 [mcc] => 460 [mnc] => 000 [sim_mcc] => 460 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => sent [length] => 6 [method] => sms [retry_after] => 64 [sms_wait] => 64 [voice_wait] => 64 )

Array ( [cc] => 86 [in] => 15649439848 [lg] => zh [lc] => CN [id] => %85%cf%a3%a4d28%f9%b5ig%c9l%84%91%7b%a0nx%95 [mistyped] => 6 [simnum] => 1 [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 4750 [rchash] => 13da0fdd3fa9cf6c9d7e143ad7e382a87fa843e8a7d40b04073311ff1023c095 [anhash] => 01e2def34e182106186cff39e521b0e1 [extexist] => 1 [extstate] => 1 [code] => 708393 ) stdClass Object ( [status] => fail [reason] => temporarily_unavailable [retry_after] => 3600 ) IP blockAn error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable

**Comment by mgp25** [comment]
@wufengleo you are using chinese numbers, and probably registering more than one under the same IP.

`temporary_unavailable` = WA flagged you
