### ISSUE TITLE
Axolotl is everywhere?

### ISSUE THREAD

**Issue by debiannuser** [mgp25/Chat-API#1774]
Hello mgp25! Please tell will you research the new encryption of whatsapp protocol nodes? Before today it was based on 4 keys generated from pw and challenge, today there are no even first not encrypted packets in traffic.. Are they using axolotl to encrypt all data?

Example of new traffic:
First packet outcomming packet: "57 41 02 00" and that's all
Second outcomming packet:
00 00 ad   12 aa 01 0a 20 fb 7c a0 6a 64 1c b1 6a d1 0d 65 1d 3f 01 ed e4 74 d2 7d 39 e9 b1 77 72 43 7a 1b 95 1a c6 11 72 12 30 fe 31 c3 c9 ee 9d 8a 6d 90 70 8e 05 e4 53 1c d1 8f 13 50 13 40 e8 59 de 62 b1 aa 59 00 ca 12 85 90 f4 fb 55 18 e4 12 6a bb 45 a5 4a f1 a2 7b 9e 1a 54 32 75 5b e1 d8 17 d6 96 d8 03 26 6d 29 c4 88 13 be 59 bc 85 d3 b0 46 7d c8 e7 d6 44 28 75 77 aa 63 e9 dd 57 df 54 a5 6f 58 dd 3a 12 41 01 06 73 ad 9b 16 1c b3 12 09 54 29 91 00 9d d0 e3 d5 08 6c fd 95 9a 3e 98 4c 4d 44 e5 c2 21 7e 68 70 93 03 de ae 1a

As you can see header now does not contains 80 or c0. Is it possible to implement new encryption of WhatsApp?

**Comment by mgp25** [comment]
My friend, welcome to WA 2.0. https://github.com/mgp25/Chat-API/wiki/WhatsApp-incoming-updates#26-march-2016

Regards
