### ISSUE TITLE
"Over 2000 messages into the future!"

### ISSUE THREAD

**Issue by VilsonFerrari** [mgp25/Chat-API#1775]
I'm receiving the following message when i try to decrypt:

```xml
Decrypted Message: Over 2000 messages into the future!
No valid sessions - /var/www/wf2/vendor/whatsapi/src/libaxolotl-php/SessionCipher.php - 178Message C7418C1C5D97F1A7EE could not be decrypted, sending retry.
```

**Comment by eduardobento** [comment]
This problem occur when much retry is sent to wa server.
The real problem is related to "bad mac" and "No valid sessions". Search for this...

**Comment by VilsonFerrari** [comment]
I'm receiving the message below for group messages. There is any way to disable temporarily group messages?

`Decrypted Message: No keys for: 1623426454`
