### ISSUE TITLE
registerTool.php outputs `There was a problem trying to request the code.`

### ISSUE THREAD

**Issue by someone235** [mgp25/Chat-API#1776]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
When I'm using registerTool.php (without any modifications), I get this error: `There was a problem trying to request the code.`

### Debug log

```xml
$ php registerTool.php 
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 972*********
Array
(
    [cc] => 972
    [in] => *********
    [lg] => he
    [lc] => IL
    [id] => &�x~yxf�|�^��m}�
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 6376
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 24450
    [voice_wait] => 0
)
There was a problem trying to request the code.
```

**Comment by mgp25** [comment]
This is a modification of the script or you are not posting full debug log, i don't see the request or the register, no `method` or `code` params

**Comment by someone235** [comment]
@mgp25 I've just run examples/registerTool.php without any modification, and this is the output I got.

**Comment by mgp25** [comment]
@someone235 then remove all `.dat` files from `wadata` folder and retry again, it should ask you for a send method.

Regards

**Comment by someone235** [comment]
@mgp25 Thank you, it worked

**Comment by mayurharne10** [comment]
Hi,

I am facing the same issue, I removed the .dat files, but still, the request is failing.

Debug Log:
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 9189********


Type sms or voice: sms
Array
(
    [cc] => 91
    [in] => 89********
    [lg] => hi
    [lc] => IN
    [id] => (ᔫk!�1�w%+d��
    [token] => 2Iq/tks++KDjkJKNgPeM2W1Nxpk=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 7416
    [rchash] => 3910ac28359ba2d810133cb527c472f3bfd7eb2db3c31de03326cb319f86a313
    [anhash] => aa346ad3f72aeb31a43ca7a02d0072cb
    [extexist] => 1
    [extstate] => 1
    [mcc] => 404
    [mnc] => 000
    [sim_mcc] => 404
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [login] => 9189********
    [status] => fail
    [reason] => old_version
)
There was a problem trying to request the code.
