### ISSUE TITLE
stream:error on pollMessage/getMessages?

### ISSUE THREAD

**Issue by VilsonFerrari** [mgp25/Chat-API#1777]
pollMessage/getMessages not working with some numbers. How can i proceed?

The numbers has been reset already, i'm following the workflow on wiki, have protobuf, curve and crypto pecl installed, followed some "solutions" on issues (like leave groups because encrypted messages, clean axolotl, msgstore and/or nextChallenge...)

```xml
rx  <chatstate from="XXXXX@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <chatstate from="XXXXX@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <stream:error>
rx    <ack id="8C649E644AA99B85DBDBBAA88593AA"></ack>
rx  </stream:error>
```

any additional info?

**Comment by mgp25** [comment]
@VilsonFerrari can you provide more data? What was the device used to sent a message, WA version, messaage content, etc etc..

**Comment by VilsonFerrari** [comment]
Was sent from iPhone 4S and Moto G, last chat api version, message was a text like "hi". 
And as i said, i used other numbers and just a few give this error. Maybe any wa configuration?

**Comment by mgp25** [comment]
@VilsonFerrari i mean WhatsApp app version

**Comment by VilsonFerrari** [comment]
iPhone 4S - WA Version 2.12.17
Moto G - WA Version 2.12.556

**Comment by bobvandevijver** [comment]
I've got the same problem, here is my debug log:

```
tx  <stream:features></stream:features>

tx  <auth user="31684638910" mechanism="WAUTH-2">7cf606143331363834363338393130f1a85087960834275a35c03e29eea0a708d0e25231343539353234373334</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>6541afe04e3f3572cb7558dce42ab46c9dc10d3f</challenge>

tx  <response>414414e97a4176bbda33d76d6635883a8cd8b7d2e2c40841b1d33c2528599e73f3854ca7efb77cd81f115cdce993f125b3d904ab619b25dec7e7dfdeb8c2b00b832859a7f2afe3e6e69ae0bedf</response>

rx  <success t="1459524734" props="4" kind="free" status="active" creation="1398871765" expiration="4444444444">2bd9c82f8633b5f11b0ed6d473bfb97f066bc814</success>

tx  <presence name="354207032126636" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq to="s.whatsapp.net" type="set" id="03" xmlns="status">
tx    <status>Bob is cool!</status>
tx  </iq>

tx  <presence name="BobBot" type="available"></presence>
tx  <iq id="04" to="31684638910@s.whatsapp.net" type="set" xmlns="w:profile:picture">
tx    <picture type="image"> 27064 byte data</picture>
tx    <picture type="preview"> 2830 byte data</picture>
tx  </iq>

tx  <message to="31645719540@s.whatsapp.net" type="text" id="931c04f327714ec416078a" t="1459524734" notify="BobBot">
tx    <enc v="1" type="msg">330a21059b6fd0c70795830c1f3e29d8c5300a52d155fd0420b9c036356de0e4d3e0ac02100818052220470a84494269cd759227b099c317aa16eeaf3b75bad334553d765a477d18d99fe0b1da922f7c384b</enc>
tx  </message>

tx  <iq id="05" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

rx  <message from="31645719540-1345018963@g.us" type="text" id="092A68805B325B46DF" participant="31638445533@s.whatsapp.net" offline="3" t="1459508797" notify="Emma Boersma">
rx    <enc v="2" type="pkmsg">33088cd7e507122105f0fe4abec4620b3285cf8ced1d9558024915410dc1372b24671a9ca968f8e1401a210595f0845d00da0f63ffbe06a780ece827001596ded68651698bb2daab3195392722b301330a2105cab545cfd4176d3665e2548df35db5d3c1392b3f352a1b5b07797b0db2d35e27100118002280015a3bc1e196d0c41a866320950e13d3db264f77cf4eb0b77c078b5b9014bfb08f5f40bf282cd72057c24851b2d4b923aaee0eef0ac3e21d5ee52dee25a371f07993842ef6233365d33b1e56590c759f9b47e34eee3c872e30baa0bb051f51c822ccc485e1b5f5b297761edd38bf3651bea9ce92c5747a3cc18103d60ec4008d23e294a2133e57850c28ae4430d3fa02</enc>
rx    <enc v="2" type="skmsg">3308d4ccb3d30310281a2051d646afed83f1dfb55e4d6268f297e3d4fd4adaa42ac6a49ab1007059fff20ae3ba84494105d4cbdb7c1188e202e98c75336cf34aa6d077d8f3516451f39101c00f7abcdf6bd65173bd326f0b7394104aa53f0f45716754c462c9d92e832f0e</enc>
rx  </message>

tx  <ack to="31645719540-1345018963@g.us" class="message" id="092A68805B325B46DF" t="1459508797"></ack>


-> Decrypted Message: No such signedprekey with id: 48467 - /data/ssd1/system/bobbot/WhatsAPI-Official/src/SqliteAxolotlStore.php - 248Message 092A68805B325B46DF could not be decrypted, sending retry.


-> Decrypted Message: Received message with old counter: 42 40 - /data/ssd1/system/bobbot/WhatsAPI-Official/src/libaxolotl-php/groups/GroupCipher.php - 73tx  <receipt id="092A68805B325B46DF" to="31645719540-1345018963@g.us" type="retry" t="1459508797">
tx    <retry v="1" count="1" id="092A68805B325B46DF" t="1459508797"></retry>
tx    <registration>b1970d3a</registration>
tx  </receipt>

rx  <presence from="31684638910@s.whatsapp.net"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <iq from="31684638910@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="03"></iq>

rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="06" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="gcm" id="GniTU_92Hi1:APA91bC3bPbY7Iby1EOn1oSi8GNC7iLF4jZNvD4L5UppYYDYgwpjWQ3QBsuiCYGUKT0GhS_ihOgQ-wceDyuhfZqJU_eNUuDP3LP_Jkq2QSLUhOO_l_UmbQE5LE7b9JhaoKJ0v2y6B3VN"></config>
tx  </iq>

rx  <ack from="31645719540@s.whatsapp.net" class="message" id="931c04f327714ec416078a" t="1459524735"></ack>

rx  <iq from="g.us" type="result" id="05">
rx    <groups>
 <SNIP>
rx    </groups>
rx  </iq>

rx  <iq from="31684638910@s.whatsapp.net" type="result" id="04">
rx    <picture id="1459524735"></picture>
rx  </iq>

rx  <ack from="31645719540-1345018963@g.us" class="receipt" type="retry" id="092A68805B325B46DF"></ack>

tx  <receipt id="092A68805B325B46DF" to="31638445533@s.whatsapp.net" participant="31638445533@s.whatsapp.net" type="retry" t="1459508797">
tx    <retry v="1" count="1" id="092A68805B325B46DF" t="1459508797"></retry>
tx    <registration>b1970d3a</registration>
tx  </receipt>

rx  <iq from="s.whatsapp.net" type="result" id="06"></iq>

rx  <ack from="31638445533@s.whatsapp.net" class="receipt" type="retry" id="092A68805B325B46DF" participant="31638445533@s.whatsapp.net"></ack>

rx  <receipt from="31645719540@s.whatsapp.net" id="931c04f327714ec416078a" t="1459524739"></receipt>

tx  <ack to="31645719540@s.whatsapp.net" class="receipt" id="931c04f327714ec416078a"></ack>

rx  <receipt from="31645719540@s.whatsapp.net" type="read" id="931c04f327714ec416078a" t="1459524750"></receipt>

tx  <ack to="31645719540@s.whatsapp.net" class="receipt" id="931c04f327714ec416078a" type="read"></ack>

rx  <presence from="31645719540@s.whatsapp.net" type="unavailable" last="1459524761"></presence>

rx  <stream:error>
rx    <ack id="092A68805B325B46DF"></ack>
rx  </stream:error>
```

Seems that removing the `axolotl.db` & `msgstore.db` fixes the problem temporarely, but it comes back after a few hours.

**Comment by VilsonFerrari** [comment]
@bobvandevijver , i tried remove also. I even change computer but still the same. I believe is something with the number config. The questions are what and how?

**Comment by bobvandevijver** [comment]
Removing the databases does not work anymore, it still comes back very soon. Appears to be related to message acking... Even re-registered the number, did not work..

**Comment by victorscatolon** [comment]
I'm also having the same problem, there are times that it gets the message of good, others he error:

Fatal error: Call to a member function getData () on a non-object in /var/www/html/whatsapp/wm.php on line 42

This started to occur in about 4 days until today

**Comment by jonathan-r** [comment]
I have the same issue. Here is my debug log : 
```xml
rx  <message from="33*******86-1447148594@g.us" type="text" id="F798164561******29" participant="33*******91@s.whatsapp.net" offline="3" t="1458896252" notify="FirstName">
rx    <enc v="2" type="pkmsg">[SOME DATA...]</enc>
rx  </message>

tx  <ack to="33*******86-1447148594@g.us" class="message" id="F798164561******29" t="1458896252"></ack>

-> Decrypted Message: Received message with old counter: 2 0 - /var/lib/openshift/562d********************/app-root/runtime/repo/chat-api/src/libaxolotl-php/SessionCipher.php - 238Message F798164561******29 could not be decrypted, sending retry.

-> Decrypted Message: Invalid signature! - /var/lib/openshift/562d********************/app-root/runtime/repo/chat-api/src/libaxolotl-php/protocol/SenderKeyMessage.php - 93

tx  <receipt id="F798164561******29" to="33*******86-1447148594@g.us" type="retry" t="1458896252">
tx    <retry v="1" count="1" id="F798164561******29" t="1458896252"></retry>
tx    <registration>Z€Dã</registration>
tx  </receipt>

rx  <ack from="33*******86-1447148594@g.us" class="receipt" type="retry" id="F798164561******29"></ack>

tx  <receipt id="F798164561******29" to="33*******91@s.whatsapp.net" participant="33*******91@s.whatsapp.net" type="retry" t="1458896252">
tx    <retry v="1" count="1" id="F798164561******29" t="1458896252"></retry>
tx    <registration>Z€Dã</registration>
tx  </receipt>

rx  <ack from="33*******91@s.whatsapp.net" class="receipt" type="retry" id="F798164561******29" participant="33*******91@s.whatsapp.net"></ack>

rx  <stream:error>
rx    <ack id="F798164561******29"></ack>
rx  </stream:error>
```

**Comment by naamakat** [comment]
same here - 

> rx  <message from="97********01@s.whatsapp.net" type="text" id="67F939C50C9E6C1B8B" t="1459759623" notify="***">
> rx    <enc v="2" type="msg">330a2105e0db4adef113f7070d7db90aa5e82c641f4aba5455ab2bd546fd970930ea291210101803221012942dc4c7211861644ad893036ecab915cb809485e4e59c</enc>
> rx  </message>
> 
> rx  <stream:error>
> rx    <ack id="67E593773E42AD2272"></ack>
> rx  </stream:error>
> 
> object(ConnectionException)#10 (7) {
>   ["message":protected]=>
>   string(18) "Connection Closed!"
>   ["string":"Exception":private]=>
>   string(0) ""
>   ["code":protected]=>
>   int(0)
>   ["file":protected]=>
>   string(77) "/var/rompr-engine-python/src/WhatsappChatApi/Chat-API/src/whatsprot.class.php"
>   ["line":protected]=>
>   int(299)
>   ["trace":"Exception":private]=>
>   array(1) {
>     [0]=>
>     array(6) {
>       ["file"]=>
>       string(61) "/var/rompr-engine-python/src/WhatsappChatApi/run-whatsapp.php"
>       ["line"]=>
>       int(121)
>       ["function"]=>
>       string(11) "pollMessage"
>       ["class"]=>
>       string(9) "WhatsProt"
>       ["type"]=>
>       string(2) "->"
>       ["args"]=>
>       array(0) {
>       }
>     }
>   }
>   ["previous":"Exception":private]=>
>   NULL
> }
>

**Comment by naamakat** [comment]
Same here - 
```
[*] Connected to WhatsApp

rx  <presence from="972526285405@s.whatsapp.net"></presence>

rx  <iq from="972526285405@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <message from="972546200701@s.whatsapp.net" type="text" id="67E593773E42AD2272" offline="1" t="1459759493" notify="נעמה">
rx    <enc v="2" type="msg">330a2105e0db4adef113f7070d7db90aa5e82c641f4aba5455ab2bd546fd970930ea2912100f180322208fe2594f199092b4f3de9d3163a1dfd1159b6cbac3f4ef4ab7c567db90492db0ee6dae982f1cbd92</enc>
rx  </message>

rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="03" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="gcm" id="qqwh9_glbGA:APA91bvx8WhyNbHZ6DmEDqmt6dhXaA8x1r4bDO7n3xOrcpvsuLgrlJAH67DLGR7DtYjZqj_F76bV-KfbWfeGfEGQE_YJEf7jSZb_ntn9vomT2AU_x_pr8XTyQsrkw7AGcQxtwefiGEHL"></config>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="03"></iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

using port: 1442
rx  <presence from="972546200701@s.whatsapp.net"></presence>

rx  <chatstate from="972546200701@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="972546200701@s.whatsapp.net" type="text" id="67F939C50C9E6C1B8B" t="1459759623" n
```otify="נעמה">
rx    <enc v="2" type="msg">330a2105e0db4adef113f7070d7db90aa5e82c641f4aba5455ab2bd546fd970930ea291210101803221012942dc4c7211861644ad893036ecab915cb809485e4e59c</enc>
rx  </message>

rx  <stream:error>
rx    <ack id="67E593773E42AD2272"></ack>
rx  </stream:error>

**Comment by naamakat** [comment]
OK, the problem was with the dependencies  - they we'rent installed properly. Re-installed it and it worked ok.

**Comment by VilsonFerrari** [comment]
This is my `php -m`

`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
curve25519
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

**Comment by naamakat** [comment]
@VilsonFerrari you're missing crypto - https://github.com/mgp25/Chat-API/wiki/Dependencies
run - 
```
sudo wget https://pecl.php.net/get/crypto
tar zxvf crypto
cd crypto-0.2.2/
sudo phpize
sudo ./configure
sudo make
sudo make install
```

**Comment by mgp25** [comment]
@VilsonFerrari @naamakat crypto is not required for this version (the currently available in Chat API), crypto is required for the next release WA 2.0

Make sure you have loaded the correctly php version (php.ini)

Regards

**Comment by bobvandevijver** [comment]
I think the problem was with Whatsapp self, however, the issue appears to be resolved now.

**Comment by VilsonFerrari** [comment]
@mgp25 , chip registered on WA with phone. After that, register through API and... work! As i said, is probably WA config.

**Comment by bobvandevijver** [comment]
Got an error again, directly after receiving a new message type (an url with loaded image from the website). Error message:

```
PHP Fatal error:  Call to a member function getData() on null in /data/ssd1/system/bobbot/WhatsAPI-Official/src/handlers/MessageHandler.php on line 68
```

@mgp25 Might it be that the problem is related to that messagetype?

I've solved this by checking the data before event generation:
```
$protocolNode = $this->node->getChild('body');
if($protocolNode !== null) $protocolNode = $protocolNode->getData();
$this->parent->eventManager()->fire('
  [
    $this->phoneNumber,
    $this->node->getAttribute('from'),
    $this->node->getAttribute('id'),
    $this->node->getAttribute('type'),
    $this->node->getAttribute('t'),
    $this->node->getAttribute('notify'),
    $protocolNode,
  ]);
```

**Comment by victorscatolon** [comment]
`tx  <stream:features></stream:features>

tx  <auth user="5513996350878" mechanism="WAUTH-2">e72df0313535313339393633353038373825d0ebb2f41973e6c2a374441e7047101da3b96531343539383731393234</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>032da2457018907c0a1ac39193b1533b17b782ec</challenge>

tx  <response>454075952d1e6952fe967b988af5ede2a10863b17130f6f0132d8254e4ac7a0dd6b2a40cb443ee02afa7f6c83d28f552a510d6d346fc05ee9b73cbd10ddddf53dcfcb57462f34d8253cf9d023d3aee</response>

rx  <success t="1459871936" props="4" kind="free" status="active" creation="1451311130" expiration="4444444444">8a53f1b02e3623427dd322e1271bec6d342e4f72</success>

tx  <presence name="John" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <presence from="5513996350878@s.whatsapp.net"></presence>

rx  <iq from="5513996350878@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="QWzSK_v5m5r:APA91b9mDxthKUgNi2VAOdX8ATDvgwIO1fcS9SeXfru7O4cyfsATqtaAWZpGxJ3dGxByEe_JUTYX-KwWTqEUploRk_9DjzfgoSo_FkoYaX0NZQ4_6_8tlLrN1D7BfCTIw32ZgQyTI0mK"></config>
rx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <chatstate from="5511963872972-1459444951@g.us" participant="5511963872972@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="5511963872972-1459444951@g.us" type="text" id="90EFE8A029E0D09B10A8990BD7EF1B" participant="5511963872972@s.whatsapp.net" t="1459871985" notify="Tougo ❤">
rx    <enc v="2" type="skmsg">3308d6e184d005106a1a8002a6d108ff870daae0854599f4b0d4d44126f74e21760ada41a747b8007c6f8e5bd33d729168126b3ed5234a38add0a1c1825e37ca6d9f22843982228a4726974e676834ae782e31da2620170197a24852de0141feb813725062a69d8b9607c0530cf22f6f1d64794fc5c4e7cd854fbc8a39d3b414925938ded692d62745d9d508eab2017af82df26f543cea3250151835706e73395a58432970d2bb8a78470e2cf3ac738a55b3343b5ba48c77f6bd4e8f8b15783db503793a623504d1da3387eeea6c63f3329fcddd9fb1bd5365135292f483d083d54bac12b44cd288a096e6779262181936c715666a5964c771a1e841e42b1c4ea6a90a643b11816cb86ca7e9167234c74fa6cb96e30e3e88e93599bfd77f6bdbf6a9e3ab6e9fa86eb2e180db0cc45295b7f74fa4a757758a06c09fc92db26474740f737091dd2f1ad0e8b18f</enc>
rx  </message>

tx  <ack to="5511963872972-1459444951@g.us" class="message" id="90EFE8A029E0D09B10A8990BD7EF1B" t="1459871985"></ack>

-> Decrypted Message: Invalid signature! - /var/www/html/whatsapp/src/libaxolotl-php/protocol/SenderKeyMessage.php - 86tx  <receipt id="90EFE8A029E0D09B10A8990BD7EF1B" to="5511963872972-1459444951@g.us" type="retry" t="1459871985">
tx    <retry v="1" count="1" id="90EFE8A029E0D09B10A8990BD7EF1B" t="1459871985"></retry>
tx    <registration>11dfa6f7</registration>
tx  </receipt>

rx  <ack from="5511963872972-1459444951@g.us" class="receipt" type="retry" id="90EFE8A029E0D09B10A8990BD7EF1B"></ack>

tx  <receipt id="90EFE8A029E0D09B10A8990BD7EF1B" to="5511963872972-1459444951@g.us" participant="5511963872972@s.whatsapp.net" type="retry" t="1459871985">
tx    <retry v="1" count="1" id="90EFE8A029E0D09B10A8990BD7EF1B" t="1459871985"></retry>
tx    <registration>11dfa6f7</registration>
tx  </receipt>

rx  <ack from="5511963872972-1459444951@g.us" class="receipt" type="retry" id="90EFE8A029E0D09B10A8990BD7EF1B" participant="5511963872972@s.whatsapp.net"></ack>


Fatal error: Call to a member function getData() on a non-object in /var/www/html/whatsapp/wm.php on line 42`

my php -m

`
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mhash
mysql
mysqli
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`

**Comment by amec1234** [comment]
I have the same problems but with images. When I`m receiving text messages everything is arrived as it should be, but when i`m receiving images i get the "invalid signature!". Even the right php.ini with all needed dependencies is loaded/installed.
