### ISSUE TITLE
 Problem with the reception of messages

### ISSUE THREAD

**Issue by juanelosrock** [mgp25/Chat-API#1778]
I have a problem with the reception of messages are encrypted think

`tx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
tx&nbsp;&nbsp;&lt;auth user="57XXXXXXXXXX" mechanism="WAUTH-2"&gt;a68fc4d0353733313833333438393530dc33df3166c6496f7a455bca0b55679ebfa1d6d331343539343534393737&lt;/auth&gt;<br /><br />
rx&nbsp;&nbsp;&lt;from s.whatsapp.net=""&gt;&lt;/from&gt;<br /><br />
rx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
rx&nbsp;&nbsp;&lt;challenge&gt;6febdd0e6bb98bf90e4ee978585a48508f67fbf2&lt;/challenge&gt;<br /><br />
tx&nbsp;&nbsp;&lt;response&gt;f7fc736514f9b3ba9363d49cfadedcb3e4ece3cfb1468cfe0c83a6552957f6220515e0e7a5ea59169ced49b8776f79d972790cc9dd74f40b940f9d83b69e0c13f891b4b183b6d8e3bd5bf2c23113&lt;/response&gt;<br /><br />
rx&nbsp;&nbsp;&lt;success t="1459454986" props="4" kind="free" status="active" creation="1459435967" expiration="4444444444"&gt;150b122669887d8a86af918b73d3c6a0dcfdb099&lt;/success&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence name="0" type="available"&gt;&lt;/presence&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="01" xmlns="jabber:iq:privacy" type="get"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;query&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;list name="default"&gt;&lt;/list&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;/query&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config&gt;&lt;/config&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence type="subscribe" to="57xxxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;ib from="s.whatsapp.net"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;offline count="0"&gt;&lt;/offline&gt;<br />rx&nbsp;&nbsp;&lt;/ib&gt;<br /><br />
rx&nbsp;&nbsp;&lt;notification from="s.whatsapp.net" type="encrypt" id="3727891381" t="1459454986"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;count value="0"&gt;&lt;/count&gt;<br />rx&nbsp;&nbsp;&lt;/notification&gt;<br /><br />
tx&nbsp;&nbsp;&lt;ack to="s.whatsapp.net" class="notification" id="3727891381" type="encrypt"&gt;&lt;/ack&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxxx@s.whatsapp.net" type="unavailable" last="1459454552"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="57xxxxxxxxxx@s.whatsapp.net" type="error" id="1"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;error code="404" text="item-not-found"&gt;&lt;/error&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="s.whatsapp.net" type="result" id="02"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config platform="gcm" id="VxHYP_uT5VV:APA91bXa8DjUBUssH8grbGpUt8RmAToXITBQ3D4wJdqJqsPzic7pfBWSZtD7jPNgXHrOqZ_Z2Xrs-AlK3VbMYBLaa_4TTMlBPir_NwV0rzQa8SS_V_wFJfq0LEmgf0Gwn4VX0xq9RiAy"&gt;&lt;/config&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxxx@s.whatsapp.net" type="unavailable" last="1459454552"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;message from="57xxxxxxxxxx@s.whatsapp.net" type="text" id="B5C37DE0BF507906FBD1C63F456203" t="1459455000" notify="Juan Manuel"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;enc v="2" type="pkmsg"&gt;331221050b3f9814c35dae9cf3c54a54ec6ca00d041c3d03fdc5924a471d3fd0f37eca201a210541a305d92ec745d0c01db13c42dadc3dcc0665957319972fe97b72d47e51e67d22c301330a2105905f04dd19ac32100cf017392a560b109ba5341253cc0a6be77f2ce85797b624103618002290010e635ffabf90c40edb17a5a3cbe1ae79edb62acad60d8107af394571674ff8d158ec62e92aa64138a54fa4f395a9e7290c7463b3630937908b9f8372e69cf690770545f5d92adb436699d6c21ab29b8dd8b2cfe9cf79ebfeb6aedce594d17914357f3a4ea87cf2aadeda92ed2db3b27909efcfd046a0124ac343454fe2d81b5198994025baaad0f4459c3c0f8472a4c22a3c56c321ce5327289edb952430e1b9ca05&lt;/enc&gt;<br />rx&nbsp;&nbsp;&lt;/message&gt;<br /><br />

(index):34 tx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
tx&nbsp;&nbsp;&lt;auth user="57xxxxxxxxxx" mechanism="WAUTH-2"&gt;ea0d41da353733313833333438393530150b122669887d8a86af918b73d3c6a0dcfdb09931343539343534393935&lt;/auth&gt;<br /><br />
rx&nbsp;&nbsp;&lt;from s.whatsapp.net=""&gt;&lt;/from&gt;<br /><br />
rx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
rx&nbsp;&nbsp;&lt;challenge&gt;a82c84fe3b38ca3f15b77803f07da88a58476ade&lt;/challenge&gt;<br /><br />
tx&nbsp;&nbsp;&lt;response&gt;2bb90f0b44cca96c23e841a612014c3e567809cd7bcdb9c9e8a9ff160d73a393f27060a14bf1b0661c95ecabc0a02216aa5497a92a0377fa3faed37c012c03ed745308b49ae213ec8839aeaf0de1&lt;/response&gt;<br /><br />
rx&nbsp;&nbsp;&lt;success t="1459455004" props="4" kind="free" status="active" creation="1459435967" expiration="4444444444"&gt;56d6fe87b7d03c78492aed057ae81296c0c1de3c&lt;/success&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence name="0" type="available"&gt;&lt;/presence&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="01" xmlns="jabber:iq:privacy" type="get"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;query&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;list name="default"&gt;&lt;/list&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;/query&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config&gt;&lt;/config&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence type="subscribe" to="57xxxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;message from="57xxxxxxxxx@s.whatsapp.net" type="text" id="B5C37DE0BF507906FBD1C63F456203" offline="1" t="1459455000" notify="Juan Manuel"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;enc v="2" type="pkmsg"&gt;331221050b3f9814c35dae9cf3c54a54ec6ca00d041c3d03fdc5924a471d3fd0f37eca201a210541a305d92ec745d0c01db13c42dadc3dcc0665957319972fe97b72d47e51e67d22c301330a2105905f04dd19ac32100cf017392a560b109ba5341253cc0a6be77f2ce85797b624103618002290010e635ffabf90c40edb17a5a3cbe1ae79edb62acad60d8107af394571674ff8d158ec62e92aa64138a54fa4f395a9e7290c7463b3630937908b9f8372e69cf690770545f5d92adb436699d6c21ab29b8dd8b2cfe9cf79ebfeb6aedce594d17914357f3a4ea87cf2aadeda92ed2db3b27909efcfd046a0124ac343454fe2d81b5198994025baaad0f4459c3c0f8472a4c22a3c56c321ce5327289edb952430e1b9ca05&lt;/enc&gt;<br />rx&nbsp;&nbsp;&lt;/message&gt;<br /><br />
rx&nbsp;&nbsp;&lt;ib from="s.whatsapp.net"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;offline count="1"&gt;&lt;/offline&gt;<br />rx&nbsp;&nbsp;&lt;/ib&gt;<br /><br />
rx&nbsp;&nbsp;&lt;notification from="s.whatsapp.net" type="encrypt" id="3986824888" t="1459455004"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;count value="0"&gt;&lt;/count&gt;<br />rx&nbsp;&nbsp;&lt;/notification&gt;<br /><br />
tx&nbsp;&nbsp;&lt;ack to="s.whatsapp.net" class="notification" id="3986824888" type="encrypt"&gt;&lt;/ack&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="57xxxxxxxxxx@s.whatsapp.net" type="error" id="1"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;error code="404" text="item-not-found"&gt;&lt;/error&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="s.whatsapp.net" type="error" id="02"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;error code="404" text="item-not-found"&gt;&lt;/error&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="03" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config platform="gcm" id="ujRAH_dkR47:APA91bmUDpJTBLrZOkBgB0Hqi473R4wyAYnpZxNaVfUfQbUFdsFUA4YnpP1pMzfS6RgwqG_Dewut-nzaXzA2cGfMR_N0o5iPvgN_wuq2qMz8JY1_4_Nd1TKmO7ofSmWGPhfYCkoJDkKf"&gt;&lt;/config&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="57xxxxxxxxx@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="s.whatsapp.net" type="result" id="03"&gt;&lt;/iq&gt;<br /><br />`

**Comment by mgp25** [comment]
reak wiki and post debug log correctly

Regards
