### ISSUE TITLE
How to install Dependencies

### ISSUE THREAD

**Issue by kadnan** [mgp25/Chat-API#1780]
I am looking at `Dependencies` Page(https://github.com/mgp25/Chat-API/wiki/Dependencies) and need bit of clarification.

- Do I have to use .`proto` file given in `src/libaxolotl-php/protobuf`. If yes then where should I put and refer compiled files?

> ffmpeg, openssl, gd, curl, sqlite PDO, sockets, mcrypt

Are all these PHP Extensions?  I am using MAMP, how do I config the? I already have all but guess not ffmpeg.

Please reply

**Comment by vnay92** [comment]
You have to build them from their source. It does not matter where you put the files. The build will take care of the final file structure and where to put the files. You would need to run PHP in developer mode to build. Just follow the instructions given [https://github.com/mgp25/Chat-API/wiki/Dependencies](Here).

**Comment by kadnan** [comment]
Yes Bro  I know this is not an issue but had no other option.

So, I can't use MAMP for the purpose as there's no binary available?

Thanks for response.

**Comment by mgp25** [comment]
https://secure.php.net/manual/en/install.windows.extensions.php
