### ISSUE TITLE
blocked after serveral hours.

### ISSUE THREAD

**Issue by jackanie** [mgp25/Chat-API#1781]
Make sure these boxes are checked before submitting your issue -- thank you!

 [y] You are using PHP > 5.6
 [y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
 [y] You have checked if someone has already asked the same issue you have.
 [y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
 [ ] Is not a programming question.
 [y] You are using latest Chat API code.

### Error
hi, my code first running is ok , but disconnected after serveral hours and find number has been blocked.  code received all messages and store into sqlite3, then reply a message to every sender, i process it in function [ onGetMessage ], is there some problem in my workflow? thanks for helping.

### listen message code

$username = SiteConfig::SITE_NUMBER;
	$nickname = SiteConfig::SITE_NICK;
	$password = SiteConfig::SITE_WAPASSWORD;
	$debug = false;

	// connect
    $w = new WhatsProt($username, $nickname, $debug);
    $w->setMessageStore(new SqliteMessageStore($username));

    $events = new MyEvents($w);
    $events->setEventsToListenFor($events->activeEvents); 

    $w->Connect();
    $w->LoginWithPassword($password);

	$w->sendGetServerProperties();
	$w->sendClientConfig();
	
	//$w->pollMessage();
	$w->sendPing();
	
	// listening msg
    while (1) 
	{
		// echo run time
		$min = intval(date('i'));
		$now = getdate();		
		if($now['minutes'] % 60 == 0 && $now['seconds'] < 3)
		{
			date_default_timezone_set("Etc/GMT-8");
			echo "Last Run Time : ".date("Y-m-d H:i:s",time())."\n";
		}
		
		// check connection
        if (!$w->isConnected()) {
            $w->connect();
            $w->loginWithPassword($password);
			
			echo "connection closed. \n";
        }

		// listen incoming message
        $w->pollMessage();
        $data = $w->getMessages();
		
    }

### file : myEvents.php

public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
{
		// Get the number 
		$target = explode('@',$from); 
			
		if(count($target)>0)
		{
			$replyNum = $target[0];
			$now = date("Y-m-d H:i:s",time());
			$replyMsg = "msg for sender."

			// check msg has processed or not. table [msg_reply] is create by myself
			$dbh = new SQLite3(SiteConfig::DB_PATH);
			$sql= 'select count(*) from msg_reply where id ="'.$id.'"';
			$count = $dbh->querySingle($sql);
			
			if ($count==0)
			{
				// add new record into processed table
				$sql= 'insert into msg_reply (id, t, reply) VALUES (:id, :t, :reply)';
				$stmt = $dbh->prepare($sql);
				$stmt->bindValue(':id', $id);
				$stmt->bindValue(':t', $now);
				$stmt->bindValue(':reply', $replyMsg);
				
				$stmt->execute();
				
				// reply msg
				$this->whatsProt->sendMessage($replyNum, $replyMsg);
			}
			else
			   echo "msg id [ ".$id." ] has been processed before\n";
			
		}
	}

**Comment by zynacks** [comment]
Are the numbers you are sending messages to, synced? If not WhatsApp may ban you (**as stated in the Wiki**)

**Comment by mgp25** [comment]
@jackanie 

- you dont need to send ping or send client config
- you are not composing or pausing text
- you are not requesting user status, profile picture or last seen time
- as the user is who started the conversation no need to sync it.

In the wiki you will find whatsapp flows

regards
