### ISSUE TITLE
Registration Errors

### ISSUE THREAD

**Issue by cpussetto** [mgp25/Chat-API#1783]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ OK] You are using PHP > 5.6
- [ OK] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ OK] You have checked if someone has already asked the same issue you have.
- [ OK] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [OK ] Is not a programming question.
- [ OK] You are using latest Chat API code.

### Error
Hello,
I'm having problems registering new numbers . The error returned Wart me and also the WS CLI is "incorrect " . Whatsapp know if anything has changed ?
4 days ago I could register 2 numbers but were blocked in 1 hour.
Thank you

### Debug log
Post your debug log below:

**Comment by mgp25** [comment]
Im sure you are using some kind of modification in `registerTool.php`. Get the lastest source, download it and run it in terminal/shell/cmd without any modification, and it should work perfect. I just tried it and works.

Regards
