### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by kadnan** [mgp25/Chat-API#1785]
Below is given below:

```
] Logging in as 'SmartConnect Agent' (12334) tx  <stream:features></stream:features>

tx  <auth user="12334" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>fafa1216bdf3c4c4528e10d80b29c6026493682d</challenge>

tx  <response>19d8120136e5897f38fe0904e54611cd8510f029bdd97f077f460faba15bc68cd0644e87ebf4b8288a143dc1914cb61bf4bfa2f17e0d7187afa8fcd18e69bb2b75d4f2da549c3d3c3facedd808bc</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

Either I run BlockChecker or Registration Tool it now gives error below: Earlier Registration Worked perfectly:

```
Array
(
    [cc] => 92
    [in] => 12334
    [lg] => en
    [lc] => PK
    [id] => >zv?+?????w!l?v?5b?
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3582
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)

There was a problem trying to request the code.
```

Please guide!!

**Comment by mgp25** [comment]
@kadnan register again using only `registerTool.php`. Once you get the password try logging in again with the password and login provided by the script.

If after doing this you still get `rx    <not-authorized></not-authorized>`

Try `blockChecker.php` and if it says `blocked` then you number is blocked
Regards

**Comment by kadnan** [comment]
@mgp25 blockchecker is giving same error I dumped above.

**Comment by kadnan** [comment]
@mgp25  Turned out that it was making multiple `id` files this got mad. It should give a proper message like *Duplicate Id file*, something like that. I removed all files, it then prompted me to enter either `sms` or `voice`- Otherwise it does not
