### ISSUE TITLE
Problema al enviar mensajes

### ISSUE THREAD

**Issue by XaiNo** [mgp25/Chat-API#1786]
Hola buenas!
Estoy haciendo pruebas y cuando envío por ejemplo 10 veces el mismo mensajes a un número, a veces funciona sin problemas, pero tras varias ejecuciones me acaban bloqueando el número. Pensaba que era porque lo hacia muy seguido pero no tiene nada que ver porque a veces he tardado horas y lo bloquean igual.
Mirando la wiki he visto dos posibles motivos pero no sé si tienen que ver..
Uno es que no hago: while ($w->pollMessage()); 
No entiendo muy bien que hace el pollMessage ni cuando se rompe ese while.. Debo ponerlo?
Y otra posible razón que vi fue que lei en la wiki que hay que sincronizar los contactos con los que vas a hablar con: $w->sendSync($myContacts, null, 0); 
¿Tampoco entiendo muy bien si esto hay que hacerlo siempre o sea incluso para enviar un simple mensaje hay que hacerlo? También me parece raro porque yo no lo hago y algunas veces funciona pero a la tercera o cuarta vez bloquean el numero..
Pero en esto tengo varias dudas, no puedo sincronizar todos los contactos cada vez, no?
Tengo que llevar un control de que números ya están sincronizados? Me gustaría saber si hay alguna forma de hacerlo sin saber que números están o no registrados, ya que la idea es enviar mensajes a diferentes números y no voy a saber si hace un mes o incluso ayer ya había registrado ese número..

Salu2 y Gracias!

**Comment by XaiNo** [comment]
Por cierto lo que hago es simplemente:
 `$numeros = ... ; //Un array de numeros a los que enviar el mismo mensaje
$mensaje = "mensaje de prueba";

$num = 'xxxxxx';
password = 'yyyyyy';
$nickname = 'whatsApp';

$w = new WhatsProt($num, $nickname);
$w->connect();
$w->loginWithPassword($password);

foreach ($numeros as $numero) {
    $w->sendMessage($numero, $mensaje);

    // con esto me lo bloqueaba igual pero intente hacer pruebas 
    /*
    $w->pollMessage();
    $w->pollMessage();
    usleep(500000);
    */
}

$w->disconnect();`

**Comment by mgp25** [comment]
@XaiNo i understand your language (im from Spain) but most of the people here don't understand Spanish and maybe this can be useful to solve other issues from other people.

Im going to close this issue, open a new one and write it in English.

Regards
