### ISSUE TITLE
Performance Chat-API v3.2

### ISSUE THREAD

**Issue by vitawM** [mgp25/Chat-API#1787]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

* I use Chat-API for personal use (not commercial, not spam)
* Sending a maximum of 10-20 messages a day (answer to incoming messages only)

Any number which I register (number, which was not previously installed WA), is blocked after a few hours. It does not matter, I will send messages or just ping. It does not matter whether or not sync numbers, composing/paused text, changing online/offline statuses and etc...

But the two numbers that I registered over a month ago, are still working and do not get banned. And all numbers use the same code.

1. Do I understand correctly that the latest release (3.2) is not suitable for use now?
2. Should we hope that in the next release this will be fixed?
3. Can I use now https://github.com/tgalal/yowsup or there are the same problems?

Similar problem: #1770 

Thank you!

```
Booo!, Phone number XXX is disconnected!
Array
(
    [0] => Connection Closed! Phone: XXX
)
```

### Debug log
Post your debug log below:

```xml
rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by mgp25** [comment]
@vitawM If you dont post full debug log we cant help you + Chat API is more updated and more stable than yowsup.

Use latest release of Chat API code. Everything works perfectly + if you dont post full debug log and script code we cant help you.

Next release WA 2.0 implements new protocol. It's already done but no ETA yet.

Regards

**Comment by vitawM** [comment]
@mgp25 thanks for the answer.

I use latest stable version by tag. It's 3.2. Or need use code from master?
I suspect that you are testing an old phone number, so you are all ok. Did you try to test a new number (which has not been previously registered in WA from Chat-API)? In the old number at me too all ok! Blocked only the new numbers.

I've tried various combinations of code, simulate real user behavior.
Now I use this code:

```
$w = new WhatsProt(
        $this->userWhatsApp['phone_number'],
        $this->userWhatsApp['name'],
        true,
        false,
        Config::get('dirs.static.whatsapp')
);

$events = new MyEvents($w);  // My class with events. Just write data to database on event fire
$events->setEventsToListenFor($events->activeEvents);

$w->setAutoRead(false);

$w->connect();
$w->loginWithPassword($this->userWhatsApp['password']);

$w->sendGetServerProperties();
$w->sendOfflineStatus();

while(true)
{
        $w->pollMessage();

        $msg = RabbitMQ::main()->getMessage($this->apiBotQueue);

        if (empty($msg))
        {
             continue;
        }

        ...

        // In this function send sync and subscribe and wait OK response.
        if (!$this->existsAndNotBlocked($recipient['phone_number']))
        {
            continue;
        }

        $w->sendActiveStatus();

        usleep(100000);

       $unreadMessages = DB::main()->messenger->message->getUnreadMessagesInDialog($fromUserWhatsApp['user_id'], $this->userWhatsApp['user_id']);

       ...

       $w->sendMessageRead($recipient['phone_number'], $ids);

       $w->sendMessageComposing($recipient['phone_number']);

        usleep(rand(100000, 2000000));

        if (rand(1,2) == 1)
        {
            $w->sendMessagePaused($recipient['phone_number']);
        }

        $w->requestProfileStatus($recipient['phone_number']);
        $w->requestProfilePicture($recipient['phone_number']);

        $w->sendMessage($recipient['phone_number'], $message);

        usleep(rand(100000, 300000));

        $w->sendOfflineStatus();
}

```

and big debug (approximately 48-72 hours online):

[nohup.txt](https://github.com/mgp25/Chat-API/files/203208/nohup.txt)

**Comment by mgp25** [comment]
If you receive this:

```xml
rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>
```

It's okay, sometimes it happens.

If you get this:

```xml
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

Means blocked or wrong password.

If your script is going to be inactive for long time, instead of sending pings its better to disconnect. To check if your number is blocked try `blockChecker.php` (the number must be registered with `registerTool.php` in order to work.

Why do you request profile image twice?

```

        $w->requestProfileStatus($recipient['phone_number']);
        $w->requestProfilePicture($recipient['phone_number']);
```

And i dont like the idea of you taking number from a database, it seems something commercial, i dont know, anyway there are a lot of mistakes and missing things. Check wiki and answered issues, you will find examples

Regards

**Comment by samuelg78** [comment]
@vitawM  Have you managed to solve the issue?
