### ISSUE TITLE
Blocking Problems

### ISSUE THREAD

**Issue by XaiNo** [mgp25/Chat-API#1788]
- [x]  You are using PHP > 5.6
- [x]  You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x]  You have checked if someone has already asked the same issue you have.
- [x]  You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x]  You are using latest Chat API code.

Hey there! I'm doing some tests. So, it sometimes works when I send the same message 10 times to the same number, but eventually after many ejecutions the number ends up blocked. I thought it was because they were all sent at the same time, so I tried sending them at different times each; but the number ends up being blocked anyway.
I didn't know why; so I looked up the reasons on wiki and I've found two possible solutions:

in the first one I don't include: while ($w->pollMessage()); 
i don't quite understand what PollMessage does neither do I understand when does that 'While' break... should I include it?

the other possible solution claims that you have to sync the numbers you're sending the messages to with:  $w->sendSync($myContacts, null, 0); 

I'm not sure if you always have to do this? mainly because I don't usually do it and it works that way but at the third or fourth time they block the number. I'm not sure if I can sync all the numbers.

Do I have to keep track of which numbers are already synced?

I would like to know if there's any way to do it without knowing which numbers are or aren't registered; since the point is sending different messages to different numbers and it's quite difficult to keep track of which numbers I have registered...

Kind regards

(Pda. en Español: Espero que se entienda más o menos..)

**Comment by XaiNo** [comment]
by the way, all I do is: 

```
$numeros = ... ; //Un array de numeros a los que enviar el mismo mensaje

$mensaje = "mensaje de prueba";
$num = "xxxxxx";
password = "yyyyyy";
$nickname = "whatsApp";

$w = new WhatsProt($num, $nickname);
$w->connect();
$w->loginWithPassword($password);

foreach ($numeros as $numero) {
    $w->sendMessage($numero, $mensaje);

    // con esto me lo bloqueaba igual pero intente hacer pruebas 
    /*
    $w->pollMessage();
    $w->pollMessage();
    usleep(500000);
    */
}
$w->disconnect();
```

**Comment by vitawM** [comment]
You are trying to send the same message to different numbers every half second. 99% you will blocked by WA server.

**Comment by mgp25** [comment]
@XaiNo there are a lot of mistakes there. Have you read the wiki?

First of all you need to sync the contact you are trying to send a message once. And you can't send the same message like that. WhatsApp has a way to detect if the number is a bot or a human, so the way you code the script is very important.

You aren't composing or pausing the conversation, not requesting profile or status either. I recommend you trying chatting with your personal phone number (remember to sync it, very important), and test with it, learn and when you are experienced enough, you can go for bigger things.

Also i recommend you to read the wiki, there a lot of useful information and examples there, like flows etc. All the question you have made are explained in the wiki, anyway...:

- Contacts must be synced only once:
```php
 $w->sendSync($newContacts); 
```

And if you want to do things properly, yes, you have to save contacts in a database to have a track of it.

- `pollMessages` is used to poll data from the socket.


Regards

**Comment by for2ne** [comment]
.
