### ISSUE TITLE
Is there a way to retrieve all contacts already synced?

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1790]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Nope, is not possible. All that info is stored in the device, in this case you should save all synced contacts in a database so you know who did you sync.

Regards
