### ISSUE TITLE
function unpadV2Plaintext($v2plaintext)

### ISSUE THREAD

**Issue by nucleux** [mgp25/Chat-API#1792]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ? not sure] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:

Hi,
Firstly, I want to thank you all for your contributions to ChatApi (https://github.com/mgp25/Chat-API).
As this is my first posting in github, pls bear with me...

i tried sending a msg
"**Arr** 7 7053 20-20 5474 20-20 1029 10-10 1026 10-10 1326 10-10 2613 10-10 6594 5-5 9594 5-5 7168 5-5 1956 5-5 1139 5-5 2019 5-5" without double quotes. and the message decrypt is 
"**rr** 7 7053 20-20 5474 20-20 1029 10-10 1026 10-10 1326 10-10 2613 10-10 6594 5-5 9594 5-5 7168 5-5 1956 5-5 1139 5-5 2019 5-5" .
the decrypt message had remove the first character 'A'

may i uncomment the lines in this function?
function unpadV2Plaintext($v2plaintext)
{
  //  if (strlen($v2plaintext) < 128) {
     //   return substr($v2plaintext, 2, -1);
  //  } else {
        return substr($v2plaintext, 3, -1);
   // }
}

### Debug log
Post your debug log below:

```xml
rx  <message from="xxxxxxxxx@s.whatsapp.net" type="text" id="57CC6AB9D387123D6D" offline="0" t="1459856285" notify="ssss">
rx    <enc v="2" type="pkmsg">33089ba7f10712210561c7339455a8a2e31466d95138c971f1be4db2ddd3b0658c29eb4eddc4bb487f1a2105a5b19f84735793f4ff28c48b86fdc527b5f6b3878b8d4b1686cd7289221a2d6322c301330a2105a2cefc7f1605eee45d4309899e8fe3bd7b4f43f1c4641c21a6f290b19bd2455610201800229001d586490b0624b463ad1cf0236db059ddcbb2bc60761cca66f416b2f86c25c821901b6b4e5977fa9eb645cb132287307a501525ede4dd3e4332fb9d91d36cfbb29924719a903e2dbbbc1c1df3fa47a99debfa3e8afd8e2ee30db45a84ce43e8f560ca9eb4dd4aead1c5a32bbc37d5c6b96852bbe2e12e75c53dacb9afe87bda1f5695198522c40cc436fa997b60ab5089a2dbaf86cec78606289e4630b2ef03</enc>
rx  </message>
tx  <ack to="xxxxxxxxx@s.whatsapp.net" class="message" id="57CC6AB9D387123D6D" t="1459856285"></ack>

-> Decrypted Message: rr 7 7053 20-20 5474 20-20 1029 10-10 1026 10-10 1326 10-10 2613 10-10 6594 5-5 9594 5-5 7168 5-5 1956 5-5 1139 5-5 2019 5-5 tx  <receipt type="read" to="xxxxxxxxx@s.whatsapp.net" id="57CC6AB9D387123D6D" t="1459856285"></receipt>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>
rx  <presence from="xxxxxxxxx@s.whatsapp.net"></presence>
rx  <presence from="xxxxxxxxx@s.whatsapp.net"></presence>
rx  <ack from="xxxxxxxxx@s.whatsapp.net" class="receipt" type="read" id="57CC6AB9D387123D6D"></ack>
rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>
tx  <iq id="03" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="gcm" id="AGrIi_NI3ML:APA91b794PMjyt97BAhNbULnnwMrYECHOfOJ628xSesgFubM47YyhtG7dYcecocbjNMzfa_aq68j-H72QL8HAmxsp_6WVJ697oP_tVvDmSMvLTF_8_xb3iIQh4pIICcJPHa1narSm4lc"></config>
tx  </iq>
rx  <iq from="xxxxxxxxx@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>
rx  <iq from="s.whatsapp.net" type="result" id="03"></iq>

```

**Comment by mgp25** [comment]
@nucleux why you have commented that lines? Of course you have to uncomment that lines, dont modify the code we publish, its working fine

Regards

**Comment by nucleux** [comment]
Sorry I didn't make myself clear.
the decrypt message had remove the first character 'A'.
If I comment those lines it didn't remove the first character. Your original code decrypt the message removing the first character.
