### ISSUE TITLE
onGetDocument is it already implemented? 

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1793]
I added in AllEvents And MyEvents but nothing happens ...

Thanks

Make sure these boxes are checked before submitting your issue -- thank you!
- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Not in this release, it is ready in the next release

Regards
