### ISSUE TITLE
RegisterTool help

### ISSUE THREAD

**Issue by samuelg78** [mgp25/Chat-API#1794]
@mgp25 Hi.... i had read the wiki but dun really understand as this is first time i am using php and CLI tools. But i had installed the xampp and really loss how to get it started. Please guide me about how to get it work

![image](https://cloud.githubusercontent.com/assets/12243527/14291764/a8295360-fb97-11e5-8d2b-be64caa5dd9c.png)

**Comment by samuelg78** [comment]
@mgp25 .... Also take note that your chat-api-net and online WART for registration is not working anymore and i had got a few of my numbers blocked. Is this PHP working for registration?

**Comment by samuelg78** [comment]
@mgp25 I managed to run the CLI code but have this error:
![image](https://cloud.githubusercontent.com/assets/12243527/14292269/fa32a100-fb99-11e5-982c-6c151f43fb2d.png)

**Comment by samuelg78** [comment]
@mgp25 i had managed to run the CLI....but have this error after keying in my mobile number:
![image](https://cloud.githubusercontent.com/assets/12243527/14292321/387e0b02-fb9a-11e5-9279-38a8a73788b8.png)

**Comment by mgp25** [comment]
@samuelg78 use the `registerTool.php` without any modification otherwise it wont work

Regards
