### ISSUE TITLE
WA-Encryption -> Can't recieve Media Messages

### ISSUE THREAD

**Issue by TobiM93** [mgp25/Chat-API#1797]
@mgp25 
- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:

Media URL is now .enc  -> Can't display media anymore.
https://mmi487.whatsapp.net/d/XXXXXXXXXXXXXXXXXX-pdZSY60Yy23eG.enc

**Comment by mgp25** [comment]
@TobiM93 use event system, derypted image is decrypted correctly, you need to use event system, and decrypted image is `$file`

Regards

**Comment by luisaugustos** [comment]
i have the same issue, and i'm using `$file` parameter. 

but the saved image is broken...
```

rx  <message from="5547xxxxxxxxxxx@s.whatsapp.net" type="media" id="60DD40D56BA22384A7" t="1459913174" notify="Luis">
rx    <enc v="2" type="msg" mediatype="image"> 3011 byte data</enc>
rx  </message>


-> Decrypted Message: HEX:0a6a6874747073......

PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /xxxxxxxxxxx/app/lib/WhatsApi/src/handlers/MessageHandler.php on line 452

Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /xxxxxxxxxxx/app/lib/WhatsApi/src/handlers/MessageHandler.php on line 452
PHP Warning:  file_get_contents(https://mmi416.whatsapp.net/d/JjxkdvmS2inAP1BhdDGXtFcEgdY/As1U-4xabUNl9eqEai6dpHRM8RjomyfoHSCpu5WBlmKu.enc): failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /xxxxxxxxxxx/app/lib/WhatsApi/src/handlers/MessageHandler.php on line 452

Warning: file_get_contents(https://mmi416.whatsapp.net/d/JjxkdvmS2inAP1BhdDGXtFcEgdY/As1U-4xabUNl9eqEai6dpHRM8RjomyfoHSCpu5WBlmKu.enc): failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /xxxxxxxxxxx/app/lib/WhatsApi/src/handlers/MessageHandler.php on line 452
```

**Comment by mgp25** [comment]
@luisaugustos you dont need to use `file_get_contents`. `$file` contains already the image bytes, just place them in a file for the correct visualization of the image, there are other closed issues with the answer

Regards

**Comment by luisaugustos** [comment]
thank for your reply @mgp25 you are correct, but i didn't use `file_get_contents` the `MessageHandler.php` uses. And the error is at this point, the image byte in the `$file` does not work like a correct image,  can be related with the new Encryption released in last update?
