### ISSUE TITLE
Negative Coordinates when send location

### ISSUE THREAD

**Issue by barbierizimmermann** [mgp25/Chat-API#1799]
Hello, I'm trying to send messages with negative coordinates

`$lat = -18.59505;`
`$lng = -55.72059849999999;`
`$w->sendMessageLocation($target, $lat, $lng);`
or:
`$w->sendMessageLocation($target, '-18.59505', '-55.72059849999999');`

but the received message contain only positive numbers (the - is ignored). What to do for solution? Thank`s a lot for your API.

**Comment by vnay92** [comment]
Could you add the debug log?

**Comment by mgp25** [comment]
@barbierizimmermann it works perfectly, at least at my side:

```xml
tx  <message to="34123456789@s.whatsapp.net" type="media" id="065a1d54150251bedb4a02" t="1460190783" notify="John Doe">
tx    <media type="location" encoding="raw" latitude="-55.72059849999999" longitude="-18.59505" name="" url=""></media>
tx  </message>
```

If you still face issue, remember to post debug log
