### ISSUE TITLE
Is there a way to delete a broadcastlist?

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1800]
Make sure these boxes are checked before submitting your issue -- thank you!
- [ X ] You are using PHP > 5.6
- [ X ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ X ] You have checked if someone has already asked the same issue you have.
- [ X ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ X ] Is not a programming question.
- [ X ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```
For testing purposes I created 3 broadcastlists, one with 2 number, another with 3 and other with 4 numbers, using onGetBroadcastLists I get all of them, although, a realize that I don´t have any method to manage them.

How can I delete or edit those lists?

Many thanks!

**Comment by mgp25** [comment]
There is a function to the delete broadcast lists passing the list as an argument of the function

Regards
