### ISSUE TITLE
Different Ways to handle Exceptions 

### ISSUE THREAD

**Issue by raheelkhan** [mgp25/Chat-API#1802]
```
try {
    // Create a instance of WhatsProt class.
    $w = new WhatsProt($username, $nickname, $debug, $log);
    // Create a instance of Registration class.
    $r = new Registration($username, $debug);

    print("How would you like to receive confirmation code?  1 - SMS  2 - Voice ");
    $choice = fgets($handle);
    switch ($choice) {
        case 1:
        $return = $r->codeRequest('sms'); // could be 'voice'
        break;
        case 2: 
        $return = $r->codeRequest('voice');
        default:
        throw new Exception("Invalid Choice, Please run the script again \n");
        break;
    }

} catch (Exception $e) {
    print($e->getMessage(). "\n");
}
```

### Error
Post your error below:
Code already sent. Retry after 406 minutes.

How can i catch these errors and take necessary actions. Its throwing Exception in all cases. I want to let user enter the old code in this situation. Is it possible to throw different kinds of exceptions so that we can take appropriate actions. If you think it is good approach, please allow me to do so as i want to be a contributor also. Thanks

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Hi, thats a programming related question not API issue.

Regards
