### ISSUE TITLE
getData() error caused by "embedded" link (site or youtube)

### ISSUE THREAD

**Issue by xhippie** [mgp25/Chat-API#1803]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:

Whenever someone send a link that whatsapp automatically convert to this new format where it shows a small picture of the site or youtube vide, the API gets this socket error and therefore impacting the getData().

Ive simulated this behavior for a tons of times, and whenever i simulate it always crash. And keeps reconnecting for a while until it finally connects back.

**Comment by mgp25** [comment]
@xhippie can you post full error stack trace?

**Comment by xhippie** [comment]
@mgp25 
Sure.

Ive replaced a few sensitive informations, hopefully it will help.

-----
Error
-----

[] Logging in as 'XXXXXXXXXXXXXX' (XXXXXXXXXXXXXX)
tx  <stream:features></stream:features>

tx  <auth user="XX" mechanism="WAUTH-2">7fd94fe13535313139383139323933343393e4f77c36482e84ae7cededca40a0de49bea06731343630323339343231</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>27531d4870415739260c283ae9cf3e24e1e3faad</challenge>

tx  <response>694f6d8fef3a44a0913f66bdaf9c78d2e33be560fb3ee7978de88c447d974a18d2f55c2d483d1b63fe23bf8ddadbee0f8af06a7ee778e73c4a3d98c9c2df6a5c3dc3c5e8d6575a6d7ce364bb84e701</response>

rx  <success t="1460239421" props="5" kind="free" status="active" creation="1443801598" expiration="4444444444">f300f4856ce14be9a4b191ffbcda47a0a37c5abe</success>

tx  <presence name="XXXXXXXXXXXXXX" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

tx  <iq id="04" xmlns="w:b" type="get" to="s.whatsapp.net">
tx    <lists></lists>
tx  </iq>

[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX
[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX
[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX
[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX
[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX
[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX
[: 2016-04-09 19:03:42 :]=-- Syncing AND Subscribing with phone XXXXXXXXXXXXXX

[*] Connected to WhatsApp

rx  <message from="XXXXXXXXXXXXXX@g.us" type="text" id="B5736C84B994B631CF" participant="XXXXXXXXXXXXXX@s.whatsapp.net" offline="3" t="1460239294" notify="Leo">
rx    <enc mediatype="url" count="1" type="msg" v="2"> 4963 byte data</enc>
rx  </message>

tx  <ack to="XXXXXXXXXXXXXX-XXXXXXXXXXXXXX@g.us" class="message" id="B5736C84B994B631CF" t="1460239294"></ack>


-> Decrypted Message: Received message with old counter: 2 0 - /home/zap/wa-bot/src/libaxolotl-php/SessionCipher.php - 238Message B5736C84B994B631CF could not be decrypted, sending retry.

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1460223232"></presence>

rx  <iq from="XXXXXXXXXXXXXX@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="05" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="gcm" id="ZZsUV_vbOEr:APA91b4Bu2PObmJUXjMIKRQx3k9cOidtaq0bwWSDO0wsSCD5n4HI4cogfA2btSwIWX4xLI_PVMOO-5PILccH3pOAT_D2EXyad1v_W8IljAM8ech_6_1VQh8kUihkhY7EcYrTt3OToB0B"></config>
tx  </iq>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1460233865"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1460239378"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="XXXXXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1460234545"></presence>

rx  <iq from="g.us" type="result" id="03">
rx    <groups>
rx      <group id="XXXXXXXXXXXXXX-XXXXXXXXXXXXXX" creator="XXXXXXXXXXXXXX@s.whatsapp.net" creation="1435145142" subject="XXXXXXXXXXXXXX" s_t="1460174527" s_o="XXXXXXXXXXXXXX@s.whatsapp.net">
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx      </group>
rx      <group id="XXXXXXXXXXXXXX-XXXXXXXXXXXXXX" creator="XXXXXXXXXXXXXX@s.whatsapp.net" creation="1458768516" subject="XXXXXXXXXXXXXX" s_t="1458768516" s_o="XXXXXXXXXXXXXX@s.whatsapp.net">
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net"></participant>
rx      </group>
rx      <group id="XXXXXXXXXXXXXX-XXXXXXXXXXXXXX" creator="XXXXXXXXXXXXXX@s.whatsapp.net" creation="1460083355" subject="TEST" s_t="1460123392" s_o="XXXXXXXXXXXXXX@s.whatsapp.net">
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net"></participant>
rx      </group>
rx      <group id="XXXXXXXXXXXXXX-XXXXXXXXXXXXXX" creator="XXXXXXXXXXXXXX@s.whatsapp.net" creation="1457115941" subject="Bot_Dev_Group" s_t="1459015552" s_o="XXXXXXXXXXXXXX@s.whatsapp.net">
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="XXXXXXXXXXXXXX@s.whatsapp.net" type="admin"></participant>
rx      </group>
rx    </groups>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <lists></lists>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="05"></iq>



You can also write and send messages to XXXXXXXXXXXXXX-XXXXXXXXXXXXXX (interactive conversation)

> PHP Fatal error:  Call to a member function getData() on null in /home/zap/wa-bot/main/bot_latest.php on line 111

Fatal error: Call to a member function getData() on null in /home/zap/wa-bot/main/bot_latest.php on line 111


------ 
Lines 109 to 115, as referred above.

		foreach ($msgs as $m)
		{
			if(is_null($m->getChild("body")->getData()))
			{
				$body = $m->getChild("body")->getData();
			}
		}

**Comment by mgp25** [comment]
@xhippie is not API issue, but the example is quite outdated. Do you know what `getChild` and `getData` does? There's the problem, i mean, you are not getting any nody with a `body` tag, so it will obviously get an error to try to get data on a tag that doesnt exist (null)

Use event system if you want to get the message data

Regards

**Comment by xhippie** [comment]
@mgp25 thanks.
