### ISSUE TITLE
Sim registration broken "no_routes"

### ISSUE THREAD

**Issue by jordynegen11** [mgp25/Chat-API#1806]
Registration is not working anymore since today. WART is not working anymore to...

### Error
Fail, no_routes

### Debug log
Array
(
    [cc] => 31
    [in] => 651436073
    [lg] => nl
    [lc] => NL
    [id] => �w4?v�x�w�j��gl@
    [token] => jm8r7WaXKgDOdtmQQgu/h61hhEY=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 7588
    [rchash] => 2b4d17f0abe4f27c3b826e2cefc1feb98bd73ec82d85ff26e42c84047afea43e
    [anhash] => 9a5d48f8d473b922114433d92e6b6829
    [extexist] => 1
    [extstate] => 1
    [mcc] => 204
    [mnc] => 000
    [sim_mcc] => 204
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
    [sms_wait] => 3600
    [voice_wait] => 3600
)

**Comment by bgani** [comment]
mgp25, explain please what means "No cell routes for your number caused by your operator"

**Comment by jordynegen11** [comment]
It is not working for 6 other working numbers too @bgani ...

**Comment by mgp25** [comment]
@jordynegen11 @bgani virtual phone number are not supported by the API or your IP is flagged. Registration works perfectly

Regards

**Comment by jordynegen11** [comment]
I'm not using a virtual phone number @mgp25. Just bought a new sim card....

**Comment by KSas** [comment]
You must also take an IP address from your country.

On my VPS in Switzerland, this also does not work (same error), only with my Raspberry at home with my real IP. Open proxies are also blocked.

Otherwise use WART.

**Comment by DarkSlayerK** [comment]
I have the same problem, same result, I cannot register number 1 week ago.
