### ISSUE TITLE
WA PW extractor password incorrect

### ISSUE THREAD

**Issue by samuelg78** [mgp25/Chat-API#1810]
Hi, WA PW extractor password extracted is incorrect.

**Comment by mgp25** [comment]
@samuelg78 its an outdated application.

Regards

**Comment by jonathan-r** [comment]
Is there a solution to extract the password ?  
I tried the two solutions for Android from [the wiki](https://github.com/mgp25/Chat-API/wiki/Extracting-password-from-device), and both failed :
* With the app, it says that it does not have root access
* The result of the bash method seems incorrect (LoginFailureException when used)

**Comment by KSas** [comment]
The app does not work, perhaps outdated.?

The PHP script `exampleRegister.php` working fine. Attempts maybe another IP, you could be listed.
Use `blockChecker.php` to see if the number is blocked. LoginFailureException is a signs for this or an incorrect password.

**Comment by samuelg78** [comment]
@KSas ...i encountered the following error:

![image](https://cloud.githubusercontent.com/assets/12243527/14420897/2bf941ba-0001-11e6-8652-65d75b87d101.png)

**Comment by KSas** [comment]
Delete the identity (located in `src/wadata/id.[phonenumber].dat`) and create a new with `registerTool.php`

**Comment by samuelg78** [comment]
@KSas Hi, can you please verify that this registertool.php is really working? I had tried to register my number but the password given is incorrect. I had also got 5 of my numbers been blocked using WART and online WART. Whenever i tried  to ask for help, i was adviced to use this and that but ended up all my numbers been blocked. Your help will be greatly appreciated.

**Comment by mgp25** [comment]
@samuelg78 you are checking credentials, remove your identity and try again.

Also those error happens because the exception needs to be caught.

Regards

**Comment by samuelg78** [comment]
@mgp25 ... I had already deleted (located in src/wadata/id.[phonenumber].dat) files. So do i need to register new number before i use blockchecker.php? Or can i use blockchecker.php to check on the status of my registered number used currently in my iphone?

**Comment by mgp25** [comment]
@samuelg78 `blockChecker.php` is for already registered. If you try a number with register tool and its blocked it will also output that.

**Comment by samuelg78** [comment]
Cos if i use it to check on the status of my current number in my iphone, it return the following error:

![image](https://cloud.githubusercontent.com/assets/12243527/14436537/bd00e890-004f-11e6-9b7b-b04b04daf174.png)

**Comment by samuelg78** [comment]
@mgp25  This number is running fine in my iphone....but have this error.

**Comment by mgp25** [comment]
@samuelg78 as said before, you need to delete your identity. It should as you a method type.

And those errors are just uncatched exceptions

Regards

**Comment by samuelg78** [comment]
@mgp25 i had already deleted the file id.6592458686.dat..... then i encountered this error. Am i missing something?

**Comment by mgp25** [comment]
@samuelg78 use `registerTool` for registering the number, not `blockChecker`

**Comment by samuelg78** [comment]
@mgp25 So are you saying that if the number is not registered using registerTool, it will throw the error  if i use blockChecker? Cos i am using blockChecker to check on number not registered using registerTool

**Comment by KSas** [comment]
ToDo:

1. Delete all identify
2. use `registerTool.php` to register you number.
3. write you number down, use SMS to verify
4. enter the code from the SMS you received
5. the script show you username as secret
