### ISSUE TITLE
How can I decrypted audio message

### ISSUE THREAD

**Issue by ruchal** [mgp25/Chat-API#1815]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:
   I can't get the tag named url for audio message? I can't download the audio file. help for me please. thanks very much!

### Debug log
Post your debug log below:
I get the response Object below:

ProtocolNode Object ( [tag:ProtocolNode:private] => message [attributeHash:ProtocolNode:private] => Array ( [from] => 8613632636380@s.whatsapp.net [type] => media [id] => 61CB2D6A2E4196C17B146C966A9287 [offline] => 2 [t] => 1460340128 [notify] => 谭木亮 ) [children:ProtocolNode:private] => Array ( [0] => ProtocolNode Object ( [tag:ProtocolNode:private] => enc [attributeHash:ProtocolNode:private] => Array ( [v] => 2 [type] => msg [count] => 1 [mediatype] => audio ) [children:ProtocolNode:private] => [data:ProtocolNode:private] => 3 !%p]����zu%�Sf&9����{�< H�'�VA"�ȶ�M����!p��tI�#�p�n�h��$����q��M�5����{M8�t�C�&3j�l�C���ȉ�X�o쨛�Cܶ���|������ �o<��M)BU�\�y��+� ]9����� U櫴j��������d�lÛ0g��r��!�q����X���ƀ�K����D�߃��G�u&�~x���_.���cv����Đ�F�~�w ) ) [data:ProtocolNode:private] => ) 

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Is not added in the code, wait for the next Chat API release

Regards

**Comment by ruchal** [comment]
Thank you very much.
