### ISSUE TITLE
Class ProcessNode not found

### ISSUE THREAD

**Issue by nicktan147** [mgp25/Chat-API#1817]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
I have this error when trying to execute the code. It successfully sent out the message but this error keep poping out each time I send message

PHP Fatal error:  Class 'ProcessNode' not found in /var/www/html/somedomain/whatsapp/Chat-API/examples/exampleFunctional.php on line 113
PHP Stack trace:
PHP   1. {main}() /var/www/html/somedomain/whatsapp/Chat-API/examples/exampleFunctional.php:0

**Comment by mgp25** [comment]
Some of the examples are quite outdated, make sure you have latest code. If you are using latest code try to make a script from zero, ill update all examples for the next Chat API release

Regards
