### ISSUE TITLE
I think there should be a warning in the docs telling you could get banned from Whatsapp

### ISSUE THREAD

**Issue by williamoliveira** [mgp25/Chat-API#1818]
I just got my number banned from Whatsapp just by trying to register using this API for the first time.
I think there should be a warning somewhere in the docs of this repository to alert people you could get easily banned by using this, I would not have tried if I had saw one.
It is not a rant and I am not blaming this API as I should have read Whatsapps terms, but a warning in the docs would be good.

Thank you.

**Comment by ddfrreire** [comment]
"This code is in no way affiliated with, authorized, maintained, sponsored or endorsed by WhatsApp or any of its affiliates or subsidiaries. This is an independent and unofficial API. Use at your own risk.".
