### ISSUE TITLE
Can not send the image message

### ISSUE THREAD

**Issue by ruchal** [mgp25/Chat-API#1820]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

Can not send the image message. Send it but the whatsapp client doesn't received.

Thanks,Best Regards!

### Debug log
Post your debug log below:

   </p>tx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
tx&nbsp;&nbsp;&lt;auth user="86131*******" mechanism="WAUTH-2"&gt;fa6f60cd38363133313238383332363935756bb032440de216c23b4c52b0c1594e4f56df8031343630343331343832&lt;/auth&gt;<br /><br />
rx&nbsp;&nbsp;&lt;from s.whatsapp.net=""&gt;&lt;/from&gt;<br /><br />
rx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
rx&nbsp;&nbsp;&lt;challenge&gt;a17b062e2ab44ed939b9a3358d47b4066ffda690&lt;/challenge&gt;<br /><br />
tx&nbsp;&nbsp;&lt;response&gt;06fca6652923ad7b2dfca8c7cd0ab0458fd39c0b171245a12056364a0983cabf5e72b98bf5e16e76aab439f351a164719b311261e7a1152b32d8be2b35e511c19cc26e8173a8b980722d275eecc1a8&lt;/response&gt;<br /><br />
rx&nbsp;&nbsp;&lt;success t="1460431482" props="5" kind="free" status="active" creation="1460029604" expiration="4444444444"&gt;db7dbba8f69c4560274109fe0ae403aa54a63e4f&lt;/success&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence name="sz" type="available"&gt;&lt;/presence&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="01" xmlns="jabber:iq:privacy" type="get"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;query&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;list name="default"&gt;&lt;/list&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;/query&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config&gt;&lt;/config&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;
)
tx&nbsp;&nbsp;&lt;iq id="03" to="s.whatsapp.net" type="set" xmlns="w:m"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;media hash="OQ5fe4/qio+8oppHYpdDKh9xs+WvI5t0+WzKYADkUWg=" type="image" size="63155"&gt;&lt;/media&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;message from="86136*******@s.whatsapp.net" type="text" id="B4CCE7EF47BC957061" offline="1" t="1460431302" notify="tml"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;enc v="2" type="pkmsg" count="1"&gt;330897f0b7021221059d268bed152bbe8a2e63909eefc97efe81dd69d354956985928686e936196c2f1a21051f41b921012d4ec02fb7d6d62dd8660600b67a25324fe933bf175e7bddd4dc4c2242330a21059807337c063b6bf80e4a2856da33d5ca71b3fcfdb739885096f688b7be0f740f10011800221032831e5c8754ec1fe1a385aedd2ef8521bcd3e50a43c4865289a3c309bc001&lt;/enc&gt;<br />rx&nbsp;&nbsp;&lt;/message&gt;<br /><br />
tx&nbsp;&nbsp;&lt;ack to="86136*******@s.whatsapp.net" class="message" id="B4CCE7EF47BC957061" t="1460431302"&gt;&lt;/ack&gt;<br /><br />

-> Decrypted Message: HEX:e78eafe5a283

tx&nbsp;&nbsp;&lt;receipt type="read" to="86136*******@s.whatsapp.net" id="B4CCE7EF47BC957061" t="1460431302"&gt;&lt;/receipt&gt;<br /><br />
rx&nbsp;&nbsp;&lt;message from="86136*******@s.whatsapp.net" type="text" id="B4CCE7EF47BC957061" offline="0" t="1460431303" notify="tml"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;enc v="2" type="pkmsg" count="1"&gt;330897f0b7021221059d268bed152bbe8a2e63909eefc97efe81dd69d354956985928686e936196c2f1a21051f41b921012d4ec02fb7d6d62dd8660600b67a25324fe933bf175e7bddd4dc4c2242330a21059807337c063b6bf80e4a2856da33d5ca71b3fcfdb739885096f688b7be0f740f100218002210f79a943bd05f71cf37fd544811aef5d39664a991fc5d9047289a3c309bc001&lt;/enc&gt;<br />rx&nbsp;&nbsp;&lt;/message&gt;<br /><br />
tx&nbsp;&nbsp;&lt;ack to="86136*******@s.whatsapp.net" class="message" id="B4CCE7EF47BC957061" t="1460431303"&gt;&lt;/ack&gt;<br /><br />

-> Decrypted Message: HEX:e78eafe5a283

tx&nbsp;&nbsp;&lt;receipt type="read" to="86136*******@s.whatsapp.net" id="B4CCE7EF47BC957061" t="1460431303"&gt;&lt;/receipt&gt;<br /><br />
rx&nbsp;&nbsp;&lt;ib from="s.whatsapp.net"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;offline count="2"&gt;&lt;/offline&gt;<br />rx&nbsp;&nbsp;&lt;/ib&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="86131*******@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="86136*******@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;ack from="86136*******@s.whatsapp.net" class="receipt" type="read" id="B4CCE7EF47BC957061"&gt;&lt;/ack&gt;<br /><br />
rx&nbsp;&nbsp;&lt;ack from="86136*******@s.whatsapp.net" class="receipt" type="read" id="B4CCE7EF47BC957061"&gt;&lt;/ack&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="s.whatsapp.net" type="error" id="02"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;error code="404" text="item-not-found"&gt;&lt;/error&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="04" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config platform="gcm" id="tcOu5_KGGXQ:APA91bwCp3gil4XBmYsHK3r2WLhQqQBZSNFCFMJ6MUEgOrZYuzyZaSuXP76WT7AYOSYtvh_Uyf05-cZ3CwHC6HWhZ_RtRs8fi4c_0wvbgjZt2zh_o_tZNo9DG3sYl1P49R3w3m9nDpGj"&gt;&lt;/config&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="86131*******@s.whatsapp.net" type="error" id="1"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;error code="404" text="item-not-found"&gt;&lt;/error&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="s.whatsapp.net" type="result" id="03"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;duplicate url="https://mmi338.whatsapp.net/d/AuSZ51SBzNfOM_8ji0K-y9FQXFLOvYZrzlUPawp342Ld.jpg" size="63155" mimetype="image/jpeg" filehash="OQ5fe4/qio+8oppHYpdDKh9xs+WvI5t0+WzKYADkUWg=" type="image" width="685" height="474"&gt;&lt;/duplicate&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;message to="86136*******@s.whatsapp.net" type="media" id="067f4fd6da581a9732e2fb" t="1460431483" notify="sz"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;media type="image" url="https://mmi338.whatsapp.net/d/AuSZ51SBzNfOM_8ji0K-y9FQXFLOvYZrzlUPawp342Ld.jpg" encoding="raw" file="AuSZ51SBzNfOM_8ji0K-y9FQXFLOvYZrzlUPawp342Ld.jpg" size="63155"&gt; 3468 byte data&lt;/media&gt;<br />tx&nbsp;&nbsp;&lt;/message&gt;<br /><br />

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
@ruchal sending encrypted media is available in the next Chat API release. Next time quote debug log properly

Regards
