### ISSUE TITLE
Set socket unblocking

### ISSUE THREAD

**Issue by BjHelm** [mgp25/Chat-API#1821]
Good morning,

I have a problem recieving and and sending messages.
I'm trying to open a connection to WhatsApp-Server to listen to incoming messages.
```php
$w = new WhatsProt($Number['iNumber'],$Nummer['sName'],1,1);   
if($w->connect())
  {
    try{
      $w->loginWithPassword($Number['sPW']);     
      while($w->pollMessage()){}
      $w->disconnect();
    } catch (Exception $ex) {
      $fail[]=$ex;
      pre($ex);
      continue;
    } 
  }
```
If i use pollMessage without while loop the socket is closed immediately but using the while loop blocks the following code and I'm not able to send messages while polling.
Is there any possiblity sending and listing on the socket at the same time?
I want to use the connection for realtime interactions.

Reegards

**Comment by KSas** [comment]
In this example, no message will be sent, call `sendMessage(contact, message);`

Polling returns false if there is nothing more to do. When false is returned the while loop is ended and sending the message, followed by PollMessage again enough or it will not send this!

**Comment by anativ** [comment]
Just do a simple while true loop

```php

while (true) {
  $w->pollMessage();
  // Send messages or do what ever you want
}

**Comment by mgp25** [comment]
Hi, thats a programming question not API issue.

Regards
