### ISSUE TITLE
on registration for new number 

### ISSUE THREAD

**Issue by softcode2** [mgp25/Chat-API#1823]
@mgp25 
- [yes] You are using PHP > 5.6
- [yes] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [yes] You have checked if someone has already asked the same issue you have.
- [yes] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [yes] Is not a programming question.
- [yes] You are using latest Chat API code.

### Error

i tried to register new number using "registerTool.php"
i got SMS
but when i put the password (6 Digit) on " $w->codeRegister('HERE');"

its showing blank page with out debug log and $debug already its true !
$debug = true;

number is working and registered , but hash password not appearing on page .

please hekp me about this , i did not doing any changes on files 
just now downloading the last version .
 

Regards

**Comment by KSas** [comment]
Use this on the console, without any http Server like Apache or nginx. Only CGI.
