### ISSUE TITLE
Unable to get the password.

### ISSUE THREAD

**Issue by wauser** [mgp25/Chat-API#1825]
Make sure these boxes are checked before submitting your issue -- thank you!

- [YES ] You are using PHP > 5.6
- [ YES ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [YES  ] You have checked if someone has already asked the same issue you have.
- [ YES ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ YES ] Is not a programming question.
- [ ]YES  You are using latest Chat API code.

### Error
@mgp25 
I am using the latest Chat-Api my problem is I got the registration code successfully. But when using the codeRequest('123456'); I got no response i.e I am unable to get the hashed password to be used with the api. I have already deleted the id and all the things but to no avail. Kindly give me some reason for this behavior. The number is successfully added to whatsapp as It shows me in my mobile in contacts. I only need the hashed password to be used by API. I cannot use resetTool.php as it also required the hashed password. Please guide.

Note : We used terminal for this purpose, as I searched through the wiki and closed issues that this problem was solved using terminal/cli, but for me its not.

Thanks and regards.
### Debug log
Post your debug log below:

This is my debug log for registration. And got no debug log when requesting code.
```Array
(
    [cc] => xxx
    [in] => xxxxxxxxx
    [lg] => en
    [lc] => xx
    [id] => fr0r←fkkπÅ▲▒)¥Ω¡=Φ↑Ö
    [token] => 8LcumrMuRzDb+XgpjwiGFpKFEGE=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3933
    [rchash] => 8e53c7d11d97f7c94db2b8f71563f03349df46d5

    [anhash] => cdd279de4b1fce81ba2ef465dea587df
    [extexist] => 1
    [extstate] => 1
    [mcc] => 422
    [mnc] => 000
    [sim_mcc] => 422
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 65
    [sms_wait] => 65
    [voice_wait] => 65
)

**Comment by softcode2** [comment]
same issue with me

**Comment by david6055my** [comment]
I'm having issue as well. Using chatapi 3.2

stdClass Object ( [status] => fail [reason] => no_routes [retry_after] => 3600 [sms_wait] => 3600 [voice_wait] => 3600 )

**Comment by michaelradhuber** [comment]
Everything was working perfectly until yesterday. Getting login not authorized message now. Can somebody else confirm that the Chat-API is working for him as of this moment?

**Comment by SudoHenk** [comment]
Works fine here, tested about an hout ago.

**Comment by wauser** [comment]
@michaelradhuber 
Yes it was also happening to me that my number first registered on whatsapp than blocked without doing any activity.

**Comment by michaelradhuber** [comment]
Thanks. I got blocked overnight, although my script was offline. Seems they cleared some accounts :-(

**Comment by wauser** [comment]
@SudoHenk
Can you be kind enough to share with us your code?

**Comment by softcode2** [comment]
i got whatsapp code by sms but when i try to active it by : 
$w->codeRegister('XXXXXX');

no thing came just blank 

i am using ssh,terminal,CGI 

also i am used latest version .

**Comment by michaelradhuber** [comment]
Go for the RegisterTool.php. Works better.

**Comment by wauser** [comment]
Yes I am also going to use RegisterTool.php. Thank

**Comment by softcode2** [comment]
@michaelradhuber 

do you test it "RegisterTool.php" ?
because i have just 1 number to check 

other number is blocked

**Comment by hknckr** [comment]
Hi, 

it is also same here, I have got 5 numbers, they are not working anymore. I checked, numbers are not blocked, but it says the password is incorrect. I think whatsapp app changed something about password hash algorithm or something like that and now the previous working password is not valid anymore.

**Comment by michaelradhuber** [comment]
No I haven't checked it yet. Will do later. Just my experience from the past.

**Comment by softcode2** [comment]
also this tools cannot give hash password !
just it send sms .

http://watools.es/pwd.html 


so till now i think no source to get password because WART already not working .


Regards

**Comment by ottowayne** [comment]
Can confirm that I can't login since last night

Error without message thrown in
`#0 /.../whatsprot.class.php(286): Login->doLogin()`

**Comment by michaelradhuber** [comment]
@ottowayne Check if you got blocked with blockchecker.php

**Comment by KSas** [comment]
**watooles.es is no longer working, which is known for quite some time!**


`registerTool.php` works fine for me.

```Array
(
    [cc] => 49
    [in] => XXXXXXX
    [lg] => de
    [lc] => DE
    [id] => ▒ñe"▒`j▒▒▒(u▒▒=▒
    [token] => FjwRlMEqvcTM1BKf+LOF80npsO8=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3898
    [rchash] => 3121b5020af15a9c79ed2edbbd58f1c0ff17ee20c659f8ef39e6217aa5097f8f
    [anhash] => 8c8736dbd933b43cdaf860d68ccbe15f
    [extexist] => 1
    [extstate] => 1
    [mcc] => 262
    [mnc] => 000
    [sim_mcc] => 262
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 46805
    [sms_wait] => 46805
    [voice_wait] => 65
)
```

SMS come to my number, show image below.
![Screenshot](http://fs5.directupload.net/images/160413/zk5e33l8.png)

**Comment by hknckr** [comment]
Ksas I got sms this morning but the new password also didn't worked. Can you confirm that new password works on ChatApi ?

**Comment by SudoHenk** [comment]
I have used `registerTool.php` this morning, without problem (received SMS, after that the secret). I can also login, so not sure what is up with you guys but it's working fine here.

**Comment by KSas** [comment]
@hknckr Sorry, don't have a number here. My own personal number I do not want to use for this.

**Comment by mgp25** [comment]
Register works perfectly, use `registerTool.php` remember it's a cli tool so run it in cmd/shell/terminal. 

Regards

**Comment by mgp25** [comment]
For further help, paste here your numbers

**Comment by wauser** [comment]
@mgp25 
Yes RegiserTool.php is working good. Only use terminal and delete all data wadata frequently.
Thank you all for your help and support.
