### ISSUE TITLE
registerTool [status] => fail ; [reason] => old_version

### ISSUE THREAD

**Issue by MaSteve** [mgp25/Chat-API#1826]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X ] You are using PHP > 5.6
- [X ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X ] You have checked if someone has already asked the same issue you have.
- [ X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ X] Is not a programming question.
- [ X] You are using latest Chat API code.

### Error
Post your error below:

On a brand new VPS (with a brand new IP), I'm unable to register a **brand new** number. The following error occurs. Yes, I'm running latest Chat API code. And I'm able to reproduce the error on machines with different IPs.

### Debug log
Post your debug log below:

```xml
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 34xxxxxxxxx
Array
(
    [cc] => 34
    [in] => xxxxxxxxx
    [lg] => es
    [lc] => ES
    [id] => scc?a??mpw??p?^?
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 5824
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => old_version
)
There was a problem trying to request the code.
```

**Comment by KSas** [comment]
You're using an old version of WhatsApp. Change `Constants.php` to current WA-Version and try again.
