### ISSUE TITLE
issue deleting broadcasts

### ISSUE THREAD

**Issue by michaelradhuber** [mgp25/Chat-API#1827]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

Could you help me out please: I am trying to delete broadcast lists. 
`$this->w->sendDeleteBroadcastLists($listarray);
Where` $listarray `is either of type array, comma separated string (number), single string number.
I always get this output: 
```
tx  <iq id="0a" xmlns="w:b" type="set" to="s.whatsapp.net">
tx    <delete>
tx      <list id="1"></list>
tx    </delete>
tx  </iq
```

This is my array:

```
array(2) {
  [1]=>
  string(10) "1460557804"
  [2]=>
  string(10) "1460557596"
}
```

Here is the error log:
```
tx  <iq id="0a" xmlns="w:b" type="set" to="s.whatsapp.net">
tx    <delete>
tx      <list id=""></list>
tx      <list id=""></list>
tx    </delete>
tx  </iq>
```

```
Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363
```

`$listarray` dumps out fine, but is not parsed rightly in the function. Instea of a 9 digit number there is a single digit one in the id-identifier. Any clue as to why? 
Thanks!!!

**Comment by michaelradhuber** [comment]
@mgp25 
Could you help me out please: I am trying to delete broadcast lists. 
`$this->w->sendDeleteBroadcastLists($listarray);
Where` $listarray `is either of type array, comma separated string (number), single string number.
I always get this output: 
```
tx  <iq id="0a" xmlns="w:b" type="set" to="s.whatsapp.net">
tx    <delete>
tx      <list id="1"></list>
tx    </delete>
tx  </iq
```

`$listarray` dumps out fine, but is not parsed rightly in the function. Instea of a 9 digit number there is a single digit one in the id-identifier. Any clue as to why? 
Thanks!!!

**Comment by michaelradhuber** [comment]
This is my array:

```
array(2) {
  [1]=>
  string(10) "1460557804"
  [2]=>
  string(10) "1460557596"
}
```

Here is the error log:
tx  <iq id="0a" xmlns="w:b" type="set" to="s.whatsapp.net">
tx    <delete>
tx      <list id=""></list>
tx      <list id=""></list>
tx    </delete>
tx  </iq>


Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: array_fill(): Number of elements must be positive in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 349

Warning: array_map(): Argument #2 should be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

Warning: implode(): Argument must be an array in X:\inetpub\wwwroot\project\whatsapp\src\BinTreeNodeWriter.php on line 363

**Comment by KduOliva** [comment]
When i try to delete broadcaslist, my key stops working. I dave to regenerate de key. Is this have relation with this issue?

Tsk!

**Comment by 0xTryCatch** [comment]
No, that has no relation

**Comment by KduOliva** [comment]
Thank you,I will investigate further.

**Comment by mgp25** [comment]
Make sure your code is right, because the function its okay:

```php
  public function sendDeleteBroadcastLists($lists)
    {
        $msgId = $this->createIqId();
        $listNode = [];
        if ($lists != null && count($lists) > 0) {
            for ($i = 0; $i < count($lists); $i++) {
                $listNode[$i] = new ProtocolNode('list', ['id' => $lists[$i]], null, null);
            }
        } else {
            $listNode = null;
        }
        $deleteNode = new ProtocolNode('delete', null, $listNode, null);
        $node = new ProtocolNode('iq',
            [
                'id'    => $msgId,
                'xmlns' => 'w:b',
                'type'  => 'set',
                'to'    => Constants::WHATSAPP_SERVER,
            ], [$deleteNode], null);

        $this->sendNode($node);
    }
```

Regards

**Comment by KduOliva** [comment]
Can u give me a quick tip?

What is the best way to constantly monitore incomming mesages?

Continualy connect -> login -> pool

OR

connect -> login --> continualy pool ?



Sent from my iPad

On 23 de mai de 2016, at 13:39, mgp25 <notifications@github.com<mailto:notifications@github.com>> wrote:


Make sure your code is right, because the function its okay:

  public function sendDeleteBroadcastLists($lists)
    {
        $msgId = $this->createIqId();
        $listNode = [];
        if ($lists != null && count($lists) > 0) {
            for ($i = 0; $i < count($lists); $i++) {
                $listNode[$i] = new ProtocolNode('list', ['id' => $lists[$i]], null, null);
            }
        } else {
            $listNode = null;
        }
        $deleteNode = new ProtocolNode('delete', null, $listNode, null);
        $node = new ProtocolNode('iq',
            [
                'id'    => $msgId,
                'xmlns' => 'w:b',
                'type'  => 'set',
                'to'    => Constants::WHATSAPP_SERVER,
            ], [$deleteNode], null);

        $this->sendNode($node);
    }

Regards

-
