### ISSUE TITLE
reply msg too fast will be blocked ?

### ISSUE THREAD

**Issue by jackanie** [mgp25/Chat-API#1828]
Make sure these boxes are checked before submitting your issue -- thank you!

- [y] You are using PHP > 5.6
- [y] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [y] You have checked if someone has already asked the same issue you have.
- [y] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [y] Is not a programming question.
- [y] You are using latest Chat API code.

### Error
hi, the main function of my program is to receive messages,  processed and reply messages to sender. 
i have used delta sync when receive msg from a new contact,  composing or pausing text before sending,  but still be disconnected and blocked after running 12 hours. 
the sender usually get reply msg within 2 seconds after sending to the my program, is it maybe reply too fast? so the wa server judge it is a robot action. should i add sleep 10 seconds before reply in the program?
thank you for helping,  i have been blocked more than 8 nums within 2 weeks, and almost crazy about the blocking problem.

### code
`
//////////////////////////////////////////////////////////
    // login and listening 
//////////////////////////////////////////////////////////
    $w = new WhatsProt($username, $nickname, $debug);
    $w->setMessageStore(new SqliteMessageStore($username));

    $events = new MyEvents($w);
    $events->setEventsToListenFor($events->activeEvents); 

    $w->Connect();
    $w->LoginWithPassword($password);

	$loginType = "first_login"; //first_login / other_login	
	if($loginType == "first_login") 
	{	
		$w->sendGetServerProperties();
		$w->sendGetGroups(); // Get groups (participating)
		$w->sendGetBroadcastLists(); // Get broadcasts lists
		
		// Sync all contacts
		$allContacts = array('12345678');
		$w->sendSync($allContacts, null, 0); 
		
		// subscribe to the user
		$arrCount = count($allContacts);
		for($i = 0;$i < $arrCount;$i++)
		{
		  $w->sendPresenceSubscription($allContacts[$i]);
		}		
		$w->sendGetStatuses($allContacts);
		
		// preview profile picture of every contact
		for($i = 0;$i < $arrCount;$i++)
		{
		  $w->sendGetProfilePicture($allContacts[$i]); 
		}
	}
	else // Other Logins 
	{
		;
	}
		
	// listening msg
    while (true) 
	{
        $w->pollMessage();
    }

//////////////////////////////////////////////////////////
//  myEvents.php
//////////////////////////////////////////////////////////

	public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
	{
		// Get the number of the person you are sending the message
		$target = explode('@',$from); 
			
		if(count($target) > 0)
		{
			$replyNum = $target[0];
			$now = date("Y-m-d H:i:s",time());
			$dbh = new SQLite3(SiteConfig::DB_PATH);
			
			// if replyNum not in contacts then sync
			$sql = 'select count(*) from my_contacts where num ="'.$replyNum.'"';
			if ($dbh->querySingle($sql) == 0)
			{
				$this->whatsProt->sendSync($replyNum);
				
				// add new num into my_contacts table
				$sql = 'insert into my_contacts (num, name) VALUES (:num, :name)';
				$stmt = $dbh->prepare($sql);
				$stmt->bindValue(':num', $replyNum);
				$stmt->bindValue(':name', $name);
				$stmt->execute();
			}			
			
			// process and get Response data
			$replyMsg = "hello world.";
			
			// check msg has processed or not.
			$sql = 'select count(*) from msg_reply where id ="'.$id.'"';
			$count = $dbh->querySingle($sql);
			
			if ($count == 0)
			{
				// add new record into processed table
				$sql = 'insert into msg_reply (id, t, reply, status) VALUES (:id, :t, :reply, 0)';
				$stmt = $dbh->prepare($sql);
				$stmt->bindValue(':id', $id);
				$stmt->bindValue(':t', $now);
				$stmt->bindValue(':reply', $replyMsg);
				
				$stmt->execute();
				
				// reply upload details to the sender
				$this->whatsProt->sendMessageComposing($replyNum); // Send composing
				$this->whatsProt->sendMessagePaused($replyNum); // Send paused

                  //  should i add sleep(10000) here ???
				$this->whatsProt->sendMessage($replyNum, $replyMsg);				
			}
			else
			   echo "msg id [ ".$id." ] has been processed before\n";
		   
		   $dbh = null;
		}
	}

`

**Comment by mgp25** [comment]
code the behaviour thinking what a human would do.

Regards

**Comment by jackanie** [comment]
@mgp25 does you mean more message composing and paused should i add ?  though i donnt catch your point, thanks at all.

**Comment by Mega4alik** [comment]
@jackanie  Hi, could you resolve the problem? If so, share please

**Comment by jackanie** [comment]
sorry , not yet.


________________________________
发件人: Mega4alik <notifications@github.com>
发送时间: 2016年4月17日 15:15
收件人: mgp25/Chat-API
抄送: jackanie
主题: Re: [mgp25/Chat-API] reply msg too fast will be blocked ? (#1828)


@jackanie<https://github.com/jackanie> Hi, could you resolve the problem? If so, share please

―

**Comment by vnay92** [comment]
Here's what I do, I send `$this->whatsApi->sendMessageComposing($target);` and the i `sleep(2);` and then send the response message. Works fine for me!

**Comment by jackanie** [comment]
thank you very much , i will try in my code , then email you my testing result.


________________________________
发件人: Vinay Bharadwaj <notifications@github.com>
发送时间: 2016年4月17日 23:46
收件人: mgp25/Chat-API
抄送: jackanie
主题: Re: [mgp25/Chat-API] reply msg too fast will be blocked ? (#1828)


Here's what I do, I send $this->whatsApi->sendMessageComposing($target); and the i sleep(2); and then send the response message. Works fine for me!

―
