### ISSUE TITLE
error deleting contacts with sendSync

### ISSUE THREAD

**Issue by josemonino** [mgp25/Chat-API#1830]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x ] You are using latest Chat API code.

### Code
Im trying to deleting contacts with a simple code like this:

```xml
$target= 'xxx';
$targets= [$targets];
$w->sendSync(null, $targets, 3);
```

### Error
Im having the following error:

```xml
rx  <iq from="xxx@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_b5b66442-3fb7-4b10-ae56-061b09ca2bb2" last="true" wait="172665" version="1460557223531206">
rx      <invalid>
rx        <user>+</user> 
rx      </invalid>
rx    </sync>
rx  </iq>
```

And whats the meaning of wait="172665" param??

### Debug log
Seeing the log I can see the following:
```xml
tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="full" context="registration" sid="sync_sid_full_b5b66442-3fb7-4b10-ae56-061b09ca2bb2" index="0" last="true">
tx      <user>+</user>
tx      <user jid="xxx@s.whatsapp.net" type="delete"></user>
tx    </sync>
tx  </iq>
```

Where the API tx a <user>+</user> if we use sendSync(null, $targets, 3) without contacts to add in the first param.

Is possible that we need to add a condition in whatsprot.class.php in lines 1898-1905? https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L1898&L1905

```xml
$i = 0;
$users = [];
if (!is_null($numbers)) {
	if (!is_array($numbers)) {
		$numbers = [$numbers];
	}
	for ($i = 0; $i < count($numbers); $i++) { // number must start with '+' if international contact
		$users[$i] = new ProtocolNode('user', null, null, (substr($numbers[$i], 0, 1) != '+') ? ('+'.$numbers[$i]) : ($numbers[$i]));
	}
}
```

Thanks!

**Comment by mgp25** [comment]
@josemonino you dont need to remove synced contacts at the moment, this is also fixed in the next Chat API release (not released yet)

Regards
