### ISSUE TITLE
Sending messages does not work

### ISSUE THREAD

**Issue by pdocarmo** [mgp25/Chat-API#1831]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
No error in sendMessage but messages are not arrived on phone. 
I test send to iPhone and Android but don't work. 
I can receive messages normally.

### My cod

// Create a instance of WhastPort.
$w = new WhatsProt($number, $nickname, $debug);
 
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents); //You can also pass in your own array with a list of events to listen too instead.
 
$w->connect(); 
$w->loginWithPassword($password); // logging in with the password we got!
 
//$w->sendGetRequestLastSeen($contato);
$w->sendMessageComposing($contato); //Send composing
$w->sendMessagePaused($contato); //Send paused composig
sleep(1);
$w->sendMessage($contato, $msg);

 
$w->disconnect();

#####xml debug

5511xxxxxxxxx connected....

```
tx  <stream:features></stream:features>

tx  <auth user="5511xxxxxxxxx" mechanism="WAUTH-2">7c747368353531313934373437393638384a3b9e781170dc9d858c9f956fb5528e368fdb5d31343630353631353334</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>08e5a3e3f11841a12ef71c939bc91c5d783b0ce8</challenge>

tx  <response>c38dae5bf0f9324b1759dddc2e2a081eb7c31e033f94e8e091c3cc833643cd54f404365bacaf5e24ec48d3bfcf50e188a66362f0eafe7e5ea0b88a24c4aa4965a7f39786907d11496904f7714f9b53</response>

rx  <success t="1460561534" props="5" kind="free" status="active" creation="1460472307" expiration="4444444444">ecee9b81b8683a9c05d0b757fce2f521b76beb09</success>

tx  <presence name="Test" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <chatstate to="XXXXXXXXXX@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="XXXXXXXXX@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="5511xxxxxxxxx@s.whatsapp.net" type="text" id="ed5327da5e34de88e8544f" t="1460561536" notify="Test">
tx    <enc v="1" type="msg">330a210539175be6c90864df8e9c4ecd43c943b1186e607efe2d99f9d86f859bb27e715710031800221022e316e2a73f969afe37483977bd82f2c538223758f632c8</enc>
tx  </message>

Target: 5511xxxxxxxxx@s.whatsapp.net ---> Node: Array ( [tag] => body [attributeHash] => [children] => [data] => Test msg !)
```

 5511xxxxxxxxx Desconect

**Comment by mgp25** [comment]
Im going to explain you what are you doing if you have a phone:

You are typing a message, and at the very same time as you click send, you just set your phone in fire and its explodes, so there is no possible time it can arrive to the WA server, so now looking to your code. Do you think you give enoguth time the script so the message is sent correct and arrive WA server?

By the way, duplicate issue

Regards

**Comment by pdocarmo** [comment]
@mgp25, Thank you!!! Its working

**Comment by mgp25** [comment]
@pdocarmo you are welcome :smile: if you are new to this, check the examples and there is also some useful info in the wiki

Regards
