### ISSUE TITLE
as a document delivery ? PDF

### ISSUE THREAD

**Issue by JoaquinVautier** [mgp25/Chat-API#1833]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

$w->sendMessageDocument($to, $pdfFile); 

as I use this function ?

**Comment by KSas** [comment]
Not in the current release, the next release is coming...
