### ISSUE TITLE
Receive message problem

### ISSUE THREAD

**Issue by developerjayesh** [mgp25/Chat-API#1834]
I used the whatsapp api, all working perfect, but message receiving code not working. it return the encrypted data. I am not able to receive message from poll. so any solutions for incoming message received.

**Comment by ngethe** [comment]
here too

**Comment by developerjayesh** [comment]
Hello thanks for reply. any solutions for that issues

**Comment by mgp25** [comment]
Use event system. Duplicate issue + read wiki
