### ISSUE TITLE
Blocked numbers

### ISSUE THREAD

**Issue by rc855699** [mgp25/Chat-API#1835]
Hello,

We are a development team and use ChatAPI in order to notify the progress of our projects (no comercial nor spam use).
We've registered two numbers two months ago and everything went fine, we update the API with last changes and all goes smooth.
Now, a few days ago, we needed to register two more numbers because our team was grow up and we are working in several projects in parallel, but they were blocked by WhatsApp.
The registration process was fine as usual but as soon (minutes) as we start to send messages the numbers were blocked (the old ones remain in line and working fine).

Before send a message we always do a sendSync, that could be the reason for the blocks? Do you know for some changes WA is made these days which are affecting new registered numbers?

We are afraid to register more numbers, we don't want more blocks.

Please, could you see what could be happening?

Thank you very much for your time and greate work.

**Comment by SudoHenk** [comment]
Account created today, so possibly a secondary account. That is already pretty suspicious.

Anyway, don't rely on the API all days of the week. There might be moments where it cannot be used, you can easily use some other (free) push service which would be as simple as a HTTP Post call, which is much less work than integrating Chat-API.

**Comment by rc855699** [comment]
I created my account today because it was not necessary to post an issue before.
As I mention, I did not have problems with the ChatAPI.

I know we can use other methods to notify, but WhatsApp is perfect, everybody use it, is fast and everybody pay attention on it.

**Comment by mgp25** [comment]
@rc855699 no provided code or debug log = invalid issue. 

Regards
