### ISSUE TITLE
Loggin getting expired very frequenty - API issue?

### ISSUE THREAD

**Issue by ramizahsn** [mgp25/Chat-API#1839]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

I am keep getting Exception `Fatal error: Uncaught exception 'LoginFailureException'`. I know it's due to password is getting expired. On running `blockchecker` I get following:
```
Wrong identity. 
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 42610
    [voice_wait] => 0
)
```

### Debug log
Post your debug log below:
`[2016-04-15 06:34:51] [ERROR]: Blocked number or wrong password. Use blockChecker.php`
```xml

My question is, is ti some issue with the API or WhatsApp System. Why my client is being unregistered again and again. I request you to guide me.

**Comment by mands72** [comment]
Same happening here since about 2 or 3 days

**Comment by mgp25** [comment]
@ramizahsn actually you don't have the same identity as blockChecker says, so probably you have registered your number using any other tool, what i recommend is using `registerTool.php` in these cases.

Register it again using registerTool make sure to remove all related `.dat` files inside `wadata` folder before running `registerTool.php`

Regards

**Comment by ramizahsn** [comment]
>  actually you don't have the same identity as blockChecker says, so probably you have registered your number using any other tool,

huh? Can you please guide me how did you figure it out? I am not using any tool other than `registerTool.php` as I am using WhatsApp very first time and that's too for a project. Yes I did learn from issues to delete `.dat` files.

My question was, will asking for Registration in short span will block me? is this an API issue or at WhatsApp End.

**Comment by mgp25** [comment]
```
Wrong identity. 
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 42610
    [voice_wait] => 0
)
```

If you abuse registration, WA will block you

**Comment by ramizahsn** [comment]
>If you abuse registration, WA will block you

Thanks @mgp25 for explanation. May be registering in short span of time(within an hour) caused this. Not sure. @mands72 also experiencing it.

**Comment by mgp25** [comment]
@ramizahsn how many numbers are you registering every hour?

**Comment by mands72** [comment]
@ramizahsn I have been running on this API for weeks / months without issues and starting a few days ago my account got locked. Took another phone number for registration, lasted for about 24 hours and I got blocked again (I'm only sending about 5-10 messages a day). If this happens one more I have no more phone numbers for registration. But to delete the .dat files I have not tried before, will try that as @mpg25 suggested.

**Comment by ramizahsn** [comment]
@mgp25 I have only one number for testing and only once I registered more than one in an hour. Prior to that my number used same password for a day but as @mands72 said, I also having issue the login expiration after short span of time.

Do they also monitor IP address? should I reset my router before each register?

Unlike @mands72 I did know process of deleting .dat and other files in `wdata`
