### ISSUE TITLE
Number is blocked

### ISSUE THREAD

**Issue by CristianOspina** [mgp25/Chat-API#1840]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Number get blocked.

I know that is duplicated, that usually blocked by spam etc etc. but something is really happening out of the normal.

I've been more than one year using this API, and yes, sometimes I was blocked for not using it well (programming), but months ago I did not have any problem.

A day ago I get blocked, try to register a new account, it worked but in less than 4 hours would be blocked.

I change the IP from where my program was running and also I do not change anything from my program (was running perfect). Therefore I fail to understand why the block, I use the account to track status, nothing more.

I've seen several issues about this recently, which makes me think that Whatsapp has been blocking intentional numbers using this API, or somehow are realizing this.

I know that you cannot do much, but reviewing and testing would be something that would help. If you actually have things working with the API for long time without problem, it must be something else.

### Debug log
```xml
tx  <stream:features></stream:features>

tx  <auth user="XXXX1734XXXX" mechanism="WAUTH-2">09e66d9e3537333231373334303239
381053c8910efaa8432d0b08e6944910c73554774e31343630363936363431</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>716d2c37233f73156c99f5a5214e9e097f59043a</challenge>

tx  <response>7907778aa8494275cea862b477462aa31c7ddc6be8c232bfcda42b819b73f77bfd
4927cd39e71d0d7c8a369e07b37b395a0e441aa9f3a39ac0980a72d8d550dd7eb651f8af552106a5
a8ee092683</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by blecge68** [comment]
Have the same issue, Registration went successfull, but first sending failed. Running blockchecker showed than, that number is blocked.

**Comment by aal89** [comment]
I'm having the same problem right now, always used the API the correct way never had any problems (never even had a number blocked before). Until recently, I now have 4 numbers blocked all within the first couple of hours after the first login.

I think it has something to do with WA2.0 being enforced(?). Either way I'm getting more convinced every day that this isn't bad use of the API.

Anyway, how often and what numbers (all or just the new ones) do you guys sync?

**Comment by mgp25** [comment]
Remember to use `registerTool` other tools may fail.

Without full debug logs of the acitivity of the number, we cant determine why its blocked. WA 1.6 is still working fine, it has nothing to do with 2.0. If any of you want further support, post as much as info as you can of the previous acitivities of the number (**full** debug log)

**Comment by aal89** [comment]
I always have used the registerTool. 

Please reopen this issue as I will get a **full** debug log this weekend, I will register a new number then and check if it gets blocked again.

**Comment by rougejack** [comment]
@mgp25 I am not sure whether debug logs would help you in this case. The registration works fine, yet the number gets blocked few hours later (even if you have never connected/logged in even once after that. Even if you connect/login and do the contact syncing etc, but never have sent a message, the number gets blocked). I have a feeling that WA is somehow able to know when someone uses ChatAPI.

**Comment by mgp25** [comment]
Debug logs always helps. And of course WhatsApp knows when someone is using the API, the main point of the API is that you can use it for personal usage only, so i didn't code few things so its more easy to WhatsApp to detect API users, this way i make sure, people not using the API properly will be blocked.

**Comment by ludufre** [comment]
Same problem here. Already I bought three sim cards. After a few hours it starts to lock.

**Comment by mgp25** [comment]
Instead of saying `same problem` start giving data. How many numbers did you tried to register or post all debug logs (full debug logs) you have, otherwise this issue makes no sense

**Comment by frenton** [comment]
I figured out a couple of things regarding this issue:

Apparently it only affects numbers, that have been activated from the time WART stopped working (someday last week around April 8th) [https://github.com/mgp25/WART/issues/66](https://github.com/mgp25/WART/issues/66)

All numbers activated before that day around April 8th are still up and running.

Any number, which is activated using registerTool.php, seems to get blocked a couple of minutes/hours after activation. It does not matter, if you log in first or not. Even if you do not log in, the number gets blocked eventually after a short period of time.

I activated a number to clearify, what is happening: 
1. I was able to log in and use the API properly.
2. I changed profile photo and status, nothing else.
3. Number got blocked eventually after a few minutes.

Debug log of blocked number, which has been activated about 1 hour ago:

`tx  <stream:features></stream:features>

tx  <auth user="4915215784032" mechanism="WAUTH-2">c08814dd34393135323135373834303332ccfa6ff661b76d19dde255e47e402d4dd5a998c731343630373237383037</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b3d86f0ba5e55c3f193a3c819da48ac633887bca</challenge>

tx  <response>6412d745663b8ec8e43bcbc9222bad195102ad1dfe72d073a12416ffff9da2315d983d98582d6e481c1e9603569673cbcf638ef14d2526cd4aea0be233d335e7124258e165df3e6e514736f818a9b6</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
`

Result from blockChecker.php

`Wrong identity. 
Array
(
    [cc] => 49
    [in] => 15215784032
    [lg] => de
    [lc] => DE
    [id] => �5q�gަ7{��
2�@��g
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3019
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /opt/lampp/htdocs/www/chat-api/src/Registration.php:89
Stack trace:
#0 /opt/lampp/htdocs/www/chat-api/examples/blockChecker.php(36): Registration->checkCredentials()
#1 {main}
  thrown in /opt/lampp/htdocs/www/chat-api/src/Registration.php on line 89`

**Comment by frenton** [comment]
I figured out a couple of things regarding this issue: 

- Apparently it only affects numbers, that have been activated from the time WART stopped working (around April 8th). [https://github.com/mgp25/WART/issues/66](https://github.com/mgp25/WART/issues/66)

- All numbers activated before that day around April 8th are still active.

- If you activate a number using registerTool.php, it gets blocked after a couple of minutes/hours. It does not matter, if you login during that time or not.

I activated a number to clearify, what is happening:
1. Number activated using registerTool.php
2. Logged in using password, changed profile picture, updated status, nothing else.
3. Number got blocked a couple of minutes later

Debug logs:

`tx  <stream:features></stream:features>

tx  <auth user="xxx5215784xxx" mechanism="WAUTH-2">c08814dd34393135323135373834303332ccfa6ff661b76d19dde255e47e402d4dd5a998c731343630373237383037</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b3d86f0ba5e55c3f193a3c819da48ac633887bca</challenge>

tx  <response>6412d745663b8ec8e43bcbc9222bad195102ad1dfe72d073a12416ffff9da2315d983d98582d6e481c1e9603569673cbcf638ef14d2526cd4aea0be233d335e7124258e165df3e6e514736f818a9b6</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>`

Debug log using blockChecker.php on that number:

`Wrong identity. 
Array
(
    [cc] => 4x
    [in] => x5215784xxx
    [lg] => de
    [lc] => DE
    [id] => �5q�gަ7{��
2�@��g
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3019
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /opt/lampp/htdocs/www/chat-api/src/Registration.php:89
Stack trace:
#0 /opt/lampp/htdocs/www/chat-api/examples/blockChecker.php(36): Registration->checkCredentials()
#1 {main}
  thrown in /opt/lampp/htdocs/www/chat-api/src/Registration.php on line 89
`

**Comment by frenton** [comment]
I figured out a couple of things regarding this issue: 

- Apparently it only affects numbers, that have been activated from the time WART stopped working (around April 8th).

- All numbers activated before that day around April 8th are still active.

- If you activate a number using registerTool.php, it gets blocked after a couple of minutes/hours. It does not matter, if you login during that time or not.

I activated a number to clearify, what is happening:
1. Number activated using registerTool.php
2. Logged in using password, changed profile picture, updated status, nothing else.
3. Number got blocked a couple of minutes later

Debug logs:

[debug1.txt](https://github.com/mgp25/Chat-API/files/221152/debug1.txt)

Debug log using blockChecker.php on that number:

`Wrong identity. 
Array
(
    [cc] => 4x
    [in] => x5215784xxx
    [lg] => de
    [lc] => DE
    [id] => �5q�gަ7{��
2�@��g
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3019
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /opt/lampp/htdocs/www/chat-api/src/Registration.php:89
Stack trace:
#0 /opt/lampp/htdocs/www/chat-api/examples/blockChecker.php(36): Registration->checkCredentials()
#1 {main}
  thrown in /opt/lampp/htdocs/www/chat-api/src/Registration.php on line 89`

**Comment by 0xTryCatch** [comment]
Seriously, the number is not even blocked!

**Comment by elchobo5** [comment]
Hello all,

I think there is no doubt that something is happening. We are a lot of people that were working fine with the API and since some days ago we're experiencing blocked numbers.

Please Chat API team, did you register new numbers these days?

**Comment by rougejack** [comment]
@mgp25: Check this one - [log.txt](https://github.com/mgp25/Chat-API/files/221308/log.txt). For this number, I never connected/logged in even once after registration, and few hours later is was blocked :/

**Comment by CuBiC3D** [comment]
Registered new number yesterday with registerTool, didn't login until now.

``
tx  <stream:features></stream:features>

tx  <auth user="xxx" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>08bc46a60149d2a01882fec73b2c0d64f8e146ab</challenge>

tx  <response>0bff3d31cd4991da3459fdf9c2d634a60014fe6b4b4452008160451aed32e31693e400dbb79478b1ad7793585c4ce1b79b2330f426aeca8682535b68084e34b508f212eee6dae30882acf3b6dd04aa</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
``

Used WhatsAPI and Chat-API now for years without any problems or beeing blocked. Never sending or receiving messages, frequently updating and human like behavior(except for never sending any messages, but hey, there are lonely people outside :D). Only one number connected. Since April I got periodically my numbers banned. Yesterday was my 5. number, that I tried to register. After April numbers lasted for about 2-3 weeks until they got banned. Yesterday, like others said, bans come almost immediately.

There is not much space to make a mistake - after registering the number with registerTool, you are blocked at login. Can anyone confirm, that the same things happens after some time, if you login immediately after registering the number? Maybe the real client doesn't allow to wait?

**Comment by frenton** [comment]
I can confirm that. I registered a number today, logged in, changed status and it got blocked around 10-15min after registration.

**Comment by elchobo5** [comment]
What about not loggin the numbers? just in case they have to send a message and then disconnect?
that could work?

**Comment by CuBiC3D** [comment]
@frenton did you behave like wiki says? Got groups info, broadcasts, sync, subscribed to presence and profile pictures? That would be the interesting point for me. Logging in right after registration (I suspect a non native client detection here) **and** doing a correct first login.

@elchobo5 what do you mean by not loggin?

**Comment by elchobo5** [comment]
@CuBiC3D I mean, do not login the number, just register it and make the login just before to send a message and then make a logoff. This could be a workaround?

**Comment by CuBiC3D** [comment]
@elchobo5 This is exactly the case I described before. I did not login with the number right after register - it got blocked on first try next day. It happens on auth process - no sending messages happens there.

**Comment by blecge68** [comment]
@elchobo5 This is also i experienced. Registered a new number on day 1 using RegisterTool.php then i tried to send a message with php on day 2. Got the fatal error during login.php. Delay was caused due to missing pdo_sqlite extension. Then i used blockChecker.php and got the info that the number is blocked.

**Comment by elchobo5** [comment]
So? there is no workaround? the only thing we can do is just wait for the next Chat API version?

**Comment by CuBiC3D** [comment]
Thought it's clear, that nothing is clear right now. You can, but GitHub is more the collaboration thing, so try to find out and fix by pull request. Please keep related to the (unfortunately closed) issue.

**Comment by oscartorres** [comment]
Just another example here. I registered one number using registerTool. Worked fine for a few days. I've stopped working on it, so the whatsapp process was not started for - let's say a week. When I tried to connect and login, number was blocked. This happened around April 8th.

**Comment by ludufre** [comment]
Brought a new simcard. Received SMS code, when send instantly:
```[root@www examples]# php exampleRegister.php
Array
(
    [cc] => 55
    [in] => 2198310XXXX
    [lg] => pt
    [lc] => BR
    [id] => m▒b▒+▒m-▒▒oxy▒(h?▒
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3690
    [rchash] => dd78c5b5c03907a1f047b4b453360faf409688e3e5e915339ffe61adabb29e4d
    [anhash] => e9a169e2106f4f08017de409c62b4c64
    [extexist] => 1
    [extstate] => 1
    [code] => 679208
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)

Fatal error: Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp. Reason: blocked' in /root/Chat-API-master/src/Registration.php on line 181

Exception: An error occurred registering the registration code from WhatsApp. Reason: blocked in /root/Chat-API-master/src/Registration.php on line 181

Call Stack:
    0.0002     223376   1. {main}() /root/Chat-API-master/examples/exampleRegister.php:0
    0.0023     422712   2. Registration->codeRegister() /root/Chat-API-master/examples/exampleRegister.php:67```

**Comment by blecge68** [comment]
@all has anybody tried to register using the smartphone and getting the pw using mitmproxy ? and then sending messages / login ? If the number is registered within an official client, the number should not be blocked.

**Comment by CuBiC3D** [comment]
@blecge68 WhatsApp is pinning its SSL certificate and won't communicate with the server, if there is a different hash - or did something changed, that i missed? Would be nice if someone could test with a rooted android and extract the password. But I don't have much hope, because another agent identifier would be used to connect afterwards.

**Comment by mgp25** [comment]
Everybody calm down. If you are using this for personal usage i guess all you can wait. Im not publishing the new release which contains all the updates and features until it passes some time, i want to make sure all spammers are blocked

**Comment by elchobo5** [comment]
dear @mgp25 are you saying this is intentional? I can tell you several personal WhatsApp accounts are blocked, when I say personal is at them phones.

**Comment by edudesouza** [comment]
Are you releasing an official API?

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.33&pv=4.3&source=email_footer_2] On Fri, Apr 15, 2016 at 5:34 PM, mgp25 < notifications@github.com [notifications@github.com] > wrote:
Everybody calm down. If you are using this for personal usage i guess all you can wait. Im not publishing the new release which contains all the updates and features until it passes some time, i want to make sure all spammers are blocked

**Comment by cmeerw** [comment]
@mgp25 I would be interested in your WA20 branch as a developer as I
am working on LoquiIM (a browser-based XMPP/WhatsApp client
implemented entirely in Javascript) and would like to implement the
new protocol in LoquiIM... What do you think?

**Comment by roguejack** [comment]
I've given up. My last attempt was by registering the number through WA, extracting the password and trying to connect. But as I expected, login fails (blockChecker gives "Wrong Identity. status => fail, reason => incorrect).
For now, I'd suggest everyone to stop trying to register numbers through ChatAPI (or any other API).

@mgp25 +1 It's good that you are trying to discourage spammers. No hurry from us/me, just that some of us got disappointed with (now) banned numbers.

**Comment by mgp25** [comment]
@roguejack `wrong identity != blocked`, have you read the wiki on the technical explanations? 

If you can't login maybe its because the protocol wa 1.6 is getting outdated, i dont know since im using wa 2.0 since 1 month ago or so. The next release is quite stable and works pretty good although it still has some bug/glitches im trying to fix.

In the other hand, i know some of you use it for personal usage (i include myself in here), but like 80% of API user are spammers, thats why WhatsApp is always pushing us, last summer we got demmanded not because we have done this API but im pretty sure because of people using it in wrong ways, so know that i have an opportunity to stop people spamming, of course i'll do it. That's why im not releasing it yet, i hope you all understand the situation, also this gives me time to improve the API and when the time arrives i'll publish the API and it wont have any error.

Have a nice weekend

_mgp25_

**Comment by yniwly43** [comment]
Wouldn't spammers be blocked by WhatsApp's spam report tools? Aren't they banned anyways?
Why would banning users that haven't even logged in, not to mention even sent a message, assist in blocking more spammers? :)

**Comment by elchobo5** [comment]
@mgp25 when spammers are back, you're gonna do the same? I mean, we have to know that this situation will repeat in the future?

**Comment by ishaquehassan** [comment]
But @mgp25 , when the time will arrive.... actually its frustrating.... i am using this for "CHAT BOT" so it can send auto messages.... but few days ago i was blocked... but everything is working fine since FEB....
Can you tell me the expected time when it will be arrive

**Comment by mgp25** [comment]
@ishaquehassan any day from today to 2017

**Comment by eaba** [comment]
@mgp25 I like you, some how ;)

**Comment by schoerg** [comment]
@elchobo5

No sane person would use this API on their main phone number.

**Comment by yniwly43** [comment]
Weird, I could've sweared I wrote a comment here yesterday. I guess I didn't submit it.

May I ask: 
1. What exactly will prevent spammers from restarting their malicious service with the next code version, when you release it? It seems nothing, based on what you say.
2. Isn't the spam-report option that all WhatsApp users have when receiving spam messages the correct solution for spammers?
3. Why would the new code version change anything, anyways? I am pretty certain that the numbers being blocked are simply VOIP numbers or virtual SIM numbers, and that is the distinction between blocked and working. This makes sense, as obviously spammers use these kind of numbers and not real SIMs.. the new code probably won't change a thing as far as the blocking goes, and that is the way it should be.

It seems to me that if indeed your code fixes the issue for normal, personal users, then releasing it won't change anything for spammers, but will help personal users. It is your choice, of course :)

BTW, I've never received a Spam message in WhatsApp. Interesting.. Maybe I've been lucky? Didn't know it was so prevalent..

**Comment by blecge68** [comment]
@yniwly43 : I can't confirm that only Virtual Sim's are blocked. I used 2 real SIMs (prepaid) getting blocked both a view minutes or a day after using registration tool. I stopped burning sim cards now.

**Comment by softcode2** [comment]
Same problem here also .
New number registered using  (registerTool)
After sending msg number getting blocked directly. 

All old number it's still working on this API , just new number getting blocked :)

**Comment by mgp25** [comment]
@yniwly43 the sooner i release the new protocol the sooner can spammers use it, you know? And im not giving that pleasure to people relying on my API to make money

WhatsApp blocks with other spam detection in server-side.

Blocks are because of many reasons and it also affects how the user authenticate and register, it also affects legit numbers.

As i said in the previous comments, i'll release it when is strictly necessary.

**Comment by yniwly43** [comment]
I understand. And I support you in your fight against spammers.

Unfortunately, truly unfortunately, it seems that the spammers will just resume their previous activities as soon as you release your new version, in a few months. Probably nothing will change.
So, this is a temporary "armistice".
What will win against the spammers is automated spam detection (by WA) and spam reporting by the users.

It seems like the best bet for you to truly stop spammers using your API is to kill the API altogether. :(

Meanwhile, legitimate users lose service...

Anyways, I truly appreciate your efforts. Good luck and let's hope the good guys win!

**Comment by andrecordeiro** [comment]
hi @ishaquehassan you pass me like implemented please chat bot ?

**Comment by roguejack** [comment]
Guys, I just saw this -> https://core.telegram.org/bots/api. Guess I wasted time with WA.
