### ISSUE TITLE
When will WA 1.6 based official clients stop working?

### ISSUE THREAD

**Issue by estcap** [mgp25/Chat-API#1841]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

In issue https://github.com/mgp25/Chat-API/issues/1832 , dev @mgp25 said 
> And yeah, im not going to publish new release until 1.6 dies and passes some time.

I know there's no ETA for next release of Chat-API (I am not asking for one), but I would like to know if there's an established official date from where official clients using 1.6 will stop connecting to Whatsapp server.

All the information I found was in [this Whatsapp blog entry](https://blog.whatsapp.com/10000617/WhatsApp-support-for-mobile-devices) which states that 

> ...by the end of 2016, we will be ending support for WhatsApp Messenger on the following mobile platforms:
>
>BlackBerry, including BlackBerry 10
>Nokia S40
>Nokia Symbian S60
>Android 2.1 and Android 2.2
>Windows Phone 7.1

What I do not know is if these plataforms will use WA 2.0 or not. This only serves to know that WA 2.0 will be mandatory before end of 2016.

- What  version of official Android client is the lastest using WA 1.6?
- Are these clients having a "This version of Whatsapp will require updating in X days" yet?

This information will be useful, mostly to know in advance when to disconnect our scripts, or when they will crash miserably. For example in my Script, I am disabling right now the auto-reconnect feature that I implemented... just in case.

Thanks again for all the effort this team has put in this project so far!

**Comment by mgp25** [comment]
@estcap we dont know when 1.6 will stop working, anyway, not API related issue

Regards
