### ISSUE TITLE
STATUS OLD VERSION ISSUE

### ISSUE THREAD

**Issue by shahidkarimi** [mgp25/Chat-API#1842]
I am getting this error. Please give a clear and accurate answer:
`Array ( [cc] => 92 [in] => 3129912287 [id] => gwo™9}ºw¡a+µð [lg] => en [lc] => PK ) stdClass Object ( [status] => fail [reason] => old_version ) `

**Comment by mgp25** [comment]
you havent posted debug log, and please read closed issues and use latest code
