### ISSUE TITLE
Unblocking!

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1845]
Hi there community,

I got pretty much intrigue about this issue, yesterday I went to my operator shop and bought a fresh SIM card, got the same problem reported as all, activated um account, received the sms code, it works for a few minutes then bang ... got the problem, not able to reconnect.

As pointed here, the number was not blocked, for some how, it was just unable to reconnect, to be sure I inserted this SIM card in a mobile phone, installed the app got the new got and the app worked smoothly ... so my conclusion was that the number was not blocked.

Next, setp, I looked the registration / login process, and found that in Registration.php line218, is hard coded carrier and platform.

So I changed the carrier to the accrual carried that the SIM card belong ... sharzam!!!!!
It is working form 12hs since them.

I cannot assure if this was just luck, or the fact I used the native app first, this unflag something at the server, or the other way, sending the registration with you native carrier unflag something there.

I would love to know if some of you try the same setp ... just setp 1 or just setp 2.

Cheers, have a nice weekend!

Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Just luck

Regards

**Comment by for2ne** [comment]
Hi, @edudesouza! your number is still alive? :)

**Comment by edudesouza** [comment]
@for2ne yes it is, not one but two number. I bought another sim card to be sure, and this other is alive too. Looking carefully, I got that what makes my numbers been alive is not the workaround I said, but the fact that I have a custom implementation, and in my request authentication I do not call checkCredentials. If I call checkCredentials, the number do not correctly got authenticated and (I guess) it got flagged as some sort wrong credentials. If I call again the authentication by voice or sms, the number got working again.

**Comment by yniwly43** [comment]
@edudesouza  could you shared your customer implementation? What's the difference?

**Comment by edudesouza** [comment]
@yniwly43 hi fellow, nothing special, I do use the whole implementation, as is presented in the examples, regarding registerTool, I do not use checkCredentials() I use CodeRegister and CodeRegisterFailed to check what is wrong, I also use version 2.12.440. I don´t know if this mean anything ... I also never did any broadcast list, never start a conversation, neither have my number associate to any group.

**Comment by samuelg78** [comment]
@edudesouza hi....is your number still working running fine?

**Comment by edudesouza** [comment]
Yes, it is, since later december.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.40&pv=4.3&source=email_footer_2] On Tue, May 03, 2016 at 7:08 AM, samuelg78 < notifications@github.com [notifications@github.com] > wrote:
@edudesouza [https://github.com/edudesouza] hi....is your number still working running fine?

**Comment by edudesouza** [comment]
I don´t know if it is something important, but I only activate my number by voice.

**Comment by yniwly43** [comment]
It seems that older numbers that had a real account (installed on real device) might survive the ban storm.
