### ISSUE TITLE
Messages are encrypted on GetMessages

### ISSUE THREAD

**Issue by Mega4alik** [mgp25/Chat-API#1846]
I get encrypted messages on using GetMessages function

```
$w->pollMessage();
$msgs = $w->getMessages();
foreach ($msgs as $m) {
    var_dump($m); 
}
```

> 1. object(ProtocolNode)#9 (4) { ["tag":"ProtocolNode":private]=> string(7) "message" ["attributeHash":"ProtocolNode":private]=> array(6) { ["from"]=> string(26) "7777777777@s.whatsapp.net" ["type"]=> string(4) "text" ["id"]=> string(18) "8DC7A9FFE3531B3D7C" ["offline"]=> string(1) "3" ["t"]=> string(10) "1460868808" ["notify"]=> string(4) "Aizh" } ["children":"ProtocolNode":private]=> array(1) { [0]=> object(ProtocolNode)#11 (4) { ["tag":"ProtocolNode":private]=> string(3) "enc" ["attributeHash":"ProtocolNode":private]=> array(2) { ["v"]=> string(1) "1" ["type"]=> string(3) "msg" } ["children":"ProtocolNode":private]=> NULL ["data":"ProtocolNode":private]=> string(66) "3 !��p�g���+n�0AȄ���`��!��N1"N�ޖsE&���m��n�<\��vӗ" } } ["data":"ProtocolNode":private]=> string(0) "" }

Am I missing something?

Thanks in advance

**Comment by 0xTryCatch** [comment]
Yes, you did not read the wiki
