### ISSUE TITLE
SPAM issue

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1847]
I was thinking about your latest statement, sure spam is terrible for the wealth fo any application, although, as said, once a new version it is available those virus will restart, like any infection.

How about an encrypted layer between rending and receiving, I mean, the API will only release messages for those numbers that already has been validated as a recipient whose already sent a message for the sender number.

... I am sure all in this community would be glad helping you to think about this feature, or brainstorming about the issue.

Best regards, 
good lucy, 
keep fighting the good fight!

Make sure these boxes are checked before submitting your issue -- thank you!
- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Ill release the API when its stricly necessary

Regards

**Comment by softcode2** [comment]
@mgp25 Thank you for your hard worker .
hope all blocked issue will fixed on new release .

because we loss our number , Whatsapp blocked us with no reason

Regards
