### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by olk49** [mgp25/Chat-API#1851]
Hi,  
  
I come from the wsp-project. First at all i want to thank you mgp25 and all others involved for the chat-api.  

What is more safe to avoid blocking ?  
To use regTool.php with actual version and token (as in 
https://coderus.openrepos.net/whitesoft/whatsapp_scratch , see a) and d) and then use the chat-api with the old version+token as in ../src/Constants.php and Token.php ?  

Or is it more safe to update the Constants.php and Token.php before using the api?  
We are a little confused here because the chat-api behaves as a api-v1.6 client.  

I know this is not a discussion place and i apologize but the point is whether to *register* a number as old or new client and then *use* the chat-api as old or new client.  

Which one is the safest and conformest way to go?

**Comment by mgp25** [comment]
You can update that data if you want, and you will register just fine, also if you dont update it still works fine.

What i havent tested is if it works registering using latest data and using WA 1.6.

In my opinion i would recommend staying in the current version, but its only a recommendation

Regards
