### ISSUE TITLE
Blocked out using watools.es

### ISSUE THREAD

**Issue by mackel90** [mgp25/Chat-API#1853]
Hi,

i wanted to make a Telegram <-> WhatsApp Bridge for our Group, so that the Telegram-Users dont miss any Converation from the WhatsApp Chat and Vice-Versa.

I Just started, and wanted to try the .net API. Therefore I used watools.es to register my number.

-I was using http://www.watools.es/pwd.html
-Entered my number.
-Code arrived.
-Entered Code.
-No Password, no success message, even no error message nothing happend. 
-Clickend on "GetPassword" Again and again.
-Downloaded WART.exe
-Tried "Confirm-Code" there.
-Debug-Out: https://drive.google.com/file/d/0Bw4MiZGMqp15R0xyX3Q4ZUt4aGs/view?usp=sharing

So i was locked out IMMEDIATELY, without using own Code or whatever.
Is there a Chance to get it running by only using WART.exe and not your Website ?
Then I will move out and buy a new Card.

- [x ] You are using PHP > 5.6 (I guess watools.es is using that)
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have. (not directly the same)
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [ x] You are using latest Chat API code. (I guess watools.es is using that)

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Not API issue

Regards

**Comment by mackel90** [comment]
Ok nice, got it, ths API-Version does not work anymore with registering new numbers.
yowsup may have the same issue.

But maybe would be so kind to tell that directly to the people and shut the Registration-Website down, 
for the while it is not working. This cost me a few bucks now.

**Comment by mgp25** [comment]
@mackel90 this is what sayd in the readme:

`This code is in no way affiliated with, authorized, maintained, sponsored or endorsed by WhatsApp or any of its affiliates or subsidiaries. This is an independent and unofficial API. Use at your own risk.`

**Use at your own risk**

And use registerTool.php

**Comment by softcode2** [comment]
@mgp25
Any way all numbers it will be blocked directly when he try to use it in chat-api .

More then 13 numbers was blocked till now .
I am using   registerTool.php

I already have one number it was registered before 2 months , it's working well till now
