### ISSUE TITLE
register old_version error

### ISSUE THREAD

**Issue by HimBig** [mgp25/Chat-API#1854]
Make sure these boxes are checked before submitting your issue -- thank you!

- [YES ] You are using PHP > 5.6
- [ YES ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ YES ] You have checked if someone has already asked the same issue you have.
- [YES  ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [YES  ] Is not a programming question.
- [YES  ] You are using latest Chat API code.

### Error
Post your error below:
I try this api last week and not have any problem.But now, when i register the same phone number , it show the old version problem.I confirm the api is the latest(21/4/2016 11am GMT+8 Download).

### Debug log
Post your debug log below:
Array ( [cc] => 852 [in] => 655xxxxx [lg] => zh [lc] => HK [id] => xxxxxxxx= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 7614 [rchash] => xxxxxx [anhash] => xxxxx [extexist] => 1 [extstate] => 1 [mcc] => 454 [mnc] => 000 [sim_mcc] => 454 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => fail [reason] => old_version ) 
Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in C:\xampp2\htdocs\chat_1\Chat-API-master\src\Registration.php:314 Stack trace: #0 C:\xampp2\htdocs\chat_1\Chat-API-master\examples\exampleRegister.php(41): Registration->codeRequest('sms') #1 {main} thrown in C:\xampp2\htdocs\chat_1\Chat-API-master\src\Registration.php on line 314

**Comment by 0xTryCatch** [comment]
No problems here

**Comment by HimBig** [comment]
I 100% use the latest code.Before few mins, i download again and unzip it. And run exampleRegister.php . it show same problem.

**Comment by 0xTryCatch** [comment]
Weird, for my number it simply still works.

**Comment by HimBig** [comment]
When i use the example phone number (34666554433)  it also echo stdClass Object ( [status] => fail [reason] => old_version )

**Comment by HimBig** [comment]
I want to know what the WHATSAPP_VER  in Constants.php????is  2.12.440?

**Comment by StApostol** [comment]
When I run registerTool.php get error. Constant version set 2.12.440
`
Array
(
    [cc] => 79
    [in] => 23xxxxxxx
    [lg] => ru
    [lc] => RU
    [id] => xxxxxxx
    [token] => xxxxx
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 202
    [rchash] => c107b59bb2de350f35e635d1b5f1ecf3a3104b20e57b245d716017ccb3243496
    [anhash] => 682672df3d55179b5d60f0f733fe5c5a
    [extexist] => 1
    [extstate] => 1
    [mcc] => 250
    [mnc] => 000
    [sim_mcc] => 250
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [status] => fail
    [reason] => old_version
)`

**Comment by pedrotoba94** [comment]
If you want this to work, change the version of whatsapp in **Constants.php**. _(chat-api/src)_

- WHATSAPP_VER = (actual version)
- WHATSAPP_USER_AGENT = 'WhatsApp/(actual version) Android/4.3 Device/Xiaomi-HM_1SW'

The actual version of whatsapp in android is **2.16.13** at 21-4-16.

**Comment by HimBig** [comment]
hi pedrotoba94,
I change it to
WHATSAPP_VER = "2.16.13"
WHATSAPP_USER_AGENT = 'WhatsApp/2.16.13 Android/4.3 Device/Xiaomi-HM_1SW'

but it return stdClass Object ( [status] => fail [reason] => bad_token )

**Comment by 0xTryCatch** [comment]
Update to the latest version, issue resolved

**Comment by pedrotoba94** [comment]
I have a problem and is how i put my Lg g3 in "user_agent", it says bad token again.

**Comment by HimBig** [comment]
thanks 0xTryCatch , the update version is solve my problem.

**Comment by SudoHenk** [comment]
@0xTryCatch how did you know that the current version/token? Is there some webservice from this (whatsapp_scratch only shows the newest version).

**Comment by mgp25** [comment]
because @0xTryCatch knows magic D:

**Comment by dgnovo** [comment]
I have the new version but i receive on Registration
stdClass Object
(
    [status] => fail
    [reason] => old_version
)

I update Constats.php
    const WHATSAPP_VER = '2.16.133';   // The WhatsApp version.
    const WHATSAPP_USER_AGENT = 'WhatsApp/2.16.133 S40Version/14.26 Device/Nokia302';        // User agent used in request/registration code.

After i receive this output:
stdClass Object
(
    [status] => fail
    [reason] => bad_token
)

**Comment by vnay92** [comment]
Seriously though, @0xTryCatch , how did you know the version/token?

**Comment by dgnovo** [comment]
This my situation:
Ubuntu 14.04

php -v
PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

php -m
[PHP Modules]
bcmath
bz2
calendar
Core
crypto
ctype
curl
curve25519
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
mhash
openssl
pcntl
pcre
PDO
Phar
posix
protobuf
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache


This is my response:

Array
(
    [in] => ***************
    [cc] => 39
    [id] => ebփ#���{��k[z��g.
    [lg] => it
    [lc] => IT
    [sim_mcc] => 222
    [sim_mnc] => 000
    [method] => sms
    [token] => 6500bc97697f1aae98f78e0966e91a4e
)
stdClass Object
(
    [status] => fail
    [reason] => bad_token
)

**Comment by halbano** [comment]
Same here @dgnovo. Have you resolved that?

**Comment by SudoHenk** [comment]
Don't bother. This API is for an older whatsapp version, even if you have the correct token, you will be banned in a matter of minutes. [Read this](https://github.com/mgp25/Chat-API/issues/2116)
