### ISSUE TITLE
Extracting password from device.

### ISSUE THREAD

**Issue by marituss** [mgp25/Chat-API#1856]
Hello,

As whatsapp got updated I'm not able to extract password from pw file. It was working very well but now extracting whatsapp from device is not working anymore. It extracts the password but that is totally wrong. Am I the only one who is facing the problem ? Please let me know.

Thank You!

**Comment by mgp25** [comment]
Not API issue, im going to close the issue, but you can keep the conversation with others if you want.

Regards

**Comment by marituss** [comment]
@mgp25  : I'm sure that's not working. I have been using it since you wrote that article. Can you please check and update it ?

Thanks!

**Comment by yniwly43** [comment]
Tried it, can also affirm that the latest Android version's password isn't correct. Strange

**Comment by hallisonboaventura** [comment]
How do you know it is totally wrong?

**Comment by hallisonboaventura** [comment]
Based on documentation at:
https://github.com/mgp25/Chat-API/wiki/nodes#login-nodes

We should have data inside the tag auth, like this:
```xml
<auth mechanism="WAUTH-2" user="34123456789">?34123456789????Q???č?\?v?l$1444056358</auth>
```

But when we try to login we face empty content:
```xml
<auth mechanism="WAUTH-2" user="34123456789"></auth>
```

And I don't know if this is expected or documentation is outdated...
