### ISSUE TITLE
Not-authorized during LoginwithPassword function executation

### ISSUE THREAD

**Issue by nageshsrivastava** [mgp25/Chat-API#1857]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
Logging in as 'raj' (91XXXXXXXXXX) What's app Connectedtx  <stream:features></stream:features>

tx  <auth user="91XXXXXXXXXX" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>1400c4a0597fae06d638ccfb82386c95fca8271d</challenge>

tx  <response>62d307e65c0138e71784cde0fc1fd9d2c2fd09f44033ed16686ffefa4eb80572a2ec3c19538adb20a05bb9b4d0ebabd9ec3033653001dff6f189a750ed7e6e009bb65a527a22d87aa8528f9e03d9</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

disconnected
Fatal error: Uncaught exception 'LoginFailureException' in /var/www/html/Chat-API-master/src/Login.php:62 Stack trace: #0 /var/www/html/Chat-API-master/src/whatsprot.class.php(287): Login->doLogin() #1 /var/www/html/Chat-API-master/examples/exampleFunctional.php(74): WhatsProt->loginWithPassword('7+jrOQcUFLbFkgrXXXXX') #2 {main} thrown in /var/www/html/Chat-API-master/src/Login.php on line 62

**Comment by hallisonboaventura** [comment]
I can see it's duplicated, but can't find what it is duplicated with
Can someone send me the link?

**Comment by mgp25** [comment]
Read the FAQ
