### ISSUE TITLE
[reason] => old_version

### ISSUE THREAD

**Issue by babahvl** [mgp25/Chat-API#1858]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Sorry, subject is [reason] => incorrect
root@debian:~/vendor/whatsapp/chat-api/examples# php5 registerTool.php
.............
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)

### Debug log
Post your debug log below:
####################
#                  #
# WA Register Tool #
#                  #
####################

Username (country code + number, do not use + or 00): 79025572277
Array
(
    [cc] => 79
    [in] => 025572277
    [lg] => ru
    [lc] => RU
    [id] => ▒▒i{j▒▒=▒▒1c        ▒▒▒
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 8817
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
There was a problem trying to request the code.

Other Phone num is OK. My num is wrong.  :-(

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Remove identity

**Comment by olk49** [comment]
Removing the id.xxxxxxxx.dat in the ./src/wadata helps ? Cool, i had this, too. thx
