### ISSUE TITLE
Registration issue: Reason: temporarily_unavailable

### ISSUE THREAD

**Issue by amrspace** [mgp25/Chat-API#1859]
I tried register new Number with regesterTool & last update for Chat-API, I get the code  on my mobile, but when enter this code for register I get below error & the number blocked!

An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable

Array
(
    [cc] => ??
    [in] => ??????????
    [lg] => ??
    [lc] => ??
    [id] => ?l????,/v?#?c>w?+?
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3665
    [rchash] => 0d814231ca242e55bf70e0d9f010c1dcc247b92b6758fcb10a44a763342df836
    [anhash] => 85f640053914350c694aa0c82f3fdd2e
    [extexist] => 1
    [extstate] => 1
    [code] => 304851
)
stdClass Object
(
    [status] => fail
    [reason] => temporarily_unavailable
    [retry_after] => 3600
)

**Comment by softcode2** [comment]
Same problem here .
All new numbers getting blocked !

Any sulotion for  this blocking issue ?

**Comment by mgp25** [comment]
If you dont post full debug including number, i consider this as invalid. `temporarily_unavailable` often means you are an spammer or registering too many numbers which is suspicious

Regards
