### ISSUE TITLE
got blocked without sending messages

### ISSUE THREAD

**Issue by engmustafamuhammad** [mgp25/Chat-API#1861]
Make sure these boxes are checked before submitting your issue -- thank you!

- [YES] You are using PHP > 5.6
- [YES] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [YES] You have checked if someone has already asked the same issue you have.
- [YES] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [YES] Is not a programming question.
- [YES] You are using latest Chat API code.

### Error
Post your error below:
I connect with number for 24 hours to get all new messages and once disconnect and reconnect i got blocked and i tried this with 2 numbers.
I never sent any message(s)

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by 0xTryCatch** [comment]
Where is the debug log?

**Comment by J-N-K** [comment]
I have the same problem and didn't open an issue because I can't provide a debug log. The Application had been Running for weeks without issues, so I turned off debugging. All I can say is that I received onPresenceAvailable and got disconnected immediately after that. I pause for 30s before reconnecting and found the number blocked.

**Comment by AndreySlashman** [comment]
I have the same problem guys, can we figure out whats wrong?

**Comment by mgp25** [comment]
Without debug logs this is an invalid issue, when you've got the **full** debug log, open a new issue and post it.

**Comment by samuelg78** [comment]
Yes... i got the same problem after running for 24 hours after using registertools.php to register new number
