### ISSUE TITLE
Question - Token generation

### ISSUE THREAD

**Issue by 0xFlitz** [mgp25/Chat-API#1862]
- [ X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).

### Error
Post your error below:

I'm investigating the latest apk to understand if there is a protocol change that causes those reported banning.

Anyway- i'm modding the apk, and of course i need to patch the functions to return proper md5 and Sha1Mac for the token generation.

To make sure i'm doing it properly, i try to regenerate the values in the Token Generation wiki. (e.g, downloading the 2.11.481 apk and verifying that the md5 -base64 i calculate is same as the wiki ).
$classesMd5   = "ZXEimx8U9X1WZwQmVJRnGA=="; // 2.11.481

but i dont get the same values as the token wiki, is it something im doing or the values in wiki are fake?

I'm getting:
md5sum -b classes.dex | base64
NjU3MTIyOWIxZjE0ZjU3ZDU2NjcwNDI2NTQ5NDY3MTggKmNsYXNzZXMuZGV4Cg==

**Comment by mgp25** [comment]
@0xFlitz yes, there is a protocol change. Check in my repos there is a tool to get the classes md5, keep in mind md5 hash must be raw and then base64 encoded, and after that you need to do the token calculation

Regards

**Comment by 0xFlitz** [comment]
Thank you.

this was probably an encoding issue, the entire classes.dex is \x characters (unicode), but the md5sum probably read it as a string..

I'll submit a python script to the repo in favor of people without windows.

**Comment by 0xFlitz** [comment]
@mgp25  - When i reviewed the apk code, i noticed that the token calculation was changed.
the pdfk key length is not 128, its 512. 

does this make any difference? 

Also,  i just took the signature of WA2.16.39 apk, and it was the same as what you have in the token wiki, how is it possible?
