### ISSUE TITLE
IP based blocking

### ISSUE THREAD

**Issue by eaba** [mgp25/Chat-API#1863]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ yes] You are using PHP > 5.6
- [yes ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ yes] You have checked if someone has already asked the same issue you have.
- [yes ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ yes] Is not a programming question.
- [ yes] You are using latest Chat API code.

### Error
Post your error below:
@mgp25 This is more of a question than an error report.
Can a number be blocked based on the connection ip address?
That is, A Japanese number connecting to WhatsApp with this api hosted in 
US web host provider.

### Debug log
Post your debug log below:
```
rx <start from="s.whatsapp.net"></start>

rx <stream:features></stream:features>

rx <challenge>�N2i!��ҍ�3����</challenge>

rx <failure>
rx   <not-authorized></not-authorized>
rx </failure>
```

**Comment by 0xTryCatch** [comment]
Yes that is certainly possible

**Comment by eaba** [comment]
Okay thanks! @0xTryCatch how are you?

**Comment by samuelg78** [comment]
@eaba ... I had switched to php version.... but my new number are still been blocked after using registertool.php to register.

**Comment by softcode2** [comment]
@samuelg78
You can not unblocked your IP .
Must to contact whatsapp , I don't know if he agree or not .

Regards

**Comment by eaba** [comment]
You know what guys? I am screaming NICE ONE here, but like @mgp25 said in 2014, I wish I could share it but I am muted!

**Comment by 0xFlitz** [comment]
@eaba - ? did you find the issue?

**Comment by eaba** [comment]
Maybe I did

**Comment by eaba** [comment]
My number was not actually blocked but was not-authorized!

**Comment by 0xFlitz** [comment]
@eaba  - How do you know its not blocked? mostly not-authorized means Blocked. 
@mgp25  @0xTryCatch  am i wrong?

**Comment by eaba** [comment]
If you re-register after getting not-authorized with this api you will get blocked

**Comment by 0xFlitz** [comment]
So, how do you login if you are not-authorized? updated token?

**Comment by eaba** [comment]
We need to ask @mgp25 that

**Comment by 0xTryCatch** [comment]
```not-authorized``` is permanently blocked
