### ISSUE TITLE
Error loginWithPassword

### ISSUE THREAD

**Issue by rogerxosoft** [mgp25/Chat-API#1868]
Hello, everything was working properly and suddenly starts to fail with authentication error.

please help..

### Error
Post your error below:

#0 /root/WhatsAPI/src/whatsprot.class.php(286): Login->doLogin()
#1 /root/WhatsAPI/examples/server1.php(39): WhatsProt->loginWithPassword('CgVA69osirEGoIo...')
#2 {main}
  thrown in /root/WhatsAPI/src/Login.php on line 54

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by softcode2** [comment]
Me too .
Today number get blocked .
Just Suddenly.

**Comment by softcode2** [comment]
Check this #1867

**Comment by rogerxosoft** [comment]
I try with different numbers and from different servers and ip's and I make the same mistake

**Comment by softcode2** [comment]
Make sure that your numbers is not blocked .
And post your deluge log .

**Comment by rogerxosoft** [comment]
I have 4 numbers I got your passwords, these only one was using as probe with 4 numbers and fail the strange thing is that also stopped working the registration tool. Sorry for the translation

**Comment by rogerxosoft** [comment]
Log: 

tx  <auth user="521735**********" mechanism="WAUTH-2">724e3e853532313733353130333737353826e73808d8f1bdb11d3c1ab7eada388378006d2331343631373330323034</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>2d05ea0780729c83b49fd0bb8ddacc9327ca03c2</challenge>

tx  <response>e4f73d663161aa4d2a56d640691fb9cd7a917a9cc725e322bbeef3412aeb6afc7b2da6076c2e9568c5f1d65765406c61b924437becccbbb08db24e2f8f48796faf8e660fdde808817019803cae8236</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /root/WhatsAPI/src/Login.php:54
Stack trace:
#0 /root/WhatsAPI/src/whatsprot.class.php(286): Login->doLogin()
#1 /root/WhatsAPI/examples/server1.php(39): WhatsProt->loginWithPassword('CgVA69osirEGoIo...')
#2 {main}
  thrown in /root/WhatsAPI/src/Login.php on line 54

**Comment by softcode2** [comment]
It's mean your number get blocked .
Please make sure by Block checker page in examples folder .

**Comment by rogerxosoft** [comment]
I try but I returned the following error:

####################
#                  #
# WA Block Checker #
#                  #
####################


Username (country code + number without + or 00): 52735*******             
Array
(
    [cc] => 52
    [in] => 735*******
    [lg] => es
    [lc] => MX
    [id] => ?,o?!r?i?Ţ??䨚/
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 555
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => old_version
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /root/WhatsAPI/src/Registration.php:89
Stack trace:
#0 /root/WhatsAPI/examples/blockChecker.php(36): Registration->checkCredentials()
#1 {main}
  thrown in /root/WhatsAPI/src/Registration.php on line 89

**Comment by softcode2** [comment]
reason] => old_version

Use the latest version of chat-api

**Comment by rogerxosoft** [comment]
Download the latest version, and throws me the following:

####################
#                  #
# WA Block Checker #
#                  #
####################


Username (country code + number without + or 00): 52735*******


Wrong identity. 
Array
(
    [cc] => 52
    [in] => 735*******
    [lg] => es
    [lc] => MX
    [id] => 
            ץ????a??7{1t????
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3429
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /root/WhatsApp/Chat-API-master/src/Registration.php:89
Stack trace:
#0 /root/WhatsApp/Chat-API-master/examples/blockChecker.php(36): Registration->checkCredentials()
#1 {main}
  thrown in /root/WhatsApp/Chat-API-master/src/Registration.php on line 89

**Comment by mgp25** [comment]
@rogerxosoft the identity is not the same so, delete the .dat file and register it again, if it says `blocked` when trying to register then you know the result

Regards
