### ISSUE TITLE
Get blocked after 2 months using Api (Using last API)

### ISSUE THREAD

**Issue by eftimie-andrei** [mgp25/Chat-API#1869]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
I get blocked yesterday, after 2 months using this Api. After the first block, i've changed the numer with a new one and i get blocked again after 10 minutes.

`rx  <failure>`
`rx    <not-authorized></not-authorized>`
`rx  </failure>`

### Debug log
Post your debug log below:

`tx  <stream:features></stream:features>`

`tx  <auth user="34629023353" mechanism="WAUTH-2"></auth>`

`rx  <from s.whatsapp.net=""></from>`

`rx  <stream:features></stream:features>`

`rx  <challenge>07e6cf7966502a77a6718a2a48152c52c36ff185</challenge>`

`tx`
`<response>091dee9dc0a45a108a84c60ab2863be5c959939f2d062a8c108648ca0a3b1e6a408069`
`b5e69da7163260cadbc92fb4eadd16c2e6d5f593968d20472b287928ec811e3c4775f6aa3efa`
`0855cafe</response>`

`rx  <failure>`
`rx    <not-authorized></not-authorized>`
`rx  </failure>`

I read the closed issues but i'm confused. Not authorized failure means i'm blocked and i can't login with whatsapp, thats OK. But i don't understant whay the new number get blocked so quickly. 

Thank you!

**Comment by pereira49** [comment]
@eftimie-andrei maybe is an IP problemn. Whatsapp can block you by ip
#1863

**Comment by samuelg78** [comment]
@pereira49 I had tried with many IPs..... but still got blocked. One thing is the more often you connect() the faster you will get blocked.

**Comment by eaba** [comment]
I am suspecting pinging does not work the way it used to before!

**Comment by softcode2** [comment]
today i got banned by WhatsApp for VPS IP and numbers .
without any reason 
it was working for 4 months ago , but just yesterday i had registered a new number then send 2 msg 
today got banned !!

**Comment by eftimie-andrei** [comment]
@pereira49 Thank you! I changed my public IP and register a new number. 
Now it's working fine... (crossing fingers)!!!  Regards!!!

**Comment by softcode2** [comment]
@eftimie-andrei 

how you registered it ?

any way, update us about you number if will got banned or not !

**Comment by eftimie-andrei** [comment]
I registered the number with registerTools. I don't know another way to register...

**Comment by yniwly43** [comment]
It will work for a day or two then it will get banned :/
