### ISSUE TITLE
Bots get banned instantly when attempting to log in.

### ISSUE THREAD

**Issue by Sydcul** [mgp25/Chat-API#1874]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
So yeah, as of today, all of my WhatsApp bots are being blocked instantly. I bought a Dutch prepaid SIM a couple of days ago which worked just fine until yesterday. For now, all it does is send one message to my personal phone number, and I did that a few times over the last few days while working on the rest of the bot. After doing that, it would disconnect from WhatsApp. When I tried to run it today, it got banned. I also bought a Moroccan sim to use for internetting and occasional calling and I registered that for WhatsApp too. When I tried to use it today with the exact same code, it got banned even before it could send any messages. I am doing all this from a Dutch IP (my server) with no history of any bans whatsoever. Also, both bots are in my contacts list. Is it some sort of bug in ChatAPI? I have installed everything using composer.

### Debug log
Post your debug log below:

Log when starting the script (login):
```
whatsappbot@server:~/lockbot/bot$ php main.php
tx  <stream:features></stream:features>

tx  <auth user="212xxxxxxxxx" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>xxx</challenge>

tx  <response>xxx</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /home/whatsappbot/lockbot/vendor/whatsapp/chat-api/src/Login.php:54
Stack trace:
#0 /home/whatsappbot/lockbot/vendor/whatsapp/chat-api/src/whatsprot.class.php(286): Login->doLogin()
#1 /home/whatsappbot/lockbot/bot/main.php(36): WhatsProt->loginWithPassword('xxx')
#2 {main}
  thrown in /home/whatsappbot/lockbot/vendor/whatsapp/chat-api/src/Login.php on line 54
```

Attempting to reregister:
```
whatsappbot@server:~/lockbot/bot$ php reg.php
Array
(
    [cc] => 212
    [in] => xxxxxxxxx
    [lg] => ar
    [lc] => MA
    [id] => xxx
    [token] => xxx
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 2603
    [rchash] => xxx
    [anhash] => xxx
    [extexist] => 1
    [extstate] => 1
    [mcc] => 604
    [mnc] => 000
    [sim_mcc] => 604
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /home/whatsappbot/lockbot/vendor/whatsapp/chat-api/src/Registration.php:314
Stack trace:
#0 /home/whatsappbot/lockbot/bot/reg.php(8): Registration->codeRequest('sms')
#1 {main}
  thrown in /home/whatsappbot/lockbot/vendor/whatsapp/chat-api/src/Registration.php on line 314
```

**Comment by mgp25** [comment]
If you dont provide previous activity debug log we dont know what happened. Paste it here when you have it

Regards

**Comment by guileh** [comment]
I had two phone numbers blocked this week. I was trying to connect with another constant settings but It was failing. So I downloaded the actual constant file in this repository and booommm! "[status] => fail [reason]=> blocked....

 I checked It using the numbers on my smartphone and it's true, the both ones are blocked. 

I believe they are tracking the constants DEVICE, WHATSAPP_VER, OS_VERSION, MANUFACTURER, BUILD_VERSION, PLATFORM and WHATSAPP_USER_AGENT.

Last Sunday my first number was blocked after I used the config bellow, so I changed the WHATSAPP_USER_AGENT constant. Today I tried the Sunday's constants and the blocking warning returned.

My Constants:

The hostname used to login/send messages.
    const DEVICE = 'armani';                                                                 // The device name.
    const WHATSAPP_VER = '2.12.556';                                                         // The WhatsApp version.
    const OS_VERSION = '4.3';
    const MANUFACTURER = 'Xiaomi';
    const BUILD_VERSION = 'JLS36C';
    const PLATFORM = 'Android';                                                              // The device name.
    const WHATSAPP_USER_AGENT = 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-HM_1SW';        // User agent used in request/registration code.
    const WHATSAPP_VER_CHECKER = 'https://coderus.openrepos.net/whitesoft/whatsapp_scratch'; // Check WhatsApp version 

Is It possible? I mean to track this constants, Is they uniquely used by this API?

This API could be a perfect tool for my project, now I'll be back to facebook plugins. :(

**Comment by Sydcul** [comment]
I think it may be very well possible that changing these variables could
help, but you have to be sure to change them to valid ones. Especially the
WhatsApp verison, that's way outdated.
