### ISSUE TITLE
question related to mobile network and no_routes error

### ISSUE THREAD

**Issue by q4z1** [mgp25/Chat-API#1875]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

Hi, I crawled through the Wiki and the FAQs - but I dont find an answer - so sorry for asking this simple question:

I try to register my own mobile number from a root server (future plan is to use this api for a web-site).
I get a no_routes error - do I have to register from inside a mobile network - e.g. using a console on my smartphone? Or can I register from my cable internet?
The FAQ mentions "no_routes appear when mobile operators can't reach your mobile network" - but that does not really answer my question (because my WhatsApp client on my smartphone is up and running) :/

I hope you can give a short reply - thank you.

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Post debug log and number...

**Comment by gi097** [comment]
You need to use the correct mnc as well as mcc, but also use all the parameters from Chat-API during request. Otherwise you get the 'no_routes' error.

**Comment by q4z1** [comment]
Hi,

fyi:

after experimenting more and more I figured it out:

* the registration of a number works only from my private home ISP network
* any registration try from one of our servers does not work and results in "no_route" error
* after a succesfull registration, sending and receiving messages from our servers works(!)

Kind regards.
