### ISSUE TITLE
After 4 month use this api, On april 30 My number blocked

### ISSUE THREAD

**Issue by b3nyariel** [mgp25/Chat-API#1876]
### Error
I try to register 5 new number again, but it happen blocked again and again. Thanksfull if this issue can be solve soon.

### Previous Activity
Before blocked, I send message to number that not sync in my google contact.
Before that date, I send message without save number not happen anything, run properly.
Maybe whatsApp use a new sistem to detect bot?

### Debug log
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /home/iben/www/Chat-Api/src/Login.php:54
Stack trace:
#0 /home/iben/www/Chat-Api/src/whatsprot.class.php(286): Login->doLogin()
#1 /home/iben/www/Chat-Api/send-message.php(36): WhatsProt->loginWithPassword('xxx')
#2 {main}
  thrown in /home/iben/www/Chat-Api/src/Login.php on line 54

**Comment by MrLuit** [comment]
I registered a new account and it also got instantly blocked. Not cool whatsapp

**Comment by mgp25** [comment]
You answered yourself: ` Before that date, I send message without save number not happen anything, run properly.`

Please check also related issues, i have explained the reason in many of them

Regards
