### ISSUE TITLE
Messages not being sent in Loop!

### ISSUE THREAD

**Issue by ammarbrohi** [mgp25/Chat-API#1880]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

Reading input file with numbers and sending messages via loop. Recipients = 5

Code:
```php
<?php

ini_set('max_execution_time', 30000);
require_once 'src/whatsprot.class.php';
date_default_timezone_set('Europe/Madrid');
$username = '';
$password = '';
$nickname = 'ammar';
$debug = false;
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

$caption = "I love you :*!";
$count = 0;
$target = [];
$handle = fopen("inputfile.txt", "r");
		if ($handle) {
			while (($line = fgets($handle)) !== false) {
				
				$target[$count] = $line;
				$count++;
			}
			fclose($handle);
		} 
		
		
	for($i =0; $i<count($target); $i++){
		
		$done =  $w->sendMessage($target[$i],$caption);	
		var_dump($done);
		
		echo $target[$i];
		
		sleep(20);
		
		
		
	}

$w->pollMessage();
```

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Programming issue

**Comment by ammarbrohi** [comment]
FUCK YOU
