### ISSUE TITLE
Extracting password from device.

### ISSUE THREAD

**Issue by marituss** [mgp25/Chat-API#1882]
Hello,

I have checked multiple times now and I'm sure that the password extracting from device is not working anymore. It gives the incorrect password. I have android device and I tried with manual steps as well as with app. Everytime it gives the false password. Could you update it please ?

Thanks!

**Comment by mgp25** [comment]
@marituss the password is extractred correctly, but new versions of whatsapp also needs a private and public key to login, thats why when you try the password you can't login. In order to login you need to extract that data too.

This is because of the new WA 2.0 (noise protocol)

Regards

**Comment by marituss** [comment]
@mgp25  : How to extract these data ? Any tutorial ?

Thanks!

**Comment by fgfinat** [comment]
It would be nice an update. Can't login too.

**Comment by mgp25** [comment]
Just register the number using registerTool.php. Dont expect any update
