### ISSUE TITLE
Another blocked number

### ISSUE THREAD

**Issue by Marco208** [mgp25/Chat-API#1884]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

Now I know you are tired of people saying this. If this isn't enough information please tell me what to provide you. The number is added to a group conversation between me and 2 of my colleages. We have added the number in our contact books.

Every timer tick is a second.
 
### Error
Post your error below:
Blocked

### Debug log
Post your debug log below:

```xml
Debug timer: 1911
Debug timer: 1912
Debug timer: 1913
Debug timer: 1914
Debug timer: 1915
Debug timer: 1916
Debug timer: 1917
Debug timer: 1918
Debug timer: 1919
tx  <iq id="c9" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1920
rx  <iq from="s.whatsapp.net" type="result" id="c9" t="1462284412"></iq>

Debug timer: 1921
Debug timer: 1922
Debug timer: 1923
Debug timer: 1924
Debug timer: 1925
Debug timer: 1926
Debug timer: 1927
Debug timer: 1928
Debug timer: 1929
tx  <iq id="ca" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1930
rx  <iq from="s.whatsapp.net" type="result" id="ca" t="1462284430"></iq>

Debug timer: 1931
Debug timer: 1932
Debug timer: 1933
Debug timer: 1934
Debug timer: 1935
Debug timer: 1936
Debug timer: 1937
Debug timer: 1938
Debug timer: 1939
tx  <iq id="cb" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1940
rx  <iq from="s.whatsapp.net" type="result" id="cb" t="1462284448"></iq>

Debug timer: 1941
Debug timer: 1942
Debug timer: 1943
Debug timer: 1944
Debug timer: 1945
Debug timer: 1946
Debug timer: 1947
Debug timer: 1948
Debug timer: 1949
tx  <iq id="cc" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1950
rx  <iq from="s.whatsapp.net" type="result" id="cc" t="1462284466"></iq>

Debug timer: 1951
Debug timer: 1952
Debug timer: 1953
Debug timer: 1954
Debug timer: 1955
Debug timer: 1956
Debug timer: 1957
Debug timer: 1958
Debug timer: 1959
tx  <iq id="cd" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1960
rx  <iq from="s.whatsapp.net" type="result" id="cd" t="1462284484"></iq>

Debug timer: 1961
Debug timer: 1962
Debug timer: 1963
Debug timer: 1964
Debug timer: 1965
Debug timer: 1966
Debug timer: 1967
Debug timer: 1968
Debug timer: 1969
tx  <iq id="ce" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1970
rx  <iq from="s.whatsapp.net" type="result" id="ce" t="1462284502"></iq>

Debug timer: 1971
Debug timer: 1972
Debug timer: 1973
Debug timer: 1974
Debug timer: 1975
Debug timer: 1976
Debug timer: 1977
Debug timer: 1978
Debug timer: 1979
tx  <iq id="cf" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1980
rx  <iq from="s.whatsapp.net" type="result" id="cf" t="1462284521"></iq>

Debug timer: 1981
Debug timer: 1982
Debug timer: 1983
Debug timer: 1984
Debug timer: 1985
Debug timer: 1986
Debug timer: 1987
Debug timer: 1988
Debug timer: 1989
tx  <iq id="d0" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="active"></presence>

Debug timer: 1990
rx  <iq from="s.whatsapp.net" type="result" id="d0" t="1462284539"></iq>

Debug timer: 1991
Debug timer: 1992
Debug timer: 1993
Debug timer: 1994
Debug timer: 1995
Debug timer: 1996
Debug timer: 1997
Debug timer: 1998
Debug timer: 1999
------ RESTART PHP SCRIPT HERE ------
[root@nagios src]# php whatsapp-daemon.php
PHP Warning:  Creating default object from empty value in /root/whatsapp-daemon/WhatsAPI-Official/src/custom/functions.php on line 121
Number "316xxxx@s.whatsapp.net" is registered as user "marco" now with level 4095
Number "316xxxx@s.whatsapp.net" is registered as user "user1" now with level 4095
Number "316xxxx-1338653109@g.us" is registered as user "user2" now with level 0
Number "316xxxx-1389726022@g.us" is registered as user "user3" now with level 0
Number "316xxxx-1403882154@g.us" is registered as user "user4" now with level 0
Number "316xxxx-1421244746@g.us" is registered as user "nagwhattwo" now with level 0
Number "316xxxx@s.whatsapp.net" is registered as user "user5" now with level 4095
Number "316xxxx-1424604789@g.us" is registered as user "home" now with level 0
[==] logging in as 'My-Whatsapp' (31649793791)
[==] Connecting to WhatsApp

<p>WooHoo!, Phone number 31649793791 connected successfully!</p>tx  <stream:features></stream:features>

tx  <auth user="31649793791" mechanism="WAUTH-2">c8c575b63331363439373933373931cc358a9a6e6dae9d8c38b910b4d48de1cab2e36431343632323838363432</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>c35f772649e64b86b78e5124acc374105e394ebf</challenge>

tx  <response>62cb56bdaa3800f46d07364865e45a991424fe5c207672634995ea2a47c00821727f7e4224835bff1a728ee3cb5efafa4e6d944ac2a0afb76ce41e96c828419d0eeafd8b8ad8298dc63c99c334</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /root/whatsapp-daemon/WhatsAPI-Official/src/Login.php:54
Stack trace:
#0 /root/whatsapp-daemon/WhatsAPI-Official/src/whatsprot.class.php(286): Login->doLogin()
#1 /root/whatsapp-daemon/WhatsAPI-Official/src/whatsapp-daemon.php(42): WhatsProt->loginWithPassword('1lIW5fVrRni3wm4...')
#2 {main}
  thrown in /root/whatsapp-daemon/WhatsAPI-Official/src/Login.php on line 54

```

**Comment by mgp25** [comment]
Another duplicate issue, i told the solution in a previous issue

Regards

**Comment by Marco208** [comment]
Can you give me the issue ID of the solution? I've been reading a lot of these before I tried again

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/issues/1872#issuecomment-215912828

**Comment by samuelg78** [comment]
@mgp25 2 pings and reconnect

`
Setting environment for using XAMPP for Windows.
Owner@OWNER-PC c:\xampp
# cd htdocs\chat-api-master\tests

Owner@OWNER-PC c:\xampp\htdocs\Chat-API-master\tests
# php whatsapp3.php -l XXXXXXXXXXX
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">93c05f8136303137373631353339373
f1a1429f7dbe778378f55a6b85291e6c729e04e31343632333331343631</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b713d8cdfc441fa6b1c8756b3753727d08f439f3</challenge>

tx  <response>eb0dcd885dc30ec7a75153d73e0aa3f0814ac97af557484846715d59dc1ecd46ec
c08f5bda93303252157459180825893ee17597ebb9cedcc4b525713004ebff19af6a67e67bd0c36f
87b559a9</response>

rx  <success t="1462331462" props="5" kind="free" status="active" creation="1462
330553" expiration="4444444444">3519511017f2219a672426d91add9f1d4315ed51</succes
s>

tx  <presence name="WAWA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_81f1f53e-feef-
4ad3-a99c-539ddd00ded6" index="0" last="true">
tx      <user>+XXXXXXXXXXX</user>
tx      <user>+XXXXXXXXXXX</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="60177615397@s.whatsapp.net"></presence>

rx  <iq from="60177615397@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="60177615397@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_81f1f53e-feef-4ad3-a99c-539ddd00ded6" l
ast="true" version="1462330619943694">
rx      <in>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx      </in>
rx    </sync>
rx  </iq>


XXXXXXXXXXX@s.whatsapp.net exists

XXXXXXXXXXX@s.whatsapp.net exists
tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="04">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.n
et">
tx    <picture type="preview"></picture>
tx  </iq>

tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="06">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="07" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.
net">
tx    <picture type="preview"></picture>
tx  </iq>



[] 11:11:02am Start Now:
rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="ob99q_s6sqI:APA91beUqB6yJ7pCbuLmu2937JPmruuIZA3
xLpjzGp72edDxFXmUOaTygaKHlKB8fN21hQ_VuJp7-8bEQoaSy3n00_y1k8PMtsX_NZ4uM6d2VHk_c_c
u16oKXeuugKAHXirDYuMOhB1I"></config>
rx  </iq>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></
presence>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="error" id="07">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <status>
rx      <user jid="XXXXXXXXXXX@s.whatsapp.net" t="1460903044">Hey there! I am usi
ng WhatsApp.</user>
rx    </status>
rx  </iq>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="result" id="05">
rx    <picture id="1447575006" type="preview"> 2176 byte data</picture>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="06">
rx    <status>
rx      <user jid="XXXXXXXXXXX@s.whatsapp.net" t="1458350655">Hey there! I am us
ing WhatsApp.</user>
rx    </status>
rx  </iq>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1462331
405"></presence>


11:16:53am.....[keep-alive] Ping sent.....
tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="08" t="1462331814"></iq>


11:22:50am.....[keep-alive] Ping sent.....
tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="09" t="1462332171"></iq>


.....Disconnected Manually.....
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">63d801be36303137373631353339373
519511017f2219a672426d91add9f1d4315ed5131343632333332353238</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>5eefd24079f3760a15b27e1f0e8b0829ca4c7f5b</challenge>

tx  <response>cb7b26d557abbd95d72db9991e30ef4ed6c2ca05ed62bc979bcc64a4ca863b33ef
964ae81ba2adc610ddfe9e68afd43adc6adc66b8ded13d1b2e0b9296649c70602b7582905688df82
41ddb02f</response>

rx  <success t="1462332529" props="5" kind="free" status="active" creation="1462
330553" expiration="4444444444">1d1710dc80e19cd99750176fd491bc48486fa428</succes
s>

tx  <presence name="WAWA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_ab8c039f-e479-
4e2f-8b73-f5f239c13a73" index="0" last="true">
tx      <user>+XXXXXXXXXXX</user>
tx      <user>+XXXXXXXXXXX</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="60177615397@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1462331
405"></presence>

rx  <iq from="60177615397@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="60177615397@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_ab8c039f-e479-4e2f-8b73-f5f239c13a73" l
ast="true" version="1462330619943694">
rx      <in>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx      </in>
rx    </sync>
rx  </iq>


XXXXXXXXXXX@s.whatsapp.net exists

XXXXXXXXXXX@s.whatsapp.net exists
tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="04">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.n
et">
tx    <picture type="preview"></picture>
tx  </iq>

tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="06">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="07" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.
net">
tx    <picture type="preview"></picture>
tx  </iq>



[] 11:28:50am Start Now:
rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="ob99q_s6sqI:APA91beUqB6yJ7pCbuLmu2937JPmruuIZA3
xLpjzGp72edDxFXmUOaTygaKHlKB8fN21hQ_VuJp7-8bEQoaSy3n00_y1k8PMtsX_NZ4uM6d2VHk_c_c
u16oKXeuugKAHXirDYuMOhB1I"></config>
rx  </iq>


11:31:49am.....[keep-alive] Ping sent.....
tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


Warning: socket_write(): unable to write to socket [10053]: An established conne
ction was aborted by the software in your host machine.
 in C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php on line 2753

11:34:50am.....[keep-alive] Ping sent.....
tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


Warning: socket_write(): unable to write to socket [10053]: An established conne
ction was aborted by the software in your host machine.
 in C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php on line 2753

.....Disconnected Manually.....
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">076426b436303137373631353339371
d1710dc80e19cd99750176fd491bc48486fa42831343632333333303730</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>808b5414c26d92d795f3994972525baa85ece49f</challenge>

tx  <response>d03bb2c6910e46f83f9b331bc83e727693f180131b091718eb58261be785145376
a79903571ae34e3f5f4f15d4526a999b8a08beae3750fe13c0c445424d8d9bea1c03bb28edec47c1
81e35b5b</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\Chat-
API-master\src\Login.php:54
Stack trace:
#0 C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php(286): Login->doLogin(
)
#1 C:\xampp\htdocs\Chat-API-master\tests\whatsapp3.php(81): WhatsProt->loginWith
Password('7H/9GddvDEay6KQ...')
#2 {main}
  thrown in C:\xampp\htdocs\Chat-API-master\src\Login.php on line 54
`

**Comment by samuelg78** [comment]
.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">93c05f8136303137373631353339373
f1a1429f7dbe778378f55a6b85291e6c729e04e31343632333331343631</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b713d8cdfc441fa6b1c8756b3753727d08f439f3</challenge>

tx  <response>eb0dcd885dc30ec7a75153d73e0aa3f0814ac97af557484846715d59dc1ecd46ec
c08f5bda93303252157459180825893ee17597ebb9cedcc4b525713004ebff19af6a67e67bd0c36f
87b559a9</response>

rx  <success t="1462331462" props="5" kind="free" status="active" creation="1462
330553" expiration="4444444444">3519511017f2219a672426d91add9f1d4315ed51</succes
s>

tx  <presence name="WAWA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_81f1f53e-feef-
4ad3-a99c-539ddd00ded6" index="0" last="true">
tx      <user>+XXXXXXXXXXX</user>
tx      <user>+XXXXXXXXXXX</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="60177615397@s.whatsapp.net"></presence>

rx  <iq from="60177615397@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="60177615397@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_81f1f53e-feef-4ad3-a99c-539ddd00ded6" l
ast="true" version="1462330619943694">
rx      <in>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx      </in>
rx    </sync>
rx  </iq>


XXXXXXXXXXX@s.whatsapp.net exists

XXXXXXXXXXX@s.whatsapp.net exists
tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="04">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.n
et">
tx    <picture type="preview"></picture>
tx  </iq>

tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="06">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="07" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.
net">
tx    <picture type="preview"></picture>
tx  </iq>



[] 11:11:02am Start Now:
rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="ob99q_s6sqI:APA91beUqB6yJ7pCbuLmu2937JPmruuIZA3
xLpjzGp72edDxFXmUOaTygaKHlKB8fN21hQ_VuJp7-8bEQoaSy3n00_y1k8PMtsX_NZ4uM6d2VHk_c_c
u16oKXeuugKAHXirDYuMOhB1I"></config>
rx  </iq>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></
presence>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="error" id="07">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <status>
rx      <user jid="XXXXXXXXXXX@s.whatsapp.net" t="1460903044">Hey there! I am usi
ng WhatsApp.</user>
rx    </status>
rx  </iq>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="result" id="05">
rx    <picture id="1447575006" type="preview"> 2176 byte data</picture>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="06">
rx    <status>
rx      <user jid="XXXXXXXXXXX@s.whatsapp.net" t="1458350655">Hey there! I am us
ing WhatsApp.</user>
rx    </status>
rx  </iq>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1462331
405"></presence>


11:16:53am.....[keep-alive] Ping sent.....
tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="08" t="1462331814"></iq>


11:22:50am.....[keep-alive] Ping sent.....
tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="09" t="1462332171"></iq>


.....Disconnected Manually.....
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">63d801be36303137373631353339373
519511017f2219a672426d91add9f1d4315ed5131343632333332353238</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>5eefd24079f3760a15b27e1f0e8b0829ca4c7f5b</challenge>

tx  <response>cb7b26d557abbd95d72db9991e30ef4ed6c2ca05ed62bc979bcc64a4ca863b33ef
964ae81ba2adc610ddfe9e68afd43adc6adc66b8ded13d1b2e0b9296649c70602b7582905688df82
41ddb02f</response>

rx  <success t="1462332529" props="5" kind="free" status="active" creation="1462
330553" expiration="4444444444">1d1710dc80e19cd99750176fd491bc48486fa428</succes
s>

tx  <presence name="WAWA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_ab8c039f-e479-
4e2f-8b73-f5f239c13a73" index="0" last="true">
tx      <user>+XXXXXXXXXXX</user>
tx      <user>+XXXXXXXXXXX</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="60177615397@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1462331
405"></presence>

rx  <iq from="60177615397@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="60177615397@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_ab8c039f-e479-4e2f-8b73-f5f239c13a73" l
ast="true" version="1462330619943694">
rx      <in>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx      </in>
rx    </sync>
rx  </iq>


XXXXXXXXXXX@s.whatsapp.net exists

XXXXXXXXXXX@s.whatsapp.net exists
tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="04">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.n
et">
tx    <picture type="preview"></picture>
tx  </iq>

tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="06">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="07" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.
net">
tx    <picture type="preview"></picture>
tx  </iq>



[] 11:28:50am Start Now:
rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="ob99q_s6sqI:APA91beUqB6yJ7pCbuLmu2937JPmruuIZA3
xLpjzGp72edDxFXmUOaTygaKHlKB8fN21hQ_VuJp7-8bEQoaSy3n00_y1k8PMtsX_NZ4uM6d2VHk_c_c
u16oKXeuugKAHXirDYuMOhB1I"></config>
rx  </iq>


11:31:49am.....[keep-alive] Ping sent.....
tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


Warning: socket_write(): unable to write to socket [10053]: An established conne
ction was aborted by the software in your host machine.
 in C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php on line 2753

11:34:50am.....[keep-alive] Ping sent.....
tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


Warning: socket_write(): unable to write to socket [10053]: An established conne
ction was aborted by the software in your host machine.
 in C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php on line 2753

.....Disconnected Manually.....
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">076426b436303137373631353339371
d1710dc80e19cd99750176fd491bc48486fa42831343632333333303730</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>808b5414c26d92d795f3994972525baa85ece49f</challenge>

tx  <response>d03bb2c6910e46f83f9b331bc83e727693f180131b091718eb58261be785145376
a79903571ae34e3f5f4f15d4526a999b8a08beae3750fe13c0c445424d8d9bea1c03bb28edec47c1
81e35b5b</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\Chat-
API-master\src\Login.php:54
Stack trace:
#0 C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php(286): Login->doLogin(
)
#1 C:\xampp\htdocs\Chat-API-master\tests\whatsapp3.php(81): WhatsProt->loginWith
Password('7H/9GddvDEay6KQ...')
#2 {main}
  thrown in C:\xampp\htdocs\Chat-API-master\src\Login.php on line 54
