### ISSUE TITLE
Whatsaap Number got blocked after sending 2-3 messages.. haven't sent any bulk message. Please tell me how to get my number unblocked,

### ISSUE THREAD

**Issue by Subhajitmukherjee93** [mgp25/Chat-API#1886]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by 0xTryCatch** [comment]
Go away
