### ISSUE TITLE
Tool doesn't work. 

### ISSUE THREAD

**Issue by jarscr** [mgp25/Chat-API#1888]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Have problem with WhatsApp api?
Use the request Code 6 digits, but doesn't work, WART don't work
There was a problem trying to request the code.

####################
#                  #
# WA Register Tool #
#                  #
####################

Username (country code + number, do not use + or 00): Array
(
    [cc] => 506
    [in] => xxxxxx
    [lg] => es
    [lc] => CR
    [id] => ��������p�|���#�
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 1541
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 25130
    [voice_wait] => 0
)
There was a problem trying to request the code.

**Comment by mgp25** [comment]
Wrong identity, delete all .dat files inside wadata folder and retry, it should work fine then, this is a duplicate issue, make sure to search before opening a new issue

**Comment by jarscr** [comment]
Hello,

Now show this: An error occurred registering the registration code from WhatsApp. Reason: mismatch

What mean?

Regards

**Comment by jarscr** [comment]
Hello, I see need wait tomorrow for try.

[status] => fail [reason] => too_many_guesses [retry_after] => 86400 ) An error occurred registering the registration code from WhatsApp. Reason: too_many_guesses 

REgards

**Comment by wehmoen** [comment]
See here for more Information about code registration errors: https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#number-registration
