### ISSUE TITLE
Ajaxdemo

### ISSUE THREAD

**Issue by jaschachtner** [mgp25/Chat-API#1889]
Recently I use the ajaxdemo in this repository to test the code but after send 5 messages to my other number, whatsapp blocked my number.

Is.any wrong with thw ajaxdemo code? 

Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by eftimie-andrei** [comment]
#1872 (Read the wiki), only 2 ping!!!

**Comment by mgp25** [comment]
@jaschachtner without debug log is hard to tell, when you have the debug log, post it here and ill check it

AjanDemo is a little outdated by the way, i recommend you to build your own script

Regards
