### ISSUE TITLE
Question: new token extraction problem

### ISSUE THREAD

**Issue by 0xFlitz** [mgp25/Chat-API#1890]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
I'm trying to reconstruct the pre-calculated key you are using in the token generation. but i reach different values.

I was able to extract the entire Key and salt in a base64. Then i replaced them in the script of the token generation, but i never reach the precalculated key base64 you are having...

I got the full WA key in B64, tried added it to the token extract tool, printed a b64 encoding of pbkdf2('sha1', $d, base64_decode($k), 128, 80, true); AND tried pbkdf2('sha1', $d, base64_decode($k), 128, 512, true); which is the same like in the code.

But i get: 
lqssRqHOGb/jdVj9FiJA7hxQjtULztQd6pQ8QiU7RUC/JkWi+UEpaCaNUbDBti8SOGdMlXNU+ZVJ0mcDOHL1Q6/mvLRFrqotSmWYsyHbwRlg6jEvDi1IeXABB7sPgqMV47l2OrXSPeZ68Oc+o1rkSysY7ioxeJdSbDu8p3zbSE0SVOZFE7Ldo/R2vQWvfinZeXHXq1Ogvs5D/W3jNydeEjiy6s03gT4o0TIvu9OnQGnZKpdkhxfepDEprO4Tw20Z8mgG2GCbN26QMLpM4ulLDTI2ejQvc07QCm5D0UH7IpJccAWq4nA6Us7EkkRQ3oa1vHsK2pBfdI27UVS70I1cwg+t+1T3iA0NNEAYAejip6ZPiR9AYw37plx1trxwhMcwrpC7IzhmC4QTU0G8d62dW9AYs9cxfG5ClhBUk4RiQaX0vgjPdKE5SCpy1t+aU0fTFpX5JEDO/TiUJtSlzizcYj/fM/bx

Which is not:
eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A= 
What am i doing wrong? would love some pointers.

**Comment by marituss** [comment]
Are you doing it using pw file ? I mean extracting from device.

**Comment by mgp25** [comment]
This is nit the best place to talk about this

Regards
