### ISSUE TITLE
Register again

### ISSUE THREAD

**Issue by Kliton** [mgp25/Chat-API#1894]
I can register ( a number ) that i have already registered with whatsapp?

**Comment by Martin29DE** [comment]
when you re-register a number - then going the number only on the new whatsapp.
when your number blocked is, the can you not register the number

**Comment by Kliton** [comment]
Ok, i have a number already registered with whatsapp but i'm not using that number at this moment in any device.

When i try to register the number it says the i have a wrong number.
Wh

**Comment by mgp25** [comment]
No debug log = invalid issue

I think this was answered in many issues + read the FAQ im sure you will find the answer in there.

Regards
