### ISSUE TITLE
Error sending to people with old versions/unenrypted

### ISSUE THREAD

**Issue by aderry** [mgp25/Chat-API#1895]
### Error
Error in function getChild() on null in IqHandler : Line 257

### Cause

The API doesn't check if the recipient has keys or not ( old versions ) , it should only encrypt messages once keys exists ( or implement a function to check if user is on an older version or not -- keys exists )

**Comment by mgp25** [comment]
Are you sure the number are you texting exists? And by exist i mean, registered in WhatsApp + without debug log this issue is invalid.

Right now most of the users should have encryption if not all.

If you want further support, post full debug log

Regards
