### ISSUE TITLE
Refresh Favorites(official client)

### ISSUE THREAD

**Issue by eaba** [mgp25/Chat-API#1896]
Make sure these boxes are checked before submitting your issue -- thank you!

- [* ] You are using PHP > 5.6
- [ *] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [* ] You have checked if someone has already asked the same issue you have.
- [ *] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ *] Is not a programming question.
- [ *] You are using latest Chat API code.

### Error
Post your error below:
@mgp25, @0xTryCatch, @shirioko, In the official client there is an option to refresh(which I believe is re-sync) favorites!

Please what mode and context does the official client use to re-sync and does it re-sync all contacts in the address book at once, even if it very large?

Thanks!

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
All at once, default

**Comment by eaba** [comment]
mode = 'full', context = 'registration' ?

**Comment by mgp25** [comment]
default. `sendSync($numbers)`

**Comment by eaba** [comment]
Sorry am on c# version, i wanted to know what php version translate to on C#
Thanks
