### ISSUE TITLE
Need suggestions

### ISSUE THREAD

**Issue by madhatter42** [mgp25/Chat-API#1899]
This isn't an issue as much as a call for suggestions. I have a script that functions like a producer-consumer. It picks up incoming messages from users and responds accordingly. The script runs for around 5 seconds each time and then restarts. It logs in to Whatsapp every time. I'd been running this successfully for the last 8 weeks or so but yesterday, all the numbers I tried with it started getting banned. 

Does anybody have suggestions as to what can be done to prevent this? Should one not log in more than once in a short period of time? 

I'm also syncing contacts per the documentation in the wiki.

**Comment by mgp25** [comment]
Post debug log.

5 seconds each time? Why? Thats completly wrong.

`Should one not log in more than once in a short period of time?` Of course not! have you read other closed issues?

Regards

**Comment by madhatter42** [comment]
Yes I did read previous issues but didn't see anything about log in frequency. Would be great if we could compile *one* list of best practices. Also, how can I maintain one long connection with the API while both sending and receiving messages? Appreciate your advice.

Here's the debug log as it stands now. I don't have it from before we got blocked:

```tx  <stream:features></stream:features>

tx  <auth user="919810375825" mechanism="WAUTH-2">689a699c3931393831303337353832350c1097ee0931d30abb6880d25807a72977666b6b31343632383834363431</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>570100a143aa093ee3228095d3fca4120048fb5c</challenge>

tx  <response>87fda177550af889c5d718d6059e1b81472de53878a98335cd675184ce48bcb4f25e9d038b0d6f162accc2f14fda2dcd69cc82078bbf830977fc34d7b192ccc732f98746b19ae275986a402290cc</response>

rx  <success t="1462884642" props="5" kind="free" status="active" creation="1462859328" expiration="4444444444">6e32d261eb3ed8d01038147313ca73377af00d77</success>

tx  <presence name="Laxmi" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="04" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="Android" version="2.12.556"></config>
tx  </iq>

tx  <iq id="05" to="919810375825@s.whatsapp.net" type="set" xmlns="w:profile:picture">
tx    <picture type="image"> 39570 byte data</picture>
tx    <picture type="preview"> 2573 byte data</picture>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="919810375825@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="03">
rx    <props version="5">
rx      <prop name="allow" value="all"></prop>
rx      <prop name="archive" value="1"></prop>
rx      <prop name="audio_opus" value="1"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="call" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="doc_types" value="csv,doc,docx,pdf,ppt,pptx,rtf,txt,xls,xlsx"></prop>
rx      <prop name="e2e_audio" value="0"></prop>
rx      <prop name="e2e_blists" value="1"></prop>
rx      <prop name="e2e_groups" value="1"></prop>
rx      <prop name="e2e_images" value="1"></prop>
rx      <prop name="e2e_video" value="0"></prop>
rx      <prop name="e2e_voip" value="1"></prop>
rx      <prop name="file_max_size" value="100"></prop>
rx      <prop name="force_long_connect" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="identity_verification" value="1"></prop>
rx      <prop name="image_max_edge" value="1280"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx      <prop name="max_participants" value="257"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="media_max_autodownload" value="32"></prop>
rx      <prop name="mspes" value="1"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="plaintext_disabled" value="1"></prop>
rx      <prop name="plaintext_reenable_threshold" value="5"></prop>
rx      <prop name="qr" value="1"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="small_call_btn" value="1"></prop>
rx      <prop name="source" value="3"></prop>
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="wbarchive" value="1"></prop>
rx    </props>
rx  </iq>

rx  <iq from="919810375825@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04"></iq>

rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="eu7Ad_ABbBY:APA91bMYX6PFwOdtUE5llm2FSvTwEIEgYBsO1zdB5oavmjkdoQvQbGQHft9YQzN6NBDqVW_vRQYZ-iARfJ4LmXJ77_qvLWIoeFu_6x9fehNsXBf_k_p5MNRbqkTQjk6BQo8aIVQ9tOPT"></config>
rx  </iq>

rx  <iq from="919810375825@s.whatsapp.net" type="result" id="05">
rx    <picture id="1462884643"></picture>
rx  </iq>```

I'm also posting my source here:

sendAndReceive.php:
```
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once 'lib/ChatClient.php';
require_once 'lib/Cache.php';
require_once 'lib/Send.php';

use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

class SendAndReceive
{
    const QUEUE_RECEIVE_MESSAGES = 'mesl_receive_messages';
    const QUEUE_SEND_MESSAGES = 'mesl_send_messages';
    const QUEUE_SYNC_CONTACTS = 'mesl_sync_contacts';
    const QUEUE_MESSAGE_STATUS = 'mesl_message_status';

    const KEY_LAST_SYNC_TIME = 'mesl_last_sync_time';

    protected $chatClient;

    protected $cache;

    protected $amqpConnection;

    protected $environment;

    protected $receiveChannel;
    protected $sendChannel;
    protected $syncChannel;
    protected $messageStatusChannel;

    public function __construct()
    {
        $this->environment = getenv('NODE_ENV');
        if(!$this->environment) {
            $this->environment = 'development';
        }

        if('production' === $this->environment) {
            $now = new DateTime();
            $now->setTimezone(new DateTimeZone('Asia/Calcutta'));
            $hour = $now->format('H');
            if($hour >= 0 && $hour <= 6) {
                sleep(600);
                throw new Exception('Sleeping!! :)');
            }
        }

        $this->chatClient = new ChatClient($this->environment);
        $this->cache = new Cache();

        $this->amqpConnection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
        
        $this->sendChannel = $this->amqpConnection->channel();
        $this->receiveChannel = $this->amqpConnection->channel();
        $this->syncChannel = $this->amqpConnection->channel();
        $this->messageStatusChannel = $this->amqpConnection->channel();

        $this->receiveChannel->queue_declare(self::QUEUE_RECEIVE_MESSAGES, false, true, false, false);
        $this->sendChannel->queue_declare(self::QUEUE_SEND_MESSAGES, false, true, false, false);
        $this->syncChannel->queue_declare(self::QUEUE_SYNC_CONTACTS, false, true, false, false);
        $this->messageStatusChannel->queue_declare(self::QUEUE_MESSAGE_STATUS, false, true, false, false);
    }

    public function __destruct() 
    {
        $this->sendChannel->close();
        $this->receiveChannel->close();
        $this->syncChannel->close();
        $this->messageStatusChannel->close();
        $this->amqpConnection->close();
    }

    public function syncContacts()
    {
        if('production' != $this->environment) {
            return;
        }

        $that = $this;   
        
        $numbers = array();
        $messageTags = array();
        $callback = function($msg) use ($that, &$numbers, &$messageTags) {
            $message = json_decode($msg->body, true);
            $phoneNumber = $message['phoneNumber'];
            
            $messageTags[] = $msg->get('delivery_tag');
            $numbers[] = $phoneNumber;
        };

        $this->syncChannel->basic_consume(self::QUEUE_SYNC_CONTACTS, '', false, false, false, false, $callback);

        try {
            while(count($this->syncChannel->callbacks)) {
                $this->syncChannel->wait(null, false, 5);
            }
        } catch(\Exception $e) {
            if(count($numbers)) {
                $this->chatClient->sync($numbers);
                foreach($messageTags as $tag) {
                    $that->syncChannel->basic_ack($tag);    
                }
                self::logMsg('Synced ' . json_encode($numbers));
            }
        }
    }

    public function getMessageStatus()
    {
        $that = $this;

        $callback = function($status) use ($that) {
            $that::logMsg('Received status: ' . json_encode($status));

            $message = array(
                'from'       => $status['from'],
                'externalId' => $status['id'],
                'status'     => $status['type'],
                'time'       => $status['time'],
            );
            
            $queueMsg = new AMQPMessage(
                json_encode($message), 
                array('delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT)
            );
            $that->messageStatusChannel->basic_publish($queueMsg, '', $that::QUEUE_MESSAGE_STATUS);
            $that::logMsg('Successfully published status; Message ID: ' . $status['id']);
        };

        $this->chatClient->getMessageRecievedClientStatus($callback);
    }

    public function receive()
    {
        $that = $this;

        $callback = function($msg) use ($that) {
            $that::logMsg('Received message: ' . json_encode($msg));

            $messageId = $msg['id'];
            $ts = $msg['time'];
            
            // Check if message already encountered
            if($that->cache->keyExists($messageId)) {
                $that::logMsg('Message already received; ID: ' . $messageId);
                return;
            }
            
            // 24 hours should be enough
            $this->cache->setKey($messageId, 1, 24 * 60 * 60);

            $receivedMessage = array(
                'from'       => $msg['from'],
                'externalId' => $messageId,
            );
            
            if('media' == $msg['type']) {
                $receivedMessage['url'] = $msg['url'];
            } else {
                $receivedMessage['message'] = $msg['data'];
            }
            
            $queueMsg = new AMQPMessage(
                json_encode($receivedMessage), 
                array('delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT)
            );
            $that->receiveChannel->basic_publish($queueMsg, '', $that::QUEUE_RECEIVE_MESSAGES);
            $that::logMsg('Successfully published message; ID: ' . $messageId);
        };

        $this->chatClient->receive($callback);
    }

    public function send()
    {
        $that = $this;
        
        $callback = function($msg) use ($that) {
            $that::logMsg('Sending message: ' . $msg->body);
            $message = json_decode($msg->body, true);
            $body = $message['message'];
            $target = $message['target'];
            $id = $message['id'];
            $ts = $message['ts'];
            $now = time();

            // Retry sending message a few times
            $numTries = $that->cache->getKey($id);
            $numRetries = 1; // No retries for now to prevent being blocked
            if($numTries >= $numRetries) {
                $that->sendChannel->basic_ack($msg->get('delivery_tag'));
                $that::logMsg('Message with ID ' . $id . ' to ' . $target . ' could not be sent');
                return;
            } else if(!$numTries) {
                $numTries = 0;
            }
            $that->cache->setKey($id, ++$numTries, 10 * 60);

            $mediaUrl = isset($message['mediaUrl']) ? $message['mediaUrl'] : null;
            $send = new Send($that->chatClient, $body, $target, $mediaUrl);
            $messageId = $send->queueMessageAndGetMessageId();

            // Sent message
            $sentMessage = array(
                'to'         => $target,
                'externalId' => $messageId,
                'internalId' => $id,
                'message'    => $body,
                'url'        => $mediaUrl, 
                'time'       => time()
            );
            $queueMsg = new AMQPMessage(
                json_encode($sentMessage), 
                array('delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT)
            );
            $that->messageStatusChannel->basic_publish($queueMsg, '', $that::QUEUE_MESSAGE_STATUS);
            
            sleep(rand(1, 5));

            $send->doSend();
            
            $that->sendChannel->basic_ack($msg->get('delivery_tag'));
            $that::logMsg('Successfully sent message to ' . $target);
        };

        $this->sendChannel->basic_consume(self::QUEUE_SEND_MESSAGES, '', false, false, false, false, $callback);

        try {
            $waitTime = rand(5, 10); // To prevent being blocked - this effects how often we log in
            while(count($this->sendChannel->callbacks)) {
                // This throws an exception when it times out
                // we want to swallow it so that the script doesn't
                // terminate unexpectedly
                $this->sendChannel->wait(null, false, $waitTime);
            }
        } catch(\Exception $e) { }
    }

    public static function logMsg($message)
    {
        echo '[' . date('Y-m-d H:i:s') . '] ' . $message . "\n";
    }
}

try {
    $fp = fopen('/tmp/chat-sendAndReceive.lock', 'w+');
    // Acquire exclusive lock on file to ensure
    // only one instance of this script runs at a time
    if(!flock($fp, LOCK_EX)) {
        exit(1);
    }
    
    $sr = new SendAndReceive();
    
    $cache = new Cache();
    $lastTime = $cache->getKey(SendAndReceive::KEY_LAST_SYNC_TIME);
    // Syncing should be done every 30 minutes
    $now = time();
    if(!$lastTime || $lastTime <= $now - 30 * 60) {
        $sr->syncContacts();
        $cache->setKey(SendAndReceive::KEY_LAST_SYNC_TIME, $now, 24 * 60 * 60);
    }
    $sr->getMessageStatus();
    $sr->receive();
    $sr->send();
} catch(\Exception $e) {
    SendAndReceive::logMsg('Exception: ' . $e->getMessage() . ' TRACE: ' . $e->getTraceAsString());
} finally {
    flock($fp, LOCK_UN);
}
```

Send.php:
```
<?php

require_once __DIR__ . '/ChatClient.php';
require_once __DIR__ . '/Response.php';

class Send 
{
	protected $message;

	protected $target;

	protected $mediaUrl;

	protected $chatClient;

	public function __construct(ChatClient $chatClient, $message, $target, $mediaUrl = null)
	{
		if(is_null($target) || (is_null($message) && is_null($mediaUrl))) {
			throw new Exception('Required argument not present');
		}

		$this->message = trim($message);
		$this->mediaUrl = trim($mediaUrl);
		$this->target = trim($target);

		$this->chatClient = $chatClient;
	}

	public function queueMessageAndGetMessageId()
	{
		if($this->isMessageAudio()) {
			return $this->chatClient->sendAudio($this->mediaUrl, $this->target, false);
		}
				
		if($this->isMessageImage()) {
			return $this->chatClient->sendImage($this->mediaUrl, $this->target, $this->message, false);
		}
		
		return $this->chatClient->sendMessage($this->message, $this->target, false);
	}

	public function doSend()
	{
		$this->chatClient->poll();
	}

	protected function isMessageAudio()
	{
		if(preg_match('/\.(wav|mp3)$/', $this->mediaUrl)) {
			return true;
		}

		return false;
	}

	protected function isMessageImage()
	{
		if(preg_match('/\.(jpg|png|gif)$/', $this->mediaUrl)) {
			return true;
		}

		return false;
	}
}
```

ChatClient.php
```
<?php

require_once __DIR__ . '/../vendor/autoload.php';

class ChatClient
{
	protected $password;

	protected $client;

	protected $receiveCallback;

	protected $messageReceivedClientCallback;

	public function __construct($environment = 'development') 
	{
		$configFile = file_get_contents(__DIR__ . '/../config/config.json', 'r');
		$configFileContents = json_decode($configFile, true);
		if(!isset($configFileContents[$environment])) {
			throw new Exception('Could not find config for environment ' . $environment);
		}
		$config = $configFileContents[$environment];

		$username = $config['username'];
		$nickname = $config['nickname'];
		$password = $config['password'];
		$this->password = $password;

		$dataFolder = __DIR__ . '/../data';
		$this->client = new WhatsProt($username, $nickname, true, true, $dataFolder);
		$this->connect();
		$this->login();

		$this->client->sendGetServerProperties();
		$this->client->sendClientConfig(); 

		$this->client->sendSetProfilePicture(__DIR__ . '/../profile/teacher.jpg');
	}

	public function __destruct()
	{
		$this->disconnect();
	}

	public function __call($method, $args)
    {
		if(is_callable(array($this, $method))) {
			return call_user_func_array($this->$method, $args);
		}
    }

	private function connect() 
	{
		$this->client->connect();
	}

	private function disconnect() 
	{
		$this->client->disconnect();
	}

	private function login() 
	{
		$this->client->loginWithPassword($this->password);
	}

	private function checkForConnection()
	{
		if(!$this->client->isConnected()) {
			$this->connect();
		}
		if(!$this->client->isLoggedIn()) {
			$this->login();
		}
	}

	public function sendMessage($message, $target, $send = true)
	{
		$this->checkForConnection();

		$messageId = $this->client->sendMessage($target, $message);

		if($send) {
			$this->poll();	
		}

		return $messageId;
	}

	public function sendAudio($fileUrl, $target, $send = true)
	{
		$this->checkForConnection();

		$messageId = $this->client->sendMessageAudio($target, $fileUrl, true, 0, '', true);

		if($send) {
			$this->poll();	
		}
		
		return $messageId;
	}

	public function sendImage($fileUrl, $target, $caption = null, $send = true)
	{
		$this->checkForConnection();

		$messageId = $this->client->sendMessageImage($target, $fileUrl, true, 0, '', $caption);

		if($send) {
			$this->poll();	
		}
		
		return $messageId;
	}

	public function receive(callable $callback)
	{
		$this->receiveCallback = $callback;

		$this->client->eventManager()->bind(
			'onGetMessage', 
			array($this, 'processReceivedMessage')
		);

		$this->client->eventManager()->bind(
			'onGetAudio',
			array($this, 'processReceivedAudio')
		);

		$this->poll();
	}

	public function poll()
	{
		$poll = true;
		while($poll) {
			$this->checkForConnection();
			$poll = $this->client->pollMessage();
		}
	}

	public function sync(array $numbers)
	{
		return $this->client->sendSync($numbers, null, 3);
	}

	public function getMessageRecievedClientStatus(callable $callback)
	{
		$this->messageReceivedClientCallback = $callback;

		$this->client->eventManager()->bind(
			'onMessageReceivedClient', 
			array($this, 'processMessageReceivedClient')
		);
	}

	public function processMessageReceivedClient(
		$phone, 
		$from, 
		$id, 
		$type, 
		$time, 
		$participant
	) {
		$matches = null;
        if (preg_match('/\d*/', $from, $matches)) {
            $from = $matches[0];
        }

		$this->messageReceivedClientCallback(array(
			'phone' => $phone,
			'from'  => $from,
			'id'    => $id,
			'type'  => $type,
			'time'  => $time,
		));
	}

	public function processReceivedAudio(
		$phone, 
		$from, 
		$id, 
		$type, 
		$time, 
		$name, 
		$size, 
		$url, 
		$file, 
		$mimeType, 
		$fileHash, 
		$duration, 
		$acodec
	) {
		$matches = null;
        if (preg_match('/\d*/', $from, $matches)) {
            $from = $matches[0];
        }

        $msg = array(
        	'phone' 	=> $phone, 
        	'from' 		=> $from, 
        	'id' 		=> $id, 
        	'type' 		=> $type, 
        	'time' 		=> $time, 
        	'name' 		=> $name, 
        	'url' 		=> $url,
        	'mimeType'	=> $mimeType,
        	'fileHash'	=> $fileHash,
        );

        $this->receiveCallback($msg);
	}

	public function processReceivedMessage(
		$phone, 
		$from, 
		$id, 
		$type, 
		$time, 
		$name, 
		$data
	) {

    	$matches = null;
        if (preg_match('/\d*/', $from, $matches)) {
            $from = $matches[0];
        }

        $msg = array(
        	'phone' => $phone, 
        	'from' 	=> $from, 
        	'id' 	=> $id, 
        	'type' 	=> $type, 
        	'time' 	=> $time, 
        	'name' 	=> $name, 
        	'data' 	=> $data,
        );

        $this->receiveCallback($msg);
    }
}
```

**Comment by mgp25** [comment]
keep listening, polling

**Comment by madhatter42** [comment]
That's what I tried initially but found that I was frequently getting the `Connection Closed` exception. Hence decided to kill the connection myself ever so often and restart.

**Comment by madhatter42** [comment]
@mgp25 Quick question - do we need to call these two functions after logging in?

```
$w->sendGetServerProperties();
$w->sendClientConfig();
```

**Comment by madhatter42** [comment]
@mgp25 @0xTryCatch - how often should one log in? Also, what should the maximum session length be? I'm assuming we'd want to emulate a WhatsApp mobile client here. Any idea what do those do? Do they have a session timeout? If so, what is it?

**Comment by KduOliva** [comment]
hello, 

did you get some answer? i have the same problem, how the best way to constantly get messages to simulate de phone app?

**Comment by Sdlion** [comment]
See how works the client example from the example folder and update your dependencies.
In other issues is being told some remarks that are not that obvious in the wiki:

* Delete the ping in pollMessage() from whatsprot.class.php and manually ping the server with your script (with a longer interval, since the original is 60 seconds). But only ping 2 times each session, then disconnect, connect and loginWithPassword.
* Don't sync an already synced contact. Only sync after a login and not each time (you could use a variable or a database to keep recorded when was the last time you made a sync on all your contacts). Currently I'm syncing my contacts each hour (all at once).
* Follow the rules of presence subscriptions and unsubscriptions AND use `onNumber*` event handlers (Add/Changed/Removed notification nodes) to implement the needed behavior to avoid sending messages to unsynced/removed/not-subscribed/etc contacts.

These aren't the only caveats to watch out for. But I think that those are the less obvious.

Also, in the wake of the whatsapp full end-to-end encryption global implementation there were a lot of problems with axolotl sessions (the protocol used in end-to-end encryption). All those failed retries to deencrypt messages (Bad Mac and another warning I don't quite remember) would break the connection. It is said in other issues that this could be fixed deleting the axolotl database (in the wadata folder). I finally went deleting all entries on the `sessions` table of the axolotl database when an `onDisconnect` event would happen. I'm not sure if the whatsapp service stabilized itself or if it was an update con the Chat-API but since, I haven't had more problems with those disconnections.

**Comment by KduOliva** [comment]
Sdlion,

Tks for the answer, finally a straight and complete answer!

Just one concern : If i try constantly loginWithPassword, i'll be blocked, right?
Is it not better do something like that:

while (1) {
    $w->pollMessage();
    $msgs = $w->getMessages();
    foreach ($msgs as $m) {
           .....
    }
}

i don't want to abuse of you, but can you send some code example?
This is my first time with PHP and i am bit confused.
