### ISSUE TITLE
Whatsapp News

### ISSUE THREAD

**Issue by acondoriml** [mgp25/Chat-API#1904]
I received this

Important note: We have decided to stop offering WhatsApp via Chat API for the time being. This decision was taken because there is no reliable and sustainable way for us to connect with WhatsApp. WhatsApp for the past few weeks has been busy shutting down unofficial ways to connect making the service too unreliable.

The situations was fixed?

Ty

**Comment by rikysunandi** [comment]
any source? reference about that note?
