### ISSUE TITLE
chatapi registerTool is not working

### ISSUE THREAD

**Issue by rikysunandi** [mgp25/Chat-API#1905]
Hi @mgp25 @CODeRUS @SikiFn @shirioko .. i try to register my number with chatapi registerTool is not working, but when i try registertool  is working and get the code and then the password, but when i use that password to login with chatapi, its not working (check report below).. 

this error generated by chatapi registertool:
```
Rikys-MacBook-Pro:examples rikysunandi$ php registerTool.php 
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number without + or 00): 6285748492737
Array
(
    [cc] => 62
    [in] => 85748492737
????]a`?^?9so04f
    [lg] => id
    [lc] => ID
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
There was a problem trying to request the code.
```

so when i try to login with chatapi thats tell me its not authorize

generate Fatal error: Uncaught exception 'LoginFailureException'
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="6285748492737"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>����w0��t�~��>��</challenge>

tx  <response>0T�W�QLH_�������r��k5��&l��4�0�%~0J</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

- [ V] You are using PHP > 5.6
- [ V] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [V ] You have checked if someone has already asked the same issue you have.
- [ V] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [V ] Is not a programming question.
- [V ] You are using latest Chat API code.

Sorry for my poor english.. thank you for your response.. 👍 

[rikysunandi.com](http://rikysunandi.com)

**Comment by mgp25** [comment]
@rikysunandi 

1) both scripts are equal, where do you think they took the registerTool?
2) You are using a modified version of registerTool, it should ask you what method you want
3) You are using an outdated version of Chat API, use the latest one!!

**Comment by rikysunandi** [comment]
```
php registerTool.php 
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number without + or 00): 6285748492737


Type sms or voice: sms
Array
(
    [in] => 85748492737
    [cc] => 62
    [id] => ???d???l?
?]                   1t??
    [lg] => id
    [lc] => ID
    [sim_mcc] => 510
    [sim_mnc] => 000
    [method] => sms
    [token] => cc294edf53b4937a9ab5dde94f54d993
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
There was a problem trying to request the code
```

I got blocked?

**Comment by mgp25** [comment]
@rikysunandi you are still using an outdated version of registerTool, can you use latest one?

And yes, it seems you got blocked.
