### ISSUE TITLE
Extracting password from Bash.

### ISSUE THREAD

**Issue by JohnSHA1** [mgp25/Chat-API#1907]
Hello,

I have pw file and I referred to this but it seems not working. I have been following this since ages :P https://github.com/mgp25/Chat-API/wiki/Extracting-password-from-device#bash but now it's not working. I I know we want to extract some more data but I dont know how to do it. Can you update it please ?

Thanks!

**Comment by 0xTryCatch** [comment]
Extracting passwords is deprecated and thus not working anymore.
