### ISSUE TITLE
Pong error: xml-not-well-formed

### ISSUE THREAD

**Issue by hgc2002** [mgp25/Chat-API#1908]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Pong fails. The cause is that the previous ping received lacks of an id and pong code use it.

Pong is sent from handlers/IqHandler.php code. See:

```
public function Process() {
...
if ($this->node->getAttribute('type') == 'get'
    && $this->node->getAttribute('xmlns') == 'urn:xmpp:ping') {
            $this->parent->eventManager()->fire('onPing',
        [
            $this->phoneNumber,
            $this->node->getAttribute('id'),
        ]);
            $this->parent->sendPong($this->node->getAttribute('id'));
        }
```

Code from whatsapi.class.php
```
    public function sendPong($msgid)
    {
        $messageNode = new ProtocolNode('iq',
            [
                'to'   => Constants::WHATSAPP_SERVER,
                'id'   => $msgid,
                'type' => 'result',
            ], null, '');

        $this->sendNode($messageNode);
        $this->eventManager()->fire('onSendPong',
            [
                $this->phoneNumber,
                $msgid,
            ]);
    }
```

From here, ping id is required by pong (also, it's logical because the pong concept).
But check the ping structure received: id is not there!

Perhaps using the "t" atribute from ping into pong's id?
Copying the "t" attribute  in pong instead of id?
Any other idea?

### Debug log
```
rx  <iq from="s.whatsapp.net" type="get" t="1463136139" xmlns="urn:xmpp:ping"></iq>

tx  <iq to="s.whatsapp.net" id="" type="result"></iq>

rx  <stream:error>
rx    <xml-not-well-formed></xml-not-well-formed>
rx  </stream:error>
```

**Comment by mgp25** [comment]
Don't use `sendPong` maybe deprecated

Regards
