### ISSUE TITLE
Repetitive ping causes account block

### ISSUE THREAD

**Issue by hgc2002** [mgp25/Chat-API#1909]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
I've seen that my test accounts get closed right after a while sending ping to whatsapp, every minute.
This is the default behavior, I've not programmed this. 

When everything goes fine, program start pinging WA server and it responds. But after a long while, the phone is blocked (communiation lost, then phone get blocked).

Avoiding all ping responses, the agent do not crash anymore.

Any idea?

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
This is answered in other issue. Duplicate
