### ISSUE TITLE
How to access Notification Nodes?

### ISSUE THREAD

**Issue by shafihuzaib** [mgp25/Chat-API#1910]
Disclaimer: I read the wiki, searched for solutions, but probably was weak enough to figure out certain things.
Please help with the following..

1. I access the received messages using _getMessages()_ method. Is that the preferable method? If not, then what is?

2. When is the _add_ Notification Node of _type='contacts'_ received? When a new account is created? When the target exists, for which I sent the sync request? or when else, please explain.

3. How can I access the Notification Nodes. I _presenceSubscribe()_ to some number. Now when that number gets deleted from WhatsApp community, I am supposed to receive the _remove_ tag in the notification node, having _type='contacts'_.

       I tried the following code. But when I deleted a number I had subscribed to..., I wasn't able to find the notification node anywhere.

`$this->whatsApp = new WhatsProt($this->app->get('WHATSAPP_USERNAME'), true);

        $this->whatsApp->connect();
        $this->whatsApp->loginWithPassword($this->app->get('WHATSAPP_PASSWORD'));
        $events = new WhatsAppEvents($this->whatsApp);
        $events->setEventsToListenFor($events->activeEvents);

// The following two lines didn't help binding with ProcessNode - for unknown reasons
//        $pn = new ProcessNode($this->whatsApp, 'mynumber');
//        $this->whatsApp->setNewMessageBind($pn); 
        
       for ($i = 0; $i < 10; $i++)
            $this->whatsApp->pollMessage();

       $pN = $this->whatsApp->getPendingNodes();
       foreach ($pN as $n){
           echo "<br>\n-PN:";
           echo $n->nodeString();
       }
        
        $msgs = $this->whatsApp->getMessages();
        foreach ($msgs as $m) {
            // process inbound messages
            $type = $m->getAttribute('type');

            echo $m->nodeString();
            switch ($type) {

                case 'text':
                    echo "<br>\nYou received a text from " . $m->getAttribute('from');
                    break;

                case 'contacts':
                    $from = $m->getAttribute('from');
                    $user = explode('@', $from)[0];
                    $action = $m->getChild(0);
                    $action_type = $action->getTag();
                    if ($action_type == 'remove') {
                        //remove contact
                        echo '<br>\nRemoving contact ' . $user;
                        $this->whatsApp->sendPresenceUnsubscription($user);
                    } else if ($action_type == 'add') {
                        //add contact
                        echo '<br>\Adding contact ' . $user;
                        //$this->whatsApp->sendPresenceSubscription($user);
                    } else if ($action_type == 'update') {
                        //update contact
                        echo '<br>\nUpdating contact ' . $user;
                        $this->whatsApp->sendPresenceUnsubscription($user);
                        $this->whatsApp->sendPresenceSubscription($user);
                    } else {
                        //nothing
                        echo $m->nodeString();
                    }
                    break;

                default :

                    break;
            }

            // print($m->NodeString("") . "\n");
        }`

**Comment by mgp25** [comment]
Use event system

Regards

**Comment by shafihuzaib** [comment]
The only relevant events I see in the wiki are

onPresenceAvailable($mynumber, $from)
    onPresenceUnavailable($mynumber, $from, $last)

I don't understand where to find the onRemoveNumber event and such kinds. Please help a bit here!
