### ISSUE TITLE
Wierd error and block in a minimalistic program

### ISSUE THREAD

**Issue by xnfcre** [mgp25/Chat-API#1912]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Minimalistic program suddenly stops without doing anything with a fatal PHP error and is blocked afterwards.

The way I got blocked is rather interesting. I've got blocked before (I did know what I did wrong since then) and it exited me out with a Systems Shutdown message, this one just gave me some error.

Why is it wierd I got blocked?

- I was only listening for incoming messages and only responded if someone said: ".hoi".
- I was correctly synced once. I synced the number who sended a message the first time. Afterwards I removed this single line of code, to prevent it from syncing every time I sended a message.

``` PHP
$w->sendSync($num);
```

- I was the only one who ever sended any messages to this "bot", a grand total of 13 messages.
- I was blocked in the middle of nowhen, I hadn't sent any messages in a day or so.
- All the messages I sent:
![Messages I sent](http://i.imgur.com/PGQkHr0.jpg)

### Debug log

> Still inside of the normally operating program.

```xml
tx  <iq id="04de" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04de" t="1463073284"></iq>

tx  <iq id="04df" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04df" t="1463073346"></iq>

```

> Last automatticaly performed ping.

```xml
tx  <iq id="04e0" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04e0" t="1463073407"></iq>

PHP Fatal error:  Call to a member function getChildren() on null in /root/www/vendor/whatsapp/chat-api/src/handlers/IqHandler.php on line 256
```

> A while later, I tried to restart the program.

```xml
root@sas:~/www# php test2.php

tx  <stream:features></stream:features>

tx  <auth user="NotGivingYouMyNum" mechanism="WAUTH-2">Well it wouldn't really matter if I gave you my num and password, they're blocked anyway</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>BlaBlaBla, Why would whatsapp still make you login if you're blocked anyway, wouldn't that cause more load on their servers?</challenge>

tx  <response>I mean, if you were spamming their login functions, a DDoS attack would be easier if more calculations are performed on the server...</response>
```
> Oh, well..  My hope, shatterd in to tiny pieces by now.

```xml
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /root/www/vendor/whatsapp/chat-api/src/Login.php:54
Stack trace:
#0 /root/www/vendor/whatsapp/chat-api/src/whatsprot.class.php(286): Login->doLogin()
#1 /root/www/test2.php(13): WhatsProt->loginWithPassword('vnq576LFx6RhlTk...')
#2 {main}
  thrown in /root/www/vendor/whatsapp/chat-api/src/Login.php on line 54
```

### Code
> This is all the code I ever ran.

``` PHP
<?php
require 'vendor/autoload.php';
require 'vendor/whatsapp/chat-api/src/events/MyEvents.php';

$wuser = "CLASSIFIED";
$wnick = "Magister";
$wpass = "CLASSIFIED"; 
$w = new WhatsProt($wuser, $wnick, true); //Our WhatsProt object.
$wevents = new MyEvents($w); //We want to get our WhatsApp events.
$w->eventManager()->bind("onGetMessage", "onMessage");

$w->connect();
$w->loginWithPassword($wpass);

while(true){
	$w->pollMessage();
}


function onMessage($mynum, $rnum, $id, $type, $time, $name, $fcmd){
	global $w;
	$num = explode("@", $rnum)[0]; //We dont want the @whatsapp crap, so cut it off.
	$rcmd = strtolower(ltrim($fcmd, '.')); //The returncmd, based of the full command, ignorecaps.
	$capitalcmd = explode(" ", ltrim ($fcmd, '.')); //The cmd[] this time, don't ignore caps, it will come in handy when sending messages.
	$cmd = explode(" ", $rcmd); //The cmd[], ignoring caps.
	
	//I had this piece of code the first time I started the program, I sent one message with my private number (got synced), exited the program and removed this code, then ran it without this code.
	//$w->sendSync($num);
	
	if($cmd[0] == "hoi"){
		$w->sendMessageComposing($num);
		sleep(1);
		$w->sendMessage($num , "HALLO!");
	}
}
?>
```

### Question(s)
So have I done anything wrong? What is it this time? >.<

Do you need to wait say one second before polling messages again?
Can't you stay online for more than a day?

> **Thanks in advance, Kasper**

**Comment by mgp25** [comment]
@xnfcre 

1) post full debug loh
2) was the number synced?
