### ISSUE TITLE
not-authorized with expire

### ISSUE THREAD

**Issue by eaba** [mgp25/Chat-API#1914]
Make sure these boxes are checked before submitting your issue -- thank you!

- [yes ] You are using PHP > 5.6
- [ yes] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ yes] You have checked if someone has already asked the same issue you have.
- [yes ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ yes] Is not a programming question.
- [yes ] You are using latest Chat API code.

### Error
Post your error below:
Hello @mgp25 @0xTryCatch
```<failure>
rx   <not-authorized expire="258441" code="105" retry="129220"></not-authorized>
rx </failure>

```
I understand the retry_after but not the code and the expire attribute!
This is about the second time i am getting this error, the first was retry_after almost 23hours
Thanks

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Read wiki
