### ISSUE TITLE
CALLING HIVEMIND: Log in frequency 

### ISSUE THREAD

**Issue by madhatter42** [mgp25/Chat-API#1916]
Hey Chat-API users - I'm using the API in passive mode but am still getting banned. My hunch is because I'm logging in too frequently (every 10-15 mins). Has anyone experimented with log in frequency successfully and figured out how not to get blocked?

1. How often should one log in?
2. How long should one stay logged in?
3. What should the delay be between consecutive log ins?

**Comment by 0xTryCatch** [comment]
Stop opening issues about this subject
