### ISSUE TITLE
Running multi instances of WA client on one server

### ISSUE THREAD

**Issue by amrspace** [mgp25/Chat-API#1917]
Hello

I was created WhatsApp client using this API, but I'm running multi instance of this client on my Server with different phone numbers, Is this numbers will get blocked for running on one server?

How I can know the maximum numbers I can register from one server?

Kindly note: I'm using this clients for receive chats from the peoples, not for start chat with him, or send bulk messages.

**Comment by decklord** [comment]
I think you have higher chances of getting blocked. It's safer to use 1 IP -> 1 Number

**Comment by lssca** [comment]
No problems with IP , no matter if mass mailing or not.
