### ISSUE TITLE
Some performance questions

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1920]
Hello before anything, yes i read the wiki but could not find a clear answer to the following question, as these questions are in term or research.

1- How many time an official app get live groups, or in another term when the official app get live groups from the server?

2- Did changing the status and the profile picture in a short time can be detected as illegal action?

3- Can we do sleep between sending text message and sending picture message or this can be detected as illegal action because this is not found in the official app?

4- If i have a phone number which is registered into the lines of country a, in short time i have used register tool to register it on the server in country b, and i continue to use it on the server in country b. Did this behavior may conduit to block ?

Hope my questions are not noisy and are answerable, so we can understand how thins go in background of an official app so we can simulate a software that acts really as human and don't parasite whatsapp servers

Best Regards !

**Comment by MorpheusBrz** [comment]
1) Look LOG on first logon. You will find this "<prop name="max_groups" value="9999"></prop>"

2) What is "short time" for you? 1s, 1m, 1h, 1day, 1M, 1Y?

3) Human behavior is the best pratice. What a human do while using whatsapp?

4) Human behavior is the best pratice. What a human do while using whatsapp?

**Comment by MoudiZd** [comment]
mmm either my questions are not clear enough , either you don't want to answer me.
1- for the first question, i don't mean how many groups i can participate, but i mean when whatsapp perform a get live groups action, may this be done on each connect ? or in an official app this will not be done but in the first time the number is registered with whatsapp ?

2- for all other questions, i want to say that an official app sure do something in background so how can i simulate official app and by the way accomplish a human scenario if i don't know what's going in background ?

Per example a human change status and picture but i don't know if the official app must sleep one second per example after this change or not, and same thing for sending a message, if their is a delay between a text message and media message that is used by the official app

Are my questions too noisy or are too technical or are too stupid in all cases i think that you must help us to understand things happens behind scene so we can use this api legally and do not abuse neither whatsapp neither your team....

Regards
