### ISSUE TITLE
no_routes problem. No way to baypass registration step.

### ISSUE THREAD

**Issue by MakoLM** [mgp25/Chat-API#1921]
Hi,

I know this problem is already asked, but I tested plenty of times by different methods. Tried with carrier, tried with default carrier. Tried with WART online, offline. Tried with exampleRegistration.php, with registerTool.php, but no way was successful.

I don't know if is my IP or what. I have a dedibox at online.net and I'm requesting the registration over there.

Country: 54 (Argentina)
Mobile Provider: Telecom Personal S.A.
Mobile Number: 1124952757

> > ####################
> #                  #
> # WA Register Tool #
> #                  #
> ####################
> 
> 
> Username (country code + number, do not use + or 00): 541124952757
> 
> 
> Type sms or voice: sms
> Array
> (
>     [cc] => 54
>     [in] => 1124952757
>     [lg] => es
>     [lc] => AR
>     [id] => mê|xïâ°>ewä¢q>,øû$
>     [token] => cR48AkMeA8PlmPTp4xILKOXVKcc=
>     [mistyped] => 6
>     [network_radio_type] => 1
>     [simnum] => 1
>     [s] =>
>     [copiedrc] => 1
>     [hasinrc] => 1
>     [rcmatch] => 1
>     [pid] => 8494
>     [rchash] => dcdcf7062c2b5275f5c9415f426754fee3b1f3c34598b9454a8013125deaf522
>     [anhash] => 08422d040e92a519d7a84d843c0dac49
>     [extexist] => 1
>     [extstate] => 1
>     [mcc] => 722
>     [mnc] => 000
>     [sim_mcc] => 722
>     [sim_mnc] => 000
>     [method] => sms
> )
> stdClass Object
> (
>     [status] => fail
>     [reason] => no_routes
>     [retry_after] => 3600
>     [sms_wait] => 0
>     [voice_wait] => 0
> )
> There was a problem trying to request the code.

------------------------------------------------------------------------
On the other hand, locally WART exe says bad_token

![prblem](https://cloud.githubusercontent.com/assets/19395193/15301192/cf7f2862-1b82-11e6-8ac8-a5991256f153.jpg)

------------------------------------------------------------------------

WEB WART says invalid number or something like that.

------------------------------------------------------------------------

I don't know how to continue with this, I have php 5.6 and all the required libraries.

**Comment by moosavialeki** [comment]
I have exactly the same problem.

**Comment by MorpheusBrz** [comment]
Delete ".dat" file in "wadata" folder and try again.

Regards

**Comment by MakoLM** [comment]
After deleting .dat in "wadata" same problem. 

> ####################
> #                  #
> # WA Register Tool #
> #                  #
> ####################
> 
> 
> Username (country code + number, do not use + or 00): 541124952757
> 
> 
> Type sms or voice: sms
> Array
> (
>     [cc] => 54
>     [in] => 1124952757
>     [lg] => es
>     [lc] => AR
>     [id] =>
> Õwº
> 
> ò6
>     [token] => 7g4ZMcjWOqqUgit/HeLC6M63tNs=
>     [mistyped] => 6
>     [network_radio_type] => 1
>     [simnum] => 1
>     [s] =>
>     [copiedrc] => 1
>     [hasinrc] => 1
>     [rcmatch] => 1
>     [pid] => 9888
>     [rchash] => 5eb3959d616292e74f1911d90b01c2d97c0145fbe3666705662469948657f0f3
>     [anhash] => 790b95be5332b3d7d8fa08ccfaa9de7f
>     [extexist] => 1
>     [extstate] => 1
>     [mcc] => 722
>     [mnc] => 341
>     [sim_mcc] => 722
>     [sim_mnc] => 341
>     [method] => sms
> )
> stdClass Object
> (
>     [status] => fail
>     [reason] => no_routes
>     [retry_after] => 3600
>     [sms_wait] => 0
>     [voice_wait] => 0
> )
> There was a problem trying to request the code.

**Comment by MakoLM** [comment]
I tested with my own phone and same problem
