### ISSUE TITLE
Contribute REST / websocket api

### ISSUE THREAD

**Issue by Mawalu** [mgp25/Chat-API#1922]
I really like your work on this project. I have used it created some "IRC style" bots for whatsapp groups with me and my friends. To make this easier and to allow me to use different languages, multiple bots per account and to change my code without restarting the bot, I created a [small project that provides a chat-api daemon with a RPC like interface](https://github.com/Mawalu/chat-api-daemon). Since I've noticed that other people (#1294) want a similar feature I wanted to ask if I should contribute my code to this repository.

I'm happy to refactor or improve the code I wrote if you want to and of course if you think it would be better to keep it in its own repository thats perfectly fine as well :)

**Comment by 0xTryCatch** [comment]
Separate projects like now is the way to go
