### ISSUE TITLE
Example application for correct workflow

### ISSUE THREAD

**Issue by yniwly43** [mgp25/Chat-API#1925]
Hi there @mgp25 , 

I have been thinking, and I think there's a good way to solve the issue of all of these annoying tickets that complain about blocking, like 3-4 new ones every day.

What if you create a simple demo application with the correct workflow, just like yowsup-cli, but with ChatAPI. 

You can show it as an example usage of the library, an application that doesn't get blocked since is does everything correctly, 2 pings etc.

Then, whenever people complain about blocked numbers, you can link them to the demo application as the perfect example specimen of what works.

What do you think? Maybe we can help you develop this, and get the issues here in order, help everyone.

Thanks!

**Comment by mgp25** [comment]
wtf, seriously?

https://github.com/mgp25/Chat-API/blob/master/examples/WA%20CLI%20Client/client.php

**Comment by eaba** [comment]
@mgp25 please kindly respond to my email!

**Comment by yniwly43** [comment]
Funny, but don't feel disappointed.

The issue is that this application has manual options.

So, I'll do the following:

1. Register.
2. Connect.
3. Set status.
4. Set profile
5. Add this number to 3 devices with WA.
6. Add 3 contacts, of the device that have our number synced.
7. Wait for 15 minutes. Send no messages.
8. Exit.

This shouldn't cause a block, correct?

Also, is the "maximum 2 pings" feature applied in this flow?

**Comment by feltkamptv** [comment]
@yniwly43 Did you already tried this with the example code? What are the results?

**Comment by BurakDev** [comment]
I use Chat-API since some months now, never blocked or banned.

I use it as I.A chatbot, receiving audio message and sending audio message and work perfectly
