### ISSUE TITLE
Password changes every day

### ISSUE THREAD

**Issue by lucasegatori** [mgp25/Chat-API#1927]
I'm using this API and it works great. Every day I have to request a new password, I don't know if it's a problem of my SIM or my phone or if WA changes password so frequently...

**Comment by mgp25** [comment]
1) WA Password doesnt change
2) If you are using your number in a device and in the API at the same time, you can be logged in only in one of them. So if you request in your device, it generates a new password, and you cant login in the API and the same happens backwards
3) If you dont provide any kind of debugs or more details we can give you any further explanation of the problem

Regards

**Comment by lucasegatori** [comment]
Thank you, in the app of my phone I'm not logged, I can see the warning telling that whatsapp is used by another device. Maybe better if I uninstall the app from the phone? Anyway I have simple code to connect and check messages, here's the code:

require_once("src/whatsprot.class.php");
require_once ("src/events/MyEvents.php");
$nickname = "WhatsApp";
$username = "XXXXXXXXX608"; 
$password = "MyPasswordHere"; 
 
$wa = new WhatsProt($username, $nickname, true);
$wa->setMessageStore(new SqliteMessageStore($username));
$events = new MyEvents($wa);
$events->setEventsToListenFor($events->activeEvents); 
try {
$wa->connect();
$wa->loginWithPassword($password);
  } catch(Exception $e) {
    echo "ERROR : Login Failed";
    exit(0);
}
$wa->pollMessage();

Every day when I try to connect this is the error: 

tx  <stream:features></stream:features>

tx  <auth user="XXXXXXXXX608" mechanism="WAUTH-2">4e29d9873339333238383436393630384fdf26988ebde1f97d0fe127e60b8f739144ce1f31343633363534303932</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>4cdb9a98abd0b8544f26cc8db0163b0b1b31f265</challenge>

tx  <response>262db8224eb7e54dcc8dd747916fd2d16d931b9474a55c34856f599913700890a637e4a3709012b30a13eaa061746da7218185e7ea30409ee8a16bd49126bff4f7ff0771a43c5f43e4bac67f1902</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

ERROR : Login Failed

If I try blockChecker.php:

stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxx/src/Registration.php:89
Stack trace:
#0 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/WA/examples/blockChecker.php(37): Registration-&gt;checkCredentials()
#1 {main}
  thrown in <b>/var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/src/Registration.php</b> on line <b>89</b><br />

**Comment by mgp25** [comment]
@lucasegatori thats why you get that errors, you are kicking yourself out of the sessions everytime, better get a different number.

And the `blockChecker.php` only works if you have registered the number with the API, otherwise it wont and it will send you a SMS code

Regards

**Comment by lucasegatori** [comment]
"you are kicking yourself out of the sessions everytime"...
 Why? So I have to change the code someway?

**Comment by 0xTryCatch** [comment]
He means do not use the same number on a phone. Remove WA application or register a different number in the phone.

**Comment by lucasegatori** [comment]
ok thank youvery much
