### ISSUE TITLE
wait for server

### ISSUE THREAD

**Issue by kwiiby** [mgp25/Chat-API#1929]
why on this commit:
https://github.com/mgp25/Chat-API/commit/9b4a2e6b4235890db0a15b09725a8b4090c8a772

you commented waitForServer function on many functions? today I have to manually 5 pollMessage after some functions.... could you please explain me? thank you!

**Comment by mgp25** [comment]
Some functions doesnt require a server response, so why wait? Thats the main reason. The second reason is that, this way API speeds up

Regards

**Comment by kwiiby** [comment]
thx
