### ISSUE TITLE
Error Login authorized

### ISSUE THREAD

**Issue by msxandroid** [mgp25/Chat-API#1936]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
I have an active account until last week stopped responding access login.
Redid another account by the device so extracting the password and applied this account in the system, where the same situation got error on login.
I tried to generate the password via PW.apk, however he refuses format telephonic number already regularly used until month ago.
Today any access is being denied.

Does anyone have this situation or can validate if the current access is operating normally in your access log.

Thank you

### Debug log
```xml
tx  <stream:features></stream:features>

tx  <auth user="5565xxxx7019" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>ff8eeb50079e3a50637f7dba52f07454e86e9eb2</challenge>

tx  <response>ee16d0f430e3afaa0fccf92888603ca4f0a4a093421f7860199dd74f41d21fb8e0c648abd8c5f4fe64afad370cad84766941da11219bc66ddfc06a3b0795ca072c4ef0ba835c2e3393848186d81a</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>w:
```

**Comment by manusreload** [comment]
This look like the number is blocked, try to register the number whit registration tool.

**Comment by msxandroid** [comment]
try to register 
http://www.watools.es/pwd.html
Phone number:5565xxxx3635

Return MSG : Seems there was an error! Check your phone number again

**Comment by msxandroid** [comment]
Number is not blocked and have registered new number with the tool, everyone is refusing registration.
Active number by whatsapp app and phaco the extraction via apk getting the password.
However the login is refused on the information obtained.
I'm from Brazil Midwest and not conheco to ah this anomaly in other region of Brazil.
I would like your opinion of the record operation and use of the api is accepting login with your old account.

**Comment by manusreload** [comment]
I have a number registered in whatsapp about 6 o 8 month, the last weekend I try to update and run the library and does not work, the messages are not decpryping, send the message but not receiving, and the library retry the same message, then other day when I try to login, the severver resoponse is the <not-authorized> error. I need to try the registration from command line, to get a new PW. I think that is possible that only whit this can fix the error.

**Comment by FrancYescO** [comment]
Having the same issue: getting banned continuosly.

i have a responder (ever online and pooling messages, and will just respond to few messages by family members) up and running from months.
first ban (**not-authorized**) happened on 16/05 09:21
So i registered a new number on 21/05 ~19:25
but just after 6h got banned again on 22/05 01:50 with just few messages exchanged (<10)

Seems they don't like anymore ever-online numbers ... solutions?

**Comment by manusreload** [comment]
You know any online phone number provider? I try nexmo, twilio, textmagic but dond receive the verification sms from whatsapp, today I will buy a new SIM from Spain, and I will try to register the number.

**Comment by mgp25** [comment]
@msxandroid i guess you havent read the wiki at all or other issues. The password extractor apk, doesn't work with newer version due the noise protocol, thats why it refuses the password, the password extractor only works with older versions (before wa 2.0). Instead use `registerTool.php` to generate a password.

**Comment by msxandroid** [comment]
@mgp25  I applied the record as indicating "register Tool.php" however it is lost.
I tried several methods, and all are being installed.
