### ISSUE TITLE
onpong event missed?

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1937]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
i read all issues and i re search all files, i could not find an `onPong` event, it is called something else or really it is missed, how we can simulate an onPong event to prevent sending 2 pings in short time without receiving pong response

What it mean inactivity time, is pollMessage time included by saying inactivity ?

Best regards !

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Its added in next chat api release, its not required anyway

regards
