### ISSUE TITLE
Get Ws Password 

### ISSUE THREAD

**Issue by rikuhen** [mgp25/Chat-API#1939]
I follow the registers steps, but nothing

**Comment by mgp25** [comment]
debug log? Nothing? No debug log = no support

**Comment by rikuhen** [comment]
Look this, it´s a new number phone
![image](https://cloud.githubusercontent.com/assets/5169412/15481918/9dee1f0e-20f2-11e6-880f-a73d83a6c619.png)

**Comment by mgp25** [comment]
Number blocked, and probably IP blocked too

**Comment by rikuhen** [comment]
why happened this? (sorry my english)

**Comment by mgp25** [comment]
Things that can block a number:

- Spamming
- Sending bulk or innapropiate requests
- Doing several number registration under the same IP
- IP block. Thats something WA manages, maybe because of the 1) or 2)
