### ISSUE TITLE
Unable to register (no_routes) on Hetzner server

### ISSUE THREAD

**Issue by pythonimus** [mgp25/Chat-API#1942]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
####################
#                  #
# WA Register Tool #
#                  #
####################

Username (country code + number, do not use + or 00): 496xxx4306xxx

Type sms or voice: voice
Array
(
    [cc] => 49
    [in] => 6xxx4306xxx
    [lg] => de
    [lc] => DE
    [id] => ▒▒▒.▒▒)q8▒▒xxx
    [token] => D2dlJ/rGHxxxxxxspU3XKrCRIzE=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 4744
    [rchash] => de3843ad92d7abe64a6e2xxxxxxx15edf3cde1775b109cb870f013312895760a
    [anhash] => 4a9011859axxxxxxc5375339286e311b
    [extexist] => 1
    [extstate] => 1
    [mcc] => 262
    [mnc] => 000
    [sim_mcc] => 262
    [sim_mnc] => 000
    [method] => voice
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
    [sms_wait] => 60
    [voice_wait] => 60
)
There was a problem trying to request the code.

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

Hi,

I get the no_routes error while trying to register through registerTool.php.
Whatsapp has a route to my provider because on my phone the registration process was flawless (with voice)(private non-Hetzner IP).
Is there a way to extract the ID from Android? (I only found in your Wiki how to extract the password)
Extra question: Is Curve25519 required even if I don't want to send encrypted messages? (as Curve25519 only compiles on 5.6 and not on 7, php 7 runs on production server)

Thanks!

**Comment by 0xTryCatch** [comment]
Probably your number is not accepted, use a different one. No way to extract Android ID. Curve is required.

**Comment by msxandroid** [comment]
I use an app that makes the extraction, however the same Capture mode .. is the lock
