### ISSUE TITLE
Extract WA PW from Android

### ISSUE THREAD

**Issue by acalatrava** [mgp25/Chat-API#1948]
Make sure these boxes are checked before submitting your issue -- thank you!

- [v] You are using PHP > 5.6
- [v] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [v] You have checked if someone has already asked the same issue you have.
- [v] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [v] Is not a programming question.
- [v] You are using latest Chat API code.

### Error
Post your error below:
I'm unable to extract the PW from Android. I'm using latest WhatsApp version from Google Play (2.16.95) and I follow the BASH guide here: https://github.com/mgp25/Chat-API/wiki/Extracting-password-from-device#bash

There is no "pw" file in the device. I tried both with "key" and "me" file with no success, the password generated is not valid.

This is the file list on the device:
130|root@GT-I9100:/data/data/com.whatsapp/files # ls -la
drwx------ u0_a74   u0_a74            2016-05-27 14:30 .trash
drwx------ u0_a74   u0_a74            2016-05-27 14:30 Avatars
drwx------ u0_a74   u0_a74            2016-05-27 14:27 Logs
-rw-rw---- u0_a74   u0_a74         14 2016-05-27 14:32 full_sync_wait
-rw------- u0_a74   u0_a74         14 2016-05-27 14:32 fullsync.dat
-rw------- u0_a74   u0_a74         53 2016-05-27 14:32 invalid_numbers
-rw------- u0_a74   u0_a74        158 2016-05-27 14:30 key
-rw-rw---- u0_a74   u0_a74        128 2016-05-27 14:30 me
-rw------- u0_a74   u0_a74         69 2016-05-27 14:28 rc2
-rw------- u0_a74   u0_a74        551 2016-05-27 14:46 statistics
-rw-rw---- u0_a74   u0_a74         14 2016-05-27 14:32 sync_backoff
-rw------- u0_a74   u0_a74        946 2016-05-27 14:42 wastats.dims
-rw------- u0_a74   u0_a74       1327 2016-05-27 14:42 wastats.log
-rw------- u0_a74   u0_a74          8 2016-05-27 14:30 wastats.timestamp

Is WhatsApp using a new algorithm to store the key? Is it possible to extract it?

Thank you

**Comment by mgp25** [comment]
These methods are outdated. Use a number and register it using `registerTool.php`

Regards
