### ISSUE TITLE
No Event Handler for Notifications-nodes in MyEvents.php

### ISSUE THREAD

**Issue by Sdlion** [mgp25/Chat-API#1949]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have. (Not resolved, I'm using the Event System)
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

I'm using the event system but there's no handler to programatically unsubscribe to a contact which from I have received an update/remove notification.

In the wiki, the only event handlers that have a $node as parameter are `onMediaUploadFailed` and `onSendMessage` none of which are relevant to the issue. No event handler mention the word "notification".

If this notifications are polled through a function (with a respective event handler) could you clarify the name of the API function on the Notification-nodes section of the wiki?

Thank you for your hard work!

**Comment by Sdlion** [comment]
Get it, 

The handlers are on the wiki but not in the list of events in MyEvents.php
The whole list of events handlers could get added to MyEvents.php?

And a clarification on the wiki which event is triggered for each notification?
Or change the title of the section to something more descriptive (adhoc to your API) like "Contact Number Modification".

**Comment by mgp25** [comment]
@Sdlion we have to do it, maybe that will be added in the next release with a better interface

If you want send a pull request and ill apply it

Regards
