### ISSUE TITLE
Seriously? Why WhatsApp why ?

### ISSUE THREAD

**Issue by JohnSHAMD** [mgp25/Chat-API#1952]
Hello,

I have updated the chat API code and registered a number with new IP. [ VPS ]. The purpose is to get the message from my friends and store it.
Here is the code.

```
//Login with password.
//Event system to store upcoming messages.

while(1)
{
      $w->pollMessage();
      sleep(10);
}

$w->pollMessage();
//disconnect
```

Basically, it retrieves messages and stores in mysql database after 10 second using Event system.

At this point I don't have any logs because it ran perfectly for 3 hours and then I put this script in background and after 9-10 hour number got blocked. So, I don't have any debug log. Do I need to improve script  or something else ?

Thank you!

**Comment by mgp25** [comment]
Yes, its already answered:https://github.com/mgp25/Chat-API/issues/1872#issuecomment-215912828

**Comment by KduOliva** [comment]
JohnSHAMD , have you find an answer?
