### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Phillipip** [mgp25/Chat-API#1953]
Hello,

after login i get always this onGetError:
a:5:{i:0;s:13:"4915792330xxx";i:1;s:28:"4915792330xxx@s.whatsapp.net";i:2;s:1:"1";i:3;O:12:"ProtocolNode":4:{s:17:"ProtocolNodetag";s:5:"error";s:27:"ProtocolNodeattributeHash";a:2:{s:4:"code";s:3:"404";s:4:"text";s:14:"item-not-found";}s:22:"ProtocolNodechildren";N;s:18:"ProtocolNodedata";s:0:"";}i:4;s:7:"privacy";}

it will be created through the first pollMessage() after loginWithPassword().

can somebody help?

best regards
paul

**Comment by mgp25** [comment]
@Phillipip i can't see anything. Please post the debug log the API provides by setting in the constructor `$debug` to `true`

**Comment by 0xTryCatch** [comment]
This is perfectly normal behaviour, it means you have no blocked list
