### ISSUE TITLE
After sending with CHAT-API, the app on smartphone does not work!

### ISSUE THREAD

**Issue by robyone67** [mgp25/Chat-API#1954]
Hello,
We use the last official library of Chat Api to send notifications to our customers from our website.
We also have a smartphone with the official app of whatsapp and a sim with the same number.
The problem is that when we send messages through the computer, the app on the phone ask us to verify the phone number by sending a code via sms or voice. When we check the number on phone,  the code to send messages through the computer is disabled and we must request it again.
When we solve with the PC, no longer works the app on smartphone and it asks us again to check the number, and so on.
I should emphasize that this is a recent issue that until a few weeks ago was not the case.
Thank you.

**Comment by 0xTryCatch** [comment]
Commercial use is NOT allowed!
