### ISSUE TITLE
Need clear explanation of bad mac status

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1957]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Hello ! I am already reading all wiki and related issues but i don't go to find clear answer for my question

"exactly when the bad mac error is occurred ?
and what meaning of mac , it is mac address ?
did chatapi send mac to whatsapp
please give us techincal details of this error because is suddently begin appearing
"

Hope issue not closed, and is answered

Regards !

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
In cryptography, a message authentication code (MAC) is a short piece of information used to authenticate a message—in other words, to confirm that the message came from the stated sender (its authenticity) and has not been changed in transit (its integrity).

So when you get a `bad_mac` error, it detects something is not right.

Hope this issue gets understand and not reopened

Sigh...

**Comment by MoudiZd** [comment]
thank you for fast answer, but what i want to ask also , did this is related to code security changes we see on an official app in a group conversion ?

**Comment by mgp25** [comment]
That is only to end to end encryption messages, it doesnt affect groups yets since its not coded

**Comment by MoudiZd** [comment]
but yesterday and suddenly a repeated "code security changed" begin to appear on my group on my official whatsapp from the number which i use the chatapi and after a short while the number is getting blocked

and in log i see too many repeat "bad mac" and also i begin to receive "key/value" pairs infinitely till i disconnect , i think this is not a normal behavior  ?

**Comment by 0xTryCatch** [comment]
@MoudiZd send the log to my e-mail please

**Comment by MoudiZd** [comment]
Hello @0xTryCatch , i sent you the email

Regards !

**Comment by dcardosoa** [comment]
Hi,

This is the same issue that I am having (https://github.com/mgp25/Chat-API/issues/1926).

And now all numbers (including old numbers ~1,5 year) are blocking...

**Comment by MoudiZd** [comment]
Hello @0xTryCatch i sent you another email.

Regards
