### ISSUE TITLE
did api detect code security changes

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1960]
Hello ! I want to know if the api for now can detect any `security code change` made by whatsapp contacts /

As whatsapp say that if  a contact reinstall whatsapp or switch phone , all keys between my number and this contact will be changed, so did the api detect these changes and store all new keys ?

in other term i want to know if the problem is in the way of storing new keys or that the api is not ever detect new keys

Regards !

**Comment by mgp25** [comment]
There is no problem in that, api does all the work. You can check it yourself by looking at the debug log

Regards

**Comment by MoudiZd** [comment]
as i see in the axolotl.db file their is a record with recipient id equal to -1 what is the reason of this recipient id , as i see this field must contain a phone number but -1 is found in the last record of database with a registration id , did this make any sense ?
