### ISSUE TITLE
Number banned after use this api

### ISSUE THREAD

**Issue by ictglobus** [mgp25/Chat-API#1965]
Dear develop,
I used your bee over six months for a few days we fail more because after a few minutes we are banned from whastapp , we followed everything recommended . And ' possible to know if some day whatsapp ended the use of this API ?

thank you very much

**Comment by mgp25** [comment]
WhatsApp blocked you because you have done something wrong or any weird request. Post debug log (previous to the not authorized) and i'll tell you which is the error

Regards

**Comment by patelprajay** [comment]
Hello I have the same issue

**Comment by ictglobus** [comment]
hello dear
add me on skype ess.salvatore.battiato
