### ISSUE TITLE
2 pings workaround

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1968]
Hello again @mgp25 may these changes do the trick ?

i add these 2 variables to the whatsprot class

````
protected $pings = 0;
protected $max_pings = 2;
````

as i can see the `sendPing` is not called anywhere other then the `pollMessage` function so i changed the `pollMessage` function as following

````
public function pollMessage()
    {
        if (!$this->isConnected()) {
            throw new ConnectionException('Connection Closed!');
        }

        $r = [$this->socket];
        $w = [];
        $e = [];
        $s = socket_select($r, $w, $e, Constants::TIMEOUT_SEC, Constants::TIMEOUT_USEC);

        if ($s) {

            // Something to read
            if ($stanza = $this->readStanza()) {
                $this->processInboundData($stanza);

                return true;
            }
        }
        if (time() - $this->timeout > 60)
            {
                if($this->pings < $this->max_pings)
                    {
                        $this->pings++;
                        $this->sendPing();
                    }
                else
                    {
                        $this->disconnect();
                        $this->connect();
                        $this->loginWithPassword($this->password);
                    }
            }

        return false;
    }
````
note : what about this line 
````
if ($stanza = $this->readStanza()) {
````

it must be or not like following
````
if ($stanza == $this->readStanza()) {
````

and as i see that you have reset the timeout on each send of node you make so i uncomment this line inside the `sendNode` function
````
//$this->timeout = time();
````

and finally i add this line
````
$this->pings = 0;
````

after this line
````
if ($node->getAttribute('status') == 'active') {
````
inside the `processInboundDataNode` function

Can you tell me if this workaround is sufficient to handle the 2 pings disconnect scenario or i must add something ?

Regards

**Comment by mgp25** [comment]
@MoudiZd im glad you like this project so much. but keep in mind we only solve API issues, not programming issues. The fact we only solve API issues is because we cant spent all our day explaining and solving programming stuff.

Dont get me wrong, but for this kind of things you should search in other sites like stackoverflow or so.

Anyway, so far seems good, i havent checked it, you should check if everything works as what we have told.

Regards

**Comment by MoudiZd** [comment]
@mgp25  thank you for your words ! But what really i am trying to do is not solving programming issues but really api issues and the code above is taken from the `whatsprot.class.php` you wrote . Anyway i will try to pull a request for that

but just i want to ask what about this line
````
if ($stanza = $this->readStanza()) {
````

the `=` must be `==` or no problem with that !

Regards

**Comment by mgp25** [comment]
@MoudiZd basic programming..

`readStanza()` returns nothing (false) if no data, and if it has data it act like a (true).

So basically, you are doing a:

```php
if(false) // if no data
```

```php
if (true) and saving its content into $stanza if there is any data
```

**Comment by MoudiZd** [comment]
@mgp25 we are not beginner but sometimes we go to be confused from small things ... anyway.

because you are talking about api issues i think that i can guide into these two issues and hope that are what you called `api issues` not `programming issues`....

in the file `MessageHandler.php` inside the **`api`** their is this line at Line 67
````
$this->node->getChild('body')->getData(),
````
which may conduit to the error of
````
fatal error : call to function getData on null
````
so this line must be like this
````
!is_null($this->node->getChild('body'))?$this->node->getChild('body')->getData():"",
````

and a bug found in the `MessageRead` function also inside the **`api`** when the receipt is sent for single message not multiple messages, if you want i can send you the solution

Regards !
