### ISSUE TITLE
My act like a human recipe

### ISSUE THREAD

**Issue by edudesouza** [mgp25/Chat-API#1972]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

Hi fellow, 
I would share my act like a human recipe, besides not sending massive messages, not contact those that are not in your contact list I have other 2 ingredients:

- I have 3 IPs on my VPS, I ran my script each time using one of them
- my script sleeping time are not equal
```php
$messages   = $w->getMessages();
$rand = rand(3,8);  
sleep($rand);
while($w->pollMessage());        
$w->disconnect();
$w=null;

////// some code ///////

$rand = rand(3,8);          
sleep($rand);

////// restart loop //////
```

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by djade007** [comment]
How long have you been able to use that approach without getting banned?

**Comment by eaba** [comment]
@edudesouza can we talk at questswa at gmail?

**Comment by mgp25** [comment]
omg… nope. I'll update some stuff in the code tonight

**Comment by djade007** [comment]
Lol.. @mgp25 thanks we will be expecting the update

**Comment by eaba** [comment]
@mgp25 you going to break the internet tonight, trust me!

**Comment by edudesouza** [comment]
I ran my number since January.

**Comment by edudesouza** [comment]
@eaba sure we can talk, can you give me your email?


via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.40&pv=4.3&source=email_footer_2] On Sat, Jun 04, 2016 at 3:51 PM, eaba < notifications@github.com [notifications@github.com] > wrote:
@edudesouza [https://github.com/edudesouza] can we talk at questswa at gmail?
