### ISSUE TITLE
two questions about last commit

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1976]
Hello @mgp25 i have 2 question: 

1- as i see that you add this 
````
$this->sendOfflineStatus();
````
within this block:
````
if ($this->pingCounter >= 3)
    {
        $this->sendOfflineStatus();
        $this->disconnect();
        $this->iqCounter = 1;
        $this->connect();
        $this->loginWithPassword($this->password);
        $this->pingCounter = 1;
    }
else
    {
        $this->sendPing();
        $this->pingCounter++;
    }
````
before disconnecting after the second ping then reconnect so i want to ask if their were any necessity to add this also in the `disconnect` function before closing the socket

2- the reset of timeout is made also before sending a node this is logic ? or just it must be reset after receiving a node

Regards !

**Comment by mgp25** [comment]
@MoudiZd before disconnecting always is better to send offline status

**Comment by MoudiZd** [comment]
Ah ! so it must be added into the api function `disconnect`

**Comment by MoudiZd** [comment]
@mgp25 and what about resetting the timeout when sending node like api , it is not wrong ?
