### ISSUE TITLE
Not An issue but a Question

### ISSUE THREAD

**Issue by tomexsans** [mgp25/Chat-API#1977]
Is there any chances that setting the WhatsApp version on [constants.php](https://github.com/mgp25/Chat-API/blob/a0300512a1d42dbc624b0e496b996dd02e1e64ff/src/Constants.php) will lead to something Good or Bad.

as i have tested i was having a chat on the  API and the official App on android and i can see that the encryption is not On but when i changed the WHATSAPP_VER to the latest version the encryption on The Offical APP was green.

by the way you could see it on _view contact_ when messaging with you contact.

**Comment by mgp25** [comment]
Better keep it like it is, i'll update it when its required

Regards

**Comment by edudesouza** [comment]
Same here, I use version 2.12.440 because video and audio are not encrypted
