### ISSUE TITLE
online offline question

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1979]
Hello @mgp25 i want to ask you did my status will be always online after login, or may it be offline if i send an offline status before disconnecting? in other mean did i need to send an active status after login or this is made automatically even if the last status i sent before disconnecting it was an offline status ?

Hope my question is clear
Regards !

**Comment by MoudiZd** [comment]
in the latest commit you made you have re login after sending an offline status , so this may be occured while i am already offline, so did this will make any conflict or conduit to unwanted behavior ?

Regards !

**Comment by KduOliva** [comment]
This new commit blocked my number. Is this related or coincidence? i don't know... i just give-up...

**Comment by edudesouza** [comment]
Is this blocked number, a pre april validated?
Do you use version 2.12.440 or 2.12.556?

**Comment by mgp25** [comment]
Every time you login status is set available again, have you follow the code before opening the issue?

**Comment by MoudiZd** [comment]
Yeah i followed the code and i arrive to this function
````
public function doLogin()
  {
      if ($this->parent->isLoggedIn()) {
          return true;
      }

      $this->parent->writer->resetKey();
      $this->parent->reader->resetKey();
      $resource = Constants::PLATFORM.'-'.Constants::WHATSAPP_VER;
      $data = $this->parent->writer->StartStream(Constants::WHATSAPP_SERVER, $resource);
      $feat = $this->createFeaturesNode();
      $auth = $this->createAuthNode();
      $this->parent->sendData($data);
      $this->parent->sendNode($feat);
      $this->parent->sendNode($auth);

      $this->parent->pollMessage();
      $this->parent->pollMessage();
      $this->parent->pollMessage();

      if ($this->parent->getChallengeData() != null) {
          $data = $this->createAuthResponseNode();
          $this->parent->sendNode($data);
          $this->parent->reader->setKey($this->inputKey);
          $this->parent->writer->setKey($this->outputKey);
          while (!$this->parent->pollMessage()) {
          };
      }

      if ($this->parent->getLoginStatus() === Constants::DISCONNECTED_STATUS) {
          throw new LoginFailureException();
      }

      $this->parent->logFile('info', '{number} successfully logged in', ['number' => $this->phoneNumber]);
      $this->parent->sendAvailableForChat();
      $this->parent->sendGetPrivacyBlockedList();
      $this->parent->sendGetClientConfig();
      $this->parent->setMessageId(substr(bin2hex(mcrypt_create_iv(64, MCRYPT_DEV_URANDOM)), 0, 22)); // 11 char hex

      if (extension_loaded('curve25519') || extension_loaded('protobuf')) {
          if (file_exists($this->parent->dataFolder.'axolotl-'.$this->phoneNumber.'.db')) {
              $pre_keys = $this->parent->getAxolotlStore()->loadPreKeys();
              if (empty($pre_keys)) {
                  $this->parent->sendSetPreKeys();
                  $this->parent->logFile('info', 'Sending prekeys to WA server');
              }
          }
      }

      return true;
  }
````
where i can see that you are calling this function `sendAvailableForChat` but not `sendActiveStatus`
when `sendActiveStatus` will send a node 
````
<presence type="active"></presence>
````
but the function `sendAvailableForChat` will send this node 
````
<presence type="available" name="{$this->name}">
````

so as you see that nodes does not have same `type` attribute so i could not guess if the available presence node do what the active presence node

Anyway thank you ! and sorry for my stupid question ......
