### ISSUE TITLE
New line blocked after verifying code

### ISSUE THREAD

**Issue by cedancp** [mgp25/Chat-API#1982]
Hi, I've doing some test with this library, last week I was able to completely register, send message and images after I got blocked. I was only doing tests and that happened. Since thursday I've been having some troubles with registering new numbers, after receiving the code and verifying I got and fail message, missing error.

I then request a new code, and the number is already blocked

Object ( [status] => fail [reason] => blocked ) 

If anybody can help me, thanks

**Comment by ShdyX** [comment]
I got the same problem !!

**Comment by mgp25** [comment]
Duplicate issue.

Probably because you have registered too many numbers, and your IP is flagged now. It could be due a wrong flow too

**Comment by mgp25** [comment]
Duplicate issue.

If you register too many numbers your IP will be flagged. Also it could be due to the flow.

**Comment by cedancp** [comment]
I thought the same so I use another server, same result.

And I am using same flow I used before, and same flow that is in documentation.
