### ISSUE TITLE
My number is banned by a period of time

### ISSUE THREAD

**Issue by Creapix89** [mgp25/Chat-API#1985]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Hello, today my line was blocked by 13234 seconds, however when that time passes, I can log in without problems.

Almost instantly whatsapp block me again, and now I get a longer waiting time.

I've read all Wikki and nothing else explains what it means. Is there a code sequence for such cases?

thanks
`
rx  <failure>
rx    <not-authorized expire="13234" code="101"></not-authorized>
rx  </failure>
`

**Comment by mgp25** [comment]
If you don't post previous debug logs with the activity, is hard to tell. But mostly because bad behaviours (sending/requesting)

Regards
