### ISSUE TITLE
Sending too many vcards can be finished to a block ?

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#1987]
Hello @mgp25, @0xTryCatch, @CODeRUS  !

did sending vcard with current api version may be finished to a block ? because as i see that the vcard is not well formed and as i guess is not encrypted , so when it is received it will be received as non valid card, so this may can this be a cause for a block ?

Regards

**Comment by 0xTryCatch** [comment]
Nobody knows
