### ISSUE TITLE
what the reason of infinity keys

### ISSUE THREAD

**Issue by newdeveloper14** [mgp25/Chat-API#1989]
hey @mgp25 i use your api and suddenly i begin receiving keys infinitely, so what is the matter if you want i can send you the log from first login until keys receiving

**Comment by newdeveloper14** [comment]
@mgp25 i sent you the log via email

Regards

**Comment by eaba** [comment]
Check your database! The keys might not have been saved! Ensure the call to your database is functioning proper

**Comment by newdeveloper14** [comment]
but i have not changed anything about communication with database, why might this not work properly ?

**Comment by newdeveloper14** [comment]
@eaba  if you want i can send you the log

**Comment by MorpheusBrz** [comment]
Delete the libaxolotl database. This API will recreate automatically and the problem is solved.

**Comment by MoudiZd** [comment]
@MorpheusBrz But did i need to re register mu number after deleting the file ?

**Comment by MorpheusBrz** [comment]
No. Work fine without re register.

**Comment by mgp25** [comment]
@newdeveloper14 remove `axolotl.db`. Delete the chat on your device, and retry everything again. It should work

Regards

**Comment by newdeveloper14** [comment]
Ah ! But why might `axolotl.db` might be damaged ? It is a limitation from sqlite ?

**Comment by newdeveloper14** [comment]
@mgp25 but why might `axolotl.db` file be damaged and become need to be deleted ?
