### ISSUE TITLE
can't receive messages

### ISSUE THREAD

**Issue by berkercanatar** [mgp25/Chat-API#1990]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
I can send messages to my mobile phone with this php api, but when i send message to this api from my phone(message is automatically encrypted by whatsapp app), i can't read messages with this api. But when i sent message to same number which i connected using this api, i cant read messages. i think this api sends message without encrypting.

### Debug log
Post your debug log below:
```
rx  <message from="--my phone number--@s.whatsapp.net" type="text" id="677AA2C933683153E2" offline="3" t="1465506457" notify="--My whatsapp name--">
rx    <enc v="2" type="pkmsg">331221052cde07e3fc322841065f8d5d5f50a9bd7577bba549d299577f47cb8eeaf8774e1a210593ac2fdead86cbdb59c144f206a224ab9e59ebfe40ca162d89dca2e0ce10e0552252330a210565e882bc92818cf9d2edbabef969e4959f9bafd1455693ae9e9f2beeff74dc7c100818002220d511db9d5b622f9729f7598d26d87fb608da42b77b28f16e0956e472d152d8f451efd15e7ab7330228974d30a0f1db07</enc>
rx  </message>
```

**Comment by 0xTryCatch** [comment]
This debug log is not helpful, post the whole debug log please

**Comment by mgp25** [comment]
@berkercanatar probably you havent installed dependencies, for further support, **post full debug log**

Regards
