### ISSUE TITLE
did this may cause any wrong behavior ?

### ISSUE THREAD

**Issue by newdeveloper14** [mgp25/Chat-API#1993]
Hello @mgp25, @CODeRUS, @0xTryCatch  as i see in the file `Curve.php` which found under `src/libaxolotl-php/ecc/Curve.php` this function exists
````
protected static function getSecureRandom($len = 32)
    {
        $rand = openssl_random_pseudo_bytes($len, $strong);
        if ($strong) {
            return $rand;
        } else {
            throw new Exception('Cannot generate secure random bytes');
        }
    }
````
but as you can see that the `$strong` variable which is passed as second parameter to the function `openssl_random_pseudo_bytes` is not defined

So this may guide to an unexpected behavior ? or this is normal ?

Regards !

**Comment by mgp25** [comment]
@newdeveloper14 this is not an API related issue

`openssl_random_pseudo_bytes` is a function of PHP you have installed in one the dependencies. Please stick only to API issue

**Comment by newdeveloper14** [comment]
@mgp25  but the problem which i ask is not about the core code of the function `openssl_random_pseudo_bytes` but in the function `getSecureRandom` where you use within the function `openssl_random_pseudo_bytes` in the api

Regards !

**Comment by Sdlion** [comment]
Read carefully the php reference manual and the nature of the second parameter `$strong`.
It falls in the category of "programming question" since it's explained in PHP's manual.
