### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by newdeveloper14** [mgp25/Chat-API#1994]
Hello @mgp25 , again when i am looking to the code i found this part of code in your `whatsprot.class.php` within `sendRetry` function

````
if (!isset($this->retryCounters[$id])) {
            $this->retryCounters[$id] = 1;
        } else {
            if (!isset($this->retryNodes[$id])) {
                $this->retryNodes[$id] = $node;
            } elseif ($this->retryCounters[$id] > 2) {
                $this->resetEncryption();
            }
        }
````
But it seems not working as expected , because as i can assume that the `retryNodes[$id]` is not set in all cases, hope you can give me sometime and check this , because i think their were a problem in the logic behind this part of code , the retry nodes must not be set on each time the retry counter is modified ?

Or what you are doing here is
````
set counter[$id] in first retry time
set node[$id] in second retry time
set counter[$id] in third retry time
set node[$id] in fourth retry time
reset encryption in fifth retry time
````

Hope some explanation

Regards !

**Comment by mgp25** [comment]
It works fine, anyway we have improved all the system for the next release. If you want, send a pull request with the changes, and we'll review it

Regards
