### ISSUE TITLE
axolotl.db is not cleared because not exists

### ISSUE THREAD

**Issue by newdeveloper14** [mgp25/Chat-API#1995]
As i see in the `clear` function of `SqliteAxolotlStore` class . That the `axolotl` db must be removed.

But whats is going wrong is that this file cannot be found to be deleted, due to path error

In other mean, my code which use chatapi is found under
`/var/www/mysite/chatapi/`

When the chatapi is found under
`/var/www/mysite/chatapi/src/

When i don't set the datafolder construct parameter the datafolder will be

`/var/www/mysite/chatapi/wadata/`

Which is absolutely wrong and must be

`/var/www/mysite/chatapi/src/wadata/`

So when api go to delete axolotl-number.db absolutely it will not found it

So as conclusion when your chatapi files don't exist in the same folder of your code , set the datafolder `whatsprot` parameter to your custom path, in my case to

`/var/www/mysite/chatapi/src/`

Regards

**Comment by mgp25** [comment]
@newdeveloper14 Hi, send a pull request and we'll review it

Regards
