### ISSUE TITLE
Critical bug :(

### ISSUE THREAD

**Issue by newdeveloper14** [mgp25/Chat-API#1996]
@mgp25, @CODeRUS, @0xTryCatch 
change the `$this->filename` witihin the `clear` function in the file `SqliteAxolotlStore.php` to `$this->fileName` :(

Critical bug that let me cry, testing for two hours to found this ...... bug

Regards

**Comment by Sdlion** [comment]
I think the protocol here is to issue a Pull Request for this.

Fork the project to your account, git clone your fork to your workstation, make the change, add, commit, push the commit into your git account, and Pull Request your commit.

**Comment by newdeveloper14** [comment]
But it is a critical bug, and i am sure that many programmers are falling down due to this bug and should not wait the time for a pull request made , not ?

**Comment by mgp25** [comment]
@newdeveloper14 send a pull request, although its already fixed in WA 2.0

Regards

**Comment by Sdlion** [comment]
@newdeveloper14 it is part of the collaboration philosophy and the reason to exist of sites like GitHub.
The dev only have to glance your pull request, and then merge the code. Easier and faster than to dust off your old project (they're already working in the new version) edit the lines and blah blah blah (follow the protocol that I mentioned before).
Remember that they're already reading and replying all the issues that are being opened, working, maintaining and collaborating in other projects, and living their lives.
