### ISSUE TITLE
Can we not send retry?

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#2002]
Hello @mgp25, @CODeRUS, @0xTryCatch again.

As workaround till you publish your release.
I want to ask if i can easily don't send retry node when failing to decrypt a message, and by the way ignore this message, and in place of adding node to a retry array, add it to ignore array

Or in other mean did i need really to decrypt messages if i don't care to the content ?

Regards !

**Comment by mgp25** [comment]
If you want to do it, do it in your code. And please, dont tag us in every issue, we check all the issues.

Regards

**Comment by MoudiZd** [comment]
Sorry for tagging , but i do this for fast response.
Sorry again, but i want to ask if i do this in my code may it conduit to any unwanted behavior ?

If you can tell me the scenario that you will use in next release for handling retry and reset encryption or at least tell me where to find resources to make my own research about this issue so i can make a work around until you publish the next release ?

Regards!
