### ISSUE TITLE
Number blocked after register

### ISSUE THREAD

**Issue by alm-92** [mgp25/Chat-API#2003]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:
Well i have been following your proyect for some time now, last friday I was able to register a number using your API and everything went smooth. I was not blocked in that whole day. I did not send any messages or anything, tried to use your example but gave me an error saying temporary unavailable. Today I used the blockChecker to see if my account was blocked seeing that there are many people having this kind of issue lately and to my surprise i am also blocked.
Is it normal to get blocked without sending anything? 
I also have read in many of the lastest issues that you are working on a WA 2.0, is there an ETA?
Thank you very much for all your effort.

### Debug log
Post your debug log below:

```xml
Your number is blocked 
Array
(
    [cc] => 34
    [in] => 6357xxxxx
    [lg] => es
    [lc] => ES
    [id] => Ć+��y�
ü�q�%q�
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 377
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
```

sorry i dont have the logs from friday D:

**Comment by 0xTryCatch** [comment]
These questions have been answered many times before, use the search function!

**Comment by alm-92** [comment]
I know it is duplicate, but the problem is that you close every issue saying the same. Just a list of examples:
- https://github.com/mgp25/Chat-API/issues/1982 : so much explanation in the answer.
- https://github.com/mgp25/Chat-API/issues/1915 : oh no answer.
- https://github.com/mgp25/Chat-API/issues/1965 : again the issue gets closed and there is nothing usefull.
- https://github.com/mgp25/Chat-API/issues/1962 : what a surprise no answer either.
- https://github.com/mgp25/Chat-API/issues/1946 : oh more people saying that the problem might be in the registerTool, and the answers are "wrong" , and " Im done with this" . 
- https://github.com/mgp25/Chat-API/issues/1935 : nothing usefull here
- https://github.com/mgp25/Chat-API/issues/1930 : this was the first issue I found something "usefull", taking into account that i have just registered 2 numbers using this API i dont think this can be my case. 
- https://github.com/mgp25/Chat-API/issues/1915 : no anwser.
- https://github.com/mgp25/Chat-API/issues/1887 : As in many other topics the problem of the 2 pings seems to be the problem for this guy. 
- https://github.com/mgp25/Chat-API/issues/1876 : I have the contact saved in both phones, so this should not be my problem
- https://github.com/mgp25/Chat-API/issues/1873 : again nothing useful just complaining about stuff...
- https://github.com/mgp25/Chat-API/issues/1872 : again the problem seems to be either sync or the pings)
- https://github.com/mgp25/Chat-API/issues/1871: not a single answer.
- https://github.com/mgp25/Chat-API/issues/1869 : again the ping is mentioned.
- https://github.com/mgp25/Chat-API/issues/1867 : the problem is the user flow here, but in my case I used YOUR examples.
- https://github.com/mgp25/Chat-API/issues/1861: more people with the same problem but without debug log so no answer.
- https://github.com/mgp25/Chat-API/issues/1845 : here we have a user that claims that he had to modify the code to prevent his numbers from getting blocked.
- https://github.com/mgp25/Chat-API/issues/1840 : here is where things start getting interesting... mgp25 admits that he has coded some parts to make it easy to get blocked, well he can do this as it is HIS proyect, but not very encouraging to read. If we continue reading we find this comment from mgp25 "i want to make sure all spammers are blocked" again he is in his full right to do this but at least give some help for the people that are not going to use this for spamming.
- https://github.com/mgp25/Chat-API/issues/1838 : no more answers in this topic.
- https://github.com/mgp25/Chat-API/issues/1814 : I dont understand your anwer here.
- https://github.com/mgp25/Chat-API/issues/1770 : The answer here is that it is OK and we have to wait until next release.
- https://github.com/mgp25/Chat-API/issues/1737: here we have users that get their issue closed without a single answer.
- https://github.com/mgp25/Chat-API/issues/1670 : at least he was lucky enough to have WART tool working, now we dont have that either.
- https://github.com/mgp25/Chat-API/issues/1667 : the issue seems to be the IP? 
 https://github.com/mgp25/Chat-API/issues/1660 : not much info here. 

Well I think this list is enough, is just the fist pages of issues searching for block. Trust me I have been following this protect for some time now.
BTW I only tried to use YOUR exampleFuncional.php after the register, which i supposed would work but gave me an error.
My fist number was blocked a month ago and I stoped testing to try to understand better your code. I have not changed anything in your examples, I have just been reading every topic that has been opened in the last month.
My general impression is that you guys work very hard but are starting to get a bit fed up of all the problems with this proyect. I see that there are at least 2 or 3 issues like mine each day but I had to try to see if I got lucky and obtained a better answer. 

So I suppose I will keep reading all your code again and again until i get a new line to test. Thought the exampleFuncional.php would work without problem with that name but guess I was wrong.
It is better to create my own workflow? 
And again all the topics that i find a mention of WA 2.0 say there is no ETA but i have to ask again. 

Thank you for all your time and efforts

**Comment by mgp25** [comment]
@alm-92 all issues are answered at least twice with the proper explanation and solution, due to the lack of free time we can't answer all questions meaning that most of the questions are duplicate. Solution can be found in the wiki too.

Answering to your duplicate question:

When you get `temporary_unavailable` as response, WhatsApp has flagged your IP / number provider / number, so subsecuent numbers will be banned instantly.

This also happens when you try to register many numbers (or maybe just a couple, depending on WhatsApp algorithm) in a short period of time.

And yes, its possible to get blocked without sending anything with a bad flow, but since you havent posted we can't guide you or tell you whats wrong with it.

WA 2.0 is already done since March, and we won't release it until the one in github stops working


Most of the issues is because bad flow or bad coding behaviours, and is not an API issue but user problem for not understanding how WhatsApp works. I know people doesnt like to read or even debug or post debug logs so in the next release everything is done automatically by the API.

Some examples are outdated, try creating your own with the documentation provided in the wiki

Regards

**Comment by alm-92** [comment]
Thanks a lot @mgp25. I understand that you flag things as duplicate but i just wanted to show that it is quite difficult to find useful information with all the topics created. 

Also there is no way of checking if my IP has been flagged right? And in the case my IP is flagged, does that mean that ONLY the numbers registered from the same IP will be instantly blocked? Or if I am able to correctly register a number from a different IP I will be able to use the API afterwards from the flagged IP? 
I thought that i had flagged my IP almost a month ago, when i first tried your API without much reading so when I was able last friday to register a number without getting banned I was very happy. 

Well I suppose i will try to register a new line from home and try again if it is possible. 
And please dont get upset by all the people that complain, it is just that Whatsapp does not provide an official API and many people are searching for one, and yours is the only one that keeps up to date. So please keep on with that hard work and sorry for any trouble.

Also I will try just using the workflow posted on the wiki as I suppose it is the most updated one.

Regards

**Comment by edudesouza** [comment]
Hi fellows, 

Try to set-up a linux box, and use a 4G modem, this way your application will connect to WA server through a mobile carrier IP.
It the IP is the matter to be blocked this will resolve, although if you are sending mass messages you will be blocked anyway.

Cheers!

**Comment by BurakDev** [comment]
@edudesouza Is exactly what I'm doing, using the correct workflow and using 4G connectivity, never banned

**Comment by karlobencic** [comment]
@mgp25 it seems that this version is very close to "not working", because my account gets banned each day and I have to register a new phone number. I don't even send any messages to anyone, just my client is always online and that's all.

**Comment by mgp25** [comment]
@karlobencic 

This code is in no way affiliated with, authorized, maintained, sponsored or endorsed by WhatsApp or any of its affiliates or subsidiaries. This is an independent and unofficial API.** Use at your own risk.**

**Comment by karlobencic** [comment]
@mgp25 risks can be reduced by keeping the API updated. It seems that WhatsApp is blocking all the clients that use old versions of WhatsApp, so all the people wouldn't get blocked in the past few days if the API would update. 

Is there a way for us to manually change the WhatsApp version, token, user-agent etc? I don't see anything in the docs about it, and I tried to manually change it in Constants.php but getting "bad_token" when trying to run the client, so I guess this file is not the only thing that has to be changed.

**Comment by mgp25** [comment]
@karlobencic oks, send a pull request with the update

**Comment by karlobencic** [comment]
@mgp25 if I change the Constnats.php file(WHATSAPP_VER and WHATSAPP_USER_AGENT), the client won't start because as I said, I don't know what is everything that has to be changed in order to stop getting banned from WhatsApp for using the old version and the same user-agent as everyone else. The only thing that I managed to change was DEVICE, OS_VERSION, MANUFACTURER and BUILD_VERSION (all supported devices with this info can be found here https://support.google.com/googleplay/answer/1727131) which only got me extra hours to not get banned again, but still it's not enough.
