### ISSUE TITLE
stream error

### ISSUE THREAD

**Issue by nolifer123** [mgp25/Chat-API#2005]
- [X ] You are using PHP > 5.6
- [X ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X ] You have checked if someone has already asked the same issue you have. someone did but long time ago and before the patches
- [X ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ X] Is not a programming question.
- [ X] You are using latest Chat API code.

### Error
Post your error below:
```xml
rx  <stream:error>
rx    <ack id="240D958D7FEDE0F52F3802B6937FC4"></ack>
rx  </stream:error>
```

### Debug log
Post your debug log below:
http://hastebin.com/evideheved.xml

and i know it's wasapbot but it's fully based at chat-api and with chat-api i got it aswell

**Comment by mgp25** [comment]
@nolifer123 thats means something with `id="240D958D7FEDE0F52F3802B6937FC4` is not acked

**Comment by nolifer123** [comment]
thanks for fast answer it looks liek deleting the db's where working is that even possible?
