### ISSUE TITLE
What is wrong?

### ISSUE THREAD

**Issue by jacoboliveira** [mgp25/Chat-API#2008]
- [ x ] You are using PHP > 5.6
- [ x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x ] You have checked if someone has already asked the same issue you have.
- [ x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [  ] Is not a programming question.
- [ x ] You are using latest Chat API code.

Hello can you help me in the code below, tell me what is wrong, because I was already banned twice and I do not know what to do more

**My first Login:**

        $username = "559193XXXXXX";
        $nickName="mentor01";
        $password="XXX";
        $numeros= array("559192XXXXXX");
        $this->w = new WhatsProt($username, $nickName, true, strtolower(urlencode(sha1($nickName, true))));

        $events = new MyEvents($this->w);
        $events->setEventsToListenFor($events->activeEvents);

        $this->w->connect();
        $this->w->loginWithPassword($password);
    
        $this->w->sendGetGroups(); // Get groups (participating)

        $this->w->sendGetBroadcastLists(); // Get broadcasts lists

        $this->w->sendSync($numeros, null, 0); // Sync all contacts

        foreach ($numeros as $numero) {
            $this->w->sendPresenceSubscription($numero); // subscribe to the user
        }

        $this->w->sendGetStatuses($numeros);

        foreach ($numeros as $numero) {
            $this->w->sendGetProfilePicture($numero); // preview profile picture of every contact
        }

        $this->w->disconnect();

**Send Message:**
        
        $username = "559193XXXXXX";
        $nickName = "mentorX";
        $password = "XXX";
        $numero = "559192XXXXXX";

        $this->w = new WhatsProt($username, $nickName, true, strtolower(urlencode(sha1($nickName, true))));

        //se já estiver aberta a sessao, somente conecta e loga
        $this->w->connect();
        $this->w->loginWithPassword($password);
        //---------------------------------

        if (!isset($_SESSION["OPEN_SESSION"])) {   //ETAPA 2
            session_start();
            $_SESSION["OPEN_SESSION"]=true;
            //abrindo uma nova sessao
            $this->w->sendSync($numero, null, 3);//3 delta interactive

            //Verificando se existe usuarios novos para inscricao

            $this->w->sendPresenceSubscription($numero); // subscribe to the user
        } else {

            //encerra sessao
            unset($_SESSION["OPEN_SESSION"]);
        }

        sleep(1);
        $this->w->pollMessage();

        $this->w->sendMessageComposing($numero);

        sleep(1);

        $this->w->sendMessagePaused($numero);

        sleep(1);

        $this->w->sendMessage($numero, "Ola5");

        sleep(2);
        while($this->w->pollMessage());
        sleep(5);
        $this->w->disconnect();

I have already been banned twice with this code

What is wrong? Can you help me?

**Comment by mgp25** [comment]
@jacoboliveira post debug log

**Comment by jacoboliveira** [comment]
DEBUG LOG

```xml
tx  <stream:features></stream:features>

tx  <auth user="559193117690" mechanism="WAUTH-2">384531ec3535393139333131373639308ecf7e6a03d47e13f1f49d9ab462c029ecf1710931343635393131333930</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>1d5b7ae365492773197e5d126ab4eef583930378</challenge>

tx  <response>f0b18723e93e8526e6de83640769f3387454c354a364e46378acf15524c03b4729811197d985a545e598617c5a3272cdbc1dd02d3bd88074dba6e1131e7db037fa144a62dc936e4658a322b67419</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by mgp25** [comment]
```xml

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

means blocked

**Comment by jacoboliveira** [comment]
but, as I do in my code to not occur blocking?

**Comment by mgp25** [comment]
Post debug log previous to the block

**Comment by jacoboliveira** [comment]
follows the DEBUG LOG previous block

```xml
tx  <stream:features></stream:features>

tx  <auth user="559192605686" mechanism="WAUTH-2">30babcb8353539313932363035363836d2aa168a5b9f9980a34743969232d0fd9ad65cd131343635393337323839</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>0512b6638fc2066d6faf000423efe3b2171d7e77</challenge>

tx  <response>00cdd15761f5642954c1abdd7452b895b019d5ac2e4ff2a60da9b042f145f4723242f82d08d2d92be50319b00cda2ce9ed400d2e9d7fcc551bac58a475301d6c73144ca5525324637b15b4f297b3</response>

rx  <success t="1465937292" props="5" kind="free" status="active" creation="1465934160" expiration="4444444444">f104e61fcf50b843982f92c464d56fb88ebc6fb5</success>

tx  <presence name="w3comm" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_437e8426-2b2b-45ab-9ee5-dffc1ca11a76" index="0" last="true">
tx      <user>+559192278836</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <notification from="s.whatsapp.net" type="encrypt" id="4149875711" t="1465937292">
rx    <count value="0"></count>
rx  </notification>

tx  <ack to="s.whatsapp.net" class="notification" id="4149875711" type="encrypt"></ack>

rx  <presence from="559192605686@s.whatsapp.net"></presence>

rx  <iq from="559192605686@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <presence from="559192278836@s.whatsapp.net"></presence>

rx  <iq from="559192605686@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_437e8426-2b2b-45ab-9ee5-dffc1ca11a76" last="true" version="1465934544357311">
rx      <in>
rx        <user jid="559192278836@s.whatsapp.net">+559192278836</user>
rx      </in>
rx    </sync>
rx  </iq>

tx  <presence type="subscribe" to="559192278836@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="04" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="gcm" id="w6J5u_mK04d:APA91b2Z9wP1YRUCVlmGkXW8yvgAEHeCrJeFvm1DgHpEjUnHxHefN9olGIsSTXJ896pDHk_GTpVk-qSRv7MjWQ1zA_nG3iIbYUf_cGBQTO9OdTX_q_SsR7skntGoGDkdVUnhd4EixnLU"></config>
tx  </iq>

tx  <chatstate to="559192278836@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="559192278836@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="559192278836@s.whatsapp.net" type="text" id="9f182b451d93f0d44c0cdb" t="1465937293" notify="w3comm">
tx    <body>Yes</body>
tx  </message>

rx  <presence from="559192278836@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="04"></iq>

rx  <ack from="559192278836@s.whatsapp.net" class="message" id="9f182b451d93f0d44c0cdb" t="1465937295"></ack>

rx  <receipt from="559192278836@s.whatsapp.net" id="9f182b451d93f0d44c0cdb" t="1465937296"></receipt>

```
