### ISSUE TITLE
decryptMessage resulting on stream:error <ack id="xx"

### ISSUE THREAD

**Issue by thiagosantos** [mgp25/Chat-API#2014]
### Error
"stream:error" with 'ack id="XXXX" '
 
I've been getting this error since I created a group, added one chat-api account to it and move this account from one computer to another computer with a FRESH Chat-API code. What I can see looking at the logs is that Chat-API tries do decrypt the message and can't do it because in this fresh code the API doesn't have the keys from the first computer. Than the API send a retry, and get the same encrypted message, and again send another retry, and get the same ecrypted message, than WhatsApp close the connection because it's something wrong  with ack on id "XXXXX".

My point here is if I force a "receipt" message as did @anativ (https://github.com/mgp25/Chat-API/issues/1791#issuecomment-205744390) I will not receive this encrypted messages a second time. But, I can lose something important, and that what I wouldn't like to. So, is it possible to "reload" or get new/same keys when they are not available in sqlite?

Best regards,

**Comment by mgp25** [comment]
I'll check it. The API still need some fixes. Ill update from time to time

Regards
