### ISSUE TITLE
onClose event workaround suggestions

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#2015]
Hello ! I noticed today that even the `Connection closed` exception is occured the `api` still process the `pollMessage` function because the `pollMessage` function read and the `connection closed!` occured when write, and the same exception occured again and again because we are reading from socket but we cannot write to it the suitable answer, so as mentioned above `Connection closed!` still occured until socket re established or number blocked .......

My question is what if we add to `api` to disconnect  and reconnect then login when firing `onClose` event , is it a good workaround , or it may has unwanted behavior ?

Or to add a flag that connection closed and test this flag when trying to write into socket within `sendData` function,if this flag is tru so connection closed so we need to re establish the connection before write, else we write into socket normally !

Regards !

**Comment by mgp25** [comment]
Tnat is something you should code as part of your script. Each person does different things when connection closed or disconnected.

Regards

**Comment by MoudiZd** [comment]
Thank you for fast answer !
As another question in other way !

Can i invoke disconnection when connection is closed in my code , it is a good practice ?

**Comment by mgp25** [comment]
Once connection is closed you can do whatever you want, as the connection is already closed

Regards
