### ISSUE TITLE
Workflow issue

### ISSUE THREAD

**Issue by BjHelm** [mgp25/Chat-API#2017]
Good Morning,

I dont understand why some of my numbers are getting blocked.
I use the following code.
```php
$w = new WhatsProt($Number,$Name,1,1);
  if($w->connect()) 
  {
    try {
      $w->loginWithPassword($Password);     
    } catch (Exception $e) {           
        exit();
    }
    if(firstLogin)
    {
      try{
        $w->sendGetClientConfig();
        $w->sendGetServerProperties();
        $w->sendGetGroups();
        $w->sendGetBroadcastLists();
      } catch (Exception $ex) {
        exit();
      }      
    }
    
    try{
      $w->sendGetPrivacyBlockedList();
      $w->sendAvailableForChat($Name);
      while($w->pollMessage()){}
      $w->sendOfflineStatus();
      $w->disconnect();
    } catch (Exception $ex) {
      exit();
    }
```

Some of my number are blocked some are working fine without any problems.
Do you have any idea why?

This is my logfile.

[2016-06-16 19:05:01] [INFO]: Connected to WA server
[2016-06-16 19:05:01] [INFO]: number successfully logged in
[2016-06-16 19:05:02] [ERROR]: Iq error with 1 id
[2016-06-16 19:05:04] [INFO]: Disconnected from WA server
[2016-06-16 19:06:01] [INFO]: Connected to WA server
[2016-06-16 19:06:02] [INFO]: number successfully logged in
[2016-06-16 19:06:02] [ERROR]: Iq error with 1 id
[2016-06-16 19:06:04] [INFO]: Disconnected from WA server
[2016-06-16 19:07:01] [INFO]: Connected to WA server
[2016-06-16 19:07:03] [ERROR]: Blocked number or wrong password. Use blockChecker.php

I use the same workflow for 2 other numbers but they are still working.
I'm trying to use your Api to create a nera time Chat, thats why I connect every minute to WhatsApp to get the latest messages.

I read the wiki a lot of times but I dont understand what I'm doing wrong.
Could you help me please?

Regards

**Comment by mgp25** [comment]
Please post full debug log, we need that to know the exact reason why you were blocked

Regards

**Comment by BjHelm** [comment]
I already posted my log file. 

tx  stream:features /stream:features

tx  auth user="493455698924" mechanism="WAUTH-2" 2c549d62343933343535363938393234a5529a10d230830c58ad6cf9392f8b65545e285131343636313530363431 /auth

rx  from s.whatsapp.net="" /from

rx  stream:features /stream:features

rx  challenge c42258ad124dc90291efd3ecea8f33c0d3c5818c /challenge

tx  response 40f6b9fbebc975c656207d28c24a8d14a7c0ace5c6ed70f40dce8e0e6f73a4903254ca2e2ccc61eafda01521957131289dbb57432f7f1826231be47e80737280161fa93be11541e438b7fd50a20c /response

rx  success t="1466150642" props="5" kind="free" status="active" creation="1465450236" expiration="4444444444" 289c971c6db26432b3c8e19f68cd6c6517f9c1d8 /success

tx  presence name="Thomas" type="available" /presence

tx  iq id="1" xmlns="jabber:iq:privacy" type="get"
tx    query
tx      list name="default" /list
tx    /query
tx  /iq

tx  presence name="Thomas" type="available" /presence

rx  ib from="s.whatsapp.net"
rx    offline count="0" /offline
rx  /ib

rx  presence from="493455698924@s.whatsapp.net" /presence

rx  iq from="493455698924@s.whatsapp.net" type="error" id="1"
rx    error code="404" text="item-not-found" /error
rx  /iq

tx  presence type="unavailable" /presence

this is the debug log of my numbers. I don't have the debug log of my blocked numbers, because i don't save it. Are you able to help me without the debug log of the blocked number?

Regards
