### ISSUE TITLE
Should sendMessagePaused be sent everytime before sending a message / image?

### ISSUE THREAD

**Issue by micp1989** [mgp25/Chat-API#2022]
Hi,

does somebody know if sendMessagePaused() is sent everytime when sending a message from WA? I sent a few messages from my phone and it seems that onMessagePaused is only fired if I am waiting for more than 2,5s after typing before I send the message.

When I send an image sendMessagePaused and even sendMessageComposing doesn't seem to be called at all. Am I right?

Greets

**Comment by mgp25** [comment]
@micp1989 yes, is always sent. Just do it like an average person would do. There is no specific time in that.

Regards
