### ISSUE TITLE
I keep getting Uncaught exception 'LoginFailureException' no matter what

### ISSUE THREAD

**Issue by yoni1306** [mgp25/Chat-API#2024]
Hey, 
5 days ago everything worked just fine (I just ran the contactsync.php example to make sure) and today when I'm trying to run the exact same script I get the mentioned error.

Thing is, I get this error no matter what, even when I use other channels or even different IP(!!) so I wanted to raise a flag here and check if everything is ok.

Here's the debug log -
```
tx  <stream:features></stream:features>
tx  <auth user="447937427803" mechanism="WAUTH-2"></auth>
rx  <from s.whatsapp.net=""></from>
rx  <stream:features></stream:features>
rx  <challenge>5b59b7a89d578f9106c050f3192b3bd34e6ed878</challenge>
tx  <response>ee8207ac576b41ef698cb30c8d510336070326bd8cf2d62bda37f8f57cd65d4bd524078a3e9076d6070a6cf5868a3abde77712e5628355cd4d4c8a8dd04fd26f79414e1ce1a95dc9b62bcf077fdb</response>
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

Yeah, I know people have posted the same log a few days ago, but that's my last option so I gotta try.

Does everything works fine for everyone?!

**Comment by 0xTryCatch** [comment]
You have been blocked. How many channels do you have?

**Comment by yoni1306** [comment]
What was blocked? my IP? my channel?

I got like 100 channels..
