### ISSUE TITLE
Get Block only new numbers

### ISSUE THREAD

**Issue by pabloruan0710** [mgp25/Chat-API#2025]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ X] You are using PHP > 5.6
- [ X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ X] You have checked if someone has already asked the same issue you have.
- [ X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X ] Is not a programming question.
- [ X] You are using latest Chat API code.

### Error
Post your error below:

I have a number that is working to 2 months , and when a new active number and place to run , this new number is blocked for a few minutes , but the other still remains , what can be wrong?
This is my workflow:

`
while (1) {
  	
	$w->pollMessage();
  	usleep(rand(500000,3500000));
  
  	//ENVIA MENSAGENS
	$mensagens = User::enviarMensagensNaoEnviadas();
    if (isset($mensagens) && !empty($mensagens) && count($mensagens) > 0) {
		if ($mensagens['body'] != NULL && $mensagens['body'] != 'msg'){
			$w->sendMessageComposing($mensagens['target']);
			//echo "DEBUG: sendMessageComposing";
			usleep(rand(500000,3500000));
			$w->sendMessagePaused($mensagens['target']);
			//echo "DEBUG: sendMessagePaused";
			usleep(500000);
            $w->sendMessage($mensagens['target'], $mensagens['body']);
			//echo "DEBUG: sendMessage";
			$w->pollMessage();
		}
    }
	
	//ATUALIZAR STATUS
	$novoStatus = User::atualizarStatus();   
    if (isset($novoStatus) && !empty($novoStatus)){
    	$w->sendStatusUpdate(utf8_decode($novoStatus));    
    }
    
    //ATUALIZAR IMAGEM PERFIL
    $caminhoImagem = User::atualizarImagemPerfil();
	if (isset($caminhoImagem) && !empty($caminhoImagem)){
		$w->sendSetProfilePicture($caminhoImagem);  
		$w->pollMessage();  
	}
	
	//ENVIAR IMAGEM PARA DESTINATARIO
   	$enviarImagem = User::enviarImagemCliente();
	if (isset($enviarImagem) && !empty($enviarImagem)) {
		foreach ($$enviarImagem as $message) {
			$w->sendMessageImage($message['target'], $message['path_imagem']);
			$w->pollMessage();
		}
    }
}

$w->disconnect();`

### Debug log
Post your debug log below:

```xml
WooHoo!, Phone number 5562849**** conectado com sucesso!
   tx  <stream:features></stream:features>
   tx  <auth user="55628499*****" mechanism="WAUTH-2">a87311363535363238343939363831310ff3f6ff38611b86fcc37afe2a81cd9fecec9cbf31343636363233383739</auth>
   rx  <from s.whatsapp.net=""></from>
   rx  <stream:features></stream:features>
   rx  <challenge>176ec16c73216bb69728e5e44acc4a4c025b843e</challenge>
   tx  <response>2c3c36683ffec57749a9889a48143c1b787e83d18d779f012121ddb46ff25b36d7d43626f898d171845df54ee160a5447d000c70ceb86468e9515845687d8db913fd9cdb62868f54706b54a9ab34</response>
   rx  <success t="1466623879" props="5" kind="free" status="active" creation="1466616005" expiration="4444444444">1d02ab93e08f24575dbeac97b27f3cdf2d4e0c11</success>
   tx  <presence name="Ale**** WhatsApp" type="available"></presence>
   tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
   tx    <query>
   tx      <list name="default"></list>
   tx    </query>
   tx  </iq>
   tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
   tx    <config></config>
   tx  </iq>
   rx  <presence from="55628*****@s.whatsapp.net"></presence>
   rx  <iq from="5562849****@s.whatsapp.net" type="error" id="1">
   rx    <error code="404" text="item-not-found"></error>
   rx  </iq>
   rx  <ib from="s.whatsapp.net">
   rx    <offline count="0"></offline>
   rx  </ib>
   rx  <iq from="s.whatsapp.net" type="error" id="2">
   rx    <error code="404" text="item-not-found"></error>
   rx  </iq>
   rx  <presence from="556282264***@s.whatsapp.net"></presence>
   rx  <stream:error>
   rx    <system-shutdown></system-shutdown>
   rx  </stream:error>

   Booo!, Phone number 5562849**** foi desconectado!
   Fatal error: Uncaught ConnectionException: Connection Closed! in
   /var/sentora/hostdata/****/public_html/****/whatsapp/275/src/whatsprot.class.php:300
   Stack trace: #0
   /var/sentora/hostdata/***/public_html/****/whatsapp/275/socket.php(263):
   WhatsProt->pollMessage() #1 {main} thrown in
   /var/sentora/hostdata/****/public_html/****/whatsapp/275/src/whatsprot.class.php on
   line 300
```

**Comment by mgp25** [comment]
IP blocked it seems
