### ISSUE TITLE
API dies on receiving a new skey

### ISSUE THREAD

**Issue by thiagosantos** [mgp25/Chat-API#2026]
### Error
API dies every time it receive the same skey when trying to send a text message.

### Debug log
Post your debug log below:

```
tx  <iq id="3" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="55XXXXXXXX@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

rx  <presence from="55XXXXXXX@s.whatsapp.net" type="unavailable" last="none"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="3">
rx    <list>
rx      <user jid="55XXXXXXX@s.whatsapp.net">
rx        <registration>9488c8d7</registration>
rx        <type>05</type>
rx        <identity>7ff6605a8098c06d014e719b0f3289d638d8f6c91c82f33e68a4894177b58d33</identity>
rx        <skey>
rx          <id>\P2</id>
rx          <value>3e391adc7f0d6a5b571bed6787addf6fa71aaddd5daa0a8761e10ecb102a0518</value>
rx          <signature>3fae2b0b2e2968d960fc6b1a28af0268a35c708efb2b0efa2609d08613ae1dc0f144041a5743d58a07f0649d838952068954e8d60a7c3a356395a6a83a93ea89</signature>
rx        </skey>
rx      </user>
rx    </list>
rx  </iq>
```
After this, the process dies and when I restart I received the same skey and the process dies again.
Nothing more is send after this, neither an error or an exception.

**Comment by thiagosantos** [comment]
Any comment on this issue?

**Comment by MoudiZd** [comment]
try to delete axolotl-number.db file found inside the wadata folder

Regards !

**Comment by thiagosantos** [comment]
It didn't work

The problem is right here

```
$preKeyId = deAdjustId($user->getChild('key')->getChild('id')->getData());
$preKeyPublic = new DjbECPublicKey($user->getChild('key')->getChild('value')->getData());
```
This XML doesn't have the node 'key' just 'skey' and the IqHandler ask for it here https://github.com/mgp25/Chat-API/blob/master/src/handlers/IqHandler.php#L265 

As described in https://github.com/mgp25/Chat-API/blob/master/src/libaxolotl-php/SessionBuilder.php#L186 when preKey is not defined, signedPreKey should be used instead as V3.

This solved my problem.
```
$preKeyId = null;
$preKeyPublic = null;
if(!is_null($user->getChild('key'))){
    //SupportsV3 only
    $preKeyId = deAdjustId($user->getChild('key')->getChild('id')->getData());
    $preKeyPublic = new DjbECPublicKey($user->getChild('key')->getChild('value')->getData());
}
```

Regards,

**Comment by gabrielcombalia** [comment]
Thiago, could you please help me???? 

Unfortunately, I dont know what happens.... I could be able to use all the files in the folder /examples. I could even send the small video small.mp4 in exampleFunctional.php. I also could make WA CLi Client/client.php works whit database. I even made some cool things like filter the database mgstore-****.db, like filter and count everyone whose answered Hello:

`<?php

$GLOBALS['msg_db'] = '../../src/wadata/msgstore-55219880******.db';

function getMessages($phone)
{
$msgDB = $GLOBALS['msg_db'];
if (file_exists($msgDB)) {
$cDB = new PDO('sqlite:'.$msgDB, null, null, [PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$sql = 'SELECT from, message,t FROM messages WHERE message = :phone';
$query = $cDB->prepare($sql);
$query->execute([':phone' => $phone]);
$messages = $query->fetchAll();

    return $messages;
}
}

$contact ='Hello';
$Msgs = getMessages($contact);

    $GLOBALS['current_contact'] = $contact;
$contar=1;
foreach ($Msgs as $msg) {
echo "\n- ".$contar.' - '.$msg['from'].': '.$msg['message']."\n".date('t/m/Y h:i:s A', $msg['t'])."\n";
$contar++;
}`

But unfortnately, im ALWAYS BLOCKED by whatsapp. Even using the WA Cli Clent/client.php using only the commands /add, /chat, /back, /exit to speak normaly whit people , im always blocked. I use the whatsapp/chat-api:dev-master. I realy dont know what more can I do to dont be blocked by whatsapp server.
