### ISSUE TITLE
Getting blocked

### ISSUE THREAD

**Issue by JohnLit** [mgp25/Chat-API#2027]
Hello,

We are getting blocked , after registering a new number.
We used the system for 3 months or so and recently got blocked.
Today we registered a new number and got blocked again, within an hour or so.

We haven't sent any spam.

Are we doing anything wrong?

Could they block our server IP?

Any suggestions?

```
tx  <stream:features></stream:features>
tx  <auth user="************" mechanism="WAUTH-2">0159602b3138353732363935373233f2772184891e1b155e443751c7c959c25d67851631343636373132393632</auth>
rx  <from s.whatsapp.net=""></from>
rx  <stream:features></stream:features>
rx  <challenge>bba3fd70149e354eb510e14cf1b9be55907b92eb</challenge>
tx  <response>344dade31459427aa09761c4b92f812a9ce10661c07ecbf0fa06ad28260cf46e9bcabbb416d297f9392a81e31688d974e3050dcd0b21e2a0c2637867a9ab25aec42d29e2c685c25961b80141b1</response>
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by mgp25** [comment]
@JohnLit yes WA can block by API, without debug log we cant know the reasons of the block, post it for further support

Regards
