### ISSUE TITLE
bad_token and old_version

### ISSUE THREAD

**Issue by dgnovo** [mgp25/Chat-API#2029]
Hello, 
with original Constats.php

 const WHATSAPP_VER = '2.13.9';                                                          // The WhatsApp version.
    const WHATSAPP_USER_AGENT = 'WhatsApp/2.13.9 S40Version/14.26 Device/Nokia302';         // User agent used in request/registration code.

This is my response:

Array
(
    [in] => *************
    [cc] => 39
    [id] => ebփ#���{��k[z��g.
    [lg] => it
    [lc] => IT
    [sim_mcc] => 222
    [sim_mnc] => 000
    [method] => sms
    [token] => 6500bc97697f1aae98f78e0966e91a4e
)
stdClass Object
(
    [status] => fail
    [reason] => old_version
)

I change it like this:
const WHATSAPP_VER = '2.16.133'; 
const WHATSAPP_USER_AGENT = 'WhatsApp/2.16.133 S40Version/14.26 Device/Nokia302';    

and output is this:

Array
(
[in] => ***************
[cc] => 39
[id] => e�bփ#���{��k[z��g.
[lg] => it
[lc] => IT
[sim_mcc] => 222
[sim_mnc] => 000
[method] => sms
[token] => 6500bc97697f1aae98f78e0966e91a4e
)
stdClass Object
(
[status] => fail
[reason] => bad_token
)

Any ideas?

**Comment by mgp25** [comment]
You have an outdated code of Chat API

**Comment by dgnovo** [comment]
I had an error on composer. 
Thanks.
