### ISSUE TITLE
Register New number

### ISSUE THREAD

**Issue by dtsrwnis** [mgp25/Chat-API#2034]
I try sms + voice but i get the same result.

I try 3 different numbers!

stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
    [sms_wait] => 0
    [voice_wait] => 0
)

**Comment by dtsrwnis** [comment]
with register tool i got this

![image](https://cloud.githubusercontent.com/assets/9705923/16358371/f07228ec-3b19-11e6-8e08-54571d5a50af.png)

**Comment by vnay92** [comment]
post the debug logs bro!

With Best Regards,

Vinay V Bharadwaj
+91 8762804962

**Comment by mgp25** [comment]
IP flag or virtual phone number
