### ISSUE TITLE
WhatsApp blocking whithou motive

### ISSUE THREAD

**Issue by pedrosoares** [mgp25/Chat-API#2035]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
Post your error below:
I have registered the number using this API and send only 2 messages with them, 1 text and 1 photo. In the next day, my number was blocked. Why that? Whatsapp are detecting this api like unofficial?

### Debug log
Post your debug log below:

```
Array
(
    [cc] => 55
    [in] => 4885005524
    [lg] => pt
    [lc] => BR
    [id] => ^vbun,þŸxçø5ëŸ§›íq
    [token] => ZcttJyKCATF1vsEWlpVlWU0M0HQ=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 473
    [rchash] => ff0b6995a02cc9fcac481df6d62c05f77d806731ca28800ca6bc153d96d278eb
    [anhash] => 07676ab7a47ba3d4d7f95d20496a7ef2
    [extexist] => 1
    [extstate] => 1
    [mcc] => 724
    [mnc] => 000
    [sim_mcc] => 724
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
```

**Comment by mgp25** [comment]
@pedrosoares WhatsApp blocks numbers yes. If you dont post the debug log previous to the block we dont know

**Comment by pedrosoares** [comment]
I`m using laravel, where is the log location of WhatsApp?

**Comment by mgp25** [comment]
debug log is shown in terminal/shell/cmd

**Comment by msxandroid** [comment]
@pedrosoares PT: Avalia o fluxo da sua script, tem que ter um comportamento humano..Pode ajudar em nosso idioma portugues
En: Evaluates the flow of your script, you have to have a humano..Pode behavior help in our Portuguese language

**Comment by pedrosoares** [comment]
@msxandroid PT: Obrigado pela ajuda, deve ser este o problema pois eu estava abrindo conexão e fechando direto depois de enviar, vou tentar mandar sempre conectado via thread e enviar mensagens quando necessário.
EN: Thanks for the help, this maybe is the problem, becouse i open conection send message and disconect in next, i go try keep conection open by thread and send message when i need.

**Comment by edudesouza** [comment]
Faz o set-up de um server linux, e usa conexão via modem 3G, dessa forma vc estar conectado usando um IP da sua operadora. Set-up a linux box, use a 3G connection, this way you will connected with an operator IP.

**Comment by edudesouza** [comment]
Comportamento humano, nao responder mensagens com menos de 3s, nao enviar spam ... etc. Human behavior, not respond messages with less ten 3s, of course, not spammig ...

**Comment by msxandroid** [comment]
PT: Tenho aplicado minuciosamente todo os requesitos desta api, porem aplicar a conexao  3G da operadora do numero vai ser uma nova implementacao. Em todos os senarios havendo sucesso de uso sem o banimento estarei compartilhando.
EN: I have thoroughly applied all the requisites of this api, however apply the 3G connection of the number of carrier will be a new implementation. In all there senarios successful use without the ban will be sharing.

**Comment by msxandroid** [comment]
@edudesouza Esta tendo sucesso no cenario com 3G e temporizador 3s em seu projeto?
EN: This succeeding in the scenario with 3G and timer 3s in your project?

**Comment by pedrosoares** [comment]
PT: Irei aplicar estes conceitos no meu aplicativo para ver o resultado também, qualquer coisa irei reportar aqui.
EN: I will apply this concepts in my project to see the results, anithing i will report here.

**Comment by schoerg** [comment]
@edudesouza you can respond at any speed you want, as long as you don't spam i don't think there will be a problem. Haven't had one with blocking.

**Comment by malufett** [comment]
same here..what I did was just using the tools provided in this project(registerTool.php and Simple CLI clien)...then in the next morning it was blocked...

**Comment by MoudiZd** [comment]
Whatsapp did not block code , it is just block a bad routine or non human scenarios

Regards !

**Comment by pedrosoares** [comment]
In this time, i use a old whatsapp number, change my source to look likes a human and i dont block yet. Someone know why `@$message->getChild('body')->getData();` from exemple don`t work? `Call to a member function getData() on null`

**Comment by malufett** [comment]
@pedrosoares same here..I even duplicate the way that I did in the new number that got blocked until now its still usable...while the new number just used twice got block...

**Comment by gabrielcombalia** [comment]
Unfortunately, I dont know what happens.... I could be able to use all the files in the folder /examples. I could even send the small video small.mp4 in exampleFunctional.php. I also could make WA CLi Client/client.php works whit database. I even made some cool things like filter the database mgstore-****.db, like filter and count everyone whose answered Hello:

`<?php


$GLOBALS['msg_db'] = '../../src/wadata/msgstore-55219880******.db';


function getMessages($phone)
{
    $msgDB = $GLOBALS['msg_db'];
    if (file_exists($msgDB)) {
        $cDB = new PDO('sqlite:'.$msgDB, null, null, [PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        $sql = 'SELECT `from`, `message`,`t`  FROM messages WHERE `message` = :phone';
        $query = $cDB->prepare($sql);
        $query->execute([':phone' => $phone]);
        $messages = $query->fetchAll();

        return $messages;
    }
}


$contact ='Hello';
$Msgs = getMessages($contact);
           
        $GLOBALS['current_contact'] = $contact;
$contar=1;
        foreach ($Msgs as $msg) {
            echo "\n- ".$contar.' - '.$msg['from'].': '.$msg['message']."\n".date('t/m/Y h:i:s A', $msg['t'])."\n";
            $contar++;
        }`

But unfortnately, im ALWAYS BLOCKED by whatsapp. Even using the WA Cli Clent/client.php using only the commands /add, /chat, /back, /exit to sekap normaly whit people , im  always blocked. I use the whatsapp/chat-api:dev-master. I realy dont know what more  can I do to dont be blocked by whatsapp server.

**Comment by pedrosoares** [comment]
I got block again with a new number, in this time i used a terminal script that is aways connected, i send message from a ramdon time 5s to 10s. Work for 2 days, i got blocked in the 3 day.
OBS: I dont send span, is for inform news from my website for clients that ask for receive by whatsapp.
OBS 2: Now i used a old number used in a phone before use in php.

I go try at last try a new method. Use WhatsApp toggether in php and CellPhone. I hope not get blocked again.

**Comment by pedrosoares** [comment]
I was thinquing that the problem is not the way we are sending messages, 
but the way that we get the password, i gone try a new script and get 
password from my cellphone and not using API.


Em 28/06/16 17:31, gabrielcombalia escreveu:

**Comment by msxandroid** [comment]
PT:Amigos venho comunicar a noticia da estabilidade ah 2 dias com interações com diversos contato.
EN:Friends come to communicate the news of stability ah two days with interactions with various contact.

**Comment by edudesouza** [comment]
PT: usando modem 3G, certo?
EN: using 3G modem, right?

**Comment by msxandroid** [comment]
PT:Nao estou usando 3G nesta solução, apliquei conexao local adsl e vps datacenter USA. Sucesso em todos os ambientes.
EN:Not'm using 3G in this solution, applied adsl connection site and vps datacenter USA. Success in all environments.

**Comment by edudesouza** [comment]
Nice!
Same thing here, but instead ADSL I am connecting with a 3G. In my findings look like WA try to resolve your IP and chances are better connecting through a real Internet Provide. Another question you are using a Linux box, which distro?

Ótimo!
Eu uso aqui do meu lado uma conexão 3G, mas minhas pesquisas mostraram que em algum momento o WA tenta verificar seu IP, e as chances de ser bloqueado usando um VPS ou algum hosting são maiores do que usando um IP de algum provedor ou 3G. Outra pergunta, vc está usando Linux, qual distro?

**Comment by msxandroid** [comment]
@edudesouza  Ubuntu

**Comment by edudesouza** [comment]
14?

**Comment by msxandroid** [comment]
@edudesouza Ubuntu 14.04.4 LTS
