### ISSUE TITLE
i can't able to login

### ISSUE THREAD

**Issue by arunmasq** [mgp25/Chat-API#2036]
I was registered my +91 number using exampleRegister.php.. But i can't able to login using that password...

can anyone help me? Thanks for advanve

**Comment by mgp25** [comment]
Post debug log for further support

Regards

**Comment by arunmasq** [comment]
ProtocolNode Object
(
    [tag:ProtocolNode:private] => from
    [attributeHash:ProtocolNode:private] => Array
        (
            [s.whatsapp.net] => 
        )

    [children:ProtocolNode:private] => 
    [data:ProtocolNode:private] => 
)
ProtocolNode Object
(
    [tag:ProtocolNode:private] => stream:features
    [attributeHash:ProtocolNode:private] => Array
        (
        )

    [children:ProtocolNode:private] => 
    [data:ProtocolNode:private] => 
)
ProtocolNode Object
(
    [tag:ProtocolNode:private] => challenge
    [attributeHash:ProtocolNode:private] => Array
        (
        )

    [children:ProtocolNode:private] => 
    [data:ProtocolNode:private] => ��&Ӿ�q�B}�
���6�
)
ProtocolNode Object
(
    [tag:ProtocolNode:private] => failure
    [attributeHash:ProtocolNode:private] => Array
        (
        )

    [children:ProtocolNode:private] => Array
        (
            [0] => ProtocolNode Object
                (
                    [tag:ProtocolNode:private] => not-authorized
                    [attributeHash:ProtocolNode:private] => Array
                        (
                        )

                    [children:ProtocolNode:private] => 
                    [data:ProtocolNode:private] => 
                )

        )

    [data:ProtocolNode:private] => 
)

**Comment by mgp25** [comment]
@arunmasq not a `var_dump`, the built-in debug log that outputs nodes in terminal/cmd/shell

**Comment by arunmasq** [comment]
@mgp25 Is this API supports +91 numbers?

**Comment by vnay92** [comment]
I've been using a +91 number for a long time, and it works perfectly. You, however may be blocked. Post the debug log by setting "debug" as true. That'll give a better information.

**Comment by arunmasq** [comment]
[2016-06-27 10:22:59] [INFO]: Connected to WA server
[2016-06-27 10:23:04] [ERROR]: Blocked number or wrong password. Use blockChecker.php
[2016-06-27 10:23:04] [INFO]: Disconnected from WA server

**Comment by arunmasq** [comment]
But i was registered my number using exampleRegister.php

**Comment by arunmasq** [comment]
Thanks its working.. Now i got the message "Success: Message Sent!".. But message not delivered to that number..

**Comment by arunmasq** [comment]
message delivered from the following url  "Chat-API-master/examples/exampleFunctional.php".

But not delivered from "Chat-API-master/examples/whatsapp.php".

Please give me a solution for that..
