### ISSUE TITLE
Receive then Read

### ISSUE THREAD

**Issue by fabianoaraujo** [mgp25/Chat-API#2043]
Hello, is there any way to receive messages and mark them as only as received and only after some time mark them as read? And if there is any way to do this? How to know when you read the messages sent by the api? Thank you

Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by MoudiZd** [comment]
Hello , try to use check the usage of this function `enableReadReceipt` it will do what you want from non auto sending receipt

and to handle messages received bind the `onGetMessage` to your function

And to send a message read receipt use `sendMessageRead` function

Regards !

**Comment by fabianoaraujo** [comment]
Thank you friend!

**Comment by baukepluggetest** [comment]
when I put the enableReadReceipt on disabled the message is still read directly.
can anyone explain how this should be configured ?
thanks

**Comment by MoudiZd** [comment]
post the part you use the `enableReadReceipt` of your code

Regards !

**Comment by baukepluggetest** [comment]
Hi MoudiZd,

thx for your reply

this is what I have changed not sure if that is correct:

```
    public function enableReadReceipt($disable)
    {
    $this->readReceipts = $disable;
	 echo "enableReadReceipt function";
     }

**Comment by MoudiZd** [comment]
Hello @baukepluggetest , i don't understand are you creating a wrapper function for the api function `enableReadReceipt` or you are changing the api function behavior ?

Please explain to me, why you want to override api function , why you don't use it at it is ?

Are you posting exactly what found within your code or you post an example ?

I need more explanation so i can help you 

Regards !

**Comment by baukepluggetest** [comment]
Hi @MoudiZd,

i misunderstood the function, maybe because the variable was called $enable. I thought I had to rename the $enable to $disable.

now I'm calling the function like this:
$w->enableReadReceipt(false);
thats working as supposed :-) the message is not being read
but then at a later time i want to send the read recipe by using:

$w->sendMessageRead('316########','DAF43C3B171B03AC2B4314CC04187F'); 

but that fails with the error : PHP Fatal error:  Call to a member function nodeString() on null in /var/www/engine/src/protocol.class.php on line 178
the message id is the one that i saved with the onGetMessage function. so im sure that is the correct one. and the phonenr is mine so im also sure that is correct.


thanks
Bauke

**Comment by MoudiZd** [comment]
Hello @baukepluggetest  try to change the `sendMessageRead` implentation to following

````
public function sendMessageRead($to, $id)
    {
        $listNode = null;
        $idNode = $id;
        if (is_array($id))
            {
                if(count($id)> 1)
                    {
                        $idNode = array_shift($id);
                        foreach ($id as $itemId)
                            {
                                $items[] = new ProtocolNode('item',
                                    ['id' => $itemId], null, null);
                            }
                        $listNode = new ProtocolNode('list', null, $items, null);
                    }
                else
                    {
                        $idNode = $id[0];
                    }
                
            }

        $children = !is_null($listNode)?[$listNode] : null;
        $messageNode = new ProtocolNode('receipt',
        [
          'type' => 'read',
          't'    => time(),
          'to'   => $this->getJID($to),
          'id'   => $idNode,
        ], $children, null);

        $this->sendNode($messageNode);
    }
````

`sendMessageRead` function contain bug when single message id is passed as parameter so i changed it to solve this bug

Try it and tell me if this solve your issue 

Regards !

**Comment by baukepluggetest** [comment]
Hi @MoudiZd,

thanks for all your effort in this project !
and even reacting on closed issues :-)

this update of the function did the trick ! this is in one word:

PERFECT !

thanks again and keep up the good work.
