### ISSUE TITLE
Uncaught Error: Class 'KeyHelper' not found after rebooting laptop

### ISSUE THREAD

**Issue by thingbreaker** [mgp25/Chat-API#2044]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:

I was succeed for sending and receiving messages, and then after rebooting my laptop i got this error when try to send and receive messages again.

### Debug log
Post your debug log below:

```xml
Fatal error: Uncaught Error: Class 'KeyHelper' not found in /Chat-API/src/whatsprot.class.php:347 Stack trace: 
#0 /Chat-API/src/Login.php(67): WhatsProt->sendSetPreKeys() 
#1 /Chat-API/src/whatsprot.class.php(287): Login->doLogin() 
#2 /Chat-API/syncContact.php(34): WhatsProt->loginWithPassword('g9kIK1vcridbb4o...') 
#3 {main} thrown in Chat-API/src/whatsprot.class.php on line 347
```

**Comment by mgp25** [comment]
Probably you have deleted some files, redownload the source again
