### ISSUE TITLE
fail [reason] => old_version

### ISSUE THREAD

**Issue by aurimar** [mgp25/Chat-API#2045]
Make sure these boxes are checked before submitting your issue -- thank you!

- [YES ] You are using PHP > 5.6
- [ YES] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [YES ] You have checked if someone has already asked the same issue you have.
- [ YES] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ YES] Is not a programming question.
- [ YES] You are using latest Chat API code.

### Error
fail [reason] => old_version

### Debug log
Array ( [cc] => 55 [in] => 83987722434 [lg] => pt [lc] => BR [id] =>  tJuDY7k4IsC73t90auYXlneqgYI= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 7177 [rchash] => 98fed3a8a94fc6c64382ee360ecddc0757f5d23f358f4fecb36001bbc40584d3 [anhash] => 6d484d7f79cc6f0c712f7d5d15168413 [extexist] => 1 [extstate] => 1 [mcc] => 724 [mnc] => 000 [sim_mcc] => 724 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => fail [reason] => old_version )

I 'm implementing the Chat -API and failing , presents a OLD_VERSION error.
Can someone help me?
I've tried updating the constants.php and not getting hit.
Would have a new update for the application ?
Awaiting!
Thank you

**Comment by 6Edge** [comment]
please use the latest update

**Comment by mgp25** [comment]
Duplicate #2042
