### ISSUE TITLE
My number is blocled 

### ISSUE THREAD

**Issue by 6Edge** [mgp25/Chat-API#2046]
- [Sure ] You are using PHP > 5.6
- [Sure  ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [Sure  ] You have checked if someone has already asked the same issue you have.
- [Sure  ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [Sure  ] Is not a programming question.
- [Sure  ] You are using latest Chat API code.

**I read closed issue and wiki many time .**

### Error
First of all:
 thank you very much for this API 
i like you work so much 
i am using this API to make whatsapp groups to learning and teaching people .
my Idea that user will send "agree" to API number then API will add the sender number to the group automatically after making sync"  $w->sendSync($from)  "  
i am using mysql to store the sender number for users and groups id .
so when i got 250 users on group the api will create new group and invite my private number "
 $w->sendPromoteParticipants($grp_id,"55555555555555");

but today my number got banned with out any reason .
please let me know why this happen ?

my code is : 
```php
<?php
set_time_limit(35000);
require('src/whatsprot.class.php');
require('includes/config.php');
$rules='none';
$tmsg ='none';
$amsg ='none';
$query = mysql_query("SELECT * FROM grp_rules");
{
  while($rows = mysql_fetch_assoc($query))
  {
    $id = $rows['uid'];
    if($id==1)
    {
      $rules=$rows['msgs'];
    } 
    else if($id==2)
    {
      $tmsg = $rows['msgs'];
    }
    else if($id==3)
    {
      $amsg = $rows['msgs'];
    }
  }
}
$username = "5555555555"; 
$password = "OIHGLKYIUF";
$w = new WhatsProt($username, "TestinGWhatsApp", true, true);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->eventManager()->bind("onGetGroups", "GetGroups");
$w->eventManager()->bind("onGroupCreate", "onGC");
$w->connect();
$w->loginWithPassword($password);

function onMessage($mynumber, $from, $id, $type, $time, $name, $body )
{
  global $w;
  global $rules;
  global $tmsg;
  global $amsg;
  $from = explode('@',$from);
  $from = $from[0];
  $body =trim($body);
  $w->sendSync($from);
  if($body!="agree")
  {
    $w->sendMessage($from,$rules);
  }
  else
  {
   $valid = mysql_num_rows(mysql_query("SELECT * FROM wagroups WHERE user_num='$from'"));
   sleep(2);
   if($valid==1)
    {
      sleep(rand(2,4));
      $w->sendMessage($from,$amsg);
    }
    else
    {
       $query = mysql_query("SELECT * FROM grps ORDER BY uid DESC LIMIT 1");
       while($rows = mysql_fetch_assoc($query))
       {
         $grp_id = $rows['grp_id'];
         $grp_num = $rows['grp_num'];
       }
       $chk = mysql_num_rows(mysql_query("SELECT * FROM wagroups WHERE group_id='$grp_id'"));
       if($chk>=250)
       {
          $new_grp_num = $grp_num+1;
          $w->sendSync("888888");
          sleep(rand(2,4));
          $w->sendGroupsChatCreate("learn".$new_grp_num,"888888");
          sleep(2);
          $query = mysql_query("SELECT * FROM grps ORDER BY uid DESC LIMIT 1");
          while($rows = mysql_fetch_assoc($query))
           {
             $grp_id = $rows['grp_id'];
           }
          sleep(rand(2,4));
          $w->sendPromoteParticipants($grp_id,"888888");
       }
       $query = mysql_query("SELECT * FROM grps ORDER BY uid DESC LIMIT 1");
       while($rows = mysql_fetch_assoc($query))
       {
        $grp_id = $rows['grp_id'];
       }
       sleep(rand(2,4));
       $w->sendMessage($from,$tmsg);
       sleep(rand(2,4));
       $w->sendGroupsParticipantsAdd($grp_id, $from);
       $query = mysql_query("INSERT INTO wagroups(group_id,user_num) VALUES ('$grp_id','$from')");
    }
  }
  
}
function onGC($mynumber, $groupId)
{
    $gquery = mysql_query("SELECT * FROM grps ORDER BY uid DESC LIMIT 1");
    while($grows = mysql_fetch_assoc($gquery))
    {
         $grp_num = $rows['grp_num'];
    }
    $ngn = $grp_num+1;
    $insquery = mysql_query("INSERT INTO grps(grp_id,grp_num) VALUE ('$groupId','$ngn')");
}
$i=0;
while($i<=200)
{
  $w->pollMessage();
  $w->getMessages();
  $i++;
}
$w->disconnect();






?>
```

 

### Debug log
Please let me know , how to get debug log ?
i am using VPS and my script working each minute using cron job .
so how to get the debug by SSH?

```xml
YOUR DEBUG LOG HERE
```

Best Regards

**Comment by mgp25** [comment]
WhatsApp blocks most of the VPS making numbers to be blocked.

Regards

**Comment by 6Edge** [comment]
Dear @mgp25

I am not spammer , because spammer doing like this to make numbers by VPS


Please read my post again and carefully. 
You will understand what I am saying .


Best Regards !

**Comment by edudesouza** [comment]
@6Edge if you have a dedicated IP address for your number you con live longer, but the problem is the reverse IP, If you reverse your hosting IP it will not be an operator domain ... something like that I guess.

**Comment by 6Edge** [comment]
@edudesouza
My IP is dedicated. 
It was working for more than a year on VPS server !

So how it will blocked today ?!
Also other number still working till this time .


Regards !

**Comment by edudesouza** [comment]
Sure, probably you where running under WA version 2.12.440, for some how, everybody using this version got banned in the last days or weeks.If you try to register as a 2.12.440 you get the message old version, so I assume they are rolling out a cleaning on numbers with old version + suspect behavior.
As you said you are on a VPS, so you IP is not a telco, adsl or mobile operator, if you reverse your IP you will probably get the url of your main website os VPS hposting provider.

**Comment by 6Edge** [comment]
@edudesouza
its not IP problem 
other number working for 1 year now and 24 hours online !
