### ISSUE TITLE
Registration directions in Wiki are possibly incorrect?

### ISSUE THREAD

**Issue by apoorvumang** [mgp25/Chat-API#2047]
The documentation I'm talking about

https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#number-registration

It says to create a registration object and call `requestCode` from it

```
$r = new Registration($username, $debug);
$r->codeRequest('sms'); // could be 'voice' too
```

However there is no Registration class in the source. Example for registration shows it has to be done like this 

```
$w = new WhatsProt($username, $nickname, $debug);
$w->codeRequest('sms');
```

**Comment by MoudiZd** [comment]
Which version of api you are using , it iseems you are using an old version

 Regards !

**Comment by apoorvumang** [comment]
Yeah, composer downloaded an old version for me, possibly because I have PHP 5.5 installed

**Comment by BurakDev** [comment]
@apoorvumang Clone the git repository and it's okay for you. When git is updated just execute a git pull.
