### ISSUE TITLE
no_routes always on php7 

### ISSUE THREAD

**Issue by alexk984** [mgp25/Chat-API#2051]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
I have erorr no_routes always on new server with php7. From other server it workes, tried many times

### Debug log
Post your debug log below:

```xml
Array
(
    [cc] => 79
    [in] => 251148057
    [lg] => ru
    [lc] => RU
    [id] => hf▒▒ed▒▒▒>▒ ▒▒x_
    [token] => /3qEd5eGwtnRJVY1+BocJojiKVQ=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 3190
    [rchash] => 833ed34e621b700f39d74f05a656d32934e37489c672f83fff0410ea9d9755e6
    [anhash] => 14a66316ca8247edf097e132a92ae575
    [extexist] => 1
    [extstate] => 1
    [mcc] => 250
    [mnc] => 001
    [sim_mcc] => 250
    [sim_mnc] => 001
    [method] => sms
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
    [sms_wait] => 0
    [voice_wait] => 0
)
Error: There was a problem trying to request the code.
```

**Comment by mgp25** [comment]
There is relationship between php version and the request. `no_routes` its because of your number/ip

Regards
