### ISSUE TITLE
Extract Password From CellPhone.

### ISSUE THREAD

**Issue by pedrosoares** [mgp25/Chat-API#2052]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [ x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
I`m trying to extrac the password from my cellphone but not exist anymore pw.dat.
And my WhatsApp not create a Cache.db.
I`m using WhatsApp IOS 7.2.

**Comment by mgp25** [comment]
The method is outdated, now the procedure to extract it, its more complex.

Regards

**Comment by pedrosoares** [comment]
You can show me a guide or something like to extract de password? I guess the blocking problem is get the password using the API because i got blocked 2 times without do anything wrong.
