### ISSUE TITLE
No Registration possible

### ISSUE THREAD

**Issue by PrimeGhostDE** [mgp25/Chat-API#2054]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

```
stdClass Object
(
    [status] => fail
    [reason] => old_version
)
```

if you try to register your phone number
also other API's have problems like that, see: https://github.com/tgalal/yowsup/issues/1335

Installed via Composer, so shouldn't work for others either...

### Debug log
Post your debug log below:

PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.'

**Comment by 6Edge** [comment]
use the latest version of chat-api  !
