### ISSUE TITLE
how to make "typing .." when API try to send message 

### ISSUE THREAD

**Issue by 6Edge** [mgp25/Chat-API#2055]
Make sure these boxes are checked before submitting your issue -- thank you!

- [sure] You are using PHP > 5.6
- [sure] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [sure] You have checked if someone has already asked the same issue you have.
- [sure] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [sure] Is not a programming question.
- [sure] You are using latest Chat API code.

### Error
I am searching in closed issue and wiki many time , but maybe because of my English little bad .
so please any one can help me to find this ?
and how to use ?

thank you very much 

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by jonofe** [comment]
use

`$w->sendMessageComposing($to)`

**Comment by 6Edge** [comment]
@jonofe 
Thank you very much for you help
its working well now .

any problem by Whatsapp if i use "$w->sendMessageComposing($to)" ?

because i already got banned without any reason

Thanks again

**Comment by BurakDev** [comment]
@6Edge You need use the workflow defined on the wiki and your script need to work like an human. Whatsapp detect all automated-like system.
