### ISSUE TITLE
Error logging in since today

### ISSUE THREAD

**Issue by modsfabio** [mgp25/Chat-API#2059]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ Yes ] You are using PHP > 5.6
- [ Yes ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ Yes ] You have checked if someone has already asked the same issue you have.
- [ Yes ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ Yes ] Is not a programming question.
- [ Yes ] You are using latest Chat API code.

### Error
```xml
Error [1]: exception 'LoginFailureException' in /home/wa/src/Login.php:54
Stack trace:
#0 /home/wa/src/whatsprot.class.php(287): Login->doLogin()
#1 /home/wa/client.php(62): WhatsProt->loginWithPassword('XXXXX...')
#2 {main}
```

### Debug log
```xml
tx  <stream:features></stream:features>

tx  <auth user="XXXXX" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>XXXXX</challenge>

tx  <response>XXXXX</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

```

I'm not sure what is wrong.. It was running till I restarted the script today. Now it won't log in again.
I also made a new registration to the number and got a new password. Doesn't work...

Thanks for your help!

**Comment by MorpheusBrz** [comment]
Your number is banned. :(

**Comment by ArielBadilla** [comment]
mine too, 3 of them, same issue.

**Comment by modsfabio** [comment]
Strange.. I did not spam or anything and it was working till I restarted today..
Did WhatsApp change anything?

**Comment by MorpheusBrz** [comment]
Post your code here.

The behavior is like a human?

**Comment by modsfabio** [comment]
It's human behaviour. Anyway, I tried to login from a different IP and it works.. Looks like WhatsApp banned the IP?

**Comment by MorpheusBrz** [comment]
Yes! Whatsapp can block IP.

Try with this API example codes and look the Wiki about whatsapp flow.
