### ISSUE TITLE
several new numbers blocked after 20 minutes

### ISSUE THREAD

**Issue by alemdg** [mgp25/Chat-API#2069]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Was using this Api for 8 month without problems, but today my number was blocked.
After this sittuation, I registered 2 more numbers, after 20 minutes both were blocked.

Any clue?, Whatsapp now is checking something else we dont know?

Thanks.

### Debug log
```xml
tx  <stream:features></stream:features>

tx  <auth user="5491164485960" mechanism="WAUTH-2">09df0791353439313136343438353
93630226e0c68d995cb7bd7dff112851dc1224252259731343638303131393639</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>afc0b52bd929f9c8e35f007e88fd705a5ca2ef78</challenge>

tx  <response>7f6c50e6e1c3da309ddaa851a86be1c32e90a3f441c2abe009fd85112064f2de2c
8cc4df77f81a2bc4df07c36f45a9d9a8b8370a81526910edb52c6e48984facc0a9899495c8b7f540
e7081649eb9ccb</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by alemdg** [comment]
tx  <stream:features></stream:features>

tx  <auth user="5491164485960" mechanism="WAUTH-2">09df0791353439313136343438353
93630226e0c68d995cb7bd7dff112851dc1224252259731343638303131393639</auth>

rx  from s.whatsapp.net=""></from>

rx  stream:features></stream:features>

rx  challenge>afc0b52bd929f9c8e35f007e88fd705a5ca2ef78</challenge>

tx  response>7f6c50e6e1c3da309ddaa851a86be1c32e90a3f441c2abe009fd85112064f2de2c
8cc4df77f81a2bc4df07c36f45a9d9a8b8370a81526910edb52c6e48984facc0a9899495c8b7f540
e7081649eb9ccb /response>

rx  failure>
rx    not-authorized></not-authorized>
rx  /failure>

**Comment by alvelig** [comment]
+1 same for me from the last week

**Comment by ulissesvaquero** [comment]
for me too, i've lost 10 numbers, using WA client

**Comment by fcosystems** [comment]
someone has been successful for at least one week in these last days ?

A serious proposal to create an open template of how to use the library mimicking the human thread behavior and following the work flow and Working together.

I have some function to share.

what do you think about ?

(sorry for my english I'm using google)
