### ISSUE TITLE
Error in receiving messages in this api

### ISSUE THREAD

**Issue by Dev-Aryan** [mgp25/Chat-API#2072]
Hello,
I am interested in using this api for myself & my community. I can easily send messages by the api but i am having problem in receiving the messages. When i call the ongetmessage function it doesn't display anything. Nor the phone got double/blue tick on whatsapp. Can you please help me to figure this error out.
*Additional info*: I am running this on my web server

Thanks

**Comment by Dev-Aryan** [comment]
@mgp25 Please look into this matter

**Comment by 0xTryCatch** [comment]
Post your debug log

**Comment by Dev-Aryan** [comment]
'tx  <stream:features></stream:features>

tx  <auth user="14849902455" mechanism="WAUTH-2">f019f308313438343939303234353544ac69808d4de2c87257bad952ef103887b154a631343638313334303331</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>aeb25de2c8993d4794815bae8283b28068514beb</challenge>

tx  <response>00ddb98fadac0dbee0cefe35f6fb8f68be0fe54e94b724e765da77d9d3c760fbf984ca5ca80a552f8496d0718f9b4a2b6062aa9f0f2d599ea9fc53e04548c5c81e856ef7a7a6861f1fbd554554</response>

rx  <success t="1468134032" props="5" kind="free" status="active" creation="1468091223" expiration="4444444444">739f26708ee35a43058b910188f4ee379ad88737</success>

tx  <presence name="Aryan" type="available"></presence>

tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="3" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="4" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="Android" version="2.12.556"></config>
tx  </iq>

tx  <iq id="5" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

tx  <iq id="6" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <chatstate to="919560954568@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <message to="xxxxxxxxx@s.whatsapp.net" type="text" id="9142f03e805b1fade4ea5c" t="1468134033" notify="Aryan">
tx    <body>try</body>
tx  </message>

rx  <presence from="xxxxxxxxx@s.whatsapp.net"></presence>'

**Comment by 0xTryCatch** [comment]
So where is the part where you receive a message? Are you disconnecting too soon?

**Comment by Dev-Aryan** [comment]
Well, i am not disconnecting but i don't know why i can't receive a message. Can you provide me the code which you use to receive messages?

**Are you on whatsapp/Skype ?**

**Comment by 0xTryCatch** [comment]
See the code examples

**Comment by Dev-Aryan** [comment]
Ok wait i will check and tell back if they work
