### ISSUE TITLE
Encrypted message

### ISSUE THREAD

**Issue by Dev-Aryan** [mgp25/Chat-API#2075]
Hello,
I can now receive messages but they are encrypted and i can't install curve php extension

> root@geekyaryan-geekyaryan-3457374:/home/ubuntu/workspace/php-curve25519-ext# phpize
bash: phpize: command not found

My log is:

```
rx  <message from="17277315606@s.whatsapp.net" type="text" id="99C89B7025CD40F35130019E318B43" offline="3" t="1468136633" notify="DevAryan">
rx    <enc v="1" type="pkmsg">33122105dd3beeb58cc1207047f1afebcdbee205150f9611c5a31cba65167cd56bddd8111a2105524c21ef6ed7e341ec5ac83e83a81330430dc5a0e79cedb1339837ce1be10c672242330a2105234b6dfd78f8279b8c983ef9c6077bc7f2baa20b2964f4eaede80c854af3ec651001180022105dbdc8af978627752e49ed82a8a90907315c69452dc4bf8928fce0f9a80230cced8107</enc>
rx  </message>
```

**Comment by mgp25** [comment]
Not API issue. Search in google to see how to install the packages you need: 
https://www.google.es/search?q=phpize%3A+command+not+found&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=ZwOCV-6QJsTU8geq-azgCA
