### ISSUE TITLE
The answer for "WhatsApp-Blocked-Me-Issue"

### ISSUE THREAD

**Issue by modsfabio** [mgp25/Chat-API#2077]
Why do you always close the issues about the "WhatsApp-Blocked-Me-Issue"?
Is there an official statement of you, why this happens?

I only see "duplicate" on every issue, but no answer ..

**Comment by 6Edge** [comment]
Because they don't have any reply for users .
It's not good .
If you cannot support your API users it's better to remove your repo .

Many time whatsapp  blocked us without any reasons .

Thanks !

**Comment by 6Edge** [comment]
It's better to make whatsapp group ,  then we can discuse about whatsapp api there and help together for all users ..

We can find sulotion there .. Regards !

**Comment by mgp25** [comment]
Solution has been posted many times, we cant answer the same question over and over again. Look at the FAQ, in the wiki.

**Comment by malufett** [comment]
sorry @mgp25  but the wiki and FAQ doesn't help cause I try just registering, login once then logout... after that login again after 4hrs or a day after then poof blocked...:(
