### ISSUE TITLE
several new numbers blocked after 20 minutes

### ISSUE THREAD

**Issue by alemdg** [mgp25/Chat-API#2079]
Make sure these boxes are checked before submitting your issue -- thank you!

 You are using PHP > 5.6
 You have installed all extensions and modules listed in here. PHP Protobuf and Curve25519 are required!
 You have checked if someone has already asked the same issue you have.
 You have read the wiki.
 Is not a programming question.
 You are using latest Chat API code.
Error

**IF YOU CLOSE IT because duplicated of WHATEVER SAY WHY, you are not being helpfull....!!!** 

Was using this Api for 8 month without problems, but today my number was blocked.
After this sittuation, I registered 2 more numbers, after 20 minutes both were blocked.

Any clue?, Whatsapp now is checking something else we dont know?

Thanks.

Debug log

tx  <stream:features></stream:features>

tx  <auth user="5491164485960" mechanism="WAUTH-2">09df0791353439313136343438353
93630226e0c68d995cb7bd7dff112851dc1224252259731343638303131393639</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>afc0b52bd929f9c8e35f007e88fd705a5ca2ef78</challenge>

tx  <response>7f6c50e6e1c3da309ddaa851a86be1c32e90a3f441c2abe009fd85112064f2de2c
8cc4df77f81a2bc4df07c36f45a9d9a8b8370a81526910edb52c6e48984facc0a9899495c8b7f540
e7081649eb9ccb</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

**Comment by mgp25** [comment]
Because there is a search bar, and its answered already, because we can write the same answer 20 timesa day, because we can't spent all the time in the API, because we have lifes, etc.

Use the search bar for God's sake!
