### ISSUE TITLE
error on retrieving new message

### ISSUE THREAD

**Issue by gentjana** [mgp25/Chat-API#2080]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

The first message is not retrieved from whatsapp api. An error is displayed as below.

### Debug log
Post your debug log below:

![image](https://cloud.githubusercontent.com/assets/5549913/16796199/ab404e18-48e1-11e6-968e-f5fcb1c8eb5d.png)

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
This is no debug log

Regards
