### ISSUE TITLE
Fresh SIM instantly banned after code request

### ISSUE THREAD

**Issue by iadj** [mgp25/Chat-API#2085]
Checked out the FAQ, didn't find a relevant answer.

I just tried to activate a new SIM Card with WATools, and I get the message 'Number or IP is blocked'.

Then I tried to activate it using my own script (Chat-API) and I get an undescribed error: There was a problem trying to request the code.

Then I tried to activate the number with the Whatsapp app on a phone, and I got the error that the number is banned from Whatsapp.

Is there something up with the Whatsapp service or is the API no longer good?

**Comment by dividebyzeer0** [comment]
My whatsapp account was banned yesterday after ~6 month of smooth usage. I tried a new sim card to register a new one but it also was banned 2 hours later after registration. Wasn't doing anynthing bad or suscpicious, just recording presence events of some contacts. Seems like whatsapp is actively fighting against the Chat API.

**Comment by iadj** [comment]
@mgp25 Why did you close the issue? It hasn't been solved nor answered.

**Comment by 0xTryCatch** [comment]
Read the wiki and 1.000.000 the same closed issues
