### ISSUE TITLE
Decrypt messages on web whatsapp

### ISSUE THREAD

**Issue by hugorezende** [mgp25/Chat-API#2086]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Hi!

Anyone could explain me with more datails how works the decryption process? 

I found decryptMessage() function on Handler class, but I'm not sure how it works.
I'm trying make a chrome extension to save the messages requests from whatapp web.

Anyone?

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by BurakDev** [comment]
@hugorezende https://en.wikipedia.org/wiki/Signal_(software)#Encryption_protocols

**Comment by hugorezende** [comment]
Thanks bud!
I'll check it.

**Comment by BurakDev** [comment]
@hugorezende I'm working on same thing, making a chat API using whatsappweb websocket :+1:
