### ISSUE TITLE
Whatsapp password extractor: file renamed

### ISSUE THREAD

**Issue by MrGlue** [mgp25/Chat-API#2088]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ NOT NEEDED] You are using PHP > 5.6
- [ NOT NEEDED] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ DONE] You have checked if someone has already asked the same issue you have.
- [ DONE] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ YES] Is not a programming question.
- [ NOT NEEDED] You are using latest Chat API code.

### Error
Post your error below:

The apk for Android which is located in the wiki is not working because whatsapp renamed the file in which the password is stored from pw to key. This applys also to the bash method i think.

**Comment by 0xTryCatch** [comment]
Password extraction is not working anymore in Android

**Comment by imagetag** [comment]
If your device is rooted or you are using bluestacks (rooted), you can copy and rename the file.
