### ISSUE TITLE
onGetGroupImage encryption

### ISSUE THREAD

**Issue by Justin991q** [mgp25/Chat-API#2089]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

The onGetGroupImage didn't work so I checked the issues and I saw in issue #1445 that the onGetGroupImage encryption is not implemented yet. This issue was submitted 7 months ago, is there already an ETA ?

**Comment by 0xTryCatch** [comment]
Not yet sorry
