### ISSUE TITLE
WhatsApp update and token

### ISSUE THREAD

**Issue by agossouvi** [mgp25/Chat-API#2090]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [ x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```
Hi,
It seems you need to change the new version of Whatsapp (to 2.16.178)  and also the MD5 class.

**Comment by mgp25** [comment]
You can send a pull request

Regards
