### ISSUE TITLE
Number Getting Banned by whatsapp

### ISSUE THREAD

**Issue by iftikhar85** [mgp25/Chat-API#2094]
Make sure these boxes are checked before submitting your issue -- thank you!

- [YES] You are using PHP > 5.6
- [YES] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [YES] You have checked if someone has already asked the same issue you have.
- [YES] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [YES] Is not a programming question.
- [YES] You are using latest Chat API code.

### Error
First of all I would like to thanks @mgp25 for such a good api.
I have read the wiki and all the other same issues, I been using the chat api for 8 months, many times I got blocked than I read wiki and other close issues and found out my mistake, I rectify it and start using the api again. 

The thing I learned is that to use the API we must pretend a human behavior, and its very true that if you use the human behavior whatsapp will not ban you.

But the thing that recently happen put me into doubt that there is something on the registerTool rather than the API itself. Because I register two real numbers, I emphasis that I only register the two numbers without sending a single message, updating status or my profile picture, than for some personal issues I was away from my computer for a week. Today I tried to use those numbers, and to my surprise both are blocked.

I would like to request @mgp25  and other admins to please not to close this issue, may be we together work and find the solution for this, I request all other members to please give your valuable suggestions that how to resolve this issue. Because I have not used my sims to communicate in any way so there is no need to pretend a human behavior, I came to the conclusion that the registerTool.php has some problems.

I have searched the wiki but there is no particular reason for this issue. So if there is also a same issue kindly provide the link.

Thanks and regards.

**Comment by mgp25** [comment]
Registration has changed, i dont know if i will ever update this

Regards
