### ISSUE TITLE
Mandatory E2E bar code not have in chat api

### ISSUE THREAD

**Issue by tarun72888** [mgp25/Chat-API#2100]
Make sure these boxes are checked before submitting your issue -- thank you!

- [Yes ] You are using PHP > 5.6
- [yes ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ yes] You have checked if someone has already asked the same issue you have.
- [ yes] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ yes] Is not a programming question.
- [ yes] You are using latest Chat API code.

### Error
Mandatory E2E bar code not have in chat api

In new E2E secure version whatsapp giving unique bar code for every wa contacts, with first sms

but in chat api currently not have any option for E2e bar code,

so the wa server not finding the specific parameters and location for E2E bar code,, and our no. ban with first sms,, please do something on E2E bar Code

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by 0xTryCatch** [comment]
The QR code has nothing to do with being blocked.
