### ISSUE TITLE
Receiving the message only once.

### ISSUE THREAD

**Issue by amankumarglobussoft** [mgp25/Chat-API#2101]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [x] You are using latest Chat API code.

### Error

First of all I would like to appreciate your work. Now my issue.
I am not able to receive the message in second time. I registered the  new number and received code, then got the password. Now when I send my first message I get that in no time but as I send the new message again I am not getting it.

**Comment by 0xTryCatch** [comment]
Debug log?

**Comment by amankumarglobussoft** [comment]
[debug log.txt](https://github.com/mgp25/Chat-API/files/383983/debug.log.txt)

**Comment by 0xTryCatch** [comment]
Thanks. Are you calling pollMessages()? Cannyou post your code?

**Comment by amankumarglobussoft** [comment]
@0xTryCatch 



$username = "63*********";
        $nickname = "phil";
        $password = "14pDP4HYn76nIKUdposDOhyzgTQ="; // The one we got registering the number
        $debug = true;

        $w = new WhatsProt($username, $nickname, $debug);

        $w->connect(); // Connect to WhatsApp network
        $w->loginWithPassword($password); // logging in with the password we got!
		
        $target = '91**********'; // The number of the person you are sending the message
	$message = 'cool aman';
	$w->sendMessage($target , $message);
	$target = '91**********'; // The number of the person you are sending the message
	$message = 'cool alok';
	$w->sendMessage($target , $message);

**Comment by BurakDev** [comment]
@amankumarglobussoft Btw, you are not using the correct workflow, you will be banned soon

**Comment by amankumarglobussoft** [comment]
@0xTryCatch 
What ??? 
Please guide me the correct why.

**Comment by 0xTryCatch** [comment]
Read the wiki
