### ISSUE TITLE
Instead of PDO can we use mysql? and why a bat file is bring created ?

### ISSUE THREAD

**Issue by amankumarglobussoft** [mgp25/Chat-API#2102]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

I found that while registering the number  bat file is being created, I would like to know why a bat file is being created, and Instead of PDO can we use mysql?

**Comment by arjunrajmp** [comment]
bat file???  dat file I think. It generates from buildIdentity function in Registration class (Registration.php) .

**Comment by arjunrajmp** [comment]
This program is keeping separate database( sqlite ) for every number you registering on it. You can change it to single  MySql db with some appropriate changes . I also wrote a similar application - whatsapp bot( using codeigniter , MySql and this project ) for a client. You can build one If you understand the workflow of this project.

**Comment by YugalXD** [comment]
@arjunrajmp can you share you code how you have developed the bot.

**Comment by amankumarglobussoft** [comment]
@arjunrajmp  Ok, I have not completed the code but I will share when Its will be completed.
