### ISSUE TITLE
How to check weather if we get logged in or not ?

### ISSUE THREAD

**Issue by amankumarglobussoft** [mgp25/Chat-API#2103]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

I am using in laravel.
I wanted to know how can I get response that weather the user is successfully logged in or not like

```
if(loginWithPassword === success ){
//code start
}
```

and also I am not able to get the any responce  from the below function.
$w->eventManager()->bind('onPresenceAvailable', 'onPresenceAvailable');
$w->eventManager()->bind('onPresenceUnavailable', 'onPresenceUnavailable');

MY CODE:
```
public function sendmsg()
    {
        $username = "63***********";
        $nickname = "phil";
        $password = "78Mrkc3+BfSCvtvFDNpisBimZIg="; 
        $debug = true;
        $w = new WhatsProt($username, $nickname, $debug);
        $w->connect(); // Connect to WhatsApp network
        $w->loginWithPassword($password);
        $w->eventManager()->bind('onPresenceAvailable', 'onPresenceAvailable');
        $w->eventManager()->bind('onPresenceUnavailable', 'onPresenceUnavailable');
        $w->disconnect();
    }
```

### Debug log

```xml
tx  <stream:features></stream:features>

tx  <auth user="639391408969" mechanism="WAUTH-2">d1d3b9de363339333931343038393639d3b792bc1d1ec89fcca36bbcbe88e025d2e3b60231343639363235333237</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>e0d452adf688a96cd8594e9250e437764c146087</challenge>

tx  <response>f54e8461de82e26b7b34665cc922e97185f19913bfed13bd560dbe4715d6161675e7d678d7fa53546d16c53e87b66c51ce22d3bdde688d7b518b92bc54d2dae6bea85802ecf2cee413fda847b565</response>

rx  <success t="1469625332" props="5" kind="free" status="active" creation="1469622146" expiration="4444444444">b3c8c1507598451fb8afbef96e25402d3e5533a0</success>

tx  <presence name="phil" type="available"></presence>

tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

```

**Comment by mgp25** [comment]
--> `rx  <success t="1469625332" props="5" kind="free" status="active" creation="1469622146" expiration="4444444444">b3c8c1507598451fb8afbef96e25402d3e5533a0</success>`
