### ISSUE TITLE
Why I am getting blocked ?

### ISSUE THREAD

**Issue by amankumarglobussoft** [mgp25/Chat-API#2105]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [x] You are using latest Chat API code.

I looked into your example to avoid the getting number by using the correct workflow but I got blocked. I am integrating this api in laravel framework. Is their any example for laravel users ?

My code:
```
public function sendmsg()
    {
        $username = "639391408969";
        $nickname = "phil";
        $password = "cRonYj3ApiUVJv7LDrYh8OOUjeE="; // The one we got registering the number
        $debug = true;

// Create a instance of WhastPort.

        $w = new WhatsProt($username, $nickname, $debug);
        $w->connect();
        $w->loginWithPassword($password);
        try {
            $w->loginWithPassword($password);
        } catch (Exception $e) {
            echo "Error: $e";
            exit();
        }

        try{
            $message = "hello";
            $w->PollMessage();
            $w->sendMessage($username , $message);
        }catch(Exception $e){
            echo "Error: $e";
            exit();
        }


        $w->disconnect();

    }
```

Debug Log:

```xml
tx  <stream:features></stream:features>

tx  <auth user="639391408969" mechanism="WAUTH-2">65c28e12363339333931343038393639f343575c40ab8c2145368f272da58acd488f653931343639363334333238</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>34e710e64159e060644c99b68c819e5118848729</challenge>

tx  <response>06d21888d7b5de2a1cfbc4fddb82035afa37587c310c73f0ae64b5ddfb9b4d40ef35555908b6e7156b8032aa7b441ff38c8240d898f40bc6be510247c44ebb5ac1cba33170814335494a0dc9a0bc</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by mgp25** [comment]
@amankumarglobussoft you need to provide debug log previous to the block to see what has really happened, anyway, check examples and wiki, your code is wrong.

Sending and disconnect is a bad behaviour

Regards
