### ISSUE TITLE
Unblock a number

### ISSUE THREAD

**Issue by igravity** [mgp25/Chat-API#2106]
I used the API to successfully register a number with whatsapp. I did not save the password, so I did the registration again. Since this gave me a new password, I thought the password could be gotten per registration. Long story short, my number got blocked.

How can I get Whatsapp to unblock my number using the API?

**Comment by BurakDev** [comment]
You can't.

**Comment by manufuentescr** [comment]
the only way is send a email to  whatsapp support and solicit the unblock
