### ISSUE TITLE
which event handle double ticks and blue ticks

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#2108]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Not error but a question, which is the event i must listen to so i can detect when to change the message status (sent(1 tick),recieved(2 gray ticks),read(2 blue ticks)) due message id ?

I search the code and i can see this event `onMessageReceivedClient` did it will do what i want ?

Regards !
### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by baukeplugge** [comment]
hi @MoudiZd 

bind the onMessageReceivedClient eventhandler
$w->eventManager()->bind('onMessageReceivedClient', 'onMessageReceivedClient');

and create a function like this:
function onMessageReceivedClient($mynumber, $from, $id, $type, $time, $participant)
{
	if (!$type)
	{
		// status clientdelivered
	} else 
	{
              //  status clientread
	}
}


good luck
Bauke
