### ISSUE TITLE
Send encrypt image

### ISSUE THREAD

**Issue by technocode** [mgp25/Chat-API#2112]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

Hi may i know how to send encrypt image. I check wiki not found anything.

**Comment by baukeplugge** [comment]
Hi @technocode its almost the same as sending a normal message

normal:
```			$w->sendMessage("targetphonenr" , "message"); ```

image:
``` $w->sendMessageImage("targetphonenr", "path + filename",false, $fsize, $fhash, "message");```

ofcourse these functions only work if you ment the requirements and working with the workflow mentioned in the Wiki.

maybe your next question, with these events you can _receive_ an image.

make an eventhandler:
``` $w->eventManager()->bind('onGetImage', 'onGetImage'); ```

and create the function used by the eventhandler:

```
function onGetImage($mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption)
{
	$timeid = time();
	$number = ExtractNumber($from);
        $nickname =  $name; //findNicknameByPhone($number);
        $path = Constants::MEDIA_FOLDER.'/';
    if (!file_exists($path)) {
        mkdir($path);
    }
    $filename = $path.$number.'-'.$timeid.'.jpg';
    $fp = @fopen($filename, 'w');
    if ($fp) {
        fwrite($fp, $file);
        fclose($fp);
	}
}```

**Comment by technocode** [comment]
@baukeplugge Thanks, ChatApi still not support media encryption in sending.
