### ISSUE TITLE
GENERATE only one password from one pc

### ISSUE THREAD

**Issue by tarun72888** [mgp25/Chat-API#2113]
Make sure these boxes are checked before submitting your issue -- thank you!

- [yes ] You are using PHP > 5.6
- [yes ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [yes ] You have checked if someone has already asked the same issue you have.
- [ yes] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [yes ] Is not a programming question.
- [ yes] You are using latest Chat API code.

### Error
Dear all chat api users if you geting ban again or again than try it..

generate one password from one pc only if you generate two or more password from single pc than your all no. will ban,,  thanks... 

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
This is false
