### ISSUE TITLE
Chat-API not working 

### ISSUE THREAD

**Issue by simoneaonzo** [mgp25/Chat-API#2115]
I used your API since 07/08/2016 without problems.
But now, despite I use the latest version, I can't login and I can't register the number (I have a dedicated sim for this purpose and I never used the mobile app with this number).

------------------------------------------------------------------------------------------------ 
-  [X] You are using PHP > 5.6 -> PHP 7.0.8
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required! 
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

------------------------------------------------------------------------------------------------ 
```xml
<p>WooHoo!, Phone number XXXXXXXXXXXX connected successfully!</p>tx  <stream:features></stream:features>

tx  <auth user="XXXXXXXXXXXX" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>51d8b355934f8611822cd8ee76a65cfbc74b9c43</challenge>

tx  <response>e948db93f2281d0d25bc9849ec88909ee2409fb19f35330d569e25f6d3603743fa440aecaaa07aa943f0ca2feabbfbbd3fdaf940c13428b976b7fcec0d98d73ecd962c46cc9ac8bdb8a94617f5c9</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught LoginFailureException 
```

------------------------------------------------------------------------------------------------ 

So I tried to use the registrationTool but:
```
Array
(
    [cc] => 39
    [in] => XXXXXXXXXXXX
    [lg] => it
    [lc] => IT
    [id] => YYYYYYYYYYYYYYY
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 4303
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)

```
There was a problem trying to request the code.

**Comment by leoallvess** [comment]
I am using for 3 weeks but stopped yesterday,  getting old_version when I try to register

**Comment by LuisG14** [comment]
Yo la he utilizado hace mas de un año y si es verdad  también no puedo extraer el password desde hace algunos días incluso. Whatsapp ya me advirtió que me bloquearan la cuenta permanentemente. Alguna ayuda?
