### ISSUE TITLE
Banned just want to know why

### ISSUE THREAD

**Issue by Lasertrap00** [mgp25/Chat-API#2117]
Hello i got banned
I just want to know if its because i didn't sync Contacts before sending an Message?

**Comment by MoudiZd** [comment]
yes that's it you are banned because you have not synchronize your contacts, read wiki

Regards !

**Comment by Lasertrap00** [comment]
@MoudiZd thanks

**Comment by Lasertrap00** [comment]
Do i just need to synchronize contacts i want to interact with?
