### ISSUE TITLE
No support for wa20?

### ISSUE THREAD

**Issue by poma** [mgp25/Chat-API#2122]
@mgp25 you mentioned in April that you have wa20 implementation almost ready. Why not publish it? Even if there are some bugs dev community will be able to fix them.

**Comment by mgp25** [comment]
@poma WA2.0 is ready since April/May, not releasing it due spammers and marketing stuff.

**Comment by cmeerw** [comment]
@mgp25 slightly different question, would you consider helping [LoquiIM](https://github.com/loqui/im) (which is a complete end-user client implemented in JavaScript)?

**Comment by 3DDario** [comment]
Please release it. Everything can be used for marketing (spam) or illegal purposes, also the old API.

**Comment by mgp25** [comment]
@cmeerw the releasing of WA 2.0 code would mean a lot of work for us
