### ISSUE TITLE
Ajax error while sending message 

### ISSUE THREAD

**Issue by syampsijk** [mgp25/Chat-API#2123]
Make sure these boxes are checked before submitting your issue -- thank you!

-You are using PHP > 5.6
- [:] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ :] You have checked if someone has already asked the same issue you have.
- [: ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [: ] Is not a programming question.
- [: ] You are using latest Chat API code.

### Error
Post your error below:
Error: There was an error with the AJAXrequest. HTTP Error (500 Internal Server Error) .Internal Server Error
### Debug log
Post your debug log below:
when i am trying to send message it reports an error.
```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Not API issue

**Comment by syampsijk** [comment]
I was using whatsapp.php example .just added and logged in ,but couldn`t send message .error appears in it.

**Comment by agossouvi** [comment]
Support is Ended !!!
This API doesn't work anymore.

**Comment by mgp25** [comment]
API still work but without support

**Comment by ranbirkumar1** [comment]
how to fix the issues Error: There was an error with the AJAX request. HTTP Error (500 Internal Server Error) .Internal Server Error

**Comment by ranbirkumar1** [comment]
how to fix the issues Error: There was an error with the AJAX request. HTTP Error (500 Internal Server Error) .Internal Server Error
when i am trying to send message it reports an error.

**Comment by badinenisaivardhan** [comment]
Whatsapp! Messenger
Error: There was an error with the AJAX request. HTTP Error (500 Internal Server Error) .Internal Server Error

Help..!!! Any One is Api Is Still Working?????
