### ISSUE TITLE
Keep it alive

### ISSUE THREAD

**Issue by flippamike** [mgp25/Chat-API#2125]
Why you guys keep closing and locking every issue? Won't you understand that the people here want to keep this github alive by communicating with each other? And trie to keep it alive? I also don't understand why you keep the new WA to your self. You started this, and then when a lot of people use it and depend of you skills you say, fuck it! I really hope people can kee this alive even you diceded you want to leave

**Comment by 0xTryCatch** [comment]
It's because of people like you this project has ended.
