### ISSUE TITLE
Bloqueo de numero

### ISSUE THREAD

**Issue by robinsoncrusoe12345** [mgp25/Chat-API#2126]
```
stdClass Object
(
    [status] => fail
    [reason] => blocked
    [login] => 5213321811636
)

Fatal error: Uncaught exception 'Exception' with message 'There was a problem tr
ying to request the code.' in C:\xampp\htdocs\xampp\ws\src\Registration.php:89
Stack trace:
#0 C:\xampp\htdocs\xampp\ws\nuevopass.php(54): Registration->checkCredentials()
#1 {main}
  thrown in C:\xampp\htdocs\xampp\ws\src\Registration.php on line 89
```

*****-----------*******
Alguien que conozca como brincar el blockeo de un numero, estoy utilizando la API y ya me bloqueo 2 numeros. Tengo ese problema que me los bloquea

**Comment by mgp25** [comment]
@robinsoncrusoe12345 this is an internation repo, try to write in English so everyone can see the actual questions / answer.

If WhatsApp blocked your number, 100% sure you are doing something wrong with the API calls, nevertheless you can send WhatsApp an email and they will unblock your number.

Regards

**Comment by robinsoncrusoe12345** [comment]
I only used the sentences

$no="5213316305224"; 
$w->sendSync([$no]);
$w->pollMessage();
$w->sendGetProfilePicture($no,true);
$w->pollMessage();
$w->sendPresenceSubscription($no);
$w->sendGetStatuses($no);

I don´t know why whatsapp blocked me
