### ISSUE TITLE
Support and new version question

### ISSUE THREAD

**Issue by baukeplugge** [mgp25/Chat-API#2130]
Hi @mgp25  ,

if there is no support any more and the current API is not up to date anymore. why do you keep this channel open? (new) People are getting to this github space to get the whatsapp api working.

Almost everybody is getting blocked and spending money on this subject. But this is useless until your new update has been released.

Can you please rethink about not releasing your updated version.

thanks
Bauke Plugge

**Comment by mgp25** [comment]
@baukeplugge spending money? isnt in the readme explicit said that you agree not to use the API as any commercial stuff and personal usage only?

Yes, i though of it already, everything is okay as it is.

Have a nice day

Regards
