### ISSUE TITLE
reaction on issue #2130

### ISSUE THREAD

**Issue by baukeplugge** [mgp25/Chat-API#2131]
Hi @mgp25 

because you closed the previous ticket (#2130)  and wanted to react on your comment here my reaction:

thanks for your reaction.
I know it is not allowed to use it for commercials stuff. but I ment spending money on SIM cards. each time the number gets block you have to buy a new one.

so trying your current API will cost money in trying.

thanks
Bauke

**Comment by mgp25** [comment]
@baukeplugge not my problem, as i said, this should be only for personal usage. You can use other alternatives. If you use it as personal usage you wouldnt have this kind of issues.

Regards
