### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by wa-clone** [mgp25/Chat-API#2135]
I need to retrieve messages and pictures from whatsapp and show it privately on my own website

Is it possible at this moment with chat-API?

Thank you very much for your help.

Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Yes, but no support, if you want to do it, you have to do it in your own

Regards
