### ISSUE TITLE
  socket_write(): unable to write to socket [32]: Broken pipe  

### ISSUE THREAD

**Issue by Lorempn2** [mgp25/Chat-API#2137]
- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

Hi,

Since tonight I'm unable to connect to WhatsApp and receive an error:

socket_write(): unable to write to socket [32]: Broken pipe  

```xml
tx  <stream:features></stream:features>

tx  <auth user="xxxx" mechanism="WAUTH-2">d1d3b9de3331363237333230323731811b27c59ab00f01546f71c07c96ab0ec071266731343734343434343035</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>537fc8dae115196a7f0816368004ef9e7ab1d3ca</challenge>

tx  <response>ae3204655d9e1c17a2a218701ab2540d564b44f713eda27a6cc272765b79ce2bb765208ed847f453016840da66f10fbb15be8c1f3eb5c36e19f7a31e7a5968cb72bc2e4597377acd14581d22ae</response>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


```

**Comment by 0xTryCatch** [comment]
Can you show more of the error message please

**Comment by TNAJanssen** [comment]
Same issue here! On multiple accounts, it looks like the connection is not created.

Here is full trace:

tx  <stream:features></stream:features>

tx  <auth user="31611564206" mechanism="WAUTH-2">80a387d53331363131353634323036f74ecc1e385eb5b6494f12f0c807106e10755cfe31343734343435383034</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>d1d78dfec2d1dfffb56df4a7e839793f3774c2b1</challenge>

tx  <response>8ea5d267f1759f0784655a17c2edc51861684b4792baa1dc9bfb0698bead52899c29104cbda171e31b42be90db3f69ad795c13bbd7857cd993509064a5c79a0ce09a9a8b1990adf8cb33fc7897</response>




tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php on line 2748
PHP Stack trace:
PHP   1. {main}() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/examples/Simple CLI client.php:0
PHP   2. WhatsProt->loginWithPassword() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/examples/Simple CLI client.php:62
PHP   3. Login->doLogin() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:287
PHP   4. WhatsProt->pollMessage() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/Login.php:49
PHP   5. WhatsProt->sendPing() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:328
PHP   6. WhatsProt->sendNode() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:1088
PHP   7. WhatsProt->sendData() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:2932
PHP   8. socket_write() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:2748

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php on line 2748

Call Stack:
    0.0004     265696   1. {main}() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/examples/Simple CLI client.php:0
    0.1218    4865008   2. WhatsProt->loginWithPassword() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/examples/Simple CLI client.php:62
    0.1219    4866880   3. Login->doLogin() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:287
  121.8391    4955200   4. WhatsProt->pollMessage() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/Login.php:49
  121.8391    4955872   5. WhatsProt->sendPing() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:328
  121.8391    4957736   6. WhatsProt->sendNode() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:1088
  121.8398    4957880   7. WhatsProt->sendData() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:2932
  121.8398    4957976   8. socket_write() /Users/AJanssen/Projecten/juanpescador/api/vendor/whatsapp/chat-api/src/whatsprot.class.php:2748

**Comment by 0xTryCatch** [comment]
Your IP is probably blocked

**Comment by TNAJanssen** [comment]
@0xTryCatch this is from 5 different IP's, and completely different subnets

**Comment by Lorempn2** [comment]
Yes, same here. Also different IP's.
