### ISSUE TITLE
End of support & GitHub Issues

### ISSUE THREAD

**Issue by sjrabe** [mgp25/Chat-API#2139]
Hi,

I know that support for this project has ended, but it would be greatly appreciated if issues could still be kept unlocked (if not open) to allow the community to find and share solutions to them.
The collaborators who don't want to be involved in this project could set their status to "Not Watching" to avoid getting notifications they aren't interested in.

As I'm currently facing the same issue as many other people (WhatsApp seems to have made slight changes to their authentication process), a way to discuss this with others would be highly appreciated and currently, this repository is the best place for that.

Thank you!

**Comment by 0xTryCatch** [comment]
We only close and lock all duplicate or invalid issues to keep things organised. Valid issues will not be closed.
