### ISSUE TITLE
Infinite loop in Login.php while waiting for authentication message (not blocked)

### ISSUE THREAD

**Issue by sjrabe** [mgp25/Chat-API#2140]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have. **Yes, but all the issues have been mistakenly closed as invalid.**
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

### Error
The program gets stuck in an infinite loop in `src/Login.php` on line 49 while waiting for an authentication message from the server that is never sent.

**Here's how I know that I am not blocked**:
- I used `registerTool.php` to create **two more accounts** with **entirely different numbers** from different networks
- On **all of the networks** I've tried to connect from, the **official app works** and new registrations are accepted
- The problem started happening overnight while account was not being used

Perhaps this could be a regional difference? I am in Israel and using Israeli numbers to sign up.

### Debug log

```xml
tx  <stream:features></stream:features>

tx  <auth user="97258XXXXXXX" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>a8d348ba220b782e92654526d36efd9d6a537a88</challenge>

tx  <response>3057c79633dc144d65e401658788ebe598da6a46e3c14b087c97f27fa1b31aefec6c5f03429ed072abd6b3db09f00549a4b9dd1877cd4324c1ead4dd19fa98f30b440468d25908640b6fe14dc162</response>

<!-- At this point, the app enters the infinite loop and does not exit unless the execution time is reached or the connection is closed -->
```

**Comment by kovalenkojuls** [comment]
I have the same problem!

**Comment by matteoarlotti** [comment]
I have the same problem. Italian IP, s.whatsapp.net seems unreacheable

**Comment by mahmoudnaja** [comment]
Hi I am facing the same issue and still didn't find a solution please if you solve the problem post the solution.

**Comment by ax25** [comment]
Any news about this? I'm also facing the same problem. GL.

**Comment by BigCX** [comment]
Thats the End of the old WA Protocol, we have to create API for WhatsApp new protocol
