### ISSUE TITLE
Creating API

### ISSUE THREAD

**Issue by JohnMKC** [mgp25/Chat-API#2141]
Hello,

 This is not an Issue but I need a help regarding creating API. Recently I downloaded Charles and created proxy and then connected my phone to the proxy. I'm trying to create Hike Messenger API. I was able to see the traffic of sending text message and registering the account in HTTPS request because installed certificate on phone. But then I send a message to my friend and I couldn't see the message in HTTPS request. Why ? It doesn't use HTTPS protocol ? Which protocol it uses ? and how can I know about it ? And which tool do you suggest to use while doing this ? Short answer will be fine.

Thanks!

**Comment by KSas** [comment]
Use SOCKS-Proxy in Charles. As far as I know connection to WhatsApp are over SOCKS.
