### ISSUE TITLE
community 

### ISSUE THREAD

**Issue by baukeplugge** [mgp25/Chat-API#2142]
Many people want to use this creation to use whatsapp.
This place is the ideal place to discuss with other people how things work and how to solve things.

This would be possible if you let the issues / questions open so other people can respond.
but no you 2 are closing the issues as duplicated / not related.

you dont have to respond to the questions. let the people use your platform here to collaborate !

thanks for your cooperation !

**Comment by 0xTryCatch** [comment]
Sigh.. Do we have to keep explaining? This is not a discussion board, therefore non-API related issues are closed.
