### ISSUE TITLE
problem during login: e[1-16].whatsapp.net

### ISSUE THREAD

**Issue by hazemmatouk** [mgp25/Chat-API#2150]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
```
Fatal error: Maximum execution time 
```

### Debug log
```xml
rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>dc84bbff4b8fbf0c70e0021fcc163bb1c5632feb</challenge>

tx  <response>769233609dcc11b844ce82ab8a74eb1bc0575670816fbcc596b08696fb373535a21ef5f3901916e867c9f26fcc0cc1c02df797bc14f169587b7fecf1b75ef1cc82136c16ab96c2cc83f9ea860e11</response>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="unavailable"></presence>

tx  <stream:features></stream:features>

tx  <auth user="963951562954" mechanism="WAUTH-2">0faf63f1393633393531353632393534dc84bbff4b8fbf0c70e0021fcc163bb1c5632feb31343737343739323034</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>36872905b9a9ccf3bd6c43ed9dd4f3dd1b445e5f</challenge>

tx  <response>6e86d5c2cd3eff30d8ce553b2edd728213ee0939295f0aebf570b9f5b5aebe98290b74d0203702cca10fad7f81a950f8a3f8bc3dd1ec04b2afbcee7284883aa2b48c5f6af12abc7f41ea8e3c5003</response>
```

====================================
in file: `src/login.php`
```php
      if ($this->parent->getChallengeData() != null) {
          $data = $this->createAuthResponseNode();
          $this->parent->sendNode($data);
          $this->parent->reader->setKey($this->inputKey);
          $this->parent->writer->setKey($this->outputKey);
          while (!$this->parent->pollMessage()) {
          };
      }
```
While in this function keep looping until time out. and the processor used 100%
so I set : `usleep(10);`
for stop using all performance of processor

but no change in the result

I need your support to fix this issue

**Comment by salunp** [comment]
Hi Is this problem solved? I am still facing this issue and am not able to solve it
