### ISSUE TITLE
Chat-API got blocked until further notice?

### ISSUE THREAD

**Issue by KyleJr** [mgp25/Chat-API#2151]
Greetings,

So your PHP WhatsApp Chat-API Library got blocked (probably temporarily) and you're going to just move on without trying to find a work around it? This was a very decent project for a lot of people, and could be for billions of programmers as well. I don't see why give up this early, just tell everyone the truth that it's not working until further notice. 

Because I've spent approximately 10 hours setting this up only to realize that it's a dead end, and I've read all the wiki and issues then notice it's dormant since August, perhaps you should put a notice on the README.md for new users, also there are other working bots right now on WhatsApp which means it's still able to work, right?

Regards

**Comment by mgp25** [comment]
@KyleJr have you bother to read? I stopped this project because of spammers, i have a working version with latest protocol, and i enjoy my projects with it, and i repeat, the reason because i haven't released it's because of people using it in wrong ways and spammers!

There is a one single issue with a big label saying: `End of support`

Regards

**Comment by KyleJr** [comment]
My apologies, I misunderstood why it was closed, I actually wrote that with a little anger due to really needing the bot to help me with Group Administrations and Support, was looking forward to a working library for a start and this seems to be the perfect fit. 

If that's the case then forgive me for my behavior.

**Comment by Raisel** [comment]
The world is full of stories like this: Good people pay for bad people.
I personally used the API to more than 1 year only for communication failures and important things for myself. Invest some time in it. The whole community helped to debug your script. Now it is good and can be your own. I regret that many people use your code to spam. I regret that people use email and all form of communication on the Internet to generate spam. But the truth is that not eliminated email to eliminate spam. But in its API spam won!
