### ISSUE TITLE
Stop working?

### ISSUE THREAD

**Issue by kesar** [mgp25/Chat-API#2152]
Is anybody having problems when logIn? It seems to be frozen when its trying to doLogin()

Code:
```
$w = new WhatsProt($username, $nickname, $debug, $log);
$w->connect();
$w->loginWithPassword($password);
```

Where stop working doLogin line 49:

```
while (!$this->parent->pollMessage()) {
          };
```

Log
```
[] Logging in as 'WhatsAPI Test' (XXXXXXX)
tx  <stream:features></stream:features>

tx  <auth user="34XXXXXXX" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>XXXXX</challenge>

tx  <response>4317645a6acd7d4eec24c38bd0e5b13fb96e42e3fcf897e8b40c39689caadb2582df9fa0e38fdc21a9c1c9f873a4ce7e82b209a09f9e82aa6e8626baf4d21aeeb91b53432bbe9094bb63b6efbf</response>
```

**Comment by mgp25** [comment]
#2116

**Comment by kesar** [comment]
yeah, I read your note and I understand your personal reasons, but if you leave the repo open why you don't let the community to help? it makes no sense.

**Comment by flippamike** [comment]
I agree.. really stupid to say it's not a discussion board

**Comment by edudesouza** [comment]
For those looking for keep the project alive, why not start a new project Github using this as a foundation?

**Comment by kesar** [comment]
> For those looking for keep the project alive, why not start a new project Github using this as a foundation?

That's what I started to do today. I forked project ( https://github.com/kesar/Chat-API )  and trying to debug the issue and also taking a look to a py project that its working ( https://github.com/tgalal/yowsup ) 👍 

any help is welcome

**Comment by mgp25** [comment]
I have tha WA20 already working since April, ill publish it when i think its good time to release it, in order to avoid spam.

It requires lot of reversing engineering. So, just wait for it. I'll eventually release it, but not now (avoid spam we need), everything has each time.
