### ISSUE TITLE
Maybe some support..

### ISSUE THREAD

**Issue by rajitbansal** [mgp25/Chat-API#2153]
Below is the new domain being used by the whatsapp

![image](https://cloud.githubusercontent.com/assets/16409867/20029593/03856d1c-a376-11e6-9b64-920606156158.png)

**Comment by mgp25** [comment]
@rajitbansal are you serious? Do you even know what you are doing? 

![dog](http://i0.kym-cdn.com/photos/images/newsfeed/000/234/765/b7e.jpg)
