### ISSUE TITLE
Just a message for you

### ISSUE THREAD

**Issue by Dev-Aryan** [mgp25/Chat-API#2156]
@mgp25 
Hello brother,
I know you have closed the support for this API but it was when this API was working perfectly but, currently this API is dead now. We know there are many users using this API for spamming but there are also many people who are using it for good and/or interesting purpose. So, can you please tell us that when will you or will you update this code with the new one so that we can stop checking this API every day for updates.

`I request you to release the new code ASAP because i also loved using this API`

Regards
Aryan Chauhan

**Comment by mgp25** [comment]
Ill update the api one day randonmly from today to the next 10 years

Regards

**Comment by Dev-Aryan** [comment]
@mgp25 

Thanks, will be waiting for that day. :)

Regards

**Comment by 0xTryCatch** [comment]
@Dev-Aryan This API still works perfectly and will continue to do so until July 2017.

**Comment by Dev-Aryan** [comment]
@0xTryCatch 
It doesn't it gets stuck when logging in with the password.
When debug enabled it got the message 

`<response>**********************************</response>`

& never goes forward from it.

BTW can i know why only till July 2017.

> It is not working Acc. to me as it gets stuck.

Regards
