### ISSUE TITLE
Unable to write to socket[32]: Broken pipe

### ISSUE THREAD

**Issue by wapjude** [mgp25/Chat-API#2158]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Unable to write to socket[32]: Broken pipe

### Debug log
Post your debug log below:
Unable to write to socket[32]: Broken pipe
```xml
Unable to write to socket[32]: Broken pipe
```

**Comment by baukeplugge** [comment]
Yesterday I got the same error message, no clue why this error occures

**Comment by wapjude** [comment]
And my site as been loading not ever stopping

**Comment by nextvikas** [comment]
same problem facing by me

**Comment by wapjude** [comment]
and it occurs anytime i use the loginWithPassword() function
