### ISSUE TITLE
Is this API working ?

### ISSUE THREAD

**Issue by shubhairan** [mgp25/Chat-API#2163]
Hello bro,

We already know that the support is ended but that doesn't mean you wont update or tell other people that this API is currently working or not?

@0xTryCatch 
@mgp25 
We don't create issues to be closed without answers.

This would not be a good impact on others

As @0xTryCatch mentioned in the previous issue that this API is working ?

But i don't see it working.Could you explain.?

I know there are many spammers, but there are also many other users who are waiting for this API to be back to make it for their personal USE.

Regards

**Comment by baukeplugge** [comment]
I agree for 100% !

**Comment by 0xTryCatch** [comment]
Seems like people don't understand the meaning of "End of support". It means it will not be updated again.
