### ISSUE TITLE
socket_write(): unable to write to socket [10053]:

### ISSUE THREAD

**Issue by ajikp** [mgp25/Chat-API#2164]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error

I got this error when i trying to send message.

socket_write(): unable to write to socket [10053]: An established connection was aborted by the software in your host machine.

### Debug log
x  <stream:features></stream:features>

tx  <auth user="91********" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>ed456db83434386f5ddda9a78517786b9fce0be4</challenge>

tx  <response>2d80d5a3d95cf0d0e4d27d8bb0392296649d12574dc67b31d951762b743431c76fb86ddf5f8aaa48e3996946633082106fb132c0b5b8f2f988269325e3a07090cd79a4e41aad94bcb1e48363fbc9</response>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

Warning: socket_write(): unable to write to socket [10053]: An established connection was aborted by the software in your host machine. in D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php on line 2748
tx  <presence type="unavailable"></presence>

Warning: socket_write(): unable to write to socket [10053]: An established connection was aborted by the software in your host machine. in D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php on line 2748
tx  <stream:features></stream:features>

Fatal error: Uncaught LoginFailureException in D:\xampp\htdocs\whatsapp_send\src\Login.php:54 Stack trace: #0 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(287): Login->doLogin() #1 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(324): WhatsProt->loginWithPassword('ZSgwIqjrA6JAnog...') #2 D:\xampp\htdocs\whatsapp_send\src\Login.php(49): WhatsProt->pollMessage() #3 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(287): Login->doLogin() #4 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(324): WhatsProt->loginWithPassword('ZSgwIqjrA6JAnog...') #5 D:\xampp\htdocs\whatsapp_send\src\Login.php(49): WhatsProt->pollMessage() #6 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(287): Login->doLogin() #7 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(324): WhatsProt->loginWithPassword('ZSgwIqjrA6JAnog...') #8 D:\xampp\htdocs\whatsapp_send\src\Login.php(49): WhatsProt->pollMessage() #9 D:\xampp\htdocs\whatsapp_send\src\whatsprot.class.php(287): Login->doLogin() #10 D:\xampp\htdocs\whatsapp_send\sen in D:\xampp\htdocs\whatsapp_send\src\Login.php on line 54

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
@ajikp read debug log

Regards

**Comment by ajikp** [comment]
"socket_write(): unable to write to socket [10053]: An established connection was aborted by the software in your host machine".
how can i solve this error?

**Comment by rajratnamaitry** [comment]
is there any way to solve this issue
