### ISSUE TITLE
How to check valid Whatsapp ?

### ISSUE THREAD

**Issue by Bou3ou** [mgp25/Chat-API#2165]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by Bou3ou** [comment]
hi i'am new in this community can you please explain me how to verify if a phone number has a whatsapp, i use the function onSyncResult but i didn't know how to call it in my program?

**Comment by mgp25** [comment]
@Bou3ou Hello, this issue is duplicate, check wiki/F.A.Q. + the API reached the end of support

Regards

**Comment by Bou3ou** [comment]
@mgp25 can you please give me some links or documentation ?

**Comment by baukeplugge** [comment]
stop putting your precious time into this project.  the api is not functioning anymore !

**Comment by mgp25** [comment]
@baukeplugge get a life

**Comment by mgp25** [comment]
@Bou3ou https://github.com/mgp25/Chat-API/wiki

**Comment by edudesouza** [comment]
Hey fellows, for Good or Bad, Facebook Messenger is the way to go.

Talking with fellows there, WhatsApp team has just moved to Facebook campus
last month, they don't have a road map for enterprise integration, but, for
sure, they are working hard to block non app connection.

Their strategy is: Facebook Messenger = Business aplications, WhatsApp =
simple, lightweight, c to c.

For playable aplications, iot, Telegram Works like a charm, general
pruposes like personalidade assistance Messenger and Telegram is nice.

Trust me I dos everything to make it work, my best combination was a Linux
box connected on a local Carrier with a 4G modem.

Em 11/12/2016 6:58 PM, "Bauke Plugge" <notifications@github.com> escreveu:

**Comment by Bou3ou** [comment]
@mgp25 Thank you so much

**Comment by shubhairan** [comment]
You can't,
This API is now outdate and you can only register numbers through this API. It is not working for anyother functions.
