### ISSUE TITLE
github page online

### ISSUE THREAD

**Issue by baukeplugge** [mgp25/Chat-API#2166]
as long as you keep this github page online. new people keep on finding your api within Google. 

each time resulting in a negative result for both parties.

maybe it is a good time to put your work on a private github instead of the public one. 

in this state it is no use to anybody only resulting for a hope frustrating people!

**Comment by mgp25** [comment]
So you prefer to hide information to other people? Isnt better to keep all the work up, so if other people come up, they can continue with this, right?

Instead of complaning i would recommend reading all the info, docs, including the issues and the announcement i did

Whats wrong with you people

**Comment by shubhairan** [comment]
Well, if this API is not working you should close this page or update the API.

**Comment by Vuelos** [comment]
I think than you have to say that the API have no current support and than it's online as a start point in case someone want to do something related, explaining the current state, on the first paragraph of the readme.md
