### ISSUE TITLE
Where to find the nickname?!

### ISSUE THREAD

**Issue by Sankaboy** [mgp25/Chat-API#2168]
HI.
**I read the wiki!**

I have registered, I used this file -> registerTool.php.
In response a program issued a the user name and password.
What to do next? How to get the nickname?

(Sorry for my bad english)

**Comment by mgp25** [comment]
Nickname is the one you set

Regards

**Comment by Sankaboy** [comment]
How to install it?

**Comment by StanleyMilligan** [comment]
@mgp25 I'm interested too. How to create a nickname through api,

**Comment by mgp25** [comment]
Please read the wiki and issues. nickname is not generated, is set by the user.........

**Comment by StanleyMilligan** [comment]
@mgp25 I read WIKI.
Without nickname, can work api?
Why right after the registration number is blocked?

**Comment by mgp25** [comment]
@StanleyMilligan if you read the wiki and other issues, could you tell me where is nickname used or where did i said is a required field?

I know what the problem might be, maybe you are not good at php and thats is okay, everybody once was a beginner too, in that case i would recommend you to practice. I spent lots of months repeating stuff until it works, sometimes raw persistance is the best tool you can have

Regards
