### ISSUE TITLE
Fatal error: Uncaught exception 'ConnectionException' with message 'Socked Write failed!'

### ISSUE THREAD

**Issue by dynasticdev** [mgp25/Chat-API#2170]
Make sure these boxes are checked before submitting your issue -- thank you!

- [y ] You are using PHP > 5.6
- [y ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [y ] You have checked if someone has already asked the same issue you have.
- [7 ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ y] Is not a programming question.
- [y ] You are using latest Chat API code.

Hello Friends,

I have followed all the guidelines and have installed the dependencies as well ,I was able to register the number and have got the code and also have verified the password , later to that i am trying to send the message using the exampleFunction.php and also have followed the WIKI and made a simple plaint text message sending code as bellow , i have also used the registerTool and have also verified my number which is not blocked by using the blockChecker.php, Please can some one help me out with this issue

<?php
require_once __DIR__.'/../src/whatsprot.class.php';
$debug = true;

$username = '919130473757';                      // Telephone number including the country code without '+' or '00'.
//$password = 'xxx';     // Use registerTool.php or exampleRegister.php to obtain your password
$password= 'xxx';
$nickname = 'Mathew_Gomes';                          // This is the username (or nickname) displayed by WhatsApp clients.
$target = "919970xxxxxx";                   // Destination telephone number including the country code without '+' or '00'.
$debug = true;         

$w = new WhatsProt($username,$nickname, $debug);
$w->connect();
try{
    $w->loginWithPassword($password);
}
catch (Exception $e)
{
    echo $e->getMessage();
}
$message = 'Hi! :) this is a test message';
echo "[*] Connected to WhatsApp\n\n";
$w->sendMessage($target , $message);

?>
### Error
Post your error below:

Fatal error: Uncaught exception 'ConnectionException' with message 'Socked Write failed!' in /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php:2751
Stack trace:
#0 /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php(2935): WhatsProt->sendData('\x80\x00Vm\x07\eVdO\x05\x86\xFCM\xAA\x9D...')
#1 /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php(2836): WhatsProt->sendNode(Object(ProtocolNode))
#2 /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php(1341): WhatsProt->sendMessageNode('919970xxxxxx', Object(ProtocolNode), NULL, Object(ProtocolNode))
#3 /home/sorucvp/public_html/chatmaster/examples/sometest.php(24): WhatsProt->sendMessage('919970xxxxxx', 'Hi! :) this is ...')
#4 {main}
  thrown in /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php on line 2751

### Debug log
Post your debug log below:

tx  <stream:features></stream:features>

tx  <auth user="919130xxxxxx" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>f24ccdbd807721b79d458d74f12c8fe5c13a75b0</challenge>

tx  <response>75f04bdb5ded78cba53ade2032e75cc3633ac44addf5ff2f51d8d3baaeb7529a085103ad0db6cad78e3e011d7af94d5d45196ef3569b4ef742113783854fb9e07dec105834b74646fe111912766f</response>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php on line 2753
Socked Write failed![*] Connected to WhatsApp

sendmessage line 1 tx  <message to="919970xxxxxx@s.whatsapp.net" type="text" id="01" t="1482388605" notify="Mathew_Gomes">
tx    <body>Hi! :) this is a test message</body>
tx  </message>

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /home/sorucvp/public_html/chatmaster/src/whatsprot.class.php on line 2753

**Comment by mgp25** [comment]
@dynasticdev read closed issues

Regards
