### ISSUE TITLE
Warning: socket_write(): unable to write to socket [32]: Broken pipe in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php on line 2748 while calling WhatsProt->loginWithPassword

### ISSUE THREAD

**Issue by shabnambanu1234** [mgp25/Chat-API#2171]
Hi,
I am trying to connect to whatsapp from my Centos godaddy vps server using WHATSAPI. I am getting same error and stuck here since last 3 days. I am providing the stack trace below. Please help . I am able to connect to whatsapp server but not login with password.

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php on line 2748

Fatal error: Uncaught exception 'ConnectionException' with message 'Socked Write failed!' in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php:2749
Stack trace:
#0 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(2935): WhatsProt->sendData('\x80\x00\x16\x00s\x1Ew\xCBi\x7F\xB6\xA5\xBD\xFA\xE6...')
#1 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(1088): WhatsProt->sendNode(Object(ProtocolNode))
#2 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(328): WhatsProt->sendPing()
#3 /home/femiza2/public_html/WHATSAPP/src/Login.php(49): WhatsProt->pollMessage()
#4 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(287): Login->doLogin()
#5 /home/femiza2/public_html/WHATSAPP/MYEXAMPLES/whatsappListener.php(20): WhatsProt->loginWithPassword('G+/dhv513YS8tmi...')
#6 {main}
thrown in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php on line 2749

Thanks,
Shabnam

**Comment by mgp25** [comment]
Read closed issues

Regards
