### ISSUE TITLE
LoginWhitPassword never connect

### ISSUE THREAD

**Issue by eduarchap** [mgp25/Chat-API#2179]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

PHP Warning:  socket_write(): unable to write to socket [10053]: Se ha anulado una conexi¾n establecida por el software en su equipo host..
 in C:\Users\eduar\Desktop\Chat-API-master2\src\whatsprot.class.php on line 2748

LoginWhitPassword never connect

### Debug log
Post your debug log below:

php "C:/Users/eduar/Desktop/Chat-API-master2/examples/prueba.php"

tx  <stream:features></stream:features>

tx  <auth user="5492262302909" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>2b4b55a3d4dd71f919ae2e6d280e51cdbc4f7d77</challenge>

tx  <response>6f3952826f3840dadac98c67d43b709f237693abe0dad67b7dabe4154f06108ec8eb6d94eb1c85106a5e5501117811de5e9a3a8f29074065a8af061251039f7fcdecfaa147b554a75298754b6cb444</response>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="unavailable"></presence>

PHP Warning:  socket_write(): unable to write to socket [10053]: Se ha anulado una conexi¾n establecida por el software en su equipo host..
 in C:\Users\eduar\Desktop\Chat-API-master2\src\whatsprot.class.php on line 2748

Warning: socket_write(): unable to write to socket [10053]: Se ha anulado una conexi¾n establecida por el software en su equipo host..
 in C:\Users\eduar\Desktop\Chat-API-master2\src\whatsprot.class.php on line 2748
tx  <stream:features></stream:features>

tx  <auth user="5492262302909" mechanism="WAUTH-2">2d8f424e353439323236323330323930392b4b55a3d4dd71f919ae2e6d280e51cdbc4f7d7731343834303132313931</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>d9d7a257180c0f24fc5822c840750609e0d3daf0</challenge>

tx  <response>92750bc02064d9eab68502270a6e2f4d200d37ae6325380e3a3e872d3cb210d84efe9e0e2831ada0156660406ec1cdca68c6f1bff58c67edaf64d4e64671feba3c4063a8ce6334cf1395cc501b3a1a</response>

tx  <presence type="unavailable"></presence>

tx  <stream:features></stream:features>

tx  <auth user="5492262302909" mechanism="WAUTH-2">cc701eb635343932323632333032393039d9d7a257180c0f24fc5822c840750609e0d3daf031343834303132323532</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>cf60ae7fafc1501aab06d4fbd30b1669858b5a70</challenge>

tx  <response>108bc36d010b2f657fcb6cd8f2783d06dd7a1dc8c986e10a6cbe0e6de8235ea3185cc51a9168aed441aa4685c20c14b5414e2ddd60dad930f49bc4247188fc56b93b2984774b0bbd21fe1e682c530c</response>

tx  <presence type="unavailable"></presence>

tx  <stream:features></stream:features>

tx  <auth user="5492262302909" mechanism="WAUTH-2">a0177d7d35343932323632333032393039cf60ae7fafc1501aab06d4fbd30b1669858b5a7031343834303132333133</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>01d15f44e63ecc5969c7b44109dc9255c9e4e5b3</challenge>

tx  <response>b066bfa5780e88960505c91cf52e152e4d9469c079b8e64c00072bbb7b58ac57a2acab07694ea1b3ab00c7f39f1f7fa94e870efa1ec1041b6e1bb698253ab0777c41d30dcc7c45c8d829d9c5b8406f</response>

tx  <presence type="unavailable"></presence>

tx  <stream:features></stream:features>

tx  <auth user="5492262302909" mechanism="WAUTH-2">d6c3c56b3534393232363233303239303901d15f44e63ecc5969c7b44109dc9255c9e4e5b331343834303132333734</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>60b2b3480ea6d8a87ac283730729be136b78cc0d</challenge>

tx  <response>71a6765240762ed70854b51faca384507fc6dc604b3b3c92cca620a29908d93f94034df2f8ceddace0217bae271b05837e00c33edbfbd27fd80706d8043252d7178dbb9c715e60e4eb8d6941e336f1</response>

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
@eduarchap please, read closed issues

Regards

**Comment by eduarchap** [comment]
I have read but none of the cases solves the problem.

The problem is that it stays in

tx  <stream:features></stream:features>

tx  <auth user="5492262302909" mechanism="WAUTH-2">2d8f424e353439323236323330323930392b4b55a3d4dd71f919ae2e6d280e51cdbc4f7d7731343834303132313931</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>d9d7a257180c0f24fc5822c840750609e0d3daf0</challenge>

tx  <response>92750bc02064d9eab68502270a6e2f4d200d37ae6325380e3a3e872d3cb210d84efe9e0e2831ada0156660406ec1cdca68c6f1bff58c67edaf64d4e64671feba3c4063a8ce6334cf1395cc501b3a1a</response>


And repeat the cicle and never end and sent message
