### ISSUE TITLE
Wrong RFCs in Wiki

### ISSUE THREAD

**Issue by SamWhited** [mgp25/Chat-API#2183]
I know you don't support this API anymore, but could you please remove the references to RFC 39xx from the wiki repo? People constantly come to me thinking that 39xx is up to date because they found it while searching (sometimes for "FunXMPP"). Thanks; 6120, 6121 and 7622 are the current XMPP RFCs.

**Comment by mgp25** [comment]
@SamWhited updated 👍 

Regards
