### ISSUE TITLE
Regarding ProcessNode

### ISSUE THREAD

**Issue by KamalGalrani** [mgp25/Chat-API#2184]
I don't need to handle nodes as I am using onGetMessage interface. So can I skip the following part of code or do I have to define a class ProcessNode and do nothing with it.

```
$pn = new ProcessNode($w, $target);
$w->setNewMessageBind($pn);
class ProcessNode implements NewMsgBindInterface

{
    protected $wp = false;
    protected $target = false;

    public function __construct($wp, $target)
    {
        $this->wp = $wp;
        $this->target = $target;
    }

    public function process(\ProtocolNode $node)
    {
      //nothing to do
    }
}
```

**Comment by mgp25** [comment]
Is not required to add that. Read wiki and examples

**Comment by KamalGalrani** [comment]
Well the wiki has no mention of ProcessNode and examples have it. So was a bit confused.

Thanks
