### ISSUE TITLE
WhatsApp Version 2.17.23 bad_token

### ISSUE THREAD

**Issue by albrox** [mgp25/Chat-API#2190]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x ] You are using latest Chat API code.

### Error
Post your error below:
I am getting "[status] => fail [reason] => bad_token" when registering. However, I have generated a new md5hash for 2.17.23 with the provided python script. It came out as "DOpVRQayPSA9fdsbIg1xIw==". Is there anything else I am missing?

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by Maiko1100** [comment]
did you fix this issue already?
