### ISSUE TITLE
old_version

### ISSUE THREAD

**Issue by sabre96** [mgp25/Chat-API#2192]
When requesting the register code(
```
$username = "";
$debug = true;

// Create a instance of Registration class.
$r = new Registration($username, $debug);

$r->codeRequest('sms'); // could be 'voice' too
//$r->codeRequest('voice');
```
)

 I get this returned:

Array ( [cc] => 31 [in] => 643187818 [lg] => nl [lc] => NL [id] => �c �o�<� }	v�yˋ� [token] => u+OXOBJt+jPkZtMcamEDmV/zXOQ= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 2669 [rchash] => dae757d6aefebf8ab234edb6233dc0d836569adb1418408ea8d6fd4523db1d1a [anhash] => 66cfd4f74dd5e20a1ff2c47f47aac2cf [extexist] => 1 [extstate] => 1 [mcc] => 204 [mnc] => 004 [sim_mcc] => 204 [sim_mnc] => 004 [method] => sms ) stdClass Object ( [login] => *** [status] => fail [reason] => old_version )

I have installed the latest version of this repo, so I don't understand why it's doing this. I'd provide a log but I can't find it.

**Comment by mgp25** [comment]
@sabre96 code outdated + no more support #2116

Regards
