### ISSUE TITLE
Is this api is working ?? 

### ISSUE THREAD

**Issue by yugalahir** [mgp25/Chat-API#2193]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by gerwim** [comment]
Unfortunately, no. See https://github.com/mgp25/Chat-API/issues/2116

**Comment by cainerland** [comment]
no not anymore .

**Comment by yugalahir** [comment]
Ok thank you everyone!!!
