### ISSUE TITLE
PLEASE HELP : {status: fail, reason: incorrect }

### ISSUE THREAD

**Issue by nbaghiro** [mgp25/Chat-API#2203]
I know you guys ended providing support but if you can help it would be really appreciated. 

So I was getting old_version issue, and I updated the version number in Constants.php to the newest (2.17.144) for both WHATSAPP_VER and WHATSAPP_USER_AGENT. It got rid of old_version issue, but now I am getting {status:fail, reason: incorrect } issue. You mentioned in a comment for some other question someone asked about same "incorrect" issue that "identity" is wrong, but I don't get how we are defining identity here. In token generation file, "signature" and "classesMD5" variables are still for 2.16.148 version as I did not update them, how can I update them to point to newest version or do I even need to update them? 

- [YES ] You are using PHP > 5.6
- [YES ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [YES ] You have checked if someone has already asked the same issue you have.
- [YES ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [YES ] Is not a programming question.
- [YES ] You are using latest Chat API code.

### Error
Post your error below:

### Debug log

```xml
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 16479985102
Array
(
    [cc] => 1
    [in] => 6479985102
    [lg] => en
    [lc] => CA
    [id] => ▒>▒▒'▒▒▒▒▒▒o▒▒5▒g▒▒
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 9100
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [login] => 16479985102
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
```

**Comment by mgp25** [comment]
This code is way way outdated, i dont recommend using it

Regards

**Comment by nbaghiro** [comment]
You mean the your chat-api project is outdated?

**Comment by mgp25** [comment]
Exactly, that is what i exactly said, i have continued in private. So people can no longer use this API

Regards

**Comment by nbaghiro** [comment]
That sucks, any other api available publicly that you would recommend? I saw yowSup and it seems to be still getting updated but that is in python, and my whole project is in php so this was very nice fit for my use case.

**Comment by mgp25** [comment]
@nbaghiro yowsup will stop working in late june since WhatsApp is dropping support for S40. The only way would be releasing my updated version of Chat API, but due spammers i wont do it, i know its a shame but its people fault

Regards

**Comment by nbaghiro** [comment]
That is very bad, then I guess my only option is to wait for WhatsApp to release their own bot system. In case if you decide to share your updated version of Chat API with me in private, it is my email: naib.baghirov@gmail.com. Thanks for your help. 

Regards

**Comment by eaba** [comment]
@mgp25 How we get those whose fault it is, so that we can punish them? Its a fight of Good people vs Bad people - be the Judge who should WIN!!!!

**Comment by alecyu** [comment]
yes... I was wondering why it was unsupported ... now I know why.... can you kindly share us with say application form to declare the usage of ? million thanks.
