### ISSUE TITLE
AutoUpdating keys and more functions

### ISSUE THREAD

**Issue by CashCode** [mgp25/Chat-API#2207]
Hey! Is there any option to autoupdate keys (signatures, which instagram can change)?
I'd like to see little bit more functions: new messages detection and thread deleting.
I read documentation a lot, but directThreadAction can only "block", "approve" and "decline", is there any delete thread parameter?
Can I get it implemented for buying your support?
Thanks.

**Comment by abdul-nine7** [comment]
Support has been removed form this repository! And this was not a Instagram API

**Comment by mgp25** [comment]
@CashCode wrong repo

Regards

**Comment by mgp25** [comment]
@CashCode this is Chat API repository (whatsapp)
