### ISSUE TITLE
Shows Status fail

### ISSUE THREAD

**Issue by ankur1209** [mgp25/Chat-API#2223]
How to solve it
 [status] => fail [reason] => old_version )

**Comment by jucedogi** [comment]
Find in the code where the version and hashes are and replace with new ones.
Latest info. on these can be found at: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by tapankumar** [comment]
@jucedogi :+1:  I took latest information from your provided url and i got the username/password for my mobile number. 

src/Constants.php
const WHATSAPP_VER = '2.17.426';
const WHATSAPP_USER_AGENT = 'WhatsApp/2.17.426 Android/4.3 Device/Xiaomi-HM_1SW';

src/token.php
$classesMd5 = 'OyTf9XK7xoJkKIxLgY6/Lw=='; // 2.17.426
