### ISSUE TITLE
Api still works?

### ISSUE THREAD

**Issue by morettic2015** [mgp25/Chat-API#2227]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] You are using PHP > 5.6
- [ ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ ] You have checked if someone has already asked the same issue you have.
- [ ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ X ] Is not a programming question.
- [ ] You are using latest Chat API code.

### Error
Post your error below:

Any chance API is still working? Do i try to run it?

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by shivangi-12** [comment]
I run the composer require command in my cmd its giving this error.. can anyone help please?
![error1](https://user-images.githubusercontent.com/32199332/58017636-54981880-7b1e-11e9-9575-18dc309dc37a.JPG)

**Comment by MartinPessoa** [comment]
Hi. Apparently, it is a problem with your local installation of pho, or better yet - not a problem but a missing extension. Do you know how to edit php.ini? Gimme a sec I try to find a tutorial, but you can search for something like "installing / enabling mcrypt php.ini"

**Comment by MartinPessoa** [comment]
Hi, since I think you are on Windows I think these are the instructions for you:

Find php.ini (main php configuration file)

Open and search for ** ;extension=php_mcrypt.dll **

Uncomment/remove “;” and save the php.ini

**Comment by MartinPessoa** [comment]
You have to remove the semi-colon in your php.ini, according to your picture it is located in D:\wamp64\bin\php\php7.2.14
