### ISSUE TITLE
What Sould i do if "There was a problem trying to request the code." ?

### ISSUE THREAD

**Issue by darkterminal** [mgp25/Chat-API#2236]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ ] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
```
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 62882xxxxxxxxx


Type sms or voice: sms
Array
(
    [cc] => 62
    [in] => 882xxxxxxxx
    [lg] => id
    [lc] => ID
    [id] => 
            ����]o-�t7�ilj�
    [token] => 8jmi2kUugaXAroYZEqSKh1V89RM=
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 7971
    [rchash] => 79559fb41e1b3cd9201202cb9456729421eee43923ab9edafb40ab78214e782f
    [anhash] => 1f310701c4ad3166c4f45b0c2271c2ad
    [extexist] => 1
    [extstate] => 1
    [mcc] => 510
    [mnc] => 000
    [sim_mcc] => 510
    [sim_mnc] => 000
    [method] => sms
)
stdClass Object
(
    [login] => 62882xxxxxxxx
    [status] => fail
    [reason] => old_version
)
There was a problem trying to request the code.
```

**Comment by mgp25** [comment]
> What Sould i do if "There was a problem trying to request the code." ?

Read closed issues + know that there is no more support for this API

Regards
