### ISSUE TITLE
what is s.whatsapp.net, v.whatapp.net

### ISSUE THREAD

**Issue by ullassameer** [mgp25/Chat-API#2237]
` <recipient jid="**********@s.whatsapp.net"></recipient>`
 in the above code what is meant by "s.whatsapp.net" ? is that  server of whatsapp??

please let me know thankyou :)

**Comment by mgp25** [comment]
It is. Similar to what an email address is.

Regards

**Comment by sandeepmeenuga** [comment]
How to get jid?
