### ISSUE TITLE
mac address of registration of whatsapp

### ISSUE THREAD

**Issue by ranshalit** [mgp25/Chat-API#2252]
Hello,

Do you know what is the role of mac address in the registration ?
I reviewed the WhatsApp-Registration-Flow wiki, but I don;t see that mac address is being mentioned.
Yet, on various hack technique it is required to change the mac address to the target mac address.
So, I try to understand, what is the role of mac, i.e. when and how it is used in registration ?

Thank you!!
ranran

**Comment by mgp25** [comment]
You can read this: https://github.com/mgp25/RE-WhatsApp

Regards
