### ISSUE TITLE
Won't send message

### ISSUE THREAD

**Issue by kwiiby** [mgp25/Chat-API#627]
Hey, after that I updated the API (now) only composing is working but not sendMessage.
I tried to put pollMessage() after sendMessage(), no success.
What can I do?

**Comment by mgp25** [comment]
@kwiiby post code and debug log, any error or notice during the script?

**Comment by technocode** [comment]
Already download latest update. And try send to iphone. Only first and second message delivered.

**Comment by lordmampf** [comment]
I had the same problem, becasue the srcipt starts everytime with messageid 1 and every message needs a unique id.
So I'm using the send message like this:

public function sendMessage($target, $text)
	{
		list($usec, $sec) = explode(' ', microtime());
		$usec = str_replace("0.", "", $usec);
		$this->w->sendMessage($target, $text, time() . '-' . $usec . '-' . rand(0,1000));
	}

**Comment by kwiiby** [comment]
That worked, thanks.
