### ISSUE TITLE
Undefined index: get_lists

### ISSUE THREAD

**Issue by neowolfman** [mgp25/Chat-API#628]
Hi, my name is Cristian Torres, and keep your project , the new branch me the following error "Undefined index: get_lists whatsprot.class.php on line 3038"

I could tell how to fix it ??

Thank you in advance .

**Comment by mgp25** [comment]
@neowolfman line 3030 you mean? line 3038 is `$name = $sublist->getAttribute("name");
`

**Comment by mgp25** [comment]
Fixed in the latest commits

Regards
