### ISSUE TITLE
Composer package not up to date

### ISSUE THREAD

**Issue by ottowayne** [mgp25/Chat-API#631]
Packagist is still on revision 1dd0813.
I just noticed this when I tried to figure out why #627 is not fixed for me.

Maybe you can setup the webhook for Packagist ;)

**Comment by mgp25** [comment]
There is a webhook with packagist already.

Maybe its taking longer than other days, but its enabled. Maybe because i renamed the repository i should update it. Ill look it now

Regards

**Comment by ottowayne** [comment]
Ok, the webhook was just a idea.
Great, thanks :+1:

**Comment by mgp25** [comment]
@ottowayne check it now. If everythings fine close issue.

Regards

**Comment by ottowayne** [comment]
Looks good so far :bow:
