### ISSUE TITLE
Helpme!

### ISSUE THREAD

**Issue by neowolfman** [mgp25/Chat-API#632]
Sirs, I am writing to make an inquiry of a problem I could not solve my company is a sales team of 100 people, which wants to implement a system whereby we will send mennsajes Day promotions , sales ranking and they can check balances and prices of products as well as developing a system of measurement of attention to the technical field , we develop based on your library ( this 50 % functional ) , at the time of application shipments , the whatsapp account created in crashes and I lost many chip. what would be the best way to develop this shipment.

for your time and patience thank you very much .

Cristian Torres

**Comment by mgp25** [comment]
**WhatsApp is only meant to be personal usage only**

We don't support any kind of aumate system, bulk sending, or massive requests.

An according to http://www.whatsapp.com/legal/?l=en you can not do that.

Regards
