### ISSUE TITLE
Can't register new number

### ISSUE THREAD

**Issue by blueslmj** [mgp25/Chat-API#633]
Can't register new number, is there any update?

**Comment by DurtyFree** [comment]
Which method have you tried to register your number?

**Comment by mgp25** [comment]
@blueslmj `registerToll.php` there wasnt any changes.

Virtual numbers are not accepted by WhatsApp. For further support post debug, get used to it.

**Comment by diogopublio** [comment]
Can't register any new number. All methods I tried seems to not be working anymore

**Comment by CODeRUS** [comment]
coderus sad
