### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by tetrakiss** [mgp25/Chat-API#634]
Hello, today I have problem with login method I try to login  with $w->loginWithPassword($password); , but nothing happens;
I tried  to use $w->checkCredentials(); this method return stdClass Object ( [status] => fail [reason] => length_short )
What does it mean? number is blocked?

**Comment by brittson** [comment]
yes, its blocked

**Comment by CODeRUS** [comment]
can you show debug output?

**Comment by tetrakiss** [comment]
I tried receive new password via WART and  it return number blocked

**Comment by CODeRUS** [comment]
then it blocked
