### ISSUE TITLE
How to get identity with the registration tool as a variable instead of storing it in a .dat file?

### ISSUE THREAD

**Issue by Mohammad75** [mgp25/Chat-API#636]
Hello dear mgp25
I'm using registration tool to register my number and get the login password and I need to have the identity  as a variable to store it in my database like the password.
is this possible and how?

**Comment by viniciusjarina** [comment]
Hi @Mohammad75 
AFAIK you can only store the password, and use you number and password only to login (using `loginWithPassword `). You don't need to store the "identity" number.

**Comment by 0xTryCatch** [comment]
A quick solution would just be to read the identity file with ```file_get_contents()```

**Comment by Mohammad75** [comment]
@viniciusjarina  I know that I don't need the identity to login but I need it to change my password. 
@0xTryCatch  this will not be a quick solution. Is there any way to get it during the registration process?

**Comment by 0xTryCatch** [comment]
Add this to WhatsProt:

<code>

public function getIdentity () {
    return $this->identity;
}
</code>

**Comment by Mohammad75** [comment]
@0xTryCatch  thank you, I'm not a php expert but I'll try ^_^

**Comment by Mohammad75** [comment]
@0xTryCatch  I tried to get it the way you told me but there is an issue
I'm getting it like this
                $phone = '123456789';
                $identity = 'myidentity';
		$w = new WhatsProt($phone, $identity, $nickname, $debug);
                $id = $w->getIdentity();
		$q = " INSERT INTO mytable(phone,password,identity,username) VALUES('$result->login','$result->pw','$id','$username')";

but when I look at the db I find the identity like this 
sÅóípºwªf‹,¸Üotë&

not like this 

sr%5e%078%f0%d7%90%a8cht%917j%bc%dd%c8%98q

why?

**Comment by mgp25** [comment]
I just visit your profile page in github, you are sending ads via WhatsApp.

1- We don't support spammer
2- That is not an API related issue
3- It goes agains WhatsApp EULA
4- Its illegal

Because of people doing this shit, you are messing up this API

Nothing more to say.
