### ISSUE TITLE
How to add Emoji as Nickname

### ISSUE THREAD

**Issue by jackbell16** [mgp25/Chat-API#637]
Hi,
I want to add two emoji (the soccer ball one and the smile happy) as the nickname, after a string in PHP. So "My Nickname ball smile". How Can I do ?

**Comment by CODeRUS** [comment]
Like this My Nickname ⚽️😊 ?

**Comment by CODeRUS** [comment]
"My nickname \xe2\x9a\xbd \xee\x81\x96"

**Comment by matteocontrini** [comment]
[Table](http://apps.timwhitlock.info/emoji/tables/unicode)
