### ISSUE TITLE
how I can use this API in asp.net or C# ?

### ISSUE THREAD

**Issue by momenimohammad23** [mgp25/Chat-API#638]
hi
I created an asp.NET webform app with this : https://github.com/venomous0x/WhatsAPI
I cant change it to php and I am not a php developer ! 
So How I can use new version ?

**Comment by CODeRUS** [comment]
became a developer

**Comment by momenimohammad23** [comment]
@CODeRUS  it mean cant use new version in asp.net ?

**Comment by CODeRUS** [comment]
No, it meant you really need to be a ddeveloper to use it

**Comment by joelhdez89** [comment]
There is an API in C# called WhatsAPINet http://1drv.ms/1JhATh5, you may keep updating the UserAgent in the module that contains the Constants.
