### ISSUE TITLE
what is the images path on the whatsapp

### ISSUE THREAD

**Issue by hablas** [mgp25/Chat-API#640]
i want to know the images path ( profile image or messages images ) after uploading it on the whatsapp server 
to use this path in the next messages
to avoid upload the same images every time 
anyone can help me ?

**Comment by CODeRUS** [comment]
profile images have no urls, for messages images you will receive all info after uploading

**Comment by hablas** [comment]
thank you
i will check this
" profile images have no urls " is that mean : whatsap api will upload the profile image every message to there servers ?!

**Comment by mgp25** [comment]
Profile image is uploaded once.

**Comment by hablas** [comment]
how ?
i send it every message " $w->sendSetProfilePicture("profile.png"); "
thanks a lot for help

**Comment by mgp25** [comment]
@hablas No, only once!

**Comment by hablas** [comment]
ooohhh
you mean i must send it only if i change it
after that .. send messages without it  ?

**Comment by CODeRUS** [comment]
You upload profile picture and it stored on server. Users will request your profile picture after adding you to ocntacts.
