### ISSUE TITLE
i see the last seen but i cant use it in php

### ISSUE THREAD

**Issue by hablas** [mgp25/Chat-API#643]
$w = new WhatsProt($Channel_Number, $identity, "xxx", true); 
$w->Connect();
$w->LoginWithPassword($password);
$w->sendGetRequestLastSeen($Number);

its appear as this : 
rx  <iq from="xxxxxxxxxxxxx@s.whatsapp.net" id="lastseen-1430156125-1" type="result">
rx    <query seconds="4430"></query>
rx  </iq>

how can i use this result : 1430156125 in php 
how can i change the seconds to a php variable ?

i try this lines :
public function onGetRequestLastSeen( $mynumber, $from, $id, $seconds )
{
  echo "Last seen of $id: ".gmdate("H:i:s", $seconds);
}
but i cant know how exactly use it

**Comment by 0xTryCatch** [comment]
This is not an Api question but a PHP question. Search php.net for the answer.

**Comment by CODeRUS** [comment]
lastseen timestamp = now - lastseen seconds, obviously

**Comment by fermino** [comment]
You have to bind the onGetRequestLastSeen function in order to use the $seconds variable. Search in the wiki :)
