### ISSUE TITLE
There was a problem trying to request the code.

### ISSUE THREAD

**Issue by pesalek** [mgp25/Chat-API#644]
Hello, with latest version, unable to register/generate code. Result no route

First, there was a missing MNC, wrong assigment of $carrierName 

Fixed it in networkinfo.csv

Problem remains. Any idea how to fix?

Array
(
    [in] => 720115338
    [cc] => 420
    [id] => 8▒u▒љu▒▒▒0f
    [lg] => cs
    [lc] => CZ
    [sim_mcc] => 230
    [sim_mnc] => 002
    [method] => sms
    [token] => 9604111c06c7b61023566229bace85a5
)
PuTTYstdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
)

Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /src/WhatsAPPI/Chat-API/src/whatsp    rot.class.php:382
Stack trace:
#0 /src/WhatsAPPI/Chat-API/examples/exampleRegister.php(45): WhatsProt->codeRequest('sms')
#1 {main}
  thrown in /src/WhatsAPPI/Chat-API/src/whatsprot.class.php on line 382

**Comment by pesalek** [comment]
Found a way, download WART 1.7.3 and generate code/password by Wart. After this, APIs working ok.

**Comment by diogopublio** [comment]
pesalek, are you using the latest version of WhatsAPI with WART 1.7.3 ?

Somehow for me it's not working.

**Comment by pesalek** [comment]
Yes, latest from GIT and WART and sending messages perfectly. Only registration is not working.

**Comment by diogopublio** [comment]
What are you currently using for registration ?

**Comment by pesalek** [comment]
wart 1.7.3.0  generates a code and registerswithout problem

**Comment by diogopublio** [comment]
Tried with different versions (whatsapp, wart and android) and none of them worked for my country. What whatsapp version are you using ?

if you could, pls shoot me at dpublio  at g m a i l

**Comment by mgp25** [comment]
@diogopublio Your IP its blocked then, try with different IP.

Regards

**Comment by diogopublio** [comment]
@mgp25 tried with many different IPs. Some public IPs too.

**Comment by mgp25** [comment]
@diogopublio then you are using virtual phone number which are being blocked by WhatsApp

**Comment by diogopublio** [comment]
@mgp25 No, I am using a physical sim card. It's might be some kind a block for my country (Brazil). I tried will all 4 carriers available in my country, none of them worked.

**Comment by mgp25** [comment]
@diogopublio contact me via email, we are going to figure it out

**Comment by mgp25** [comment]
By the way use this WART from me: https://github.com/mgp25/WART

Regards

**Comment by MalikKan** [comment]
@mgp25 What is your email

**Comment by breakerh** [comment]
Dude.. read the first issue.. ![end of support](http://image.prntscr.com/image/47d432fa6359433a804d7af242eb2a80.png)
