### ISSUE TITLE
Does Whatsapp Monitor the IP address of the client computer?

### ISSUE THREAD

**Issue by TaralPatoliya** [mgp25/Chat-API#646]
We are creating a webapp that is used to communicate with all of out employees, so when we are sending the same message to more then 20 message does ip get blocked after certain times of connections?

**Comment by mgp25** [comment]
@TaralPatoliya That is considered spam, read WhatsApp EULA. If not spam, your contacts should have added you in their contact list.

Yes, they can block IP too.

Regards
