### ISSUE TITLE
Help Checkin contact list

### ISSUE THREAD

**Issue by neowolfman** [mgp25/Chat-API#647]
Good day, I would like to ask for your help again, I'm trying to implement a sending messages whenever a server goes down in my office, I dropped the contacts list in my phone and select people on duty for sending whatsapp me it has happened that some numbers had not whatsapp Teleno and using whatsapp lastseen blocked me, my first question is, is there another way to check if the number has whatsapp? and in the same application to send the message to a maximum of 10 people (electric, development, infrastructure, etc.) what is the best way Shipping 1-1 or broadcast ?, this travez of the persistent blocking numbers cell (and go 6).

in advanced
many Thanks

**Comment by mgp25** [comment]
@neowolfman everything its explained in thw wiki, and maybe there are also closed issues that you maybe find useful.

The use of broadcast or send message depends on what you need, just think like if you had a real app, what will you do? So do the same.

You need to sync contacts.

Regards
