### ISSUE TITLE
Help with onGetMessege

### ISSUE THREAD

**Issue by Pudins** [mgp25/Chat-API#648]
Hello!
I need some help I am using successfully API to talk to my targets, however now I need automatically to reply with this message "Hello I'm busy, as I talk to you!".
I'm using exampleFunctional.php code with little modifications to talk to my targets.
This would be using onGetMessage? If it is, how to avoid reconnection?
Does someone can give me a hint how to do this?

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#using-events

If you have more question be more specific

Regards

**Comment by Pudins** [comment]
I'm sorry for not being as specific!
The fact is I am trying to do so without success:

```
$w->eventManager()->bind("onGetMessage","sendMsg");

function sendMSG($mynumber, $from, $id, $type, $time, $name, $body)
{
    $username = "****************";
    $password = "********************";
    $nickname = "**SharkTalks**";
    $debug = false;
    $w = new WhatsProt($username, $nickname, $debug);
    $w->sendMessage($from, "Hello I'm busy, as I talk to you! - " . date('H:i'));

}
```
To run this code it returns me this error:

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/ubuntu/Chat-API-master/src/whatsprot.class.php:548
Stack trace:
#0 /home/ubuntu/Chat-API-master/src/whatsprot.class.php(1959): WhatsProt->pollMessage()
#1 /home/ubuntu/Chat-API-master/src/whatsprot.class.php(3764): WhatsProt->waitForServer('-1')
#2 /home/ubuntu/Chat-API-master/src/whatsprot.class.php(1490): WhatsProt->sendMessageNode('***************@s....', Object(ProtocolNode), NULL)

I thank you for your help and for your time!
