### ISSUE TITLE
UNABLE TO WATCH STDIN

### ISSUE THREAD

**Issue by usinadeideia** [mgp25/Chat-API#649]
Hello, I'm having a hard time, when I run exampleFunctional.php in my server, received from the image and message on my phone, but it presents the error below then. What should I fazr? Could anyone help me?

```
Warning: stream_select(): No stream arrays were passed in /home/admin/public_html/usina/testes/examples/exampleFunctional.php on line 21
$ 001 Socket Error : UNABLE TO WATCH STDIN. 
Strict Standards: Only variables should be passed by reference in /home/admin/public_html/usina/testes/examples/exampleFunctional.php on line 21
```

Thank You

**Comment by mgp25** [comment]
@usinadeideia its a CLI (command line) script, not for running in a webserver.

Regards

**Comment by usinadeideia** [comment]
Ok, it's working now. Thank You
