### ISSUE TITLE
strange problem appear

### ISSUE THREAD

**Issue by hablas** [mgp25/Chat-API#650]
can you help me to solve this suddenly problem
iam try to : `getMessages `

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'onMessage' not found or invalid function name in /home/xxx/public_html/whatsapp/src/events/WhatsApiEventsManager.php on line 15`

it was not appear yesterday
what is the wrong please ?

**Comment by mgp25** [comment]
@hablas post your code script.

**Comment by hablas** [comment]
$w = new WhatsProt($Send_Channel_Number, $identity, "Hablas", true); 
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->Connect();
$w->LoginWithPassword($password);
$w->pollMessage();

$msgs = $w->getMessages();
foreach ($msgs as $m) {
            $indxmessage = "";
			$image = "";
			$video = "";
			foreach (($m->getChildren()) as $child) { 
				   $childTag = $child->getTag();
                   if ( $childTag == "body") { 
                       $indxmessage = $child->getData(); 
                   } else if( $childTag == 'media') {
							$media_type = $child->getAttribute("type");
							$media_url = $child->getAttribute("url");
							if($media_type=='image') {
								$image = $media_url;
							} elseif($media_type=='video') {
								$video = $media_url;
							}
				   } else if ( $childTag == "notify") { 
                       $indxmessage = $child->getAttribute('name'); 
                   } 
            } 
			$tag = $m->getTag();
			
			if ($tag == "message") 
		    {
				$nick_name = $m->getAttribute('notify');
				$mobile_number = str_replace("@s.whatsapp.net", "", $m->getAttribute('from'));
				$time = $m->getAttribute('t');
		    }

echo"(($mobile_number))<BR>";
echo"$indxmessage<BR>";
echo"$nick_name<BR>";
echo"(($time))<BR>";

$w->disconnect();

        }

**Comment by mgp25** [comment]
@hablas 

You are using a wrong constructor, you havent coded the binded function to the event, use events instead of all code you have posted.

Using events: https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#using-events
Wiki: https://github.com/mgp25/Chat-API/wiki

Regards

**Comment by hablas** [comment]
thanks alot @mgp25  
you make it easy for me 

:+1:  :+1:
