### ISSUE TITLE
blockchecker didnot get the id , i can't get new passwrod 

### ISSUE THREAD

**Issue by OTHv2** [mgp25/Chat-API#651]
Hi
I have this problem.
in blockchecker.php
i want to change the password of my channel and i get this error with php api
Wrong identity.

`Array ( [cc] => 1 [in] => 4188005989 [id] => ºér%s‹\É6cë³˜\µ [lg] => en [lc] => CA ) stdClass Object ( [status] => fail [reason] => incorrect [sms_length] => 6 [voice_length] => 6 )`

if i use whatsapp finder last version the pass change successfully 
what is the problem :(

**Comment by mgp25** [comment]
What do you use the API for?

**Comment by OTHv2** [comment]
i use it for a desktop chat software

**Comment by mgp25** [comment]
You have wrong identity. Register number using registerTool.php or copy identity to a file in wadata folder

Regards
