### ISSUE TITLE
User-defined Message-ID for Media-Messages

### ISSUE THREAD

**Issue by eltem** [mgp25/Chat-API#655]
Hi,

I need to use other message-ids than the generated ones with unix-timestamp + internal counter.
When using the sendMessage-method, I can use my $id as third parameter, fine! Could you please add this possibility to sendMessageImage (Audio / Video)?
Of course I could modify the code for my needs, but then merging new changes may be hard.

kind regards, eltem

**Comment by CODeRUS** [comment]
you will be banned in whatsapp if so

**Comment by eltem** [comment]
Are you sure? Is it part of the protocol to have a ID like
$this->loginTime.'-'.$this->messageCounter
?

**Comment by mgp25** [comment]
Yes

**Comment by eltem** [comment]
Ok, thanks!
