### ISSUE TITLE
New Strange problem

### ISSUE THREAD

**Issue by phpjoker** [mgp25/Chat-API#658]
Today when i want to send a message my compose response appear in debug output but no any message in output...
But after several restart script messages arrived.
another problem that happened today after one minutes:
```xml
<stream:error>
  <ack></ack>
</stream>
```

**Comment by mgp25** [comment]
@phpjoker you didnt send an ack to a message, so you got that error, search when it happened and log at the debug log, there was some message you didnt send an ack back.

Regards

**Comment by phpjoker** [comment]
```
<stream:error>
  <ack></ack>
</stream>
```
Appear one minute After Script start and login
```
...
$w->sendPing();
while(1){
$w->pollMessage();
}

I temporary solve it with:
```
$pingtimeout=time();
while(1){
$w->pollMessage();
if ($pingtimout+30<=time()){
	$w->sendPing();
	$pingtimout=time();
}
}
```

**Comment by phpjoker** [comment]
When I type and send a message from my device to Bot debug log only show <chatstate> but no any <message> and no any message does not appear to onGetMessage() !!!

Regards

**Comment by CODeRUS** [comment]
RTFM

**Comment by mgp25** [comment]
@phpjoker should be fixed now
