### ISSUE TITLE
Vcard sending Problem

### ISSUE THREAD

**Issue by Abtab** [mgp25/Chat-API#660]
Hi @mgp25 

I am sending a vcard. Not finding any error. Posting debug result here, Please guide me

```xml
tx  <message to="9180545XXXXX@s.whatsapp.net" type="media" id="5" t="1430387369">
tx    <media type="vcard">
tx      <vcard name="Contact">BEGIN:VCARD VERSION:3.0 CLASS:PUBLIC PRODID:-//class_vCard from WhatsAPI//NONSGML Version 1//EN REV:2015-04-30 09:49:29 FN:Arun Kumar N:Kumar;Arun;;; TEL;type=CELL,voice:80545XXXXX TZ:+0000 END:VCARD </vcard>
tx    </media>
tx  </message>

rx  <ack from="9180545XXXXX@s.whatsapp.net" id="5" class="message" t="1430387369"></ack>

rx  <receipt from="9180545XXXXX@s.whatsapp.net" id="5" t="1430387370"></receipt>

tx  <ack to="9180545XXXXX@s.whatsapp.net" id="5" type="read" t="1430387370"></ack>

```

According to debug results i am receiving vcard But In actual I am not receiving anything. 

Thanks in advance

**Comment by CODeRUS** [comment]
@Abtab update API, your one is outdated

**Comment by Abtab** [comment]
thanks  @CODeRUS .. One more query and how can i send .vcf file ?

**Comment by CODeRUS** [comment]
RTFM

**Comment by Abtab** [comment]
sorry @CODeRUS .. I will check by myself.. I was not expecting this behavior from you. anyways. tc

**Comment by mgp25** [comment]
@Abtab everything its well explained in the wiki, is there and with examples.

**Comment by Abtab** [comment]
ok . Thanks
