### ISSUE TITLE
Better Exception-Message

### ISSUE THREAD

**Issue by eltem** [mgp25/Chat-API#662]
Hi,

In the "checkCredentials"-method there could be an exception named "There was a problem trying to request the code". I can understand that this piece code is very similar to the "codeRequest"-method, but could you please adapt the exception-message to get clearlier feedback?

In addition, I am not sure if it wouldn't be even better to return the response-object, even if the status is not "ok"? May be useful for further processing?

kind regards

**Comment by mgp25** [comment]
There is an event for that, check the wiki

Regards
