### ISSUE TITLE
too_many_guesses exception with no retry_after specified

### ISSUE THREAD

**Issue by avivcarmis** [mgp25/Chat-API#664]
Hi all,
I'm receiving a too_many_guesses  exception but i do not have a retry_after field specify in the returned JSON.
All the output details are below:
Array
(
    [in] => 7781484000
    [cc] => 44
    [id] => ����程a�����[���
    [lg] => en
    [lc] => GB
    [sim_mcc] => 234
    [sim_mnc] => 000
    [method] => sms
    [token] => 529905d68e7e153e8d5a1a97fe8f5343
)
stdClass Object
(
    [status] => fail
    [reason] => too_many_guesses
)

After that, there are the obvious PHP warning saying:
Undefined property: stdClass::$retry_after
Filename: whatsapp/whatsprot.class.php
Line Number: 386

and 

Undefined property: stdClass::$retry_after
Filename: whatsapp/whatsprot.class.php
Line Number: 388

Thx!

**Comment by CODeRUS** [comment]
if you have no retry you should wait 24 hours

**Comment by avivcarmis** [comment]
3 days after, still getting the same response.
