### ISSUE TITLE
Differences between sync types

### ISSUE THREAD

**Issue by matteocontrini** [mgp25/Chat-API#665]
Hi,
I see in the source code many sync types, that are different combinations of modes and contexts.

[Line 2269](https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L2269)

In the wiki I see described only two types: full-registration and delta-background.

[Wiki link](https://github.com/mgp25/Chat-API/wiki/Sync)

Then, in `yowsup` I only see 2 accepted modes, that are `full` and `delta`, and 2 contexts, that are `registration` and `interactive`.

https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_contacts/protocolentities/iq_sync_get.py

Now, I understand full-registration, but what's the difference between the others? Why should I prefer delta-interactive to delta-background, or vice versa?

Thanks

**Comment by mgp25** [comment]
@matteocontrini thats a very good question, we know all the types that exists but in the practice we have only seen the 2 we always talk about, anyway ill update the wiki if i gather more information about when its triggered and how is used. Ill check it soon.

Ill update the wiki as soon as i check that.

Delta interactive (our default) its when addind during online activity, delta background its when you have whatapp in the background and you add a new contact, then its synced in delta and notice the background. Thats why we only use that 2 types.

Regards

**Comment by matteocontrini** [comment]
Thanks, a bit clearer now. The online/offline difference makes sense!

**Comment by matteocontrini** [comment]
I've found this looking at the official apps source code:
* `registration-full` made only the first time
* `background-full` every time the app launches
* `interactive-delta` when a new contact is added
