### ISSUE TITLE
How to distinguish error messages 

### ISSUE THREAD

**Issue by SudoHenk** [mgp25/Chat-API#666]
I'm trying to send a massive amount of mess.. just kidding :).

I'm fooling around with the API, and it works pretty good. I do however hava a slight problem. I request both the profile picture and last seen of a user (like in the example script), but if the user has the privacy options set in such a way I can't access those a `onGetError` is triggered.

I retrieve the following information:

- My phonenumber
- Users phone number
- MsgID
- Data array with tag = error and attributes code = 404 and text = item-not-found.

But how can I determine this error message is for the profile picture or for the last seen? Is there a way to store this MsgID on requesting it or determine the action based on the MsgID?

**Comment by mgp25** [comment]
If you request `last seen` you will get 404 (privacy on), if you request profile 404 (privacy on), there are 2 different requests that trigger the same event, but you can check which is using the `msgid` if you look at the node, it will tell you which one has the error.

Regards
