### ISSUE TITLE
problem starting up

### ISSUE THREAD

**Issue by sabado** [mgp25/Chat-API#669]
my script goes running over october past, to 3 days ago. I had a login error. __Number isn't banned__, i tested runnin a new password in  WART. 

But, when i check it 

_this happens using my own number too_
```
####################
#                  #
# WA Block Checker #
#                  #
####################


Username (country code + number without + or 00): XXXXXXXXXXXX6


Wrong identity.
Array
(
    [cc] => XX
    [in] => XXXXXXXXXXXX6
w\vÑ╗]+] => y Ý←←)ô¶:kÜ╝
    [lg] => es
    [lc] => XX
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)
PHP Fatal error:  Uncaught exception 'Exception' with message '
There was a problem trying to request the code.' 
in .\src\whatsprot.class.php:181
Stack trace:
#0 .\check.php(26): WhatsProt->checkCredentials()
#1 {main}
  thrown in .\src\whatsprot.class.php on line 181
```

i updated the api code and checked everything

```php
<?php
require_once('config.whatsapi.php');
require_once('mysq.estable.php');
require 'src/events/MyEvents.php';



$w = new WhatsProt($config['cfg']['number'], $config['configuracion']['id'], $config['cfg']['nick']);

$events = new MyEvents($w);

$w->eventManager()->bind("onGetMessage","RecibirMensaje");
$w->eventManager()->bind("onGetVideo","RecibirVideo");
$w->eventManager()->bind("onGetImage","RecibirImagen");

$w->Connect();
$w->LoginWithPassword($config['configuracion']['waPassword']);

/* ...

```

but i get this debug code and _quit_

```
#CMD>php code.php
        tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="XXXXXXXXXXXX6"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>òn^[$Æ┌¹¢↓§ì¶áP® ¿ø3</challenge>

tx  <response>ß}Ó-☺BX¦½@9 XË☺e§7Ð▲êu3ò╦®┤©═_╩,²1å</response>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in 
.\src\whatsprot.class.php:2201
Stack trace:
#0 .\src\whatsprot.class.php(534): WhatsProt->doLogin()
#1 .\code.php(19): WhatsProt->loginWithPassword('XXXXXXXXXXXXXXX...')
#2 {main}
  thrown in .\src\whatsprot.class.php on line 2201
```

i'm missing something new? 

thanks for help me!

**Comment by aesedepece** [comment]
Something changed in the WhatsApp protocol and now every WhatsApp API (yowsup, Loqui IM, Chat API, etc.) is not working.

Like in previous times @mgp25, @tgalal, @CODeRUS, me and everyone implied in the development of these APIs will cooperate to find a solution ASAP.

**Comment by mgp25** [comment]
Im going to check everything today

Regards

**Comment by janpieterz** [comment]
Hi guys, 

Just to inform you, we updated our Device ID and version and have a version that is currently working. See change sanderdriesen/WhatsAPINet@84cc3452e0384540fe7f3d4f0ee87892a207bb4.

**Comment by aesedepece** [comment]
Thanks @janpieterz for the hint, it works!

**Comment by technocode** [comment]
how?

**Comment by janpieterz** [comment]
@aesedepece You're welcome!
@technocode Sorry, the link to the commit was broken, I fixed it. This is a .NET version though, but the logic should be the same.

**Comment by CODeRUS** [comment]
so, you just using outdated code?

**Comment by domingopa** [comment]
@janpieterz janpieterz What is the logic?

thanks

**Comment by CODeRUS** [comment]
nothing, Chat-API using latest tokens, it's not a problem here

**Comment by aesedepece** [comment]
I have no time to fix it in Chat-API right now, but for reference here you have the Pull Request fixing it in Yowsup: https://github.com/tgalal/yowsup/pull/748

**Comment by mgp25** [comment]
@aesedepece nothing to update in Chat API, we are already up to date

Sigh...

**Comment by mgp25** [comment]
By the way, WART doesnt generates the identity the same way Chat API does, so check your own identity

Regards

**Comment by aesedepece** [comment]
@mgp25 Ok, sorry for the hassle and thanks :wink:
