### ISSUE TITLE
Always get null for sendGetRequestLastSeen

### ISSUE THREAD

**Issue by aghict** [mgp25/Chat-API#672]
Hello,
This is my code
```php
        $w = new WhatsProt($number, $nickname, $debug);
        $events = new MyEvents($w);
        $events->setEventsToListenFor($events->activeEvents);
        $w->connect();
        $w->loginWithPassword($password);
        $w->sendGetRequestLastSeen($target);
```
all of the time I get `null` why?

**Comment by mgp25** [comment]
@aghict debug log?

**Comment by aghict** [comment]
```
rx  <receipt from="mexxxxx@s.whatsapp.net" id="1430484776-1" offline="0" type="read" t="1430484787"></receipt>

tx  <ack to="mexxxxx@s.whatsapp.net" id="1430484776-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484930@broadcast" id="1430484930-1" participant="323222332@s.whatsapp.net" offline="0" t="1430484934"></receipt>

tx  <ack to="1430484930@broadcast" id="1430484930-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484618@broadcast" id="1430484618-1" participant="222221212@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484618@broadcast" id="1430484618-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484653@broadcast" id="1430484653-1" participant="222221212@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484653@broadcast" id="1430484653-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484687@broadcast" id="1430484687-1" participant="222221212@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484687@broadcast" id="1430484687-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484930@broadcast" id="1430484930-1" participant="222221212@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484930@broadcast" id="1430484930-1" type="read" t="1430487110"></ack>

rx  <presence from="323233232@s.whatsapp.net"></presence>

rx  <iq from="222221212@s.whatsapp.net" id="1430487110-1" type="error">
rx    <error code="403" text="forbidden"></error>
rx  </iq>
```

**Comment by 0xTryCatch** [comment]
Post full log please. And what do you mean with "I get null"?

**Comment by aghict** [comment]
WooHoo!, Phone number 989215778281 connected successfully!
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="989215778281">��^989215778281
rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>�������|��D� ��e�</challenge>

tx  <response>n���������5t�o����]�5^w����$�</response>

rx  <success t="1430487118" props="4" kind="free" status="active" creation="1416859311" expiration="1448395311">^u�^C �^����H�Su�W�</success>

tx  <presence name="Hamed"></presence>

tx  <iq to="989173086269@s.whatsapp.net" type="get" id="1430487110-1" xmlns="jabber:iq:last">
tx    <query></query>
tx  </iq>

rx  <receipt from="1430484618@broadcast" id="1430484618-1" participant="989170492217@s.whatsapp.net" retry="3" offline="3" t="1430484621"></receipt>

tx  <ack to="1430484618@broadcast" id="1430484618-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484653@broadcast" id="1430484653-1" participant="989170492217@s.whatsapp.net" offline="0" t="1430484657"></receipt>

tx  <ack to="1430484653@broadcast" id="1430484653-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484687@broadcast" id="1430484687-1" participant="989170492217@s.whatsapp.net" offline="0" t="1430484691"></receipt>

tx  <ack to="1430484687@broadcast" id="1430484687-1" type="read" t="1430487110"></ack>

rx  <receipt from="989374955090@s.whatsapp.net" id="1430484776-1" offline="0" t="1430484780"></receipt>

tx  <ack to="989374955090@s.whatsapp.net" id="1430484776-1" type="read" t="1430487110"></ack>

rx  <receipt from="989374955090@s.whatsapp.net" id="1430484776-1" offline="0" type="read" t="1430484787"></receipt>

tx  <ack to="989374955090@s.whatsapp.net" id="1430484776-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484930@broadcast" id="1430484930-1" participant="989170492217@s.whatsapp.net" offline="0" t="1430484934"></receipt>

tx  <ack to="1430484930@broadcast" id="1430484930-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484618@broadcast" id="1430484618-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484618@broadcast" id="1430484618-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484653@broadcast" id="1430484653-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484653@broadcast" id="1430484653-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484687@broadcast" id="1430484687-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484687@broadcast" id="1430484687-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484930@broadcast" id="1430484930-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484930@broadcast" id="1430484930-1" type="read" t="1430487110"></ack>

rx  <presence from="989215778281@s.whatsapp.net"></presence>

rx  <iq from="989173086269@s.whatsapp.net" id="1430487110-1" type="error">
rx    <error code="403" text="forbidden"></error>
rx  </iq>

tx  <iq id="1430487110-2" type="get" xmlns="w:profile:picture" to="989173086269@s.whatsapp.net">
tx    <picture type="preview"></picture>
tx  </iq>

rx  <iq from="989173086269@s.whatsapp.net" id="1430487110-2" type="result">
rx    <picture id="1396558389" type="preview"> 3154 byte data</picture>
rx  </iq>

**Comment by aghict** [comment]
```
WooHoo!, Phone number 989215778281 connected successfully!
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="989215778281">��^989215778281
rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>�������|��D� ��e�</challenge>

tx  <response>n���������5t�o����]�5^w����$�</response>

rx  <success t="1430487118" props="4" kind="free" status="active" creation="1416859311" expiration="1448395311">^u�^C �^����H�Su�W�</success>

tx  <presence name="Hamed"></presence>

tx  <iq to="989173086269@s.whatsapp.net" type="get" id="1430487110-1" xmlns="jabber:iq:last">
tx    <query></query>
tx  </iq>

rx  <receipt from="1430484618@broadcast" id="1430484618-1" participant="989170492217@s.whatsapp.net" retry="3" offline="3" t="1430484621"></receipt>

tx  <ack to="1430484618@broadcast" id="1430484618-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484653@broadcast" id="1430484653-1" participant="989170492217@s.whatsapp.net" offline="0" t="1430484657"></receipt>

tx  <ack to="1430484653@broadcast" id="1430484653-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484687@broadcast" id="1430484687-1" participant="989170492217@s.whatsapp.net" offline="0" t="1430484691"></receipt>

tx  <ack to="1430484687@broadcast" id="1430484687-1" type="read" t="1430487110"></ack>

rx  <receipt from="989374955090@s.whatsapp.net" id="1430484776-1" offline="0" t="1430484780"></receipt>

tx  <ack to="989374955090@s.whatsapp.net" id="1430484776-1" type="read" t="1430487110"></ack>

rx  <receipt from="989374955090@s.whatsapp.net" id="1430484776-1" offline="0" type="read" t="1430484787"></receipt>

tx  <ack to="989374955090@s.whatsapp.net" id="1430484776-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484930@broadcast" id="1430484930-1" participant="989170492217@s.whatsapp.net" offline="0" t="1430484934"></receipt>

tx  <ack to="1430484930@broadcast" id="1430484930-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484618@broadcast" id="1430484618-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484618@broadcast" id="1430484618-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484653@broadcast" id="1430484653-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484653@broadcast" id="1430484653-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484687@broadcast" id="1430484687-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484687@broadcast" id="1430484687-1" type="read" t="1430487110"></ack>

rx  <receipt from="1430484930@broadcast" id="1430484930-1" participant="989173086269@s.whatsapp.net" offline="0" t="1430486797"></receipt>

tx  <ack to="1430484930@broadcast" id="1430484930-1" type="read" t="1430487110"></ack>

rx  <presence from="989215778281@s.whatsapp.net"></presence>

rx  <iq from="989173086269@s.whatsapp.net" id="1430487110-1" type="error">
rx    <error code="403" text="forbidden"></error>
rx  </iq>

tx  <iq id="1430487110-2" type="get" xmlns="w:profile:picture" to="989173086269@s.whatsapp.net">
tx    <picture type="preview"></picture>
tx  </iq>

rx  <iq from="989173086269@s.whatsapp.net" id="1430487110-2" type="result">
rx    <picture id="1396558389" type="preview"> 3154 byte data</picture>
rx  </iq>
```

**Comment by phpjoker** [comment]
This is forbidden to see it.

**Comment by 0xTryCatch** [comment]
You are not allowed to request the last seen

**Comment by aghict** [comment]
How can I fix this problem?

**Comment by 0xTryCatch** [comment]
You cannot fix it, it is controlled by WhatsApp

**Comment by mgp25** [comment]
@0xTryCatch Or whatsapp has deny you to request the last seen of that user, or that user has blocked you.

**Comment by fermino** [comment]
Or, you have that function disabled in your profile privacy settings, then, you can't see the last seen of any user

**Comment by swapnilbh25** [comment]
Post full log please. And what do you mean with "I get null"?

**Comment by swapnilbh25** [comment]
connected successfully!
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="989215778281">���^989215778281��
rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>��������|��D� ���e�</challenge>

tx  <response>n������������5�t�o����]�5^w����$�</response>

rx  <success t="1430487118" props="4" kind="free" status="active" creation="1416859311" expiration="1448395311">^u�^C �^����H�Su�W�</success>

tx  <presence name="Hamed"></presence>

tx  <iq to="989173086269@s.whatsapp.net" type="get" id="1430487110-1" xmlns="jabber:iq:last">
tx    <query></query>
tx  </iq>

rx  <presence from="989215778281@s.whatsapp.net"></presence>

rx  <iq from="989173086269@s.whatsapp.net" id="1430487110-1" type="error">
rx    <error code="403" text="forbidden"></error>
rx  </iq>

tx  <iq id="1430487110-2" type="get" xmlns="w:profile:picture" to="989173086269@s.whatsapp.net">
tx    <picture type="preview"></picture>
tx  </iq>

rx  <iq from="989173086269@s.whatsapp.net" id="1430487110-2" type="result">
rx    <picture id="1396558389" type="preview"> 3154 byte data</picture>
