### ISSUE TITLE
 My system can not be more than 5 minutes online

### ISSUE THREAD

**Issue by lennon3d** [mgp25/Chat-API#675]
Hello, I have a problem, my system can not be more than 5 minutes online. Cai and not back, I have to restart and yet he does not read the messages, to restart an 8 more times to return to normal. The following error:
```
- Lennon3d: I i 21:56
PHP Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/vigbox/whatsapi/src/whatsprot.class.php:548
Stack trace:
# 0 /var/vigbox/whatsapi/client.php(85): WhatsProt-> pollMessage ()
# 1 {main}
   thrown in /var/vigbox/whatsapi/src/whatsprot.class.php on line 548
```
What could be happening?

**Comment by thiagosantos** [comment]
Are you sendPing ?

**Comment by lennon3d** [comment]
yes

**Comment by thiagosantos** [comment]
can you post your code?

**Comment by mgp25** [comment]
Post full debug log please

Regards

**Comment by matteocontrini** [comment]
Have you updated to this commit? https://github.com/mgp25/Chat-API/commit/07d28e15ce1a41793556230f61441d9705119d20

There could be a stream error because of the acks

**Comment by mgp25** [comment]
@lennon3d fixed with latest commits

Regards
