### ISSUE TITLE
UTF-8 message with long length not being sent

### ISSUE THREAD

**Issue by matteocontrini** [mgp25/Chat-API#676]
I'll bring here a problem reported on node-whatsapi [here](https://github.com/hidespb/node-whatsapi/issues/41).

Sending long messages with special UTF-8 characters (Italian or Russian accents) results in the message being sent as `0`.

On node-whatsapi the problem is slightly different, because the library still tries to send it but it is never received by the server.

Sample code:

```
$m = "Aaaaaaaaa aaaaa aaaaaaa: \n" +
  "Aà: Aaaaaa aa a aaaa aaaaaa aaaa aaaa aaa aa aaaa aaaaaa aaaa aaaa aa aaaa\n"+
  "Aà: Aaaaaaa aaaa aaaa aaaa aa aa aa aa aaaaaa aaaa aaa aaaaa aa aaaaaaaaaa\n"+
  "Aà: Aaa aaa aaaaa aaaa\n"+
  "Aà: Aaaaaa aaaaaaaa\n"+
  "Aà: Aaaaaa aaaa aaaa\n" +
  " Aaaa aaaa ?";

$w->sendMessage('xxx', $m);
```

A workaround has been posted [here](https://github.com/hidespb/node-whatsapi/issues/41#issuecomment-93850388), consisting in making the message even longer (longer than 256 characters it seems), so that it can be sent again. But it's just a hack...

**Comment by 0xTryCatch** [comment]
You are using it wrong. In PHP strings are concatenated with the dot (.), not with + which turns $m into the integer 0.
