### ISSUE TITLE
What's the meaning Contacts notification

### ISSUE THREAD

**Issue by phpjoker** [mgp25/Chat-API#677]
Excuse me 
What is this notification?
```xml
rx  <notification from="xxx" id="12312" type="contacts" t="123">
rx     <remove jid="yyy"></remove>
rx  </notification>
rx  <notification from="xxx" id="12312" type="contacts" t="123">
rx     <add jid="yyy"></add>
rx  </notification>
rx  <notification from="xxx" id="12312" type="contacts" t="123">
rx     <update jid="yyy"></update>
rx  </notification>
```

Regards

**Comment by mgp25** [comment]
@phpjoker what your common sense think it is?

**Comment by matteocontrini** [comment]
It means that something has changed with the contact mentioned in the `jid` attribute.
More specifically:
* `add` requires you to mark a contact you synced previously as an actual WhatsApp user
* `remove` means that a user is not on WhatsApp anymore, so it becomes just a regular contact
* `update` means that something has changed on the user profile. You should:
 * reset the presence subscription (unsubscribe and subscribe again)
 * request the user status
 * request the user profile image
