### ISSUE TITLE
sendSetProfilePicture not working

### ISSUE THREAD

**Issue by albertosl01** [mgp25/Chat-API#678]
The file exampleFunctional.php does not run almost i comment the line 
```php
$w->sendSetProfilePicture("demo/venom.jpg");
```
The function alone does not work

**Comment by thetitoo** [comment]
Post your code please

**Comment by mgp25** [comment]
@albertosl01 post debug log, if you dont post debug log, this issue will be closed

Regards

**Comment by albertosl01** [comment]
My code
<?php
require_once '../src/whatsprot.class.php';
$username = '521**********';
$password = "*********************************";
$w = new WhatsProt($username, 0, "WhatsApp Messaging", true);
$w->connect();
$w->loginWithPassword($password);
$target = '521*********';
$w->sendSetProfilePicture("demo/venom.jpg");
$w->pollMessage();
$w->sendMessage($target,"Saludos");
$w->pollMessage();
$w->disconnect();
?>

Result
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="5215510953837">�n�5215510953837�L�꙽f!ޓ�:q҈V[w1430668680</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>���8�w�����܌���</challenge>

tx  <response>i��h\]�]2��[�"�p`�K'��{�4����n</response>

rx  <success t="1430668681" props="4" kind="free" status="active" creation="1429363300" expiration="1460899300">�j���_����/����i~</success>

tx  <presence name="0"></presence>

**Comment by albertosl01** [comment]
Result
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="5215510953837">�n�5215510953837�L�꙽f!ޓ�:q҈V[w1430668680</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>���8�w�����܌���</challenge>

tx  <response>i��h\]�]2��[�"�p`�K'��{�4����n</response>

rx  <success t="1430668681" props="4" kind="free" status="active" creation="1429363300" expiration="1460899300">�j���_����/����i~</success>

tx  <presence name="0"></presence>

**Comment by mgp25** [comment]
@albertosl01 you are using an outdated constructor, please check wiki for new one.

Post the error you are getting.

**Comment by albertosl01** [comment]
The new code
<?php
require_once '../src/whatsprot.class.php';
$username = '5215510953837';
$password = "X80bU1/IVMv+N9h1SBVwA4s8fng=";
$w = new WhatsProt($username, "Alberto", TRUE);
$w->connect();
$w->loginWithPassword($password);
$target = '5213331281205';
$w->sendSetProfilePicture("demo/venom.jpg");
$w->pollMessage();
$w->sendMessage($target,"Saludos");
$w->pollMessage();
$w->disconnect();
?>

Result

![aaa](https://cloud.githubusercontent.com/assets/12221943/7445831/9ae90d18-f188-11e4-80ed-12b47029bee5.jpg)

**Comment by mgp25** [comment]
@albertosl01 if you want, sent me an email, and later ill help you, im a bit busy

**Comment by mgp25** [comment]
@albertosl01 i have tried in my side and its working, make sure you have an updated code and the path are right + you have all dependencies installed

Regards
