### ISSUE TITLE
Call whatsapp.php in index.php

### ISSUE THREAD

**Issue by usinadeideia** [mgp25/Chat-API#681]
Good evening,

I am a student of PHP and chose the API to train, I would like someone to help me with some information, I would like whatsapp.php with -l option within a php, for example:

<? php
include ("whatsapp.php");
?>

Could anyone help me?

thank you very much

**Comment by mgp25** [comment]
Thats more a PHP question rather than a API one.

There are a lot of PHP forums where you can learn PHP. and if you have an API question, you will be welcome :)

Regards
