### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mmalbergier** [mgp25/Chat-API#682]
Is it possible that I receive the
< failure >< not-authorized >< /not-authorized >< / failure >
But, if I go again to the cell phone and register using the Whatsapp APP, it works?
If the phone gets blocked using the API, is it supposed that it shouldn't work in the phone?

**Comment by mgp25** [comment]
@mmalbergier are you using latest code?

Post here debug log

**Comment by mmalbergier** [comment]
Hi. I'm using the latest version from WhatsApiNet and trying to update with your latest changes.
But, I'm still getting the Not Authorized.

SENT: `<stream:features></stream:features>`
SENT: `<auth mechanism="WAUTH-2" user="XXXXXXXXXXX"></auth>`
RECVD: `<start from="s.whatsapp.net"></start>`
RECVD: `<stream:features></stream:features>`
RECVD: `<challenge>J??6:^?r??9??(</challenge>`
SENT: `<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">?+VP?????????9??M??/0K????"???</response>`
RECVD: `<failure>`
RECVD:   `<not-authorized></not-authorized>`
RECVD: `</failure>`

**Comment by mgp25** [comment]
@mmalbergier this is not .NET API, go to the proper repository
