### ISSUE TITLE
Sync Contact

### ISSUE THREAD

**Issue by neowolfman** [mgp25/Chat-API#683]
Good gentlemen day again ask for your help, I have not encontrdao information so annoying , <ul><li>how I synchronize my contacts, if I add a new number , just adding the number or do I sync the entire list ?</li><li>it is possible to recover whatsapp contact list from?</li> <li>and how can I remove contacts list ?</li><ul><br>

<b>beforehand, Thank you.-</b>

Atte
Cristian Torres

**Comment by mgp25** [comment]
Its explained in other issues + wiki


Regards

**Comment by matteocontrini** [comment]
Sync is only between your number and the server, in one direction. You can't pull the list of contacts.
To remove a contact from the synced contacts, you need to sync the whole collection again.
The sync modes are better explained [here](https://github.com/mgp25/Chat-API/issues/665#issuecomment-98364131), with details about when you should use them.
