### ISSUE TITLE
Getting last seen

### ISSUE THREAD

**Issue by mhamzas** [mgp25/Chat-API#684]
Hi,
I m not able to get last seen. Can anybody help me ?

**Comment by mgp25** [comment]
@mhamzas its explained in the wiki: https://github.com/mgp25/Chat-API/wiki

If you have any problem, post code and debug log

Regards

**Comment by mhamzas** [comment]
Hi,
Yes i am able to fetch but in a row format. What is the right method to
fetch it as LAST SEEN : $dst 25sec ago

**Comment by mhamzas** [comment]
Got it. Thanks
