### ISSUE TITLE
Error in login from time to time

### ISSUE THREAD

**Issue by moshere** [mgp25/Chat-API#689]
Hi,
I'm getting below error from time to time while running login. Can you explain how to resolve it?

Thank you in advance,
Moshe
```php
Code
#!/usr/bin/php
<?php


require_once('whatsapp_whatsapi_config.php');

function escapeJsonString($value) {
    # list from www.json.org: (\b backspace, \f formfeed)    
    $escapers =     array("\\",     "/",   "\"",  "\n",  "\r",  "\t", "\x08", "\x0c");
    $replacements = array("\\\\", "\\/", "\\\"", "\\n", "\\r", "\\t",  "\\f",  "\\b");
    $result = str_replace($escapers, $replacements, $value);
    return $result;
  }

$w = new WhatsProt($userPhone, $userName, $debug);
$w->Connect();
$w->LoginWithPassword($password);
 

    while ($w->pollMessage());
    $msgs = $w->GetMessages();
    foreach ($msgs as $m) {
		$from = str_replace("@s.whatsapp.net", "", $m->getAttribute("from"));
		$name = $m->getAttribute("notify");
		$time = $m->getAttribute("t");
		if($m->getChild("body"))
		{
        $messagebody = $m->getChild("body")->getData();
        $messagebody = escapeJsonString($messagebody);
		$from = escapeJsonString($from);
		$name = escapeJsonString($name);
		
		}
		echo "json: {\"from\":\"$from\", \"name\":\"$name\", \"time\":\"$time\", \"message\":\"$messagebody\"}\n";
		}

$w->Disconnect();



?>
```

Error

```
Response MIB search path: c:/usr/share/snmp/mibs
Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (SNMPv2-SMI): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)
PHP Warning:  socket_connect(): unable to connect [10060]: A connection attempt failed because the connected party did not properl
y respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\Chat-API-master\src\whatsprot.class.php on line 418
```

```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="972586898794">?♥??972586898794??????#☼q??QFTZ?^?1430829228</auth>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\Chat-API-master\src\whatsprot.c
lass.php:548
Stack trace:
#0 C:\Chat-API-master\src\whatsprot.class.php(2188): WhatsProt->pollMessage()
#1 C:\Chat-API-master\src\whatsprot.class.php(534): WhatsProt->doLogin()
#2 C:\Chat-API-master\src\whatsapp_whatsapi_recieve.php(17): WhatsProt->loginWithPassword('7Dk83zsARnWPtyc...')
#3 {main}
  thrown in C:\Chat-API-master\src\whatsprot.class.php on line 548
```

**Comment by mgp25** [comment]
Not related https://stackoverflow.com/questions/16467712/php-snmp-cannot-find-module

**Comment by moshere** [comment]
@mgp25 
I'm talking about this issue.
Is it related to MIB?

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\Chat-API-master\src\whatsprot.c
lass.php:548
Stack trace:
#0 C:\Chat-API-master\src\whatsprot.class.php(2188): WhatsProt->pollMessage()
#1 C:\Chat-API-master\src\whatsprot.class.php(534): WhatsProt->doLogin()
#2 C:\Chat-API-master\src\whatsapp_whatsapi_recieve.php(17): WhatsProt->loginWithPassword('7Dk83zsARnWPtyc...')
#3 {main}
  thrown in C:\Chat-API-master\src\whatsprot.class.php on line 548

**Comment by mgp25** [comment]
Quote what you post, so its easier to read

Yes

**Comment by moshere** [comment]
@mgp25 
Thank you. I implemented your recommendation but still I see errors
"Exit status 255
Response tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="972586898794">?o`?972586898794D??e?J?▬????H??G??Js1430831166</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in C:\Chat-API-master\src\whatsprot.class.php:2201
Stack trace:
#0 C:\Chat-API-master\src\whatsprot.class.php(534): WhatsProt->doLogin()
#1 C:\Chat-API-master\src\whatsapp_whatsapi_recieve.php(17): WhatsProt->loginWithPassword('7Dk83zsARnWPtyc...')
#2 {main}
  thrown in C:\Chat-API-master\src\whatsprot.class.php on line 2201

Exit status 255
Response tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

?972586898794.↕?V??4S?~↓f☼??,(↑☺?1430831185</auth>p?

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in C:\Chat-API-master\src\whatsprot.class.php:2201
Stack trace:
#0 C:\Chat-API-master\src\whatsprot.class.php(534): WhatsProt->doLogin()
#1 C:\Chat-API-master\src\whatsapp_whatsapi_recieve.php(17): WhatsProt->loginWithPassword('7Dk83zsARnWPtyc...')
#2 {main}
  thrown in C:\Chat-API-master\src\whatsprot.class.php on line 2201"

**Comment by mgp25** [comment]
@moshere read FAQ, wrong passwd

**Comment by moshere** [comment]
@mgp25 
It's can't be wrong password. I'm passing the same password on any login. I get error only from time to time
