### ISSUE TITLE
Chat-API + web.whatsapp

### ISSUE THREAD

**Issue by orsgah** [mgp25/Chat-API#690]
Is it possible to use chat api with web.whatsapp?

**Comment by mgp25** [comment]
No

**Comment by CODeRUS** [comment]
no, but it's possible to develop such integration, but only if you can very fast  write login token from qr scanner to web login formm :D

**Comment by orsgah** [comment]
QR code need only one time, if it used on the same browser.

**Comment by CODeRUS** [comment]
anyway, you need to write this code very fast and without mistakes, qr code is changing each one minute (if i remember correctly)

**Comment by valentinmari** [comment]
It's possible... Get the QR with your phone, send it via HTTP, process it with PHP.
The ugly part is the communication between web & Chat-API. If you guys can do that... I do the app to send the QR. :)

**Comment by mgp25** [comment]
@valentinmari I'm already doing it and i hope it will be working fine in a while but it won't be public.

Regards
