### ISSUE TITLE
How "Caption" attribute is being received with Image?

### ISSUE THREAD

**Issue by pablokerestezachi** [mgp25/Chat-API#692]

**Comment by mgp25** [comment]
@pablokerestezachi read thw wiki

**Comment by pablokerestezachi** [comment]
But if you snif xmlnode media, attribute caption is not present

Saludos,
Pablo

**Comment by 0xTryCatch** [comment]
Then the sender did not include a caption?

**Comment by pablokerestezachi** [comment]
Yes I do

Saludos,
Pablo

**Comment by CODeRUS** [comment]
show debug log to us :)
