### ISSUE TITLE
About whatsapp payment

### ISSUE THREAD

**Issue by jacoboliveira** [mgp25/Chat-API#693]
Hello my friends, I wonder if when running the command:
```php
    generatePaymentLink ($ number, $ sku)
```
the situation is like this, before I make this payment I first registered my phone with yowsup, after this I will make the payment, this already this payment associated with my phone? the system made in php whatsapi he already recognizes the new expiration time is in years?

**Comment by mgp25** [comment]
@jacoboliveira The payment is associated to the number, so can use your number in the device you want with any problem.

You can use the events to capture the expiration time (unix timestamp), you need to convert that to a date, pretty simple, like this:

```php
$timestamp=1333699439;
echo gmdate("Y-m-d\TH:i:s\Z", $timestamp);
```

Regards
