### ISSUE TITLE
how can i check the message sent or not ( is that any Event for that )

### ISSUE THREAD

**Issue by abdooweb** [mgp25/Chat-API#694]
Hello Every body
thanks for all your work and help

how can i check the message sent or not 
( is that any Event Or Function  for that ) ?

**Comment by Incher25** [comment]
If sending was successfull $w->sendMessage($target , $message) returns message id from WhatsApp server, so you can check is that value defined or not

**Comment by mgp25** [comment]
Read the wiki, everything itsin there

Regards

**Comment by abdooweb** [comment]
@mgp25  i read it carefully 
but i didn't found it
so i am asking
@Incher25 
i mean how by PHP to check this : message id

**Comment by Incher25** [comment]
For example
```php
$msgId = $w->sendMessage($target , $message);
if (isset($msgId)) {
      echo 'Message sent successful.';
}
```

**Comment by abdooweb** [comment]
thank you very very much @Incher25 
can i ask another question like this ?
how can i get the Hash of the image after sending it ?

**Comment by Incher25** [comment]
I never had to send images by Chat-API, so i don't know how about getting hash, but you can similary check the message id returned by sendMessageImage to make sure that image was sent successfully.

**Comment by abdooweb** [comment]
i check is it sending or not successfully
but i didn't catch the real whats app id for the message sent ?
can you help me

**Comment by mgp25** [comment]
@abdooweb read the wiki please, use the event system.

Regards

**Comment by Incher25** [comment]
what do you mean by "real whats app id"? In my example $msgId contains id that looks like <login_unixtimestamp>-<sequence_message_number>, for example: 1430907036-1, it returns by function createMsgId() (https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php). So i don't know about any other possible ids.

**Comment by abdooweb** [comment]
this is my code 

$w = new WhatsProt($Send_Channel_Number, $identity, "xxxx", true); 
$w->Connect();
$w->LoginWithPassword($password);

$msgId =$w->sendMessage($target , $message);
if (isset($msgId)) {
      echo "Message sent successful.  with id : (($msgId)) :)";
}else{?>Not Send !!!!!!!!!<? }

this current code show me " 1 " not an ip of the message 

how can i use the : createMsgId()  Function ?
to appear the real id

**Comment by Incher25** [comment]
It looks strangely, because my code
``` php
...
 $w->Connect();
 $w->loginWithPassword($password);
 $messageId = $w->sendMessage($target , $message);
 if ($messageId) {
         echo "send success: $message";
  }
...
```
returns like  "send success: 1430981116-2" if it was sent.
