### ISSUE TITLE
unable to register

### ISSUE THREAD

**Issue by suraj-mahajan** [mgp25/Chat-API#696]
I can revive registration code , but $w->codeRegister('456123'); this function not returning any object, It showing blank screen

**Comment by CODeRUS** [comment]
you need to show your debug log if you want to get help

**Comment by suraj-mahajan** [comment]
Dear sir, i am not a php developer. can you please how to do it exactly ?
thanks in advance :)

**Comment by CODeRUS** [comment]
Try to check this great wiki please: https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#number-registration

**Comment by abdooweb** [comment]
@suraj-mahajan  
you are right
this page not clear for me to
it need more explain
