### ISSUE TITLE
Parsing Emoji

### ISSUE THREAD

**Issue by hansrouge** [mgp25/Chat-API#697]
Hi there,

a few commits back, you removed the "parseMessageForEmojis"-function (.
So, how do you parse them now?
Sending an emoji, i.e. "##1F454##", won't change it to the "xF0\x9F\x91\x94" anymore.

I couldn't find any other change.

Receiving emojis still works fine.

Thanks!

**Comment by CODeRUS** [comment]
you should send "\xF0\x9F\x91\x94"

**Comment by hansrouge** [comment]
I know what I should send.

I want to know where you change in whatsapp.php "##1F454##" to "xF0\x9F\x91\x94".
You dont call any function in as far as I can see.

Why did you delete the "parseMessageForEmojis"-function and what did you replace it with?

**Comment by matteocontrini** [comment]
To make thinkgs simpler: when composing your message, use a PHP library to convert the emoji name to the Unicode

**Comment by mgp25** [comment]
Reference: https://github.com/mgp25/Chat-API/wiki/Frequently-asked-questions#how-can-i-send-emojis

**Comment by luciano-work** [comment]
Please , how I do convert this code: "## 1F454 ##" for this code " "xF0\x9F\x91\x94"
in "example/whatsapp.php" dont work any more :(

**Comment by mgp25** [comment]
@luciano-work check FAQ

**Comment by luciano-work** [comment]
I do not know how to do :(

**Comment by arth1992** [comment]
I tried all solution. But still i am unable to parse emoji @mgp25
