### ISSUE TITLE
limit on requesting LAST SEEN ?

### ISSUE THREAD

**Issue by mhamzas** [mgp25/Chat-API#698]
Hi,
Is there any limit on requesting last seen. Cause now i am getting 

    <iq from="xx@s.whatsapp.net" id="lastseen-xx-26" type="error">
      <error code="404" text="item-not-found"></error>
    </iq>

**Comment by CODeRUS** [comment]
it means user is online :D

**Comment by mhamzas** [comment]
I tried checking my number and i was offline..

**Comment by CODeRUS** [comment]
then lastseen bug on server or privacy settings. remember if you have lastseen privacy on this number you can't also see lastseen of other people.

**Comment by mhamzas** [comment]
I am using this method

     $numbers=array('923453267559','923142594611','971566522007','923162362639','923452431951','971508672231');
			foreach($numbers as $a):
				echo $a.": ";
				$this->whatsprot->sendGetRequestLastSeen($a);
				$this->whatsprot->pollMessage();
				echo "<br>";
			endforeach;


And it should give me

    923453267559 : Last seen 0 days 0 hours 23minutes ago
    92xxxxxxxxxxx: Last seen 0 days 0 hours 23minutes ago
    92xxxxxxxxxxx: Last seen 0 days 0 hours 23minutes ago
    .....

**Comment by mhamzas** [comment]
I do not have privacy enabled.
Let me tell you the complete history.
It was working perfectly but suddenly it started giving me the 404 error.
but i was able to sync them.

**Comment by CODeRUS** [comment]
reset your privacy settings then

**Comment by mhamzas** [comment]
And what about the other numbers?

**Comment by mhamzas** [comment]
Oh.. see its working now but sometimes it shows error. I thought may be
there is some limit

http://pokit.org/get/img/0adb176cb6bad1a81b58b21299fe8b80.jpg

**Comment by matteocontrini** [comment]
You probably shouldn't request last seen for many users in the same moment, because that's not quite a regular usage. Use presence subscription if you need to monitor *when* many users are online or offline.

**Comment by mhamzas** [comment]
But presence subscriptions shows me just
    tx  <presence name="M Hamza"></presence>
    tx  <presence type="subscribe" to="923453267559@s.whatsapp.net
"></presence>

**Comment by matteocontrini** [comment]
Presence subscription will notify you when the contact goes online or offline.

**Comment by mhamzas** [comment]
But its not..
I am using it as described in wiki
    $w->sendPresenceSubscription('923453267559');
and in response i am getting
    tx  <presence name="M Hamza"></presence>
    tx  <presence type="subscribe" to="923453267559@s.whatsapp.net
"></presence>

**Comment by mgp25** [comment]
@mhamzas 

this is yuor presence, when you are available in WhatsApp, showing your nickname:

```xml
    tx  <presence name="M Hamza"></presence>
```

When you subscribe to someone you send this:
```xml
 tx  <presence type="subscribe" to="923453267559@s.whatsapp.net
"></presence>
```

You dont receive any result node, you will receive the user acitivity you have subscribed, like when he comes online.

Regards

**Comment by mhamzas** [comment]
tx  <presence name="M Hamza"></presence> 
M Hamza is a nickname i set for the API its not user's nickname.

**Comment by matteocontrini** [comment]
You will get notified WHEN the user is online or offline. I said that three times...

**Comment by mhamzas** [comment]
But its not.. I am currently online but its still showing me the same lines.

**Comment by mhamzas** [comment]
I apologize but may be it is not clear to me or i am expecting more clear result.

**Comment by mgp25** [comment]
@mhamzas do you read what we are writing? and do not doble comment, this is not a forum, you can edit your comment.

Look... this is your own presence, your and only yours:

```xml
 tx  <presence name="M Hamza"></presence> 
```

When you are subscribed to X user you will ONLY receive the following nodes when the user goes online/offline:

```xml
rx <presence from="X@s.whatsapp.net"></presence>

rx <presence from="X@s.whatsapp.net" type="unavailable" last="deny"></presence>
```

**Comment by mhamzas** [comment]
okay i got it.
just one last question.
Will i get the following response with same subscription function or there
is another function ?
    rx <presence from="X@s.whatsapp.net" type="unavailable"
last="deny"></presence>

**Comment by matteocontrini** [comment]
I don't get what you mean.
The events fired are these:

```php
onPresenceAvailable( $mynumber, $from ) 
onPresenceUnavailable( $mynumber, $from, $last )
```

**Comment by mhamzas** [comment]
Thanks for the help. I got it working
but now after subscribing 8-9 numbers, now i am not getting any response?

    tx  <presence type="subscribe" to="923453267559@s.whatsapp.net"></presence>
    tx  <presence type="subscribe" to="923142594611@s.whatsapp.net"></presence>
