### ISSUE TITLE
Connection Exception after some seconds

### ISSUE THREAD

**Issue by jueroesc** [mgp25/Chat-API#699]
Hi, 

After nearly one minute running, i got the following error:
 
```
Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/aco-vorstand/members/inc/whatsapi/whatsprot.class.php:548
Stack trace:
#0 /var/lib/scripts/whatsappinbox.php(14): WhatsProt->pollMessage()
#1 {main}
 thrown in /home/......./whatsapi/whatsprot.class.php on line 548
  ```

**Comment by mgp25** [comment]
@jueroesc post debug log

**Comment by jueroesc** [comment]
ehm okay.. good point...


rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>


and so i think i know a script that makes an include to a script that opens a new connection :-(

I will have to manage everything by a database - incoming and outgoing messages and that would fix that error...

Thanks
