### ISSUE TITLE
How to correctly use sendPresenceSubscription($target) / sendPresenceUnsubscription($target);

### ISSUE THREAD

**Issue by hansrouge** [mgp25/Chat-API#700]
Hi,

I am not sure about how to use these two functions, especially the Unsubscribe-function.

At the moment I always call sendPresenceSubscription() right before I send a msg to a user. I never call sendPresenceUnsubscription();.

Is it more WhatsApp-Like if I would send sendPresenceSubscription() just once each time I log in? Should I do a loop around all my contacts to send the PresenceSubscription?

Do I need sendPresenceUnsubscription at all?

Wiki doesn't say much about these functions. 

Thanks!

**Comment by matteocontrini** [comment]
Enable presence subscription when you're about to interact with a contact. Unsubscribe from presence on the next login and when you get a "contact update" notification. You can subscribe again after that.

**Comment by hansrouge** [comment]
@matteocontrini @mgp25  
Interact = Just send a normal message. Or do I have to do this when i am sending a group msg?

"Unsubscribe from presence on the next login"
Am I not automatically unsubscribed when I disconnect from whatsapp?

"contact update" notification - Do you have an example?

Thanks!

**Comment by matteocontrini** [comment]
Interact means the equivalent of entering a chat in the mobile application.
Subscriptions are persistent between sessions, you must unsubscribe manually when you login again.
[Contact notifications](https://github.com/mgp25/Chat-API/issues/677). Events have been added after that.

**Comment by hansrouge** [comment]
Thank you!
Now I think I understand it :)
