### ISSUE TITLE
Illegal?

### ISSUE THREAD

**Issue by GildedHonour** [mgp25/Chat-API#702]
Isn't it illegal? Check this https://github.com/venomous0x/WhatsAPI out.
I'm asking because I'm going to port it on haskell.

**Comment by mgp25** [comment]
Port it then.

Regards

**Comment by GildedHonour** [comment]
Isn't it illegal?

**Comment by CODeRUS** [comment]
Just do not put your real name inside your work, do not use emails associated with any facebook services and you in safety :)

**Comment by mgp25** [comment]
@GildedHonour and if you want to be 100% anonymous, browse through a VPN or Tor Network

**Comment by GildedHonour** [comment]
And what's the reason and necessity of creating a free library with MIT license at github in a **public repository** on one hand and striving to be anonymous of on the other?

**Comment by CODeRUS** [comment]
To break the proprietary word.

**Comment by GildedHonour** [comment]
That's a bunk.
