### ISSUE TITLE
Removing a group participants returning 404 item-not-found error

### ISSUE THREAD

**Issue by rayidi** [mgp25/Chat-API#705]
Hello,

I'm working on a grouping application where, I'm trying to remove few members from the group which is returning me the 404 error.

`tx  <iq id="remove_group_participants_-1431085261-1" type="set" xmlns="w:g2" to="917506935751-1430997543@g.us">
tx    <remove>
tx      <participant jid="917506935751@s.whatsapp.net"></participant>
tx      <participant jid="919810108206@s.whatsapp.net"></participant>
tx    </remove>
tx  </iq>`

`rx  <iq from="917506935751-1430997543@g.us" id="remove_group_participants_-1431085261-1" type="error">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>`

Can you please help me what was the problem?

**Comment by mgp25** [comment]
@rayidi 

1- Your are using a outdated code
2- then the user is not in the group

**Comment by matteocontrini** [comment]
Clearly because that contact is not in the group
