### ISSUE TITLE
Use of PSR-4's namespaces standards

### ISSUE THREAD

**Issue by Arrogance** [mgp25/Chat-API#708]
Hi,

I'm going to fork and setup ChatAPI namespaces in all around the project, to maintain a consistency when using it inside frameworks, like Symfony.

I'm also preparing a Symfony2 bundle, to act as a bridge between the lib and symfony, that's one of the reasons why I'll do the mentioned change.

**Comment by mgp25** [comment]
When finished send Pull Request, i close this issue.

Regards

**Comment by VMosoti** [comment]
@Arrogance was this ever done?

**Comment by Arrogance** [comment]
Yeah @VMosoti but I need to add the last months of updates of Chat-API. There is a functional version right now, but not suitable to use in prod.

**Comment by joostvandermeijden** [comment]
What is the status on this one? I would really love to see proper namespaces :)
