### ISSUE TITLE
sendGroupsChatEnd is not available in last version ?

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#710]
Hello i am trying to remove a group that i am admin in and i try to use this function sendGroupsChatEnd but it seems is not available so how we can remove groups ?

Note i have searched in the wiki but i have not found any related infos !
Best ! Regards !

**Comment by mgp25** [comment]
`public function sendGroupsLeave($gjids)`

**Comment by MoudiZd** [comment]
I know this function ,but as i know this function will just leave group ! What if i want to remove the group at all ! Did this feature still available or not ?

**Comment by mgp25** [comment]
Its the same

**Comment by MoudiZd** [comment]
Thank you ! Regards !
