### ISSUE TITLE
Nickname Issue

### ISSUE THREAD

**Issue by harishannam** [mgp25/Chat-API#711]
I have used a nickname while registering and while sending message. But still the recipient gets my Number instead of nickname. Any idea why?

<?php
require_once('../src/whatsprot.class.php');
$debug = true;

//echo "\n\nUsername (country code + number without + or 00): ";
$username = "919xx65xx212";
$nickname = "MyNickName";
$password = "";
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

$target = '9198xx6xx882'; // The number of the person you are sending the message
$message = 'Hi! this is a test message';

$w->sendMessage($target , $message);

**Comment by CODeRUS** [comment]
use sendAvailableForChat function

**Comment by harishannam** [comment]
@CODeRUS  Used sendAvailableForChat before sendMessage function. But still it sends my number instead of nick

**Comment by mgp25** [comment]
@harishannam post debug log
