### ISSUE TITLE
List id and create list explanation

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#712]
hello ! As i see that when i want to delete a broadcast i must send its id ! Okay !
But i searched all wiki and all class function i could not find a function that create a list to get the list id and all i found is send brodcast message function which will send a message to a set of numbers at fly (not from a list that we provide its id)

So what is this behaviour and where we can get lists ids and how to create a list like the list which create in the client whatsapp application !

As i can note that in the official application you can create as many lists you want in condition that list members be synced with you (added your number to their address book)

So please more explanation as i don't find any related info in wiki nor in issues !

Regards !

**Comment by mgp25** [comment]
its in the wiki, `sendGetBroadcastLists()`, next time search further

**Comment by MoudiZd** [comment]
as i see that the sendGetBroadcastLists() will list my lists but my question is how i create a list .

Note the wiki doesn't have enough infos about broadcasts .

Regards !

**Comment by CODeRUS** [comment]
Broadcast list is creating automatically on server when you sending broadcast message. Not sure how it handled in Chat-API and if you can reuse it again or not.

**Comment by MoudiZd** [comment]
so we need more infos about managing lists in the Chat-Api

Or managing lists is not available via the api ? And just we can create a list from the whatsapp official client ?

Regards !

**Comment by mgp25** [comment]
What are you using the API for?

**Comment by CODeRUS** [comment]
Broadcast list is creating automatically on server when you sending broadcast message. Broadcasts are not managing like groups. Server only keeping list of participants and broadcast name after sending broadcast using same broadcast id.

**Comment by MoudiZd** [comment]
i am just trying to understand how i can manage lists exactly as the whatsapp official client does . And as you ask what i am using the api for i told you that i use it for legal purposes to send event to local company employees but i want to manage list in a way that enginners in a list and technicals in another list and workers in a list and to be able to manage these lists from the api

So did i need to create lists manually on my device ? As CideRus say that the list is automatically created on server so how to identify each part of employees (engineers-technicals-workers)

by another word when i send a broadcast to a set of numbers how to name this list in my server by the name of the type of work to identify lists in next time i would sent to a list not to another !

Hope my question is fairly clear ! And sorry for bad english :)

Regards !

**Comment by hansrouge** [comment]
Why dont you create a new list each time you send a broadcast?
I dont think it is necessary to manage old lists.

You can just delete the old lists with sendGetBroadcastLists and sendDeleteBroadcastLists.
