### ISSUE TITLE
Error when registration failed

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/Chat-API#713]
Hello ! When i try to register a number with an invalid code this error have place :

Undefined property: stdClass::$retry_after in <b>whatsprot.class.php</b> on line <b>251</b>

as i can see that the error is occured from this callback onCodeRegisterFailed when the response object doesn't contain the retry after property

Regards !

**Comment by mgp25** [comment]
That error its because of using xampp. Try running it in a webserver or shell/terminal.

By the way `retry_after` you will need to wait
