### ISSUE TITLE
Presence Subscription for more than 3 at a time?

### ISSUE THREAD

**Issue by mhamzas** [mgp25/Chat-API#714]
Hi,
I tried the following code but its not working for more than 3
```php
   			$w->SendPresenceSubscription('923453267559');
			$w->SendPresenceSubscription('923142594611');
			$w->SendPresenceSubscription('971566522007');
			$w->SendPresenceSubscription('923162362639');
			$w->SendPresenceSubscription('923452431951');
```

**Comment by mgp25** [comment]
@mhamzas debug log?

**Comment by mhamzas** [comment]
Now not working for 2 too.

    tx  <stream:features>
    tx    <readreceipts></readreceipts>
    tx    <groups_v2></groups_v2>
    tx    <privacy></privacy>
    tx    <presence></presence>
    tx  </stream:features>

    tx  <auth mechanism="WAUTH-2" user="923468224040">«“¢ß923468224040³áÉ’¼;
    rx  <start from="s.whatsapp.net"></start>

    rx  <stream:features></stream:features>

    rx  <challenge>ý³ÂcPN9î*h Ö{ø#Z¥ôƒ</challenge>

    tx  <response>lã¸¨Ü<¤ãâÿ‘0Ž\¡ßdùÈÕ¦kP¿¤½òÙªÕ</response>

    rx  <success t="1431432845" props="4" kind="free" status="active" creation="1430756890"     expiration="1462292890">£ÌßÓÜå+@£I‡bRÌ</success>

    tx  <presence name="System"></presence>

    tx  <presence type="subscribe" to="923453267559@s.whatsapp.net"></presence>

    tx  <presence type="subscribe" to="923142594611@s.whatsapp.net"></presence>

**Comment by mgp25** [comment]
@mhamzas remember to poll messages after that do this...

```php
            $w->SendPresenceSubscription('923453267559');
            $w->SendPresenceSubscription('923142594611');
            $w->SendPresenceSubscription('971566522007');
            $w->SendPresenceSubscription('923162362639');
            $w->SendPresenceSubscription('923452431951');
            $w->pollMessage();
            $w->pollMessage();
            $w->pollMessage();
```

**Comment by mhamzas** [comment]
Okay let me try

**Comment by mhamzas** [comment]
I am using this method

		    $numbers=array('923453267559','923142594611','971566522007','923162362639','923452431951','971508672231');


		foreach($numbers as $a){
			$this->whatsprot->SendPresenceSubscription($a);
			$this->whatsprot->pollMessage();
		}

But in result i am just getting response from 3 only


    tx  <stream:features>
    tx    <readreceipts></readreceipts>
    tx    <groups_v2></groups_v2>
    tx    <privacy></privacy>
    tx    <presence></presence>
    tx  </stream:features>

    tx  <auth mechanism="WAUTH-2" user="923468224040">Þÿ©‹923468224040wŒØŒfàè{:.†>¬Y¿}1431433661</auth>

    rx  <start from="s.whatsapp.net"></start>

    rx  <stream:features></stream:features>

    rx  <challenge>k)€Æët¸Œx2³(+šçÃNM</challenge>

    tx  <response>·©^¯no™ÏLÈ`õ¬îv÷ÂÁ%Ôud“7Ž]5ÐžŸ|</response>

    rx  <success t="1431433662" props="4" kind="free" status="active" creation="1430756890" expiration="1462292890">pùhüÁ©ÜðV¢Ê—áï˜“</success>

    tx  <presence name="System"></presence>

    tx  <presence type="subscribe" to="923453267559@s.whatsapp.net"></presence>

    rx  <ib from="s.whatsapp.net">
    rx    <offline count="0"></offline>
    rx  </ib>

    tx  <presence type="subscribe" to="923142594611@s.whatsapp.net"></presence>

    rx  <presence from="923468224040@s.whatsapp.net"></presence>

    tx  <presence type="subscribe" to="971566522007@s.whatsapp.net"></presence>

    rx  <presence from="923453267559@s.whatsapp.net" type="unavailable" last="1431406563"></presence>

    tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="1431433662-1">
    tx    <status>
    tx      <user jid="923453267559@s.whatsapp.net"></user>
    tx    </status>
    tx  </iq>

    tx  <presence type="subscribe" to="923162362639@s.whatsapp.net"></presence>

    rx  <presence from="971566522007@s.whatsapp.net" type="unavailable" last="1431432947"></presence>

    tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="1431433662-2">
    tx    <status>
    tx      <user jid="971566522007@s.whatsapp.net"></user>
    tx    </status>
    tx  </iq>


    tx  <presence type="subscribe" to="923452431951@s.whatsapp.net"></presence>

    rx  <presence from="923142594611@s.whatsapp.net" type="unavailable" last="1431262787"></presence>

    tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="1431433662-3">
    tx    <status>
    tx      <user jid="923142594611@s.whatsapp.net"></user>
    tx    </status>
    tx  </iq>


    tx  <presence type="subscribe" to="971508672231@s.whatsapp.net"></presence>

    rx  <iq from="s.whatsapp.net" id="1431433662-1" type="result">
    rx    <status>
    rx      <user jid="923453267559@s.whatsapp.net" t="1430912558">Test</user>
    rx    </status>
    rx  </iq>

**Comment by mgp25** [comment]
@mhamzas its working

**Comment by mhamzas** [comment]
but not for 6.. its showing only 3

**Comment by mhamzas** [comment]
Anybody please
