### ISSUE TITLE
Error sending media, image

### ISSUE THREAD

**Issue by jfrancinaldo** [mgp25/Chat-API#719]
I send image takes a long time after I have that answer, but the image does not send, moreover can not read the error has coding error;
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="558487056005"> }}558487056005&©+Ý"Ù>HÌ‘EÖ/ô1¼Ï;Ð1431567282</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>WIð´U¹yñ×ˆèäï3>ÏðÀ-</challenge>

tx  <response>ât"„ð"1)®Ÿ4yèÜH]ÓA˜Bù°ˆ­šº.Ù±1ö</response>

rx  <success t="1431567282" props="4" kind="free" status="active" creation="1431561169" expiration="1463097169">T©Å>`‚‰Ïí!0ñÛ¥`Ì“&K(</success>

tx  <presence name="0"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

tx  <iq id="1431567282-1" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="KyBD+OIucSEAts2qx8nXTk5fMDcqQwu3JePDnfcObOg=" type="video" size="50271"></media>
tx  </iq>

rx  <presence from="558487056005@s.whatsapp.net"></presence>

rx  <presence from="558499438096@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" id="1431567282-1" type="result">
rx    <media url="https://mmi637.whatsapp.net/u/M8UCxelbv0rxrUyE1FMveEnCmQUABRYArgETVQ/Ahg1JHcsNhbHXDJxbx6SIYTYJX3UKfqASTkJzvK9Fnj2" ip="184.173.195.59"></media>
rx  </iq>

rx  <presence from="558499438096@s.whatsapp.net" type="unavailable" last="1431567291"></presence>
```

**Comment by 0xTryCatch** [comment]
This debug log shows nothing. Post a proper debug log containing the error and use markdown

**Comment by mgp25** [comment]
@jfrancinaldo remember to quote the output.

As you can see in the debug, the media was successfully uploaded, but there is no message node, so you didn't send anything.

Post your full code here

Regards

**Comment by jfrancinaldo** [comment]
<?php
require 'src/whatsprot.class.php';

$username = "558487056005"; //Mobile Phone prefixed with country code so for india it will be 91xxxxxxxx
$password = "bXFryGs6vsIvleTkdYJexiBBe1g=";

$w = new WhatsProt($username, 0, "SMSBR", false); //Name your application by replacing "WhatsApp Messaging"
$w->connect();
$w->loginWithPassword($password);

$target = $_REQUEST["cel"]; //Target Phone,reciever phone

//==========================
//Enviando Mensagem de Multimidia
//==========================
$caption = "Caption da imagem";
$pathToVideo = "pictures/smsbr.gif"; // This could be url or path to video.
$fhash = base64_encode(hash_file("sha256", $pathToVideo, true));
$fsize = 50271;

$w->sendMessageVideo($target, $pathToVideo);
$w->pollMessage();

// If you have already the video size and hash, you can send it without re-uploading it to whatsapp servers
$w->sendMessageVideo($target, $filepath, false, $fsize, $fhash, $caption);
$w->pollMessage();
?>

**Comment by mgp25** [comment]
@jfrancinaldo we dont support spamming / marketing
