### ISSUE TITLE
Synicng more than 3000 users

### ISSUE THREAD

**Issue by mhamzas** [mgp25/Chat-API#721]
Hi,
I am getting the following error while syncing more than 3000 users. 

    rx  <stream:error>
    rx    <xml-not-well-formed></xml-not-well-formed>
    rx  </stream:error>

I've also find a similar issue but don't know how to implement the solution. 
https://github.com/mgp25/Chat-API-.NET/issues/6#issuecomment-78305770

**Comment by mgp25** [comment]
no no no
invalid

**Comment by mhamzas** [comment]
What is not valid ? more than 3000 users or solution ?

**Comment by mgp25** [comment]
@mhamzas can i ask you why are you going to sync 3000 users and why?

**Comment by mhamzas** [comment]
I am making a solution where customers can see how many his contacts are available on whatsapp.
So if customer have more than 3000 contacts, i was testing for it.

**Comment by mhamzas** [comment]
There is an old issue https://github.com/venomous0x/WhatsAPI/issues/126
But haven't find any solution.

**Comment by mgp25** [comment]
@mhamzas use API only for personal purposes

**Comment by mhamzas** [comment]
Okay, but apart from that. Lets says if i am having more than 4000 contacts on my phone.(As i've 4250) So i am not able to sync them ?
Please suggest your solution for others too.
Thanks

**Comment by mgp25** [comment]
Jokes apart, i dont think you are talking with 4k contacts

**Comment by mhamzas** [comment]
okay but i cannot do anything if you don't think. Lets talk about the solution instead of other things.
