### ISSUE TITLE
i Can't resive Message

### ISSUE THREAD

**Issue by bloftd** [mgp25/Chat-API#722]
am using  this api for along time now i have a strange problem i can sent message but i can't resive, my code is updated.
my scrip stop after 50s and display a error on pull message
 $w->pollMessage();
$messages = $w->getMessages();

![seleccion_080](https://cloud.githubusercontent.com/assets/4915408/7634416/d0fc4430-fa28-11e4-8cf5-0abf109bd7ba.png)

**Comment by CODeRUS** [comment]
post full debug log

**Comment by bloftd** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="59170778155">,ŽÉ|59170778155ÍÃJXÝke@ŽÃ aeÂÑ;û1431616610</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge> X¹¹f0‘dõƒœEŽ½úÖé§</challenge>

tx  <response>‘@œ>µb-Ú¬Ò¼öšÅú ìí@¥[ŠÞ6úæ ¿+¸†I b</response>

rx  <success t="1431616611" props="4" kind="free" status="active" creation="1418832241" expiration="1450368241">ÈŸ~mÏýOõúØ¨»¨EFs</success>

tx  <presence name="AutoSia"></presence>

tx  <iq id="1431616611-1" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-38" retry="4" offline="4" type="read" t="1430973615"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-38" type="read" t="1431616611"></ack>

[Start] rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-44" offline="0" type="read" t="1430973629"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-44" type="read" t="1431616611"></ack>

**Comment by CODeRUS** [comment]
it's not full. post log until moment you got an error.

**Comment by bloftd** [comment]
my script run on terminal
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

A�59170778155�s���-�(��*b�Rsl�1431618066</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>
:�����2�Z�u</challenge>

tx  <response>��K<����2Vp�~|��ׂwTH����Ic^T�U��F</response>

rx  <success t="1431618067" props="4" kind="free" status="active" creation="1418832241" expiration="1450368241">�Ԧ{&�#�Vy���9�k��</success>

tx  <presence name="AutoSia"></presence>

tx  <iq id="1431618067-1" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-44" retry="2" offline="2" type="read" t="1430973629"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-44" type="read" t="1431618067"></ack>

[Start]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-62" offline="0" type="read" t="1430973690"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-62" type="read" t="1431618067"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-69" offline="0" type="read" t="1430973711"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-69" type="read" t="1431618071"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-74" offline="0" type="read" t="1430973728"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-74" type="read" t="1431618075"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-82" offline="0" type="read" t="1430973747"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-82" type="read" t="1431618077"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-91" offline="0" type="read" t="1430973772"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-91" type="read" t="1431618079"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430973524-96" offline="0" type="read" t="1430973785"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430973524-96" type="read" t="1431618082"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430975957-11" offline="0" type="read" t="1430975978"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430975957-11" type="read" t="1431618087"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430975957-12" offline="0" type="read" t="1430975983"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430975957-12" type="read" t="1431618089"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <receipt from="59172218868@s.whatsapp.net" id="1430975957-13" offline="0" type="read" t="1430975985"></receipt>

tx  <ack to="59172218868@s.whatsapp.net" id="1430975957-13" type="read" t="1431618090"></ack>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <presence from="59170778155@s.whatsapp.net"></presence>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <iq from="s.whatsapp.net" id="1431618067-1" type="result">
rx    <props version="4">
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="qr" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="audio" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="image_max_edge" value="1280"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="max_participants" value="101"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx    </props>
rx  </iq>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
rx  <stream:error>
rx    <ack></ack>
rx  </stream:error>

[termino get msg]
[Termino Envio respuesta]
[Conectado a internet]
[start get msg]
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/fb/hserver/wptm/src/whatsprot.class.php:548
Stack trace:
#0 /home/fb/hserver/wptm/start.php(39): WhatsProt->pollMessage()
#1 {main}
  thrown in /home/fb/hserver/wptm/src/whatsprot.class.php on line 548
fb@fb-AOD255E:~/hserver/wptm$

**Comment by mgp25** [comment]
Ack error, it should be working, try latest release.

Regards

**Comment by bloftd** [comment]
@CODeRUS  @mgp25 Gracias.
