### ISSUE TITLE
error "TypeError: data is null"

### ISSUE THREAD

**Issue by JenishWorldwide** [mgp25/Chat-API#724]
in firebug : console comes this error "TypeError: data is null"
Chat-API-master/examples/whatsapp.php line number: 499

when i choose sender then comes issue of "please wait" till i not reload the page.

please help to solve this issue.

**Comment by mgp25** [comment]
There is nothing in line 499, please post error or stack trace from your web browser

**Comment by JenishWorldwide** [comment]
private function connectToWhatsApp()
    {
        if (isset($this->wa)) {
            $this->wa->connect();
            $this->wa->loginWithPassword($this->password);
            return true;
        }

        return false;
    }

**Comment by mgp25** [comment]
@JenishWorldwide can you please post stacktrace error?

**Comment by JenishWorldwide** [comment]
![capture](https://cloud.githubusercontent.com/assets/12469215/7665462/b7d65834-fbd5-11e4-81b8-0aa2a5553cf8.JPG)

**Comment by JenishWorldwide** [comment]
issue is in above image..

**Comment by jesperveldhuizen** [comment]
This is a JS error... not API related.

**Comment by JenishWorldwide** [comment]
okay

**Comment by JenishWorldwide** [comment]
$.ajax({
							type: "POST",
							url: "<?php echo $_SERVER['PHP_SELF'] ?>",
							cache: false,
							data: formData,
							dataType: "xml",
							timeout: 45000,
							success: onSuccess,
							error: onError,
							//beforeSend: function(jqXHR, settings) {
							//},
							complete: function() {
								$.unblockUI();
							}
						});

**Comment by JenishWorldwide** [comment]
now come following error
"Error: There was an error with the AJAX request. XML/Json format is bad."

**Comment by jesperveldhuizen** [comment]
Says it all doesn't it?

**Comment by mgp25** [comment]
Ill check eventually. Use exampleFunctional.php meanwhile

Regards

**Comment by JenishWorldwide** [comment]
here is required any database configuration in chat-whatsapp-api?

**Comment by mgp25** [comment]
no
