### ISSUE TITLE
Registration fails, token missing

### ISSUE THREAD

**Issue by everyusernameistaken123** [mgp25/Chat-API#725]
Hi,

I am new to this API and I am already in troubles during the registration process.
If I follow the "exampleRegister.php" I get the following debug-output:

Array
(
    [in] => [mynumber]
    [cc] => 43
    [id] => ���c�
	�g,o���h���]
    [lg] => de
    [lc] => AT
    [sim_mcc] => 232
    [sim_mnc] => 000
    [method] => sms
    [token] => 222e2f20e0bcd5d8de361660ae35d33b
)
stdClass Object
(
    [status] => fail
    [reason] => missing_param
    [param] => token
)

Am I seeing right? Whatsapp is missing the token? but its given above?
Please help me!

**Comment by mgp25** [comment]
@everyusernameistaken123 contact me via mail, im going to help you

**Comment by mgp25** [comment]
It's working, if you need help, contact me via mail

```
Array
(
    [in] => *********
    [cc] => 34
    [id] => ????m&?&??)???;{?m
    [lg] => es
    [lc] => ES
    [sim_mcc] => 214
    [sim_mnc] => 000
    [method] => sms
    [token] => f2048a604b3102e4c4eabddb0f87a18f
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
```

Regards

**Comment by swapnil91991** [comment]
I m having same problem listed as above can you please help me out

**Comment by swapnil91991** [comment]
What is STDIN ?

**Comment by swapnil91991** [comment]
[status] => fail [reason] => security_code [guess_wait] => 0 [guesses_left] => 15 [email_wait] => 0 [wipe_wait] => 599383 [wipe_type] => offline [wipe_token] => 1549659676 [server_time] => 1549659676 [min_poll] => 5 ) An error occurred registering the registration code from WhatsApp. Reason: security_code
