### ISSUE TITLE
How get participant of a group

### ISSUE THREAD

**Issue by amin0256** [mgp25/Chat-API#729]
Hi,
I have a group id and i want to get participant of the group.
I want to use sendGetGroupV2Info but can't access to the result of this function.
sorry my bad language and please help me.
thanks.

**Comment by everyusernameistaken123** [comment]
Take a look at the source-code, whatsprot.class.php line 4022.
There is an Event "onGetGroupV2Info". I used it yesterday, worked fine.
Can someone please update the list of all events? ( https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#list-of-all-events )

**Comment by mgp25** [comment]
Added

**Comment by amin0256** [comment]
Thanks for Answering.
this is my code: 
$w->eventManager()->bind('onGetGroups', 'GetGroups');
$w->eventManager()->bind('onGetGroupV2Info', 'getGroupPart');
function getGroupPart($r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8){
	var_dump($r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8);
}
function GetGroups($result,$res2){
	global $w;
	foreach($res2 as $value){
		var_dump($value);
		$w->sendGetGroupV2Info($value['id']);
		echo '//'.PHP_EOL.PHP_EOL.PHP_EOL;
	}
}
$w->sendGetGroups(true);
die();
and I change the class: 
    public function sendGetGroups($type = false)
    {
        $this->sendGetGroupsFiltered($type ? "owning" : "participating");
    }
this code work but don't work onGetGroupV2Info function and function dont dump any data.
thanks.
