### ISSUE TITLE
Long length messages aren't read 

### ISSUE THREAD

**Issue by aris0** [mgp25/Chat-API#730]
Hi,
When a long message  is sent it doesn't come through on the api.
Only something like this appears:
[message from="***" id="**" participant="-*-" offline="0" type="text" t="--" notify="***"]
  [body] 1263 byte data[/body]
[/message]

**Comment by mgp25** [comment]
Can you post you message and full debug log?

**Comment by Incher25** [comment]
Maybe it's because the maximum size of a  WA message should not exceed 1000 characters

**Comment by mgp25** [comment]
Its being sent but not shown in the debug, as you can see its shown like `1263 byte data`

**Comment by aris0** [comment]
Why is it closed? 

The issue is still there: while WA reads and sends long messages this
api can't read long ones. It just reads the bytes. 

Στις 2015-05-25 09:29, mgp25 έγραψε: 

> Closed #730 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/mgp25/Chat-API/issues/730
[2] https://github.com/mgp25/Chat-API/issues/730#event-312846082

**Comment by mgp25** [comment]
Check you log:

```xml
rx  [message from="---------@g.us" id="----" participant="----@s.whatsapp.net" phash="1:Db0PdnoO" offline="0" type="text" t="---" notify="----"]
rx    [body] 1310 byte data[/body]
rx  [/message]

tx  [receipt type="read" participant="----@s.whatsapp.net" to="--------@g.us" id="---" t="---"][/receipt]
```

You have received a message and you have sent a read receipt, btw it seems you are using outdated code and with android credetials

Regards

**Comment by aris0** [comment]
But where is the real message? 

Can you try with your updated api and let us know if you can read long
messages? Get the real content? Not just that it is 1310 byte data. 

>

**Comment by mgp25** [comment]
@aris0 maybe you are not understanding. The message is there, if you exceed bytes it will show like a media file, showing ONLY that in the debug, but the message its being sent CORRECTLY

So nothing to worry about

**Comment by CODeRUS** [comment]
@aris0 debug output is for DEBUGGING, surprise! Use api to get message contents after receiving and many other useful things.

**Comment by aris0** [comment]
@CODeRUS I'm using the api to get message contents. 

After using the $w->pollMessage() I get exactly what the debug shows 

[message from="---------@g.us" id="----"
participant="----@s.whatsapp.net" phash="1:Db0PdnoO" offline="0"
type="text" t="---" notify="----"]
 [body] 1310 byte data[/body]
[/message]

If it was an image it would give the link and I could get the image. 
Now it only gives the size of the message, but noting of the message
itself.
Is there another function to get large images?

>

**Comment by CODeRUS** [comment]
read wiki: https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#receiving-messages
