### ISSUE TITLE
I am getting 400 bad request error while logging 

### ISSUE THREAD

**Issue by bhargavgollamudi** [mgp25/Chat-API#737]
Hi, i am getting 400 bad request error while running example script file contactsync.php. I have managed to locate the code line where i am getting this error. 

In readStanza() function of whatsprot.class.php file, the $buff variable has data as 400 bad request.
 $buff = socket_read($this->socket, $treeLength);

Please help me, how to solve this issue.

Thanks,
Bhargav G

**Comment by mgp25** [comment]
Post your code and debug log

**Comment by bhargavgollamudi** [comment]
I am running example file examples/contactsync.php by changing $username, $password variables.
/////////
$identity = strtolower(urlencode(sha1($username, true)));
$wa = new WhatsProt($username, $identity, "test", true);
//bind event handler
$wa->eventManager()->bind('onGetSyncResult', 'onSyncResult');
$wa->connect();
$wa->loginWithPassword($password);

This is the debug log i am getting

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="917075169730"></auth>


After this code i am getting Exception error.

Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 169 & treeLength = 813172)' in D:\Program Files\Apache Software Foundation\Apache2.2\htdocs\whatsapp\src\whatsprot.class.php:

This error is from  src/whatsprot.class.php file on readStanza() function. I have printed $buff variable also.
 $buff = socket_read($this->socket, $treeLength);

In this $buff variable i am getting data as 

ml>
400 Bad Request
_________________________________________________
nginx/1.4.2

**Comment by mgp25** [comment]
You are using outdated code, update your code

**Comment by bhargavgollamudi** [comment]
I have downloaded latest files only. Can you please direct me what are the changes i have to make ?
