### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Raghava525** [mgp25/Chat-API#738]
```
400 Bad Request
nginx/1.4.2
Errors :
Socket :Resource id #18
header length : 3
treeLength :813172
```

Please check the code.
I am getting 400 bad request repeatedly .
```php
 public function readStanza()
    {
        $buff = '';
        if ($this->socket != null) {
            $header = @socket_read($this->socket, 3);//read stanza header
            if ($header === false) {
                $error = "socket EOF, closing socket...";
                socket_close($this->socket);
                $this->socket = null;
                $this->eventManager()->fire("onClose",
                    array(
                        $this->phoneNumber,
                        $error
                    )
                );
            }

            if (strlen($header) == 0) {
                //no data received
                return;
            }
            if (strlen($header) != 3) {
                throw new ConnectionException("Failed to read stanza header");
            }
            $treeLength = (ord($header[0]) & 0x0F) << 16;
            $treeLength |= ord($header[1]) << 8;
            $treeLength |= ord($header[2]) << 0;

            //read full length
            $buff = socket_read($this->socket, $treeLength);
			echo $buff;
			echo "Errors : <br>";
			echo "Socket :".$this->socket.'<br>';
			echo "header length : ".strlen($header)."<br>";
			
			echo "treeLength :".$treeLength."<br>";
			exit;
			
            //$trlen = $treeLength;
            $len = strlen($buff);
            //$prev = 0;
            while (strlen($buff) < $treeLength) {
                $toRead = $treeLength - strlen($buff);
                $buff .= socket_read($this->socket, $toRead);
                if ($len == strlen($buff)) {
                    //no new data read, fuck it
                    break;
                }
                $len = strlen($buff);
            }

            if (strlen($buff) != $treeLength) {
                throw new ConnectionException("Tree length did not match received length (buff = " . strlen($buff) . " & treeLength = $treeLength)");
            }
            $buff = $header . $buff;
        } else {
            $this->eventManager()->fire("onDisconnect",
                array(
                    $this->phoneNumber,
                    $this->socket
                ));
        }

        return $buff;
    }
```

Can you please tell me mistake in this code ?

**Comment by Raghava525** [comment]
![400 bad request error](https://cloud.githubusercontent.com/assets/12528568/7725341/4fa45e56-ff17-11e4-8493-63b0d361b34f.JPG)

**Comment by mgp25** [comment]
Post your script + debug log

**Comment by Raghava525** [comment]
<?php
set_time_limit(30);

require_once("../src/whatsprot.class.php");

$username = '91970XXXXXXX';
$password = "ADjuIAlclXYKjabXfV************";
$u        = '918688XXXXXX';

if (!is_array($u)) {
    $u = array($u);
}

$numbers = array();
foreach ($u as $number) {
    if ($number[0] != "+") {
        //add leading +
        $number = "+$number";
    }
    $numbers[] = $number;
}

//event handler
/**
 * @param $result SyncResult
 */
function onSyncResult($result)
{
    foreach ($result->existing as $number) {
        echo "$number exists<br />";
    }
    foreach ($result->nonExisting as $number) {
        echo "$number does not exist<br />";
    }
    die(); //to break out of the while(true) loop
}

$wa = new WhatsProt($username, "raghava", false);

//bind event handler
$wa->eventManager()->bind('onGetSyncResult', 'onSyncResult');

$wa->connect();

$wa->loginWithPassword($password);


//send dataset to server
$wa->sendSync($numbers);

//wait for response
while (true) {
    $wa->pollMessage();
}




am getting error in readStanza() function.

**Comment by Raghava525** [comment]
<?php

require_once('../src/whatsprot.class.php');

/**
 * Config data.
 */
$debug = true;

$username = '91970XXXXXXX';                      // Telephone number including the country code without '+' or '00'.
$nickname = 'raghava';                         // This is the username displayed by WhatsApp clients.

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->codeRegister('715335');

**Comment by 0xTryCatch** [comment]
Are you having many groups?

**Comment by Raghava525** [comment]
no. I have no groups.

**Comment by Raghava525** [comment]
when I print the $buff value after socket_read();   am getting 400 bad request error.

**Comment by leoetlino** [comment]
Still using Windows XP? Oh dear.

**Comment by mgp25** [comment]
@Raghava525 you are not passing any value to GET

**Comment by Raghava525** [comment]
Is this not working for windows XP ?
