### ISSUE TITLE
How much reliable?

### ISSUE THREAD

**Issue by iffifan** [mgp25/Chat-API#739]
Hello,

I have a simple question to ask to everyone who is using this api for whatsapp.
Actually I want you to share your experience with api and how reliable you think it is at the moment.
I am not asking because I am going to build some product out of it but I want to know how fruitful the efforts are so far? 

Thanks

**Comment by iffifan** [comment]
First of all i will share my experience,

I got interested in api as a student. I wanted to know how these things work and how whatsapp handle its operation. 
I found that it is some time hard to keep api updated along with whatsapp updates. All contributors worked really hard (and thanks to them for their efforts) but it is main issue that this api is facing. 
I noticed that we need to mimic whatsapp mobile app in order to get benefit from this api to its full potential.

**Comment by mgp25** [comment]
Not an API issue. It works like a charm as long as you are not an spammer and know how to code.

Regards
