### ISSUE TITLE
Warning: Unexpected character in input: '\' (ASCII=92) state=1

### ISSUE THREAD

**Issue by Raghava525** [mgp25/Chat-API#746]
When I'm trying to register my number using examples/exampleRegister.php file . I have hot the following error. 
And Please tell me the  CHAT-api   supporting versions.
 Am using PHP Version 5.2.0 
Please tell me the what mistake I did.
![error](https://cloud.githubusercontent.com/assets/12528568/7766309/97a050ec-0085-11e5-9140-ca2696fc8619.JPG)

**Comment by Raghava525** [comment]
I have faced this issues also. Please guide to solve this issues.

Fatal error: Call to undefined function openssl_random_pseudo_bytes() in D:\Program Files\Apache Software Foundation\Apache2.2\htdocs\chatapi\src\whatsprot.class.php on line 2288

**Comment by mgp25** [comment]
I guide you to read the wiki
