### ISSUE TITLE
onSyncResult

### ISSUE THREAD

**Issue by abd65000** [mgp25/Chat-API#748]
dears,

`OnSyncResult` was working at me before 2 weeks, today i face the problem, that the result returned (`iq , type =error`)
and no result came back.

i search on wiki and didnt find results, and searched on last commits, and didnt find updates on this area, is there any problem??

thank you for helping and best regards,

**Comment by mgp25** [comment]
@abd65000 Post your debug log

**Comment by abd65000** [comment]
Sorry. But i dont have debug log.
My code based on shiroko .net code, and i am following your updates and
update my code.
But it happenes as follows.
It send the contacts as it was before and nothing hit the function
(onSyncResult).

So i debug the code and see whats returned back. And it was (iq) message
received . And it hit (case "error" ).

Last time i use this function and it was working was on 7 may.

Best regards

**Comment by mgp25** [comment]
Then is not an API issue. You can set debug in there too, so when you have the debug, post it, and ill help you.

Regards

**Comment by abd65000** [comment]
the error msg is sendsync_3

and how can i set debug there?? can you help me in that??

thank you for helping :)

**Comment by mgp25** [comment]
Set debug to true

**Comment by abd65000** [comment]
\nSENT: <iq to=\"8613725571096@s.whatsapp.net\" type=\"get\" id=\"sendsync_0\" xmlns=\"urn:xmpp:whatsapp:sync\">\nSENT:   <sync mode=\"Full\" context=\"Background\" sid=\"130768610007970232\" index=\"0\" last=\"True\">\nSENT:     <user>+962796893000</user>\nSENT:   </sync>\nSENT: </iq>

**Comment by abd65000** [comment]
i make the debug to write on a text file, and the following appeared:

SENT: <stream:features></stream:features>

SENT: <auth mechanism="WAUTH-2" user="8613725571096"></auth>

RECVD: <start from="s.whatsapp.net"></start>

RECVD: <stream:features></stream:features>

RECVD: <challenge>��&�	��r迋Y���Y</challenge>

SENT: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">x�Mcm
k��ˣ�Z"Gg�_��*����ְ�5=κ</response>

**Comment by mgp25** [comment]
@abd65000 you haven't posted full debug + code outdated + not related you are using different API

**Comment by abd65000** [comment]
the question is: is there any changes done last month on this function (sync contacts)??
because my code is sending messages, and recieve replies and receive msg status, but the only thing not working is sync contacts, and it was working before 2 weeks!!!

thank you again for helping and best regards,

**Comment by abd65000** [comment]
sorry, here is a full debug :)


SENT: <stream:features></stream:features>

SENT: <auth mechanism="WAUTH-2" user="8613725571096"></auth>

RECVD: <start from="s.whatsapp.net"></start>

RECVD: <stream:features></stream:features>

RECVD: <challenge>Yn�[`&s!kkxc��N�</challenge>

SENT: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">��{ܜ�=�F>
bDlʜ1
����wԹD�q(&�tw�4�</response>

RECVD: <success t="1432472992" props="4" kind="free" status="active" creation="1430779286" expiration="1462315286">*���lLN]�7�M%4��yT</success>

RECVD: <ib from="s.whatsapp.net">
RECVD:   <offline count="0"></offline>
RECVD: </ib>

SENT: <iq to="8613725571096@s.whatsapp.net" type="get" id="sendsync_0" xmlns="urn:xmpp:whatsapp:sync">
SENT:   <sync mode="Full" context="Background" sid="130769465973821446" index="0" last="True">
SENT:     <user>+962786893407</user>
SENT:   </sync>
SENT: </iq>

RECVD: <iq from="8613725571096@s.whatsapp.net" id="sendsync_0" type="error">
RECVD:   <error code="406" text="not-acceptable" backoff="3600"></error>
RECVD: </iq>

**Comment by abd65000** [comment]
i dont know when i paste the debug, its appears empty when i send it !!!!

**Comment by abd65000** [comment]
i found the solution, i was using (full, background) in the sync, when i change it to (delta,interactive) then it worked.

thank you for your help
