### ISSUE TITLE
socket_connect

### ISSUE THREAD

**Issue by AlexxOrlovv** [mgp25/Chat-API#749]
Hello. Why to work with the connections you use socket_connect? After all, it contains bugs, and gradually goes deprecated. As far as I know - it is common to use stream_socket_client, as it is safer and provides more opportunities for work.

**Comment by AlexxOrlovv** [comment]
https://github.com/AlexxOrlovv/Chat-API/blob/master/src/whatsprot.class.php

**Comment by AlexxOrlovv** [comment]
Why is it necessary? If you interact with the server which does not meet the ip country and country code numbers - nothing is work-no) to this functionality need to specify proxy in curl and context.

**Comment by mgp25** [comment]
As far as i know, is not deprecated and works pretty good, if we ever had a problem, we will change it.

Thanks

Regards
