### ISSUE TITLE
How can i formate a message in Chat-API

### ISSUE THREAD

**Issue by wpinfotech** [mgp25/Chat-API#750]
How can i put hyperlink or new line in message?

**Comment by mgp25** [comment]
@wpinfotech just write the link and it will show up and new line is `\n`

**Comment by mgp25** [comment]
@wpinfotech right?

**Comment by wpinfotech** [comment]
no it shows \n in text.. and how can i send hyperlink?

**Comment by CODeRUS** [comment]
did you ever tried to send link before asking?

**Comment by wpinfotech** [comment]
$message = "This is test message \n http://www.example.com";
$w->sendMessage("TARGET NUMBER**", $message);
$w->pollMessage();


this is my code

**Comment by mgp25** [comment]
@wpinfotech you are spamming then

**Comment by wpinfotech** [comment]
no i just start testing to send link on whatsapp.. m not spamming on whatsapp

**Comment by mgp25** [comment]
@wpinfotech man, the link only shows up in the user have your number added, you are spamming

**Comment by wpinfotech** [comment]
thanks.. its done i saved number on my device and it shows as link thank you
