### ISSUE TITLE
Getting the group list

### ISSUE THREAD

**Issue by DarkRanger** [mgp25/Chat-API#752]
I need to get a list of groups assigned to my number. This is how I do it, but it returns null.
```php
    $number = ***********;
    $password = **********;
    if(!empty($number)) {
        $w = createWhatsapp($number);
        $w->connect();
        $w->loginWithPassword($password);
        $groups = $w->sendGetGroups();
    }
```
I've created a group like this. Can anyone help with what I'm doing wrong?
```php
        $w = createWhatsapp($number);
        $w->connect();
        $w->loginWithPassword($password);
        $groupId = $w->sendGroupsChatCreate($name,array());
```
I have the events enabled. And I do get a `$groupId` back, so it seems to be creating fine.

**Comment by ducch** [comment]
sendGetGroups() returns void. it's only used to _send_ a 'GetGroups', and it does not handle receiving the answer. see [whatsprot.class.php#L847](https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L847).
the answer of sendGetGroups, is an even called onGetGroups, which is what you need to bind to, to handle the answer that's received. see [AllEvents.php#L64](https://github.com/mgp25/Chat-API/blob/master/src/events/AllEvents.php#L61).

**Comment by DarkRanger** [comment]
In my events file I have this:

    public function onGetGroups( $mynumber, $groupList) {
        return $groupList;
    }

onGetGroups is also uncommented.

How would I get the group list that I have?

**Comment by ducch** [comment]
`return` isn't what you're after here, because you're not collecting the returned data anywhere.
try `var_dump($groupList);` or something.

**Comment by DarkRanger** [comment]
Not sure I understand. I need to get the list and work with that data. How would I do that?

I've tried changing that function to `var_dump`, but even so I get nothing back.

**Comment by ducch** [comment]
it really depends on your implementation.
if this is a cli script that runs constantly, you could use [$GLOBALS](http://php.net/manual/en/reserved.variables.globals.php) or some other more preferred techniques.
otherwise, if this is a web thing, you can consider using a [session](http://php.net/manual/en/book.session.php).
bottom line is, sendGetGroups() will _send_ a get-groups request. the onGetGroups event will _receive_ the answer, and you should manipulate that data however you wish there.

**Comment by DarkRanger** [comment]
It's a PHP web app. My issue is it seems to not even be firing the `onGetGroups` event. Because if I `die();` in that function, nothing happens. It carries on like it would usually.

**Comment by ducch** [comment]
i have the feeling you are using events improperly.
please take a look at the [events part of the wiki](https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#using-events) and make sure you follow the instructions.
fwiw, you shouldn't touch the AllEvents.php file at all, but rather the example at MyEvents.php.

**Comment by DarkRanger** [comment]
I'm extending the AllEvents class. Just easier to manage and then I don't modify any of the files.

But thanks for saying what your feeling is. That pointed me in the right direction. I never called

    $events = new ModifyEvents($w);
    $events->setEventsToListenFor($events->activeEvents);

In my constructor. Such a moron.  Thanks again
