### ISSUE TITLE
When i using 'loginWithPassword()' i am getting ConnectionException  

### ISSUE THREAD

**Issue by pallikiran** [mgp25/Chat-API#753]
Hi,
I need to find mobile number having whatsapp account or not.
So, I am trying to connect Whatsapp using whatsprot.class.php class.

I did the following:
1. <code> $wa = new WhatsProt($username, "WhatsApp", $debug);
 $wa->codeRequest('sms'); </code> 
2. received the 6 digit  WhatsApp code.
3. And used the received code
<code>    
$result = $wa->codeRegister($code);
    $password = $result->pw;
</code>
4. And used the above password to login
<code> $wa->connect();
$wa->loginWithPassword($password);
</code> 
Here i am getting below ERROR:
Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 169 & treeLength = 813172)'

Could any one help me to solve this problem?

Thanks in advance ...

**Comment by mgp25** [comment]
@pallikiran how many groups do you have in that account?

**Comment by pallikiran** [comment]
@mgp25 , there are no groups in my account.
I tried with 3 numbers. But i got same error.

Thanks 
Kiran

**Comment by mgp25** [comment]
@pallikiran then you are using android credentials

Regards

**Comment by pallikiran** [comment]
@mgp25, I want this fix in PHP website.
could you do any favor regarding this issue?

Thanks
