### ISSUE TITLE
tagging required

### ISSUE THREAD

**Issue by inmarelibero** [mgp25/Chat-API#755]
Hi, could you please make a tag, in order to better handle requirements with composer (for example)?

**Comment by 0xTryCatch** [comment]
Can you explain why you need a tag and why you cannot use ```dev-master``` or specific commits?

**Comment by inmarelibero** [comment]
sure. you can read some doc here: [https://getcomposer.org/doc/01-basic-usage.md#package-versions](https://getcomposer.org/doc/01-basic-usage.md#package-versions)

the idea is that if the repo maintainer uses the Semantic Versioning ([http://semver.org/](http://semver.org/)), I can put in composer something line:

```
"mgp25/whatsapi": "1.1.*"
```

instead of the awful:
```
"mgp25/whatsapi": "dev-master"
```

one of the advantages is that the minor improvements or bug fixes (the third number on the right) would be fetched in my project, without compromising the stability of the whole project.

**Comment by mgp25** [comment]
@inmarelibero i know, but its more than recommended to use only the lattest source, thats why im not adding version tags

**Comment by inmarelibero** [comment]
and what happens if you do a BC break? how can I know which was the last working commit?

semver would help a lot the developers to adopt your library

**Comment by inmarelibero** [comment]
do you really consider this as closed?

**Comment by mgp25** [comment]
@inmarelibero is a huge work to maintain all this, and that will be a plus os work, as we have to create several branches and versions looking at backwards compatibility.

As i said before, it's more than recommended to only use the latest code, generally before pushing any commits we test it, so we dont introduce any erros/bugs, and if somehow i push an error, it will be fixed quickly.

**Comment by inmarelibero** [comment]
well you could do only two branches, `master` and `dev`, and tag only master.

there are many levels to do this, you could for example use only X.Y notation, and stuck for a long time on 1.* tag, while you are developing so fast.

not using tags is discouraging many developers when thinking about using your library. I don't doubt it's a huge work and I'm not arguing on this.
I personally don't use a non-tagged library if there's at least another viable choice; more, no developer would use a non-tagged library in production, at least because he will not be sure for stability when updating. 
I hope you, or someone for you, will reconsider dedicating some time on this feature, because more developers will use this, more will contribute and so on.

Cheers.

**Comment by ducch** [comment]
@inmarelibero a devel branch was created per #419, but it's not being used.
