### ISSUE TITLE
GoDaddy Server

### ISSUE THREAD

**Issue by DanieelLpz** [mgp25/Chat-API#756]
I uploaded Chat-API to my webserver (Goddady) but it doesn't work. The php used is 5.3. What's the problem? Is maybe the web server, isn't? 
The code is working fine in my localhost, but here is:

      <?php
       require_once 'whatsprot.class.php';

      $username = '521111111111'; 
      $password = '11111111111';
      $nickname = "Admin";
      $debug = true;

      $w = new WhatsProt($username, $nickname, $debug);

		$w->connect();
		$w->loginWithPassword($password);
  
  
	$target = '5211111111111';
	$message = 'Prueba Mensaje' ;
	$w-> sendMessage($target, $message);
	  
	  $pathToImage ="http://kuzkas.com/images/bordados/huesito.jpg";
          $w->sendMessageImage($target, $pathToImage, $storeURLmedia = false);
          $w->pollMessage();

           ?>

**Comment by thetitoo** [comment]
1. Debug log?
2. Format your code

**Comment by DanieelLpz** [comment]
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)."

**Comment by thetitoo** [comment]
This is not a debug log, 
Please search the wiki and other issues for example.
