### ISSUE TITLE
How to add emojis?

### ISSUE THREAD

**Issue by chtha** [mgp25/Chat-API#759]
I know that this question was asked several times, but I don't really get it working.

I wrote a PHP function to convert emoji codes to UTF-8 according to this list: http://apps.timwhitlock.info/emoji/tables/unicode

The input for a message now is (i.e.) "This is a \xF0\x9F\x98\x84 test".
But the message text will not be converted (by WhatsApp?), but will appear on the received message as this: "This is a \xF0\x9F\x98\x84 test". The assumed UTF-8 string is not converted to an emoji. How can I fix this? Am I making something wrong? Can you give me some PHP function to handle this?

Thank you in advance

Chris

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/wiki/Frequently-asked-questions#how-can-i-send-emojis

you need to have enabled UTF-8. If you dont have enabled by default and don't know how to enable, you can use this with your message ` string utf8_encode ( string $data )`

**Comment by chtha** [comment]
Sorry to bother again, but when I use this function (i.e. utf8_encode("This is a \xF0\x9F\x98\x84 test")) it outputs the same text ("This is a \xF0\x9F\x98\x84 test".)

So when I encode the message before sending it still only sends the text with all these characters instead of the emoji.

For further explanation:
I insert emojis with this pattern: ```::emoji emoji-####::``` while #### is the Unicode of the respective emoji, for example 1F601. Before sending the message into the network I encode it to UTF-8 by the following function: 
```php
function convert_message($message) {
	if($message=='') return false;
	else {
		preg_match_all("/\:\:emoji emoji\-(\w+)\:\:/is", $message, $match);
		$match=$match[1];
		$j=0;
		foreach($match as $i) {
			$emoji = emoji($match[$j]);
			$message = str_replace("::emoji emoji-".$match[$j]."::",$emoji,$message);
			$j++;
		}
		$message = preg_replace('/[[:space:]]{2,}/',' ',$message);
		return utf8_decode($message);		
	}
}
```
the function ```emoji()``` just checks for the delivered code and replaces it with the new UTF-8 code if found (i.e. replaces "1F601" with \xF0\x9F\x98\x81 according to http://apps.timwhitlock.info/emoji/tables/unicode.

Can you help me with this?

**Comment by ducch** [comment]
show us the source code of emoji().
if it's too long, put it in a gist please.

**Comment by chtha** [comment]
Thank you for your answer.

Here is the missing function:
```php
function emoji($unicode) {
	if($unicode=='') return false;
	else {
		$data = csv_to_array('emoji/emojis.txt',';');
		$found = false;
		foreach($data as $row) {
			$key = array_search($unicode, $row);
			if($key) {
				$found = true;
				return $row['utf'].' ';	
			}
		}
		if($found == false) return false;
	}
}
```
csv_to_array does this:
```php
function csv_to_array($filename='', $delimiter=',') {
    if(!file_exists($filename) || !is_readable($filename))
        return FALSE;

    $header = NULL;
    $data = array();
    if (($handle = fopen($filename, 'r')) !== FALSE) {
        while (($row = fgetcsv($handle, 1000, $delimiter)) !== FALSE) {
            if(!$header)
                $header = $row;
            else
                $data[] = array_combine($header, $row);
        }
        fclose($handle);
    }
    return $data;
}```
The CSV-file is structured like this:
```uni;utf
1F601;\xF0\x9F\x98\x81
1F602;\xF0\x9F\x98\x82
etc```
Maybe it is because the CSV is not in UTF-8 format?

**Comment by chtha** [comment]
I fixed this now with this library: https://github.com/NickyX3/Emoji-PHP-Static

Thank you nevertheless!

Chris

**Comment by fermino** [comment]
@chtha I think it doesn't work beacuse your csv doesn't have the utf-8 characters, only the hexa codes. So your PHP code doesn't convert that escaped strings, only sends '\xXX\xXX\xXX\xXX', as literal. 

Regards!
-fermino-

**Comment by James2376** [comment]
@chtha How did you fix this ? I got the same problem:     "I found out that when I send a message "hardcoded" like $w->sendBroadcastMessage("This is a \xF0\x9F\x98\x84 test") it works (with double quotes). When I use my function to convert the string, it does not."

**Comment by chtha** [comment]
@James2376 I used the library https://github.com/NickyX3/Emoji-PHP-Static with the function Emoji::html_to_emoji(). I think there are cleaner solutions, but I didn't got one. Hope this helps you as well!

**Comment by James2376** [comment]
@chtha Sorry for bothering you again. How did you use the library ? I got the following situation: 
1. HTML File with 1 Faketextbox (div) and 1 hidden Input-Field and AJAX to get everthing in my PHP File.
2. PHP File to get everything inside the Network.

**Comment by chtha** [comment]
@James2376 Let's say you have transferred the message into the PHP file for further processing in the variable ```$_POST['message']``` and the content is something like ```php $_POST['message'] = 'this is a test &#x1f60a;';``` (emoji converted as seen in http://apps.timwhitlock.info/emoji/tables/unicode). You now have to use the method of the above mentioned class. For that purpose you could use a function like this (it is not very clean but does it's work):
```php
function convert_message($message) {
	if(!$message) return false;
	else {
		preg_match_all("/\&\#x(\w+)\;/is", $message, $match);
		$match=$match[1];

		$j=0;
		foreach($match as $i) {
			$emoji = Emoji::font_to_emoji('&#x'.strtolower($match[$j]).';');
			$message = str_replace("&#x".$match[$j].";",$emoji,$message);
			$j++;
		}
		
		return $message;		
	}
}
```

**Comment by arth1992** [comment]
@chtha can you please share your piece of code. I send post message like this ```php This is a test message &amp;#x1F603 ``` I stuck what to do afterwards.
