### ISSUE TITLE
Presence subscription required?

### ISSUE THREAD

**Issue by tim-hanssen** [mgp25/Chat-API#761]
Hey all,

When receiving a message from a new contact, I sync that contact using interactive sync to the WhatsApp server. Doing then all again once a day.

Is it necessary to run sendPresenceSubscription for all the users, or is it not required like the sync?

Thxs for helping me out.

**Comment by mgp25** [comment]
@tim-hanssen when you `sendSync`, always you need to `sendPresenceSubscription(contact)`

Regards
