### ISSUE TITLE
Is there any event that inform our number being added (synced) by other whatsapp number.

### ISSUE THREAD

**Issue by assegaf** [mgp25/Chat-API#762]
hi maybe this kind of question, or maybe some event that lost in api, that should be needed.
is there any event to know that our number using this api, has been added /synced by other whatsapp number.

if we made some auto reply function we might need some basic rules, only if has been synced before by other Wa number, reply it.

**Comment by mgp25** [comment]
That is not possible, whatsapp has not that feature

Regards
