### ISSUE TITLE
send broadcasts

### ISSUE THREAD

**Issue by murillosupera** [mgp25/Chat-API#765]
I work at a startup that provides service to taxi drivers, and we need to keep them informed so needed this functionality in whatsapp to send messages to someone they could help me , if not cause any problems?

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#sending-messages

Regards

**Comment by murillosupera** [comment]
sorry, I did not know that this functionality was so would be like
