### ISSUE TITLE
WhatsAppAPI .net

### ISSUE THREAD

**Issue by vovanb** [mgp25/Chat-API#766]
Hi I am using Whatsapp API for .NET 15.4.29 which is ported from chat -api as i understood.
I have problem that I get disconnect after rundom number of time. How I should reconnect ? Where I can see debug log?
Thanks

**Comment by alijundi** [comment]
I have the same issue. I simply use send active every two mins and then i reconnect if i receive a disconnect event. I have no clue why I get disconnectef randomly like you mentioned in your comment. Maybe @mgp25 can assist. Thanks

**Comment by CODeRUS** [comment]
Are you peoples drunk to post issues here?

https://github.com/mgp25/Chat-API-.NET
